### ISSUE TITLE
-b option is failing

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-monitoring#1005]
*Installation details*

Scylla-Monitoring Version: scylla-monitoring-scylla-monitoring-3.4.1
Scylla-Version: n/a

```sh

$ ./start-all.sh  -d /opt/scylla-monitoring/data  -v latest  -N /opt/scylla-monitoring/scylla-monitoring-scylla-monitoring-3.4.1/prometheus/scylla_manager_servers.yml  -b storage.local.retention=1000h -b query.staleness-delta=1m
Wait for alert manager container to start
Loading prometheus data from /opt/scylla-monitoring/data
Wait for Prometheus container to start........
Error: Prometheus container failed to start
For more information use: docker logs aprom

$ docker logs aprom
Error parsing commandline arguments: unknown short flag '-s'
prometheus: error: unknown short flag '-s'
```

Without the `-b` argument(s) everything starts just fine

**Comment by amnonh** [comment]
check the documentation for the correct syntax:
http://scylladb.github.io/scylla-monitoring/master/start_all.html#prometheus-retention-period

**Comment by dyasny** [comment]
I got the example from here: https://github.com/scylladb/scylla-monitoring#prometheus-command-line-options

**Comment by amnonh** [comment]
Thanks @dyasny I have updated the README.
