### ISSUE TITLE
CURRENT_VERSION.sh is set to master in the 3.4.2 release

### ISSUE THREAD

**Issue by carlosms** [scylladb/scylla-monitoring#1016]
*Installation details*
Panel Name: N/A
Dashboard Name: N/A
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) 3.4.2
Scylla-Version: N/A

After downloading last release (`scylla-monitoring-3.4.2.tar.gz`), `start-all-sh` shows this warning:
```
*****************************************************
* WARNING: You are using the unstable master branch *
* Check the README.md file for the stable releases  *
*****************************************************
```
The version file included:
```
$ cat CURRENT_VERSION.sh 
master
```

**Comment by amnonh** [comment]
Thanks for noting this, 3.4.3 is out and fixes this issue
