### ISSUE TITLE
Total Storage Reporting is not accurate

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#102]
Using GCE platform with 3 NVMe drives, each 375GB (total of 1.1TB), 3 servers.
Each looks like the following in terms of drivers:
[eyal@sdb1bignvme ~]$ sudo fdisk -l

Disk /dev/sda: 10.7 GB, 10737418240 bytes, 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk label type: dos
Disk identifier: 0x00091e3d

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048    20971519    10484736   83  Linux

Disk /dev/nvme0n1: 402.7 GB, 402653184000 bytes, 98304000 sectors
Units = sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/nvme0n2: 402.7 GB, 402653184000 bytes, 98304000 sectors
Units = sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/nvme0n3: 402.7 GB, 402653184000 bytes, 98304000 sectors
Units = sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/md0: 1207.6 GB, 1207556898816 bytes, 294813696 sectors
Units = sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 524288 bytes / 1572864 bytes

The total reported storage space is "yellow" as if there is an issue with the total storage, See image.
![image](https://cloud.githubusercontent.com/assets/17868115/21283518/90ea6f9c-c3b8-11e6-81df-6ee29ca42227.png)

Changing Query A to:
sum(node_filesystem_avail{mountpoint="/var/lib/scylla"})/1000000000

and Query B to:
(sum(node_filesystem_size{mountpoint="/var/lib/scylla"})-sum(node_filesystem_avail{mountpoint="/var/lib/scylla"}))/1000000000

provided the accurate view of the chart:
![image](https://cloud.githubusercontent.com/assets/17868115/21283719/8f39f114-c3bc-11e6-856c-714d977e744c.png)

![image](https://cloud.githubusercontent.com/assets/17868115/21283756/4e0c7e72-c3bd-11e6-9380-be5640ccec07.png)
![image](https://cloud.githubusercontent.com/assets/17868115/21283757/56119cf6-c3bd-11e6-980f-1fb725670058.png)

**Comment by tzach** [comment]
@eyalgutkind thanks for reporting
@amnonh can you please take a look? @eyalgutkind update makes sense to me but you are the node_exporter expert. If you agree please send PR.

**Comment by tzach** [comment]
@amnonh ping

**Comment by tzach** [comment]
@eyalgutkind can you please validate the problem is solved?
Thanks
