### ISSUE TITLE
Issue in page Adding and Modifying Dashboards

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla-monitoring#1020]
I would like to report an issue in page http://docs.scylladb.com/updating_dashboard

### Problem

To overcome these issues, the dashboard generation script will generate the dashboards in the Grafana version 5.0 format. In the transition, rows will be replaced with a calculated absolute position.

Panels height will be taken from their row. The span attribute is stil supported like you expect it to work, so does row height.

you can use the gridPos attribute which is a Grafana 5.0 format, but not like Grafana, you can use partial attributes.

is awkward.

###  Suggest a fix

make it clearer and provide some example for reference

**Comment by amnonh** [comment]
The link is wrong, https://docs.scylladb.com/operating-scylla/monitoring/3.4/updating_dashboard/

have you look at: https://docs.scylladb.com/operating-scylla/monitoring/3.4/updating_dashboard/#grafana-formats-and-layouts
that explains this part?

**Comment by lauranovich** [comment]
https://docs.scylladb.com/operating-scylla/monitoring/3.4/updating_dashboard/#grafana-formats-and-layouts contains the text which I am questioning
something doesn't make sense grammatically and conceptually and before I correct it, I need to understand what it is we want to say.
