### ISSUE TITLE
Error: Template parsing error: template: image:1:24: executing "image" at <.NetworkSettings.Networks>: can't evaluate field Networks in type *libpod.InspectNetworkSettings

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-monitoring#1026]
*Installation details*
Scylla-Monitoring Version: 3.4.3
Scylla-Version: 2020.1

Getting the following error, when running on CentOS8 with podman/podman-docker:

```sh
cd /opt/scylla-monitoring/scylla-monitoring-scylla-monitoring-3.4.3/
./start-all.sh  -d /opt/scylla-monitoring/data  -v latest,2020.1  -s /opt/scylla-monitoring/scylla-monitoring-scylla-monitoring-3.4.3//prometheus/scylla_servers.yml  -N /opt/scylla-monitoring/scylla-monitoring-scylla-monitoring-3.4.3//prometheus/scylla_manager_servers.yml  -b -storage.tsdb.retention.time=14d  -M 2.1 -a P@ssw0rd123
```
STDOUT:

``` 
Wait for alert manager container to start
Loading prometheus data from /opt/scylla-monitoring/data
Wait for Prometheus container to start..
Wait for Grafana container to start........
Start completed successfully, check http://localhost:3000
```

STDERR:

``` 
Error: Template parsing error: template: image:1:24: executing "image" at <.NetworkSettings.Networks>: can't evaluate field Networks in type *libpod.InspectNetworkSettings
```

With this, the stack seems to be working, so this might be cosmetic. 

versions:
podman-1.6.4-10.module_el8.2.0+305+5e198a41.x86_64
podman-docker-1.6.4-10.module_el8.2.0+305+5e198a41.noarch

I found this: https://github.com/containers/podman/issues/4193 as something with a similar error output

**Comment by amnonh** [comment]
@dyasny can you update your podman and see if the issue got resolved?

**Comment by dyasny** [comment]
I just checked again on a fresh CentOS8 - same error. The versions I have installed are the latest in the repos:
podman-1.6.4-10.module_el8.2.0+305+5e198a41.x86_64
podman-docker-1.6.4-10.module_el8.2.0+305+5e198a41.noarch

```
$ dnf info podman
Name         : podman
Version      : 1.6.4
Release      : 10.module_el8.2.0+305+5e198a41
Architecture : x86_64
Size         : 55 M
Source       : podman-1.6.4-10.module_el8.2.0+305+5e198a41.src.rpm
Repository   : @System
From repo    : AppStream
Summary      : Manage Pods, Containers and Container Images
URL          : https://podman.io/
License      : ASL 2.0
Description  : podman (Pod Manager) is a fully featured container engine that is a simple daemonless tool.  podman provides a Docker-CLI comparable command line that eases the transition from other container engines and allows the management of
             : pods, containers and images.  Simply put: alias docker=podman.  Most podman commands can be run as a regular user, without requiring additional privileges.
             : 
             : podman uses Buildah(1) internally to create container images. Both tools share image (not container) storage, hence each can use or manipulate images (but not containers) created by the other.
             : 
             : Manage Pods, Containers and Container Images
             : libpod Simple management tool for pods, containers and images
```

**Comment by dyasny** [comment]
PS - it would make sense to have a hook that removed the "need info" label once a new comment has been added, like bugzilla does

**Comment by amnonh** [comment]
@dyasny as it's possible a podman issue that got resolve I would look at moving to a newer release (1.9 was out on April).

I saw in the podman documentation (https://podman.io/getting-started/installation.html) that they recommend using kubic project for up-to-date packages (See the centos section).

**Comment by dyasny** [comment]
@amnonh it's not resolved if it's in the current CentOS8 repos. I am using the latest available binaries for podman there. 

As for kubic - it's a rawhide repo:
> The Kubic project provides updated packages for CentOS 7, 8 and Stream. These packages haven’t been through the official Red Hat QA process and may not be preferable for production environments.

In short, we should be able to work with podman normally, and this error is probably something we should work out, potentially in their issue tracker if we can't fix it on our side.

**Comment by amnonh** [comment]
Closing as stale
