### ISSUE TITLE
Visually present error/no error on the node table

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1035]
Please make sure that this is a feature request. 

**Describe the feature and the current behavior/state.**
On the node table, it will be useful to add a visual indication to the Error, CQL, IO links to let the user know there are errors
![image](https://user-images.githubusercontent.com/170200/92319728-02854a00-f024-11ea-9a89-77addf1924dd.png)

**Who will benefit with this feature?**
Scylla Users

**Comment by amnonh** [comment]
The idea is good, but the description is too wide, what do you mean by error?

**Comment by tzach** [comment]
For example, when there are errors, the "Errors" link can be red. Call for action: click me to see the errors!
When there are not errors, it can be dimmed, disabled). Call for action: ignore me for now

**Comment by amnonh** [comment]
I think https://github.com/scylladb/scylla-monitoring/pull/1275 covers it,
closing, reopen if you think more things are needed
