### ISSUE TITLE
Doc Issue: wget commands must be updated per version / release

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla-monitoring#1039]
In *all* instructions where there is a code example
the monitoring version needs to match or else it needs to be replaced by a variable which can be updated with the branch - release number

**Comment by tzach** [comment]
This is not urgent, we can revisit once w e have a solution for variables in code sections

**Comment by lauranovich** [comment]
we have the solution now
I will start the PR on this

**Comment by dgarcia360** [comment]
We have now a solution for variables in code sections, you can see the example here: https://sphinx-theme.scylladb.com/master/examples/

To have different variables per version build, please change the dependency of ``sphinx-multiversion-scylla`` in https://github.com/scylladb/scylla-monitoring/blob/master/docs/pyproject.toml#L16 to ``0.2.5``.

```
sphinx-multiversion-scylla = "0.2.5"
```
