### ISSUE TITLE
Dashboards don't work with scylla 1.6+

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#104]
The following sed fixes some graphs, but not all:

```
sed 's/{type=\\\"\([a-zA-Z_ ]*\)\\\", metric/_\1{type/g' -i grafana/scylla-dash-per-server.json
```

**Comment by tzach** [comment]
@amnonh we need either a branch (or tag) per Scylla release or a dashboard group per version.
You have been looking at the second, any results?

**Comment by amnonh** [comment]
Yes,
Without changing grafana (maybe we should)
Tagging works.
Starring does not works (based on storing in the DB)
row repeat does not work
No hierarchy support

**Comment by tzach** [comment]
Thanks, please send a PR

**Comment by tzach** [comment]
@amnonh ping

**Comment by tgrabiec** [comment]
@amnonh ping

People are using monitoring with master branch as well. Keeping dashboards broken for so long is a source of pain to people like me, who want to test changes. Changes to scylla-grafana-monitoring should be ready at the same time as changes to scylla.

\cc @slivne

**Comment by amnonh** [comment]
On Tue, Jan 3, 2017 at 3:24 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> ping
>
> People are using monitoring with master branch as well. Keeping dashboards
> broken for so long is a source of pain to people like me, who want to test
> changes. Changes to scylla-grafana-monitoring should be ready at the same
> time as changes to scylla.
>
> \cc @slivne <https://github.com/slivne>
>
We have moved to tag based dashboards.
There's a v1.6, v1.5 supported dashboard, I'll add v1.7 and will keep it up
to date with master.

**Comment by tzach** [comment]
Closing since we now have a dashboard pre Scylla release (and master)
