### ISSUE TITLE
Docs: https://scylladb.github.io/scylla-monitoring/ path does not works:

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1051]
https://scylladb.github.io/scylla-monitoring forward to 
https://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.4/index.html
which does not exisit.

**Comment by tzach** [comment]
@dgarcia360 please take a look

**Comment by dgarcia360** [comment]
@tzach Fixed here: https://github.com/scylladb/scylla-monitoring/pull/1045 https://github.com/scylladb/scylla-monitoring/pull/1049

**Comment by psarna** [comment]
I posted an identical request yesterday :) #1050 so feel free to close both once it's solved

**Comment by amnonh** [comment]
Fixed by #1049
