### ISSUE TITLE
Grafana: Use UTC by default

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-monitoring#1065]
Please consider make Grafana to use UTC timezone instead of local browser timezone by default.  We have bigger chance that the server metrics uses the UTC than tge timezone of the one viewing the monitor data. It is quite inconvenient to change to UTC all the time.

**Comment by asias** [comment]
@tzach @amnonh  @slivne could you please consider this issue. It is very annoying to modify it all the time in every window you open. e.g, Advanced / Detailed.

**Comment by amnonh** [comment]
It's not a complicated change, but I'm not sure that it's correct
@tzach @avikivity @vladzcloudius your input will be valuable

**Comment by avikivity** [comment]
I prefer UTC too (and even more that the time zone will be clear).

I rarely look at servers in my own timezone.

**Comment by asias** [comment]
> It's not a complicated change, but I'm not sure that it's correct

I am not sure why using local browser time and UTC by default is a correctness issue.

**Comment by asias** [comment]
> I prefer UTC too (and even more that the time zone will be clear).
> 
> I rarely look at servers in my own timezone.

Btw, it would be super super useful if when we change the dashboard (Overview / Detailed) the time frame persists. I spend most of the time choosing the previous time frame after switch to new view. 

I believe Avi requested if somewhere too.

**Comment by amnonh** [comment]
> > I prefer UTC too (and even more that the time zone will be clear).
> > I rarely look at servers in my own timezone.
> 
> Btw, it would be super super useful if when we change the dashboard (Overview / Detailed) the time frame persists. I spend most of the time choosing the previous time frame after switch to new view.

It was added in 3.4, it's on the top right:
https://www.scylladb.com/product/release-notes/scylla-monitoring-stack-3-4/

> 
> I believe Avi requested if somewhere too.
