### ISSUE TITLE
Issue in page Install Scylla Monitoring Stack

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla-monitoring#1072]
I would like to report an issue in page http://docs.scylladb.com/monitoring_stack

### Problem
The link http://scylladb.github.io/scylla-monitoring/monitor_without_docker
is missing. 

###  Suggest a fix

There are such links with pointers to the specific version (same link, suffixed with
something like '2.1' in this case, this is the latest monitor stack document
so it should point to the latest link w/o docker too

**Comment by lauranovich** [comment]
@dorlaor  thanks for your feedback. To answer your request can you please tell me if you want this link to be on this page https://docs.scylladb.com/operating-scylla/monitoring? Each version has its own file. The only reason there was a _2.1 prefix was that when we originally had all of the versions together, versions prior to 2.1 had a different procedure for Docker. Now there is no need for the version syntax. At the time we thought we would just truncate the name of the file and remove the 2.1 going forward. I can make this change for versions before 2.1 as well, but I don't see a point. 

If you click a version such as https://docs.scylladb.com/operating-scylla/monitoring/3.4/, there is a link to https://docs.scylladb.com/operating-scylla/monitoring/3.4/monitor_without_docker/.

From the http://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.5/ branch, you can see the link for http://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.5/monitor_without_docker.html. 

If this is acceptable, I'll close the issue.
