### ISSUE TITLE
Move the configuration to a setup part

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1073]
The idea is to remove files from the start-all.sh script and pass it to a setup phase.
Version (OS/Enterprise)
Alternator
Additional dashboards.

All can be decided with a setup script, it can even create a docker-compose file at the end.

**Comment by tzach** [comment]
Make sense to refactor start_all script, which become to large and complex.
I do not want the users to run set_up and that start. If we can hide refactoring I'm in favor

**Comment by amnonh** [comment]
@tzach 
My thought was users would run set up (or another sexier name) once.
it would generate a docker-compose file
and instead of start-all/kill-all (we can still support them) but it will be a wrapper around
docker-compose up/down

**Comment by tzach** [comment]
> My thought was users would run set up (or another sexier name) once.
> it would generate a docker-compose file

Why do you need to generate the compose file?

> and instead of start-all/kill-all (we can still support them) but it will be a wrapper around
> docker-compose up/down

You can check if the file exist, and generate it if it is not.

I like the idea, but I'm worried about breaking backward compatibility for all the users (including Scylla Cloud)

**Comment by amnonh** [comment]
there are some file manipulations that we need to do like: state which version is being used, prometheus and grafana external directory etc'.
We can keep both options, or have the start-all/kill-all mapped to docker-compose up/down
