### ISSUE TITLE
master's dashboard shows idle load as 100 and busy as 0

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla-monitoring#110]

**Comment by amnonh** [comment]
We've changed that, you're right

**Comment by tzach** [comment]
@amnonh is this still relevant?

**Comment by tzach** [comment]
@amnonh ping

**Comment by amnonh** [comment]
It was solved by:
reactor utilization should return the utilization in 0-1 range
See also scylladb/seastar#248
