### ISSUE TITLE
Remove the avg line from the multi-graph panels in the overview

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1115]
*Installation details*
Panel Name: read latencies/write latencies
Dashboard Name: Overview
Scylla-Monitoring Version: 3.5
Scylla-Version: all

The gap between 99% and avg is too big for the same graph, avg is less interesting, so just remove it

**Comment by tarzanek** [comment]
will avg be in some separate view?

**Comment by amnonh** [comment]
It's still in the detailed dashboard, on the top row and was voted as unuseful in the overview dashboard
