### ISSUE TITLE
Scylla Manager Metrics shows twice the number of nodes when scylla_manager_servers.yml has the new port set

### ISSUE THREAD

**Issue by ziggythehamster** [scylladb/scylla-monitoring#1131]
Scylla Monitoring 3.5.1 (and 3.5), when scylla_manager_servers.yml lists the manager server with the correct/new (:5090) port number, are showing twice the number of nodes under "Total Nodes", and would also have the same problem under No CQL Connectivity/Active Repair/Active Backup. This is because the query is too selective:

```
count(scylla_manager_healthcheck_cql_rtt_ms{cluster=~"$cluster|$^"})
```

If you add `by (job)` to the end of this query, you clearly see the issue:

![image](https://user-images.githubusercontent.com/66674/98754936-7e7d7480-237c-11eb-9922-781b21e19cb6.png)

Changing the query to this will show the correct number of nodes:

```
max(count(scylla_manager_healthcheck_cql_rtt_ms{cluster=~"$cluster|$^"}) by (job))
```

That said, I have no idea if `max` or `min` is the appropriate aggregate here for those migrating with the old port.

**Comment by tzach** [comment]
@amnonh can we close this with https://github.com/scylladb/scylla-monitoring/pull/1132 ?
