### ISSUE TITLE
Overview dashboard: Manager snippet is misleading

### ISSUE THREAD

**Issue by nbenaglia** [scylladb/scylla-monitoring#1133]
The dashboard "Overview" has a snippet called Manager with metric:
```
1+scylla_manager_task_active_count{type=~"repair",cluster=~"$cluster|$^"} + scylla_manager_task_active_count{type=~"backup",cluster=~"$cluster|$^"} * 2
```
I have Scylla Manager active and running, but this snippet (with the above metric) is misleading and says "Offline"

There should be another more meaningful metric.

![Screenshot 2020-11-11 at 18 51 30](https://user-images.githubusercontent.com/52411515/98846120-f1efb680-244e-11eb-8dfe-dad4d55caf4c.png)

scylla-version=4.2
monitoring-version=master
dashboard=overview-4-2

**Comment by amnonh** [comment]
This was fixed by ##1118 and part of 3.5.1
