### ISSUE TITLE
5 second refresh time is to fast

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#114]
On a slower network, it can cause bad experience. 30 s should be enough.

**Comment by tzach** [comment]
@tgrabiec you suggested going down to 1s
I tend toward 30s because we seen this values used in users monitoring systems.
At the end of the day, its just the default, which anyone can change.

**Comment by avikivity** [comment]
@tgrabiec probably meant the scrape interval.

The default should be reasonable, not something that results in bad experience.

**Comment by tgrabiec** [comment]
@avikivity Do you mean dashboard refresh or prometheus poll period?

**Comment by avikivity** [comment]
Dashboard refresh.

On Jan 24, 2017 21:12, "Tomasz Grabiec" <notifications@github.com> wrote:

@avikivity <https://github.com/avikivity> Do you mean dashboard refresh or
promethous poll period?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla-grafana-monitoring/issues/114#issuecomment-274904916>,
or mute the thread

**Comment by tgrabiec** [comment]
Yes, I meant the scrape interval, it's already lowered: https://github.com/scylladb/scylla-grafana-monitoring/issues/93

I've got nothing against increasing default dashboard refresh period.
