### ISSUE TITLE
99th percentile and 95th percentile Latency are no longer present on Overview of 3.5

### ISSUE THREAD

**Issue by pidiaquez** [scylladb/scylla-monitoring#1151]
scylla-version=2019.1
monitoring-version=3.5
dashboard=overview-2019-1

99th percentile and 95th percentile Latency are no longer present on Overview of 3.5

**Comment by amnonh** [comment]
@pidiaquez 
95, 99% Read/Write latencies are now shown on the same graph.

You have one on the top for the entire cluster and a per-DC on the per DC section.

Is the data missing? or are you missing the panels?

**Comment by pidiaquez** [comment]
Thanks, you right they are indeed there

but the 95 is labeled as **[Write Latencies]** and **[Read Latencies]** ( without the 95)

 and the 99 switched from chart to numeric single value ( stat ) ?

I got the filling this may generate questions from customers.

![image](https://user-images.githubusercontent.com/26748533/100051282-4d7c5580-2dfa-11eb-89f1-6fbbe68a9c50.png)

this one can be closed

**Comment by amnonh** [comment]
The read/write latencies graphs hold two lines, one for 95% and one for 99%, hovering over the graph will give you the extra information.
