### ISSUE TITLE
Recommendations for production systems

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#116]
It can be useful for production systems to have a basic configuration settings, before they start installation of Scylla-Grafana-monitoring.

For example:
1. In some environment it is impossible to install docker, what other options are available?
2. When using in production systems, define minimum requirements for storage of data (suggesting :500GB minimum). For example, default EBS volumes come at 8GB, a monitoring solution running for 3-4 days can consume the 8GB and cause monitoring data loss. 
3. provide an answer if it is possible to monitor multiple clusters from a single browser? or it is mandatory to create an installation of the scylla-grafana for each cluster?

**Comment by tzach** [comment]
> 1. In some environment it is impossible to install docker, what other options are available?

You can install Grafana and Prometheus on your own and upload the dashboard
This is the same as #123 

> 2. When using in production systems, define minimum requirements for storage of data (suggesting:500GB minimum). For example, default EBS volumes come at 8GB, a monitoring solution running for 3-4 days can consume the 8GB and cause monitoring data loss.

Require size a function of Prometheus retention value (#124) and the monitored nodes number. We need to do some calc and estimate the size per node per day. The result should be update when ever we add more metrics.

> 3. provide an answer if it is possible to monitor multiple clusters from a single browser? or it is mandatory to create an installation of the scylla-grafana for each cluster?

Prometheus and Grafana can already collect and present data from many clusters.
The right way to handle multiple clusters is by adding a label per target group and add a selector per cluster. Should be easy to do #139

**Comment by amnonh** [comment]
@tzach I think it was solved in the documentation, can we close this?

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
@amnonh please check
https://github.com/scylladb/scylla-docs/issues/1842
