### ISSUE TITLE
start-all: restart aprom container if it crashes

### ISSUE THREAD

**Issue by rjeczalik** [scylladb/scylla-monitoring#1160]
The most common reason for a crash is OOM, like this one:

```
level=info ts=2020-11-29T17:01:21.633Z caller=head.go:734 component=tsdb msg="WAL checkpoint complete" first=36551 last=36557 duration=40.386209591s
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x26d56d3, 0x16)
```

If the container was started with `--restart=on-failure`, then the service will be up without operator intervention. While it does not solve the issue for the OOM itself, it at least buys some time until the real problem is solved.

**Comment by amnonh** [comment]
@rjeczalik you can use the `-D` flag to start-all.sh to pass additional docker commands to all docker
