### ISSUE TITLE
Add info to each of the balance signs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1166]
https://github.com/scylladb/scylla-monitoring/pull/1162 adds signs for balanced (or imbalance) metrics, like connections, CQL Traffic, Node Latency etc. For each, we need to explain what metric is measured, and when it is become imbalance (formula)
The first is unique per metric 
The later can be explain in docs, and we can point to it

For example, Connections: 
is it just CQL? what about alternator? internal connections? Is it per node or core?

Example wording
The number of CQL (over TCP) connection from clients (drivers) to each Scylla Node

**Comment by amnonh** [comment]
@tzach have you look at the information each of them already has?

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
> have you look at the information each of them already has?

@amnonh not sure to which version the original issue was referring (shame on me for not including it)
Can you please point me to this info?

**Comment by amnonh** [comment]
@tzach you can either run the latest and check if that's enough or look a the dashboard code starting from here:
https://github.com/scylladb/scylla-monitoring/blob/7dbbc43a5d615540cc6ec134365ad8fe52e2eca8/grafana/scylla-overview.master.template.json#L182

**Comment by tzach** [comment]
I do not think the current descriptions are clear enough.

For example:
"Indicates that the CQL traffic is not unified between shards"

- is this metric for CQL connection, CQL operations (which?), or something else (we are not using "traffic" elsewhere)
- Is the imbalance of shared in one node, or of sum (or average?) of the same share number across all nodes?

I suggest something more explicit like:

"Indicates that the number of CQL operations (inserts, updates, deletes, reads) is not balance between shards in a node"

(which node?)
