### ISSUE TITLE
Grafana Capacity pie chart is not clear enough + Need for Capacity indication per node

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#117]
The Pie chart is not very clear and some info is missing
1. What color represents the Free / available capacity vs the used? (no legend)
2. Why does the toolbar shows '{}: [value] (%)' ? need a more professional string.
3. As for the actual calc, a single Capacity pie chart is not enough. If it's a sum of the total capacity from all nodes, than this does not reflect situation where data is not balanced, and some node/s might be storing too much data, which will assist the customer when write errors occur.
We need to create a container view / pie chart view per node to illustrate the capacity used per node.
4. From my experience in the Storage world, percentage is nice to have, but users like to know the actual capacity numbers (in GB / TB):
- Total capacity at hand
- Used capacity
- Free capacity (I assume it's not total - used. as there are reservations for Compaction or other background activities)

**Comment by eyalgutkind** [comment]
Piggy backing on this issue, 
Regarding item number 1 in the above list, change the  color of the pie chart to red when reaching out to 50% of disk capacity

**Comment by tzach** [comment]
@amnonh can you please take a look?
Its related to #125

**Comment by amnonh** [comment]
@tzach can be closed by afe76affaaf8dc78e106996a209b11009a253431

**Comment by tzach** [comment]
@amnonh what about @eyalgutkind addition:

> change the color of the pie chart to red when reaching out to 50% of disk capacity

If not solved, please open a new issue for it

**Comment by amnonh** [comment]
There is no way to change color based on values.

What we can do:
* Add an alert when disk space is low (already part of a PR)
* Add percentage to the pie chart (not just the absolute numbers)

**Comment by amnonh** [comment]
@tomer-sandler can we close this?

**Comment by tzach** [comment]
@amnonh please add commit

**Comment by amnonh** [comment]
There were a few but commit afe76affaaf8dc78e106996a209b11009a253431
Move all host related metric to a specific dashboard, where we have one pie chart per machine

**Comment by tomer-sandler** [comment]
@amnonh we can close it.
