### ISSUE TITLE
Some cases, Balance latency metric may show ∞

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1170]
![image](https://user-images.githubusercontent.com/170200/102008510-d02d6c00-3d39-11eb-849e-ef17774aab1c.png)

**Comment by amnonh** [comment]
Should be solved by #1186

**Comment by tzach** [comment]
![image](https://user-images.githubusercontent.com/170200/104601008-637ff700-5682-11eb-9410-8f79bb1b5a50.png)
