### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by sitano** [scylladb/scylla-monitoring#1177]
Please provide the latest docker build at https://hub.docker.com/r/scylladb/scylla-monitoring

**Comment by amnonh** [comment]
We don't support docker images for scylla monitoring

**Comment by sitano** [comment]
If you will ever will change your mind this is how docker-compose / docker image shall look like https://github.com/scylladb/care-pet/pull/29
@tzach https://github.com/scylladb/care-pet/blob/master/quick-start/docker-compose.yaml now we have an example of how to setup scylla monitoring in docker without all complex scripts

**Comment by amnonh** [comment]
For docker-compose (not docker image) see #273

**Comment by sitano** [comment]
@amnonh thank you! I guess I even partially solved 273d issue.
