### ISSUE TITLE
Print more info about backups

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#1180]
Scylla Manager metrics could expose more info about backups

E.g. 
show when was the last successful backup run (or their list)
show when was last failure of backup (or their list)

customer reference is in
https://scylladb.happyfox.com/staff/ticket/88

**Comment by tarzanek** [comment]
ok, this is kind of weird request, since annotations in 3.5.2 show the backups if you list a bigger time period (e.g. 24h or whatever is the time of you backup and few hours around it)
anyways
would it be possible to add some field that will show last successful backup timestmap? (and last failed, if any?) - so one can easily see what time period to look at on detailed graphs?

**Comment by amnonh** [comment]
@mmatczuk I'm assigning it to you to supply the metrics/data once it will be available I will see how to add it to the dashboard

**Comment by mmatczuk** [comment]
@amnonh can you point me to resources how you think it shall be delivered?

Unix timestamp in UTC as metric value (float)?

**Comment by amnonh** [comment]
unix timestamp should work, but i have an idea maybe I can reuse the existing metric for total backups

**Comment by tarzanek** [comment]
well I also hoped existing metrics can be reused - the graph prints it on the time axis already, or would the query to get this be too expensive?
