### ISSUE TITLE
Issue in page Install Scylla Monitoring Stack

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#1182]
I would like to report an issue in page https://scylladb.github.io/scylla-monitoring//scylla-monitoring-3.5.2/monitoring_stack

### Problem
There's a linkg to install without docker, which leads to a 404 page:
http://scylladb.github.io/scylla-monitoring/monitor_without_docker

###  Suggest a fix
The link which I found to be working is this:
https://docs.scylladb.com/operating-scylla/monitoring/2.2/monitor_without_docker.2.1/

**Comment by tzach** [comment]
@dgarcia360 we need you help on this one.
The link does work correctly on a local preview.

On production it links from https://scylladb.github.io/scylla-monitoring//scylla-monitoring-3.5.2/monitoring_stack
to 
https://scylladb.github.io/scylla-monitoring//monitor_without_docker

while it should link to https://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.5.2/monitor_without_dockerm although the link in the doc is relative `<../monitor_without_docker>`_`

Please advise

**Comment by tzach** [comment]
Another example in page 
http://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.5.2/monitoring_apis.html

link to 
http://scylladb.github.io/scylla-monitoring/monitoring_stack

**Comment by amnonh** [comment]
Fixed by 918de37e8e42bf195c4b9764566e4e106fe998e3

**Comment by dgarcia360** [comment]
@tzach Your PR will fix the issue in future releases or if you decide to update the 3.5.2 tag.  I've submitted a PR fixing other links with the same problem: https://github.com/scylladb/scylla-monitoring/pull/1187

**Comment by lauranovich** [comment]
@tzach I am not seeing this fixed, @dgarcia360 what needs to be done here?

**Comment by tzach** [comment]
@lauranovich what fix do you *not* see?
The original issue from @tomer-sandler is fixed.

**Comment by lauranovich** [comment]
When I click the links they are 404, https://scylladb.github.io/scylla-monitoring//scylla-monitoring-3.5.2/monitoring_apis/#prometheus for example.

**Comment by tzach** [comment]
> When I click the links they are 404, https://scylladb.github.io/scylla-monitoring//scylla-monitoring-3.5.2/monitoring_apis/#prometheus for example.

Which page have this link?

**Comment by lauranovich** [comment]
https://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.5.2/monitoring_stack 

"This document describes the setup of Scylla Monitoring Stack, based on[ Scylla Prometheus API](https://scylladb.github.io/scylla-monitoring/scylla-monitoring-3.5.2/monitoring_apis/#prometheus)."
 click the link Scylla Prometheus API

**Comment by tzach** [comment]
@lauranovich this is already fix in https://github.com/scylladb/scylla-monitoring/commit/d445353a5b35a5baaa5e8c022175426bec38adc9

@amnonh please backport

**Comment by dgarcia360** [comment]
@lauranovich Once https://github.com/scylladb/scylla-monitoring/commit/d445353a5b35a5baaa5e8c022175426bec38adc9 is backported to 3.5.2 or a new release is tagged it should appear as fixed.

**Comment by amnonh** [comment]
@dgarcia360 @lauranovich @tzach Actually it was backported, the issue was the trailing back-slash:
This works:
https://scylladb.github.io/scylla-monitoring//scylla-monitoring-3.5.2/monitoring_apis#prometheus

This does not work:
https://scylladb.github.io/scylla-monitoring//scylla-monitoring-3.5.2/monitoring_apis/#prometheus
