### ISSUE TITLE
Wrong units displayed in Materialized View backpressure panel

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-monitoring#1217]
This is a spinoff of Scylla issue https://github.com/scylladb/scylla/issues/7853

@aleksbykov saw the following in the monitoring 
![a](https://user-images.githubusercontent.com/584227/103654023-05f6f680-4f6e-11eb-916f-0396530679c7.png)

There are two problems here:
1. The "view flow control" has units of "ops", which is wrong. Should be seconds or milliseconds or nanoseconds or whatever is appropriate, not ops...
2. The "view update backlog" should have (IIRC) units of bytes, not 100%...

**Comment by amnonh** [comment]
@nyh What dashboard are you seeing that?

**Comment by nyh** [comment]
I don't know, @aleksbykov reported this in https://github.com/scylladb/scylla/issues/7853. There is a link there, I don't know how to tell you "what dashboard" this is, I assumed you will be able to recognize it when you see it.

**Comment by amnonh** [comment]
as I wrote on the Scylla issue, It does not look like a monitoring dashboard,  I think it's QA.

Closing, re-open if needed.

**Comment by nyh** [comment]
On which Scylla issue?
@aleksbykov could this be what @amnonh said - some non-standard dashboard which you guys added?

**Comment by aleksbykov** [comment]
@nyh , yes i saw it in out QA dashboard which we always use in sct and scylla monitoring: https://github.com/scylladb/scylla-cluster-tests/blob/master/data_dir/scylla-dash-per-server-nemesis.master.json
use next queries:
`avg(scylla_database_view_update_backlog{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}) by ([[by]])`
`avg(scylla_storage_proxy_coordinator_last_mv_flow_control_delay{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}) by ([[by]])`

**Comment by nyh** [comment]
@aleksbykov wow, I didn't know that. Why does QA invent their own dashboards instead of using the default ones?
If you guys find useful stuff missing in the default dashboards, you can report those guys to be fixed in the default ones - that's QA for the monitoring project :-)

**Comment by aleksbykov** [comment]
These dashboard show additional info for sct tests like nemesis, annotations but use prometheus stats from scylla.

**Comment by nyh** [comment]
@aleksbykov I don't know who is responsible for those extra dashbords or where to report problems in them, so I'm trying my luck here... The materialized-view statistics are not specific to sct, so SCT shouldn't have its own versions of them. When your new dashboards are wrong this is confusing and counter-productive, but when they are good, they should be integrated with the main dashboards and not only benefit QA.
