### ISSUE TITLE
Load - Scylla nodes can run at 100% - its not strange nor alarming - it should not be highlighted in red

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1224]
Panel Name: Overview
Scylla-Monitoring Version: 3.6

Scylla runs in 100% when it has things todo

**Comment by amnonh** [comment]
It's not an error, but it is something to notice, I suggest to chang the color to orange.
@tzach what do you think?

**Comment by slivne** [comment]
On Sun, Jan 10, 2021 at 4:46 PM Amnon Heiman <notifications@github.com>
wrote:

> It's not an error, but it is something to notice, I suggest to chang the
> color to orange.
> @tzach <https://github.com/tzach> what do you think?
>

If Scylla has things todo and its not at 100% disk or 100% cpu its a bug we
should fix :)

Its true that other databases can't utilize the cpu fully and if they reach
80% its alarming and a bad indication for Scylla its the other way around
