### ISSUE TITLE
Add log analysis to detect cases in OS level

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1226]
Need to add Loki log analysis for 
- Cases in which scylla was restarted because of a crash - currently we detect scylla was restarted - but not the source - if we dect this was because of a non sig term it is a bug (scylla crashed - it was not stopped)
- 
- Check the system log for os level errors (OOMKiller / disk errors)

**Comment by mykaul** [comment]
This will be done via Loki in cloud, closing for the time being.
