### ISSUE TITLE
Add additional finer grained state of nodes based on operations beeing run

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1227]
There are cases in which an operation is being run on a node 

- <del> backup upload by manager</del> Coverred by annotations
- major compaction
-  <del>node being drained </del> Coverred the node table
- node being rebuilt 
- node running nodetool flush - relates to scylladb/scylla#8271

It would help if we mark this clearly on the node view so it will be clear a node has an Admin operation running on it. 

In addition systemd reports the status of nodes - not sure if this is logged or not - but if it is it would help to export this as well - user can see we are replaying the logs / repshape the sstables at boot time.

Need to figure out how analysis of this should be done (some of these are exported as metrics - others are visible via logs) - the issue with logs is that they are at times trimmed because of bandwidth - yet its better then nothing

**Comment by amnonh** [comment]
We don't realy have a node dashboard, the closest that we have is the detail, that can, but does not have to be per node.
We can move to that direction.

Most items on the list are covered by other issues, or already implemented, but I'm leaving this here as a unified display, another place this can be shown is the node table (that already shows the node status - joining, leaving, etc')

**Comment by tzach** [comment]
> We don't relay have a node dashboard

We can add one, but  user would not know to look into it
One idea is add operation in progress in the node table, and a link to a (new) node dashboard
Note there can be more than one operation at a time

Another is add low level alert per operation, listing operations on the the alter table.

**Comment by amnonh** [comment]
@slivne can a node have more than one admin operation at the same time? A comment @avikivity had on scylla#8271 is that it adds a metric per core that most of the time is just saying, nothing happens.

If we can combine all the operation under the same metrics (and maybe report one metric per node) it could solve this

**Comment by slivne** [comment]
AFAIK there is no limitation of a single operation happening on a node

you can run major compaction on the node and multiple ones and also nodetool flush - and in parallel there will be a bootstrap of a new node in the cluster

**Comment by amnonh** [comment]
@slivne So maybe we can just limit it to a node level, and maybe we can use bit operations, so all the operations will be reported on the same metrics as a bit mask

**Comment by amnonh** [comment]
This is covered by stream operation
