### ISSUE TITLE
Provide indication of coordinator / replica errors per node

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1229]
Lets convert the errors reported by metrics at coordinator / replica level to some indication in overview and provide a shortcut to the appropriate location 

this can be done at the node level - we have that at the per dc listing

https://docs.google.com/drawings/d/1-k1JMR-64HLrQZXfmBuAc5mia1ZY4gTV3eh5vK2j4i4/edit?usp=sharing

alternatively we can decide to have this as an error indicator - generic one for the whole cluster and then jump from it to the causes.

**Comment by amnonh** [comment]
relates to #1035
We allready have advisor warning on different kind of errors
