### ISSUE TITLE
Easy installation and upgrade without Docker

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#123]
Some users do not want to run Docker.
We should provide instructions on setting up the monitoring stack on top of Grafana and Prometheus install. It can be as easy as running the API part of the start-all.sh script, uploading the dashboard

**Comment by eyalgutkind** [comment]
@tzach Is there anyone we can work with on making this procedure happen?

**Comment by amnonh** [comment]
@tzach I think we can close this

**Comment by amnonh** [comment]
@tzach ping
