### ISSUE TITLE
Proposal: Maintain a stable tag

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylla-monitoring#1233]
Related issue: https://github.com/scylladb/sphinx-scylladb-theme/issues/87

Every repository with docs could maintain a `stable` tag. The purpose is to have a default link to share that does not change, which is also beneficial for SEO purposes.

## Create / Update the tag

**Note:** Before creating the tag, please merge https://github.com/scylladb/scylla-monitoring/pull/1222

To create a `stable` tag, the repo maintainer should run the following commands:

```
# Creates or updates the tag reference. You can change HEAD for a commit id.
git tag -f stable HEAD
# Publishes all local tags to the remote repository.
git push --tags
```
Every time you create a new release that's stable, the tag reference should be updated. Once the tag is created, please ping me, and I'll submit a PR including this tag to the docs build.
 
## Alternative

If you don't want to maintain the stable tag, we'll build docs for ``master`` or equivalent default branch. However, since this branch is used normally to integrate changes, it might be possible that the docs are not aligned with the latest published version.

**Comment by amnonh** [comment]
seems like a duplicatin of #1107

**Comment by lauranovich** [comment]
@amnonh - it is - let's close one
