### ISSUE TITLE
Provide Prometheus retention value

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#124]
Without a retention value, Prometheus will fill up the disk.
Prometheus expose this value with `-storage.local.retention` parameter.
The actual value depends on the use case and disk

**Comment by avikivity** [comment]
I think 1 month is a sensible default.

**Comment by gmizrahi** [comment]
We use a 20GB instance and had to reduce the retention time to 7 days.
for 8 nodes and 7 days our disk usage is 5.6GB just for the Prometheus data.

It is something which needed to be taken into consideration...

**Comment by avikivity** [comment]
All I can say is, the number of metrics is going to increase all the time.

**Comment by amnonh** [comment]
@tzach please close this issue or merge the pull request

**Comment by tzach** [comment]
fix by #250 
retention is avilable as a command line option 
```
-b storage.local.retention=1000h
```

**Comment by JackThird** [comment]
> fix by #250 retention is avilable as a command line option
> 
> ```
> -b storage.local.retention=1000h
> ```

-b storage.local.retention=1000h didn't work for me.

As per prometheus 2.43 documentation (https://prometheus.io/docs/prometheus/latest/storage/) there are new parameters for retention:
-b "-storage.tsdb.retention.time=7d"
or/and
-b "-storage.tsdb.retention.size=1GB"
