### ISSUE TITLE
DOCS: Index default version is not correct

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla-monitoring#1240]
http://monitoring.docs.scylladb.com/scylla-monitoring-3.5.2/index.html is the default home page 
it should be
http://monitoring.docs.scylladb.com/scylla-monitoring-3.5.3/index.html
![Screenshot from 2021-01-14 19-46-52](https://user-images.githubusercontent.com/36125151/104628894-781fb780-56a1-11eb-8dcd-28be15d7c4b7.png)
when you go to 3.5.3 you are told that the version is old and that 3.5.2 is the newer version when the opposite is true
![Screenshot from 2021-01-14 19-46-37](https://user-images.githubusercontent.com/36125151/104628992-92f22c00-56a1-11eb-9f48-f43c96f62437.png)
the correct version is set in the pages.yaml

**Comment by lauranovich** [comment]
@dgarcia360 please advise

**Comment by tzach** [comment]
@lauranovich is this still valid?

**Comment by dgarcia360** [comment]
I believe this was fixed, now the latest is ``stable`` which points to ``3.6.0``.
