### ISSUE TITLE
need a compitability matrix for grafana prometheus to monitoring version

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1241]
For users that use their own servers, we need to specify what versions they need to use

**Comment by amnonh** [comment]
Monitoring | Prometheus|Grafana|
---------------|-----------------|-----------|
3.4 | 2.18.1|6.7.3|
3.5|2.18.1|7.1.5|
3.6|2.18.1|7.3.5|

**Comment by lauranovich** [comment]
@amnonh - sorry to bounce this back to you can you please define "their own servers"
Do you mean that they download the Monitoring stack but want to use their own version of Grafana or Prometheus? 
If so do we have installation instructions that specify that this can be done and how?

**Comment by amnonh** [comment]
You are refering to: http://monitoring.docs.scylladb.com/stable/monitor_without_docker.html

The compatibility matrix is what version of prometheus/grafana is needed

**Comment by lauranovich** [comment]
@amnonh so this ^^ table needs to be on this -> page? : http://monitoring.docs.scylladb.com/stable/monitor_without_docker.html??

let me know

**Comment by amnonh** [comment]
I think so, or with a direct link from it
