### ISSUE TITLE
Provide some indication of hinted handoff being accumulated / being sent  

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1258]
We have metrics for hints being written / sent - yet on the overview we need a simple indication of hints being written/sent vs not

(naturally when this happens latency of ongoing requests maybe higher)

**Comment by amnonh** [comment]
We have it in the detailed dashbaord, not sure it shuld be part of the overview dashboard

**Comment by slivne** [comment]
Its like repair or backup running in the background

**Comment by amnonh** [comment]
relates to #1227

**Comment by amnonh** [comment]
We have two options here:
1. show a text (like the text we show in the nodes table) which is relevent if it happens right now
2. use annotation, that have the benefit of showing history and show it on a graph, annotations can be turn on or off by defatult

@slivne ping

**Comment by amnonh** [comment]
@slivne I'm assigning it to you just for the decision, I think annotations are better becasue of the context and history.

**Comment by amnonh** [comment]
Closed by #1281
