### ISSUE TITLE
Issue in page Install Scylla Monitoring Stack

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla-monitoring#1260]
I would like to report an issue in page https://monitoring.docs.scylladb.com/scylla-monitoring-3.6.0/monitoring_stack

### Problem
in section Download and extract the latest Scylla Monitoring Stack binary - the version is missing:

```
wget https://github.com/scylladb/scylla-monitoring/archive/scylla-monitoring-|version|.tar.gz
tar -xvf scylla-monitoring-|version|.tar.gz
cd scylla-monitoring-scylla-monitoring-|version|
```

###  Suggest a fix

**Comment by tzach** [comment]
@dgarcia360  can you please provide a way to use a variable in side a code section? 
 @amnonh please fix manual for now
