### ISSUE TITLE
0 writes with 120us writes latency

### ISSUE THREAD

**Issue by yakirgb** [scylladb/scylla-monitoring#1261]
scylla-version=4.1
monitoring-version=master
dashboard=overview-4-1
How it possible that i have 127us writes latency with 0 writes to cluster( 100% that not was writes to cluster at this time)
And after that i started writes into cluster, writes latency reduced instead increase.
![image](https://user-images.githubusercontent.com/12082308/106145639-74e6fa00-617e-11eb-874d-41ff7311a569.png)

Thank you, Yakir Gibraltar

**Comment by dorlaor** [comment]
Could it be a system table write? Anyway, even more puzzling is the 50us
latency with 100k ops

**Comment by yakirgb** [comment]
Could be system table, [as i wrote in Slack](https://scylladb-users.slack.com/archives/C2NLNBXLN/p1611828105173900), right now scylla have a log of metrics for debug shards but not simple and useful metrics for overview on tables and keyspaces.
I'm doing tests between C* 4 and Scylla, and right now it's very hard to compare with peaks of latency in graphs, even with 0 load.
The cluster was without any work during few 12 hours, should be 0 latency. 
Example from now, the cluster **without any activity** but still have peaks or read(2ms)/write(1ms) latency 
![image](https://user-images.githubusercontent.com/12082308/106193850-bd220e80-61b6-11eb-99e3-34dda53e413a.png)

**Comment by dorlaor** [comment]
It's the system table and/or Scylla manager keep alive CQL query.
I am sure that you don't really care about the performance at 0 ops,
per my calculations Scylla is 1000x better at 0 ops than any other database
;)

Looking forward to the performance under load. Pls make sure you use the
sharded drivers. Also best to use a client with coordinated
omission support,
tls-stress doesn't have one

**Comment by tzach** [comment]
Both Scylla Manager and Scylla Monitoring (in latest version) use CQL requests to Scylla periodically.
If this is important, you can try activate full tracing and see if this is the case. IMHO is meaningless to look at latency numbers with out load.

**Comment by yakirgb** [comment]
Hi @dorlaor  and @tzach , thank you for your answer.

> Looking forward to the performance under load. Pls make sure you use the
> sharded drivers. Also best to use a client with coordinated
> omission support,
> tls-stress doesn't have one

 I'm using `tlp-stress` with scylla with `scylla-driver`, complied from : https://github.com/tarzanek/tlp-stress


Just thinking, I'm loading data into one table only, maybe the latency during load in graphs coming from system table/s and not from my table.
Another option, maybe the compare of metrics of C* and Scylla it's incorrect,  i'm checking coordinator read latency on C*4  via:
`cassandra_stats{name=~"org:apache:cassandra:metrics:table:coordinatorreadlatency:95thpercentile,..."}`
While on Scylla it's:
`histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{...}[60s])) by (le))`

**Comment by yakirgb** [comment]
@tzach @dorlaor 
I did simple test:
1. Changed `--enable-keyspace-column-family-metrics 1 ` to all nodes
2. Started load on cluster

I created 4 metrics of:

1. p95 Read latency on all keyspaces: `histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket[120s])) by ( le))`
2. p95 Write  latency on all keyspaces: `histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket[120s])) by ( le))`
3. p95  Read latency only on tlp_stress keyspace: `histogram_quantile(0.95, sum(rate(scylla_column_family_read_latency_bucket{ks="tlp_stress"}[120s])) by (le))`
4. p95  Write latency only on tlp_stress keyspace: `histogram_quantile(0.95, sum(rate(scylla_column_family_write_latency_bucket{ks="tlp_stress"}[120s])) by (le))`


You can see in my graph that read/write latency on tlp_stress are 90-100us but read latency on all keyspaces it's up to 473us.
So, it's clear that latency coming from system keyspace.
But looks that `--enable-keyspace-column-family-metrics 1` is not working on system keyspaces, all the values of `scylla_column_family_write_latency_bucket`/ `scylla_column_family_read_latency_bucket` are 0 exclude on `tlp_stress`

Based on `tablestats` looks that `system.local` with high read latency but i have no idea why:
```
[root@r1 ~]#  nodetool tablestats -- system.local| grep "read latency"
		Local read latency: 0.380 ms
```
![image](https://user-images.githubusercontent.com/12082308/106479872-77658e80-64b3-11eb-922a-cfbc4d8d1f9a.png)


1. How can i know what making the load on `system.local` ?
2.  I think that need to exclude system keyspaces from `scylla_storage_proxy_coordinator_read_latency_bucket` by default and show only keyspaces that users created.
3. Enable `--enable-keyspace-column-family-metrics` increasing the number of metric to 262.7K per host, remove shards from metrics, will reduce to 8.2K metrics per host (include all KS/CF details! amazing).
4. I think that need to take Prometheus config from scylla-server.service into external service of scylla-prometheus.service like [cassandra_exporter](https://github.com/criteo/cassandra_exporter) or [jmx_exporter](https://github.com/prometheus/jmx_exporter), in the new service will be option to make allowlist/denylist/rules(like remove shards or CAS metrics)/change port/change collection interval for heavy metrics/etc... , and all this changed without restart scylla-server.service
5. Not need all metrics on same endpoint of `localhost:9180/metrics`, it possible to split into two endpoints of : `localhost:9180/metrics-short` and `localhost:9180/metrics-debug` , all the debug metrics with shards will on `metrics-debug` but the top useful 1-10K metrics will be in `localhost:9180/metrics-short`

Thank you, Yakir.

**Comment by tarzanek** [comment]
the drivers do talk to system.local to get metadata and possibly do a heartbeat, after connect metadata they should piggyback on cql traffic,
how many times do you reconnect in your tests? (how many times tlp reconnects?)

ideally is to enable tracing: https://docs.scylladb.com/using-scylla/tracing/#tracing 
and check what is happening (either probability or slow query logs)

**Comment by yakirgb** [comment]
Hi @tarzanek , my test is simple, running [tlp-stress](https://github.com/tarzanek/tlp-stress/commits/master) 
```
/root/tlp-stress/bin/tlp-stress run KeyValue -d 1d -p 100M -c 100 --pg sequence -t 4 -r 0.2 --rate 30K --populate 200000 --replication "{'class': 'NetworkTopologyStrategy', 'my_data_center': 3}" --cl LOCAL_ONE --compaction "{'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}" --ttl 86400 --host rc1.tab.com --field.keyvalue.value='random(1000,7000)' --prometheusport "$(echo $(( ( RANDOM % 10000 )  + 1 )))" >/dev/null 2>&1 </dev/null &
/root/tlp-stress/bin/tlp-stress run KeyValue -d 1d -p 100M -c 100 --pg sequence -t 4 -r 0.2 --rate 30K --populate 200000 --replication "{'class': 'NetworkTopologyStrategy', 'my_data_center': 3}" --cl LOCAL_ONE --compaction "{'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}" --ttl 86400 --host rc2.tab.com --field.keyvalue.value='random(1000,7000)' --prometheusport "$(echo $(( ( RANDOM % 10000 )  + 1 )))" >/dev/null 2>&1 </dev/null &
/root/tlp-stress/bin/tlp-stress run KeyValue -d 1d -p 100M -c 100 --pg sequence -t 4 -r 0.2 --rate 30K --populate 200000 --replication "{'class': 'NetworkTopologyStrategy', 'my_data_center': 3}" --cl LOCAL_ONE --compaction "{'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}" --ttl 86400 --host rc3.tab.com --field.keyvalue.value='random(1000,7000)' --prometheusport "$(echo $(( ( RANDOM % 10000 )  + 1 )))" >/dev/null 2>&1 </dev/null &
/root/tlp-stress/bin/tlp-stress run KeyValue -d 1d -p 100M -c 100 --pg sequence -t 4 -r 0.2 --rate 30K --populate 200000 --replication "{'class': 'NetworkTopologyStrategy', 'my_data_center': 3}" --cl LOCAL_ONE --compaction "{'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}" --ttl 86400 --host rc4.tab.com --field.keyvalue.value='random(1000,7000)' --prometheusport "$(echo $(( ( RANDOM % 10000 )  + 1 )))" >/dev/null 2>&1 </dev/null &
/root/tlp-stress/bin/tlp-stress run KeyValue -d 1d -p 100M -c 100 --pg sequence -t 4 -r 0.2 --rate 30K --populate 200000 --replication "{'class': 'NetworkTopologyStrategy', 'my_data_center': 3}" --cl LOCAL_ONE --compaction "{'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}" --ttl 86400 --host rc5.tab.com --field.keyvalue.value='random(1000,7000)' --prometheusport "$(echo $(( ( RANDOM % 10000 )  + 1 )))" >/dev/null 2>&1 </dev/null &
/root/tlp-stress/bin/tlp-stress run KeyValue -d 1d -p 100M -c 100 --pg sequence -t 4 -r 0.2 --rate 30K --populate 200000 --replication "{'class': 'NetworkTopologyStrategy', 'my_data_center': 3}" --cl LOCAL_ONE --compaction "{'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}" --ttl 86400 --host rc6.tab.com --field.keyvalue.value='random(1000,7000)' --prometheusport "$(echo $(( ( RANDOM % 10000 )  + 1 )))" >/dev/null 2>&1 </dev/null &
```

After 24 hours of tests looks that system KS taking a lot of resources:
P95 Write latency on all keyspaces(tlp_Stress + system): 16.06 ms
P95 Read latency on all keyspaces(tlp_Stress + system): 4.77ms
P95 Write latency on tlp_stress only: 98us
P95 Read latency on tlp_stress only: 2.82 ms
\* Ignore the title in graph
![image](https://user-images.githubusercontent.com/12082308/106746567-663f8d80-662b-11eb-94b3-88c521455081.png)

BTW, working on recording rules for latency graphs, the Grafana/PRom* unable to handle all the metrics, i cannot see data overtime, like 24 hours-7 days, the Prom* need to filter 203K from every collect, it's 292,320,000 metrics per day, and it's only for one graph of  metrics of latency:
![image](https://user-images.githubusercontent.com/12082308/106749728-91c47700-662f-11eb-9320-cb85e4c1604d.png)

**Comment by amnonh** [comment]
Changes in release 3.6.1 should solve this issue, you will need to update to a newer version (4.2 or 4.3) or to enterprise 2020.1.
Specifically #1265

Scylla uses scheduling group for low priority tasks, in practice some internal operatios would take longer on purpose in favor of user traffic, which would populate the 99% latency.

In monitoring 3.6.1 the reported graphs are for the users traffic and this confusion should be removed.

I'm closing this issue, please reopen if you think it is needed
