### ISSUE TITLE
Update all advisor / cql dashboard queries taking into account only the user gerenated queries and not internal ones

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1263]
Some of scylla internal queries are non pages and non pre-pared

While in some cases we will work to fix that - some queries are very rare and it may not be neded / may be atoo big of an effort to convert them.

We can remove those queries and only consider user's queries as we do have counters exposing the internal query counts

```
# HELP scylla_cql_reads_per_ks Counts the number of CQL SELECT requests executed on particular keyspaces. Label `who' indicates where the reqs come from (clients or DB internals)
scylla_cql_reads_per_ks{ks="system",shard="0",who="internal"} 27
scylla_cql_reads_per_ks{ks="system",shard="1",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="2",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="3",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="4",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="5",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="6",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="7",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="8",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="9",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="10",who="internal"} 12
scylla_cql_reads_per_ks{ks="system",shard="11",who="internal"} 12
```

update the metrics and inputs reducing the internal generated queries and then provide the inputs on non-pages / non-prepared / non tokenaware based on that.

**Comment by amnonh** [comment]
@slivne what scylla versions is this part of?
One more thing, we can calculate the user traffic by subtracting the per_ks{"internal"} from the total value, but then the ratio will become meaningless

We show ``Unpreparded/Total_number_of_CQL``
as some of the internal queries are prepared, we cannot just subtract the internal queries from the unprepared counter, we may get to negative

**Comment by slivne** [comment]
amnon git blame and git log will provide you the answer

**Comment by amnonh** [comment]
@slivne but not will solve the actual problem, of how to calculate the ratio

**Comment by slivne** [comment]
It will be more correct to begin with - the number of internal queries is
supposed to be small - so its just to fix misleading the user that is doing
everything correct that he has unprepared statements / non paged queries.

There is a bigger issue with system tables - and we should also reduce all
of those - since drivers generate non paged and non prepared statements -
so we should remove the could for all the kesyapces that are ours

system + system_schema + system_auth + system_tracing + system_distributed

**Comment by amnonh** [comment]
@slivne the problem is with the numerator 

We know what the denominator is (i.e. requests done by the users) but i have no way of calculating the non-prepared done by the user, because some of the internal requests are prepared.

**Comment by slivne** [comment]
reduce the internal and system* table from both ....  (it will not be 100%
percent correct - e.g. we may miss some user non prepared statements - but
it will not be the other way around).

If there is a lot of traffic it will be negligible since internal is
supposed to be low.

**Comment by amnonh** [comment]
It can become negative

**Comment by slivne** [comment]
so make sure it doesn't ... max (0, value).

**Comment by amnonh** [comment]
it's not that simple but set it aside, it's just a meaningless number negative is the extreme

**Comment by slivne** [comment]
- Currently internal queries are not prepared (maybe aside of tracing)
- most drivers do not prepared the queries for system* (maybe in gocql they
are - since they auto prepare).

SoI think the reality is that it  will be correct.
