### ISSUE TITLE
Grafana: Node down-normal not reflected in Grafana as down (we need a better indication of node Status+state possible combinations)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#127]
Bug: node can be Down-Normal (DN), but currently is not reported as Down in Grafana.
I run Cassandra stress fill-up the capacity in each node to 90% (and even more). Eventually write ACK failed which led to moving the node out of the cluster ->  state is Down-Normal (DN), but this is not reflected in Grafana.

We should have an indication for all of the node Status+State possible combinations.

[tomer@tomer-4cpu-15gb-rhel7-2 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens  Owns    Host ID                               Rack
DN  10.240.0.26  36.46 GB   256     ?       61782a07-2c58-41ee-b40b-938a1570acec  rack1
UN  10.240.0.27  31.15 GB   256     ?       acdcf6a6-bf4a-4f61-804b-6846f23bd822  rack1
DN  10.240.0.28  36.57 GB   256     ?       654d04a5-ad47-4c9d-b18f-87ddcdc1d47e  rack1

**Comment by amnonh** [comment]
@tomer-sandler can you test with 3.0 dashboards?

**Comment by tomer-sandler** [comment]
@slivne / @roydahan - can QA please test it, if it's not already part of the ongoing regressions (might be that you already tested it...). Thanks.
