### ISSUE TITLE
Docs: Stable branch should not replace the release number

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1277]
For example:
https://monitoring.docs.scylladb.com/scylla-monitoring-3.6.0/monitoring_stack
should still exist, even if 3.6.0 is currently the latest

@dgarcia360

**Comment by dgarcia360** [comment]
The latest version of the multiversion extension addresses this issue.
This should be automatically fixed with the next documentation build. 
For example, docs will be build again when we merge https://github.com/scylladb/scylla-monitoring/pull/1278

**Comment by dgarcia360** [comment]
@tzach This can be closed, http://monitoring.docs.scylladb.com/scylla-monitoring-3.6.0/index.html is working now.

**Comment by tzach** [comment]
Thanks @dgarcia360 !
