### ISSUE TITLE
Add Safe-Mode / Production indication

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1280]
We have the CQL connecttor that is able to read data from the CQL tables

We have issues related to Safe-Mode in Scylla - some of them related to schema 

https://github.com/scylladb/scylla/issues/6923

https://github.com/scylladb/scylla/issues/6635

Need to align with @eliransin on Safe-Mode and how it will be exposed / given that it will take time to rollout this features - it may make sense to add a validator in scylla-monitoring to expose this info to the user (even prior to having scylla have a mechanism to block this)

**Comment by mykaul** [comment]
@amnonh - any idea what's the next step here?

**Comment by amnonh** [comment]
I'm not sure what the status of Scylla Safe mode, I'm not even sure it has a time frame.
The header make sense, if we'll have a Safe mode in Scylla we would like an indication if it's on or off.

Not sure about the suggested implementation. There are plenty of ways of getting information from Scyllas

**Comment by mykaul** [comment]
@tzach - I think we can close this?

**Comment by tzach** [comment]
> @tzach - I think we can close this?

Yes
