### ISSUE TITLE
Huge spike in "active sstable reads" after restart

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#1284]
scylla-version=4.1
monitoring-version=master
dashboard=detailed-4-1

![image](https://user-images.githubusercontent.com/1017210/107926219-198a7980-6f7e-11eb-946e-1852d2aaf8fa.png)

**Comment by amnonh** [comment]
@avikivity this is a scylla issue:
https://github.com/scylladb/scylla/issues/7762
