### ISSUE TITLE
Active Alert table is not readable 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1289]
*Installation details*
Panel Name: Active Alert
Dashboard Name: Overview
Scylla-Monitoring Version: 3.6.1
Scylla-Version: 4.5.dev-0.20210211.718976e79 with build-id

![image](https://user-images.githubusercontent.com/170200/108326671-34096080-71d3-11eb-90ef-8b44ad6eb8a1.png)

- Time format is wrong
- Alert description is too short, provide no info
- Alert IPs appears twice
Look like the Alert table deserve more space

Source: https://github.com/scylladb/scylla/issues/8115

**Comment by amnonh** [comment]
Duplication of #1288

**Comment by tzach** [comment]
@amnonh I do not understand how a new plugin version can fix the width issue

**Comment by amnonh** [comment]
The old plugin does not work with the new table format, without that we cannot do any changes to the table
