### ISSUE TITLE
inconsistency use of legends in DC panel 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1290]
### Installation details
Panel Name: Information For *
Dashboard Name: Overview
Scylla-Monitoring Version: 3.6.1
Scylla-Version: 4.5.dev-0.20210211.718976e79 with build-id

### Problem
Legend is (sometime) useful when there are more than one series of data.
The panel have it for charts with one line (read/write)
And do not have for chart with more than one charts, when it can be useful (Cache hit/missed) 

![image](https://user-images.githubusercontent.com/170200/108328703-95323380-71d5-11eb-8ee7-0677749c1860.png)
source: https://github.com/scylladb/scylla/issues/8115

* Information For is a strange name for a section

**Comment by amnonh** [comment]
The information should be the name of the DC, maybe there is no DC configured in your configuration?
