### ISSUE TITLE
Install section - need to "add IP" example 

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla-monitoring#13]
Under Install section, there is no example how the IP format need to look like:
['<server_ip>:<port>'] in case that there is more than one server - use comma to separate between the IP

**Comment by tzach** [comment]
@nirmaayan I'm closing since this issue is not relevant anymore.
The IP is extract automatically from the docker container.

**Comment by nirmaayan** [comment]
@tzach np
