### ISSUE TITLE
Need an advisor documentation

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1303]
The avisor issues needs specific explenation on what the issue is an links on how to solve them.

To link the advisor to a doc issue, we need a simple url path, the simplest will be to add a advisor section in the documentation:
Something like:
http://monitoring.docs.scylladb.com/scylla-monitoring-3.6.0/advisor/ **issues**/**id**

So each advisor issue would get its own page with a few description lines and links to the main scylla documentation

**Comment by amnonh** [comment]
@tzach you are assign on this to get feedback

cc @slivne

**Comment by lauranovich** [comment]
@amnonh - if you can give me a list of possible "errors" or "warnings" I can create a table so we can map it to the correct page in the docs and where docs are missing we will provide the content.

**Comment by amnonh** [comment]
https://docs.google.com/document/d/1uJsKHMZqN9iELRfQHwPUp3CR914q5MIAoz1_cYHx46g/edit#heading=h.35w1g1jqbw57

**Comment by amnonh** [comment]
Closed by #1347
