### ISSUE TITLE
Incorrect node count

### ISSUE THREAD

**Issue by prasus** [scylladb/scylla-monitoring#1307]
Greetings, I have deployed scylla monitoring v3.6 for having monitoring capabilities for our scyllaDB clusters deployed by scyllaDB operator v1.1.0-rc.3 (upgraded from v.1.0). We already have a prometheus stack running in our enviornment hence I haven't created new deployment of Prometheus and grafana and have integrated scylla specific `ScrapeConfigs` from [monitoring/values.yaml](https://github.com/scylladb/scylla-operator/blob/master/examples/common/monitoring/values.yaml#L86-L123) and then followed the procedure listed [here](https://github.com/scylladb/scylla-operator/blob/master/docs/source/monitoring.md)

The setup works fine and the dashboards looks good,  the only issue we have is that it incorrectly lists the node count 🙁. we only have got 2 singe node cluster's in the test environment, but the node count shows as 4 in the `# Nodes` dashboards panel.  I think it just ignores the cluster selection (`count(up{job="scylla", cluster=~"$cluster|$^"})`) and counts everything `job="scylla"` label

The promQL query `count(up{job="scylla"})` has 4 objects with `job="scylla"` label as seen below, Is there a way to fix this and get the actual cluster node count in the dashboard? Thanks!

```promql
up{container="scylla",endpoint="prometheus",instance="10.24.83.1:9180",job="scylla",namespace="scylla",pod="simple-cluster-us-east-1-us-east-1a-0",scylla_cluster="simple-cluster",scylla_datacenter="us-east-1",service="simple-cluster-client"} | 1
up{container="scylla",endpoint="prometheus",instance="10.244.3.173:9180",job="scylla",namespace="scylla-manager-system",pod="scylla-manager-manager-dc-manager-rack-0",scylla_cluster="scylla-manager",scylla_datacenter="manager-dc",service="scylla-manager-client"} | 1
up{endpoint="agent-prometheus",instance="10.24.83.1:5090",job="scylla",namespace="scylla",pod="simple-cluster-us-east-1-us-east-1a-0",scylla_cluster="simple-cluster",scylla_datacenter="us-east-1",service="simple-cluster-client"} | 1
up{endpoint="agent-prometheus",instance="10.244.3.173:5090",job="scylla",namespace="scylla-manager-system",pod="scylla-manager-manager-dc-manager-rack-0",scylla_cluster="scylla-manager",scylla_datacenter="manager-dc",service="scylla-manager-client"} | 1

```

scylla-version=4.3
monitoring-version=master
dashboard=overview-4-3, Advanced-4.3

**Comment by amnonh** [comment]
Yes, it count the empty cluster as well (i.e. scrap jobs without a cluster label), the promql that can be used instead is:
count(up{job="scylla", cluster="$cluster"})).

Typically, job `scylla` is only for the scylla nodes and historically, not everyone set their cluster label.
Maybe it's time to change it

**Comment by prasus** [comment]
Thanks @amnonh I had to use the below query to make it display the correct cluster member count.

`count(up{job="scylla", scylla_cluster=~"$cluster|$^", endpoint=~"prometheus"})`

As you see it in the above promQL query result, the `agent-prometheus` endpoint was also counted so I had to explicitly specify the endpoint name, also somehow the `cluster` label is not available in the `count(up{job="scylla"})` result so had to use scylla_cluster. Thanks! 🙂

**Comment by amnonh** [comment]
The issue you are having is around your prometheus configuration, you can fix it by leaving only scylla nodes under the scylla job (and use somether job for non-scylla nodes) and make sure you add a cluster label to the scylla nodes.

Regardless, you can remove the |$^ part, the nodes should have a cluster name configure as a "claster" label,
I'm closing this issue as a configuration problem
