### ISSUE TITLE
Per server storage chart

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#131]
While the current chart only shows the summary of all servers file system
Its important to know if one of the servers is getting close to its storage capacity.

The dashboard needs to include a compact chart of storage per server, with alarms on a file system which is more than 50% full.

**Comment by amnonh** [comment]
Pie charts does not support alaram

**Comment by tzach** [comment]
@amnonh no need to attach this to the pie chart
we need to set an alarm on an event

**Comment by amnonh** [comment]
On Thu, Mar 2, 2017 at 11:47 AM, Tzach Livyatan <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> no need to attach this to the pie
> chart
> we need to set an alarm on an event
>
Split it into two issues, and explain what would you like to see in the
storage pie chart

**Comment by amnonh** [comment]
@tzach can be closed by afe76affaaf8dc78e106996a209b11009a253431
