### ISSUE TITLE
Extend dead an live node metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#133]
Scylla nodes have two statuses:  U (up) or D (down)
and two states: N (normal), L (leaving), J (joining), M (moving)

Currently, nodes in DN states are reported as Alive, altho they are not part of the cluster. This can be a result, for example, of a full disk.

**Comment by tzach** [comment]
related to https://github.com/scylladb/scylla/issues/1234 and #83

**Comment by nirmaayan** [comment]
@tzach any progress with this issue?

**Comment by tzach** [comment]
Yes, @benoit-canet commit https://github.com/benoit-canet/scylla/commit/8241cfc091c092cb66d3b31e0409d2791103da07 add the relevant info to metrics. Now we need to update the Dashboard to include it.
@amnonh want to try?

**Comment by amnonh** [comment]
It's not merged yet

**Comment by nirmaayan** [comment]
@amnonh did you merged it yet?

**Comment by amnonh** [comment]
Benoit code is not merged, you can check with our committers about it

**Comment by tzach** [comment]
@benoit-canet @amnonh any update?

**Comment by nirmaayan** [comment]
@benoit-canet @amnonh ping

**Comment by nirmaayan** [comment]
@benoit-canet @amnonh ping

**Comment by nirmaayan** [comment]
@amnonh was Benoit code merged?

**Comment by amnonh** [comment]
@tzach can we close this in 3.0?
