### ISSUE TITLE
Issue in page Scylla Monitoring Stack: No SSL (https)

### ISSUE THREAD

**Issue by PeterCorless** [scylladb/scylla-monitoring#1344]
I would like to report an issue in page https://monitoring.docs.scylladb.com/scylla-monitoring-3.6.3/index

### Problem

Warning: **http://** monitoring.docs.scylladb.com/ is not secure.

###  Suggest a fix

Add SSL (**https://**).

**Comment by tzach** [comment]
@amnonh as project admin you can enforce https from the project setting
![image](https://user-images.githubusercontent.com/170200/113098759-9194c200-9201-11eb-953a-a20f8cac291b.png)

**Comment by amnonh** [comment]
I don't have the permission to change that

**Comment by lauranovich** [comment]
@tzach assigning this to you as I don't have permissions

**Comment by tzach** [comment]
Closing. HTTPS is enforced for some time now.
