### ISSUE TITLE
Doc: Add link to Monitoring Git in the top menu 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1345]
Add a link to the project github page
See https://prometheus.io/ for an example with the github icon

Maybe we can add this to the Scylla doc design.

**Comment by lauranovich** [comment]
![Screenshot from 2021-03-31 11-14-59](https://user-images.githubusercontent.com/36125151/113113069-99a92d80-9212-11eb-9a36-06d4911421e4.png)
![Screenshot from 2021-03-31 11-15-17](https://user-images.githubusercontent.com/36125151/113113064-98780080-9212-11eb-9bd5-70105d25478c.png)

**Comment by lauranovich** [comment]
@amnonh - this enhancement will be handled in the new design we are implementing. I already reorganized the content and the link to the project is a bit more prominent. I will also add a github icon but this will take some time.
