### ISSUE TITLE
Revisit the Doc tree

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1346]
- High level description
- Using Scylla Monitoring
  - The CQL Optimization
  - Advisor
- Install + Download
  - Start-all
  - Non docker
  - Compose
  - Thanus
- Procedures
  - Alerting
  - Adding and Modifying Dashboards
  - Upgrade
- Troubleshooting
- Reference
  - Start All options
  - Support Matrix

**Comment by lauranovich** [comment]
closing - fixed with #1353
