### ISSUE TITLE
Something is broken with the advisor doc

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1360]
![image](https://user-images.githubusercontent.com/2118079/114403639-a54f0980-9bad-11eb-94b5-12cbb8492716.png)
https://github.com/scylladb/scylla-monitoring/runs/2324279554?check_suite_focus=true

**Comment by lauranovich** [comment]
@dgarcia360 - can you assist here please?

**Comment by tzach** [comment]
@amnonh @lauranovich look like the redirect part is broken

**Comment by tzach** [comment]
Relevant error:
```
Exception occurred:
  File "/home/runner/.cache/pypoetry/virtualenvs/scylla-monitoring-docs--KRTMvsg-py3.7/lib/python3.7/site-packages/sphinx_scylladb_theme/extensions/redirects.py", line 97, in create_redirects
    with open(os.path.join(target_path + '.html'), 'w') as t_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/scylla-monitoring/scylla-monitoring/docs/_build/dirhtml/scylla-monitoring-3.7.0//advisor/cqlAllowFiltering.html'
```

I suggest to temporary remove the redirection to fix this

**Comment by lauranovich** [comment]
I see the error 
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/scylla-monitoring/scylla-monitoring/docs/_build/dirhtml/scylla-monitoring-3.7.0//advisor/cqlAllowFiltering.html'
there is a double ``//`` but this cannot be found where I thought it would be.
