### ISSUE TITLE
Make it easy to run grafana and Scylla in the same machine

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla-monitoring#137]
I had to add --net="host" before each 'docker run' for prometheus container to interact with scylla and node-exporter. We possibly don't wanna to attach container to host interface by default, so how about adding an option like --local to start-all.sh?

**Comment by tzach** [comment]
@raphaelsc can you elaborate on why it was required?
I used Scylla, Grafana and Prometheus on the same machine with no problems.

**Comment by raphaelsc** [comment]
On Wed, Feb 22, 2017 at 3:26 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> can you elaborate on why it was
> required?
> I used Scylla, Grafana and Prometheus on the same machine with no problems.
>

Scylla and node-exporter listen on 127.0.0.1, and prometheus container
wasn't able to communicate with them using the bridge interface. Do you use
external ip address?

I patched start-all.sh as follow:

diff --git a/start-all.sh b/start-all.sh
index 8a76dbe..a5d6d27 100755
--- a/start-all.sh
+++ b/start-all.sh
@@ -53,11 +53,11 @@ fi

 if [ -z $DATA_DIR ]
 then
-    sudo docker run -d \
+    sudo docker run --net="host" -d \
          -v $PWD/prometheus/:/etc/prometheus/:Z -p $PROMETHEUS_PORT:9090
--name $PROMETHEUS_NAME prom/prometheus:$PROMETHEUS_VERSION
 else
     echo "Loading prometheus data from $DATA_DIR"
-    sudo docker run -d -v $DATA_DIR:/prometheus:Z -v
$PWD/prometheus/:/etc/prometheus/:Z -p $PROMETHEUS_PORT:9090 --name
$PROMETHEUS_NAME prom/prometheus:$PROMETHEUS_VERSION
+    sudo docker run --net="host" -d -v $DATA_DIR:/prometheus:Z -v
$PWD/prometheus/:/etc/prometheus/:Z -p $PROMETHEUS_PORT:9090 --name
$PROMETHEUS_NAME prom/prometheus:$PROMETHEUS_VERSION
 fi

 if [ $? -ne 0 ]; then
@@ -90,7 +90,7 @@ then
         exit 1
 fi

-sudo docker run -d -i -p $GRAFANA_PORT:3000 \
+sudo docker run --net="host" -d -i -p $GRAFANA_PORT:3000 \
      -e "GF_AUTH_BASIC_ENABLED=false" \
      -e "GF_AUTH_ANONYMOUS_ENABLED=true" \
      -e "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin" \

**Comment by amnonh** [comment]
I run into the same issue a few times, I think it's related to using wifi
with docker, I've checked that the net flag does work.
I'll send a patch with a -l flag option to add the flag

**Comment by amnonh** [comment]
closed by commit https://github.com/scylladb/scylla-grafana-monitoring/commit/293a705da1502844ae872a1de1fff922d1b8eb14
