### ISSUE TITLE
The OS overview should have CPU utilization graph.

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1378]
There is already information about the reactor CPU utilization in the details page. But there is no overview of the actual CPU utilization. This includes spinning and whatever else is running. You will always have customers that are running other things on a system and currently we are blind/

**System information**
Scylla Monitoring 4.3

**Who will benefit with this feature?**
Any admin that wants to have a quick impression of how the system is doing.

**Comment by amnonh** [comment]
@pveentjer 
It's not clear what you are looking for, in most cases, scylla would take all available CPU so you'll get 100% regardless of other proccess

**Comment by pveentjer** [comment]
If the system is not experiencing a lot of load, Scylla won't be spinning. CPU utilization is an important metric and currently we are completely blind.

**Comment by pveentjer** [comment]
If the system is not experiencing a lot of load, Scylla won't be spinning. CPU utilization is an important metric and currently we are completely blind.

**Comment by pveentjer** [comment]
If the system is not experiencing a lot of load, Scylla won't be spinning. CPU utilization is an important metric and currently we are completely blind.

**Comment by amnonh** [comment]
@pveentjer the issue was closed with a PR, please take a look before re-opening
