### ISSUE TITLE
The OS overview should have memory utilization graph

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1379]
There is already information about the shard memory utilization in the details page. But there is no overview of the actual memory utilization of the machine. It should include everything that is running, not just Scylla. You will always have customers that are running other things on a system and currently we are blind.

System information
Scylla Monitoring 4.3

Who will benefit with this feature?
Any admin that wants to have a quick impression of how the system is doing.

**Comment by amnonh** [comment]
@pveentjer 
It's not clear what to show here, plain memory utilization have little value, Scylla would take over most of the available memory and the rest of the applications would fight over the rest,
what kind of graph you think will be helpful and how?
