### ISSUE TITLE
Overview read/write latencies are unclear

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1381]
Scylla Monitoring 3.6.3 with -v 4.3

It is unclear what kind of read/write latencies are being displayed in the Overview page.

![image](https://user-images.githubusercontent.com/105243/117419104-df999580-af24-11eb-819c-3adc65d00a74.png)

What is that value? Average? p99? Max?

**Comment by amnonh** [comment]
hi @pveentjer please follow the instruction of how to submit a bug, specifically, if you are talking about a panel, specify the dashboard you are referting to

**Comment by amnonh** [comment]
The two lines are 95% and 99% if you hover over it, you will get the details.
This is already fixed in 3.7 and will not be backported to 3.6.
