### ISSUE TITLE
Screenshot button not working

### ISSUE THREAD

**Issue by noam-ma-ma** [scylladb/scylla-monitoring#1386]
scylla-version=2020.1
monitoring-version=3.6.1
dashboard=overview-2020-1

Trying to screenshot from the main monitoring dashboard fails with ```No file``` error

![Screen Shot 2021-05-09 at 17 08 25](https://user-images.githubusercontent.com/71635658/117575132-2cc66480-b0e9-11eb-8152-762eaf950de0.png)

**Comment by amnonh** [comment]
It should be solved with the updated grafanarenderer plugin and grafana as well as full screen capture
