### ISSUE TITLE
Monitor multiple clusters / DCs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#139]
One way to do that is by adding a label per each cluster targets, and a filtering variable to select the cluster.

**Comment by tzach** [comment]
@amnonh ping

**Comment by matt2000** [comment]
PR #261 Makes it possible to do this on separate dashboards by using a separate Prometheus service per cluster.

**Comment by tzach** [comment]
@amnonh can we do the following 
- add cluster and DC name labels to the target file example
- provide examples on how to add DC, Cluster
- add a drop-down menu to choose the cluster and DC to all dashboards

**Comment by amnonh** [comment]
@tzach can we close this?
