### ISSUE TITLE
Add Support for Scylla Manager 2.4

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-monitoring#1391]
This is a feature but may soon become a bug.

Metrics changes in Scylla Manager 2.4
* Labels use cluster ID not name
* New metric for cluster ID to name mapping
* Removes internal metric aggregation aka metrics watcher for repair and backups
* Remakes repair and backup metrics providing per table view and aggregation capabilities
* Removes cluster metrics on repair / backup run, only shows metrics for a current run

Examples:

Cluster ID to name mapping

```
# HELP scylla_manager_cluster_name Mapping from cluster ID to name.
# TYPE scylla_manager_cluster_name gauge
scylla_manager_cluster_name{cluster="0d61b791-cccc-42fb-a64f-b9c636bbd21c",name="d"} 0
```

Repair progress:

```
# HELP scylla_manager_repair_token_ranges_error Number of segments that failed to repair.
# TYPE scylla_manager_repair_token_ranges_error gauge
scylla_manager_repair_token_ranges_error{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 1
# HELP scylla_manager_repair_token_ranges_success Number of repaired token ranges.
# TYPE scylla_manager_repair_token_ranges_success gauge
scylla_manager_repair_token_ranges_success{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 2
# HELP scylla_manager_repair_token_ranges_total Total number of token ranges to repair.
# TYPE scylla_manager_repair_token_ranges_total gauge
scylla_manager_repair_token_ranges_total{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 3
```

Repair active jobs:

```
# HELP scylla_manager_repair_inflight_jobs Number of currently running Scylla repair jobs.
# TYPE scylla_manager_repair_inflight_jobs gauge
scylla_manager_repair_inflight_jobs{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h"} 1
# HELP scylla_manager_repair_inflight_token_ranges Number of token ranges that are being repaired.
# TYPE scylla_manager_repair_inflight_token_ranges gauge
scylla_manager_repair_inflight_token_ranges{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h"} 10
```

Backup snapshot progress:

```
# HELP scylla_manager_backup_snapshot Indicates if snapshot was taken.
# TYPE scylla_manager_backup_snapshot gauge
scylla_manager_backup_snapshot{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k0"} 0
scylla_manager_backup_snapshot{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k1"} 1
```

Backup upload progress:

```
# HELP scylla_manager_backup_files_failed_bytes Number of bytes failed to upload to backup location.
# TYPE scylla_manager_backup_files_failed_bytes gauge
scylla_manager_backup_files_failed_bytes{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 2
# HELP scylla_manager_backup_files_size_bytes Total size of backup files in bytes.
# TYPE scylla_manager_backup_files_size_bytes gauge
scylla_manager_backup_files_size_bytes{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 10
# HELP scylla_manager_backup_files_skipped_bytes Number of deduplicated bytes already uploaded to backup location.
# TYPE scylla_manager_backup_files_skipped_bytes gauge
scylla_manager_backup_files_skipped_bytes{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 3
# HELP scylla_manager_backup_files_uploaded_bytes Number of bytes uploaded to backup location.
# TYPE scylla_manager_backup_files_uploaded_bytes gauge
scylla_manager_backup_files_uploaded_bytes{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h",keyspace="k",table="t"} 5
```

Backup purge progress:

```
# HELP scylla_manager_backup_purge_deleted_files Number of files that were deleted.
# TYPE scylla_manager_backup_purge_deleted_files gauge
scylla_manager_backup_purge_deleted_files{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h"} 1
# HELP scylla_manager_backup_purge_files Number of files that need to be deleted due to retention policy.
# TYPE scylla_manager_backup_purge_files gauge
scylla_manager_backup_purge_files{cluster="b703df56-c428-46a7-bfba-cfa6ee91b976",host="h"} 2
```

**Comment by mmatczuk** [comment]
cc @tzach @slivne

**Comment by slivne** [comment]
@amnonh we need todo the updates - we will be rolling out manager 2.4 (it has fixes that we need in the cloud)

**Comment by amnonh** [comment]
I need a 2.4 manager docker for working on this

**Comment by amnonh** [comment]
@mmatczuk I see that we no longer have a progress metric for each of the operation, how can I tell what is the percent done?

**Comment by mmatczuk** [comment]
Scylla Manager no longer performs any aggregation on metrics.
You need to aggregate data with a Prometheus query and calculate percentage.

**Comment by amnonh** [comment]
@mmatczuk please supply the requested methods of getting those results

**Comment by mmatczuk** [comment]
repair progress:

sum of scylla_manager_repair_token_ranges_success and scylla_manager_repair_token_ranges_error over selected hosts, keyspaces and or tables divided by sum of scylla_manager_repair_token_ranges_total over selected hosts, keyspaces and or tables multiplied by 100%

backup progress:

sum of scylla_manager_backup_files_uploaded_bytes and scylla_manager_backup_files_skipped_bytes and scylla_manager_backup_files_failed_bytes over selected hosts, keyspaces and or tables divided by sum of scylla_manager_backup_files_size_bytes over selected hosts, keyspaces and or tables multiplied by 100%

Two nuggets here:
* we may wish to distinguish between successful progress and total progress, as you see we add failed segments to success segments it's interesting to see if things are going well or we are failing all the time
* we may want to show total and per keyspace/table splitup

**Comment by amnonh** [comment]
@mmatczuk  I've just tried to test it with 2.4.rc1, I only tried with repair, the result was that `scylla_manager_repair.* ` showed after the repair was completed.

Please validate that it works

**Comment by mmatczuk** [comment]
I'll have a look.

**Comment by mmatczuk** [comment]
I think that what could happened is that your tables were too small and SM decided to repair them in a single job.
You can try running repair with `--small-table-threshold=0` and / or repairing more data.

**Comment by amnonh** [comment]
@mmatczuk I have tried running repair again with more data, metrics are still bugy,
you can see that there are holes in the graphs, this is a bad behaviour, metrics shold be continuous.
![image](https://user-images.githubusercontent.com/2118079/120928792-e87db280-c6ee-11eb-95dd-7dc7eef1729a.png)

Please fix this behaviour so we can progress.

**Comment by mmatczuk** [comment]
I'll have a look
