### ISSUE TITLE
By default scylla-monitoring is not persistent.

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1392]
**System information** 3.6.3

By default the Scylla Monitoring is not persistent. You need to pass '-d dir' to the 'start-all.sh' for it to become persistent.

It should be the default that Scylla Monitoring is persistent. If no setting is passed, then by default the system should just make a local directory and store the state.

I already ran into a 'gotcha' moment when the Prometheus node was stopped because it was running too long and I lost valuable debugging information. 

If you want non persistent Scylla Monitoring, then an explicit option should be passed.

**Comment by amnonh** [comment]
I disagree, we can add a  warning to start-all but you cannot just drop huge amount of data to a disk without having the user knows about it

**Comment by pveentjer** [comment]
Where is it currently stored? It still must be on disk somewhere because it is too large to keep in memory.

**Comment by amnonh** [comment]
it's stored inside the container, that means when the container dies, so does the disk with it
