### ISSUE TITLE
Slack alert - Grafana URL is localhost:3000

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylla-monitoring#1395]
Hi Team,

Currently we are using scylla monitor 3.6, and we noticed that the grafana domain is localhost by default, thus our slack alert message all pointing to localhost:3000. 

Is there any solution to change localhost to user-defined domain name without manually changing the grafana config file and restarting docker container? 

Thanks

**Comment by amnonh** [comment]
Why this is an advisor issue?
How does it relates to slack alerts?

You can also use the `-A` to bind the listening address to another adress: 
https://monitoring.docs.scylladb.com/stable/install/start_all.html

**Comment by codingcuisg** [comment]
sorry, please ignore the issue tag

Explanation here:

we are using alert manager to send slack message, the issue is, the grafana URL link in slack message is point to localhost:3000, so when click the link it doesn't go to my grafana. Basically I just wanna to replace localhost to my own domain name

See the issue below:
https://community.grafana.com/t/how-can-i-update-the-grafana-dashboard-url-in-the-slack-notification/15075

Could you advice how to solve my issue without manual updating grafana config file?
Any solution to overwrite the default grafana config file when run `./start-all.sh`?

**Comment by codingcuisg** [comment]
Understand scylla monitoring have -c grafana environment variable, I guess one solution is to pass in environment var `GF_SERVER_ROOT_URL`.  Which script may help me add this env var to existing container?

**Comment by amnonh** [comment]
@codingcuisg as I wrote in my original comment, if all you need is to bind the address to something else you can use the `-A` command line flag to `start-all.sh`

**Comment by amnonh** [comment]
@codingcuisg is this still an issue?

**Comment by codingcuisg** [comment]
Hi amnonh, 

I solved it by -c "GF_SERVER_ROOT_URL=xxx". Kindly close this issue.

Thanks for your help!
