### ISSUE TITLE
Need to update the disk warning levels

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1403]

**Comment by tzach** [comment]
Please link the current values

**Comment by amnonh** [comment]
Current values:
https://github.com/scylladb/scylla-monitoring/blob/889a03950e6e23a05ee9af5cf98fe609f7c67c16/prometheus/prometheus.rules.yml#L179

**Comment by amnonh** [comment]
@slivne I'm assigning this to you just for the values (add them as a comment here) I'll do the actual change

**Comment by slivne** [comment]
@tzach what do you want this updated to - the Disk Policy we talked about

65%, 75%, 85% ?
