### ISSUE TITLE
Issue in page Install Scylla Monitoring Stack - broken link to manager

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1404]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-3.7/install/monitoring_stack

### Problem
broken link to manager 
at 

> NOTE
> 
> If you want to add your managed cluster to Scylla Monitoring Stack, add the IPs of the nodes as well as the cluster name you used when you added the cluster to Scylla Manager. It is important that the label cluster name and the cluster name in Scylla Manager match.
> 

###  Suggest a fix

**Comment by lsnovich** [comment]
seems to be fixed, @amnonh please close

**Comment by lsnovich** [comment]
In the source code it is fixed, on the site it is not, please deploy

**Comment by lauranovich** [comment]
Sorry didn't see that I wasn't signed in correctly. @amnonh  / @tzach I looked at the code and it is right. The site is wrong. Can we please deploy?

**Comment by lauranovich** [comment]
Link works, it may not work for 3.7 - but future versions 3.8, 3.9 are working - closing
