### ISSUE TITLE
Change the OS/Metrics Disk Size By XXXX to be Percentage and not by size.

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1408]
This is the current graph
![DS](https://user-images.githubusercontent.com/3465480/120307926-34d68600-c2dc-11eb-9512-930c17d1aa7b.png)

but it not useful like

![ds_percent](https://user-images.githubusercontent.com/3465480/120307969-428c0b80-c2dc-11eb-8897-5a3cb817d2b1.png)

providing the disk usage in which its clear that we have lower disk space which needs to be checked ....

**Comment by amnonh** [comment]
Both are valiable, I'll add a panel instead of replacing it
