### ISSUE TITLE
Doc: Move monitoring upgrade to the monitoring repo

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1418]
Monitoring upgrade is currently in the Scylla site
https://docs.scylladb.com/upgrade/upgrade-monitor/

This does not make much sense, and is error prune
It will be easier to include these docs in the Monitoring repo

**Comment by lauranovich** [comment]
FIXED with https://github.com/scylladb/scylla-monitoring/pull/1462, closing
