### ISSUE TITLE
The install the monitoring without containers is out-of-date

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1435]
Please make sure that this is a documentation related 
install/monitor_wihtout_docker is out-of-date, it should be updated and tested with newer versions.

**Comment by tzach** [comment]
@amnonh either send a PR, or include *exactly* what you need here.
For testing, please handle it yourself, or with QA.

**Comment by amnonh** [comment]
I'll work on that, I happend to look at the docs and saw that it's out of date and opened the issue to track it
