### ISSUE TITLE
Metrics well-described + dedicated documentation

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-monitoring#1452]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): N/A
- Are you willing to contribute it (Yes/No): N/A

**Describe the feature and the current behavior/state.**
Metrics provided are poorly described. Here you have some examples:
`scylla_database_counter_cell_lock_acquisition: The number of acquired counter cell locks.` `scylla_database_counter_cell_lock_pending: The number of counter updates waiting for a lock.`

There's no documentation about them, so it's pretty impossible to know exactly what a metric is if there's no extra information about it. A one-liner description could help, but Scylla should have dedicated documentation to better explain each one.

**Who will benefit with this feature?**
Any person that works as Ops, Support, Architect, etc which uses metrics to get conclusions (and maybe taking decisions based on them).

**Any Other info.**

**Comment by amnonh** [comment]
I agree to the general idea, but this issue should be open under Scylla repository, not under monitoring, closing it here.

**Comment by vladzcloudius** [comment]
@ebenzecri Let's open a GH about the description of graphs on each dashboard of Scylla Monitoring.

@amnonh The context help messages that we have today are nice but we also need this as a Web page to make these searchable.

Which repo you think it would be the most appropriate?

**Comment by amnonh** [comment]
@vladzcloudius metrics should be documented part of scylla, they are scylla specific and should match the scylla version, so a web document should be part of scylla documentation.

Issues about Scylla Monitoring graphs that needs more description should be in Scylla Monitoring, or even better a PR to scylla monitoring :)

**Comment by ebenzecri** [comment]
I've opened this one the other day after this issue was closed: https://github.com/scylladb/scylla/issues/8888
