### ISSUE TITLE
Query Error 504 for Active Alert and Advisor

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1455]
*Installation details* 
Panel Name: Cluster View
Dashboard Name: 
Scylla-Monitoring Version: 3.7.0
Scylla-Version: 2020.1

Active Alert and Advisor both show a scary rad warning "Query Error 502" 
While, as far as I understand, there are simply no data.
For this tables, and other like them, it would be better to remove this warning.

![image](https://user-images.githubusercontent.com/170200/122923985-ef9ef480-d36d-11eb-9564-934a1960fe45.png)

**Comment by amnonh** [comment]
This does not look like a no data scenario, which typically looks like:
![image](https://user-images.githubusercontent.com/2118079/122932924-d2baef00-d376-11eb-8c5a-08359cef3f2d.png)


it looks like a problem with the setup

**Comment by tzach** [comment]
The red triangle flicker, so it might be hard to catch.
I see this with every new cloud cluster, so its easy to reproduce on the cloud.

**Comment by amnonh** [comment]
Is that only with a new cluster and goes a way after a minute or two?

**Comment by tzach** [comment]
No. I see this with Cloud clusters running for months.

**Comment by amnonh** [comment]
This is a cloud-specific issue, closing for https://github.com/scylladb/siren/issues/5784
