### ISSUE TITLE
Overview Dashboard - Reads at a DC level dont support all scheduling groups - only query group

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla-monitoring#1467]
*Installation details*
Panel Name: Reads - DC level
Dashboard Name: Overview Dashboard
Scylla-Monitoring Version: 3.6.1
Scylla-Version: 2021.1.7

![image](https://user-images.githubusercontent.com/1077762/123661650-91e52f00-d7e9-11eb-8a92-cb166a89a0c7.png)

Looks like the reads at the DC level don't support all scheduling groups but only the query group. But in addition BYPASS_CACHE reads are not shown in the query group. THe picture above is an example of a cloud customer who saw this issue. This is very misleading.

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-monitoring/pull/1479
