### ISSUE TITLE
Monitoring 3.8 docs are showing wrong download link

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1468]
Docs link
https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html

Problem
For monitoring 3.8, docs are still showing download link for monitoring 3.7:
wget https://github.com/scylladb/scylla-monitoring/archive/scylla-monitoring-3.7.0.tar.gz

Suggest a fix
Change download link address to:
wget https://github.com/scylladb/scylla-monitoring/archive/scylla-monitoring-3.8.0.tar.gz

**Comment by tzach** [comment]
Reported by @Pawel-Kr

**Comment by amnonh** [comment]
@dgarcia360 can you please take a look? I've updated what I thought needs to be updated at master, I now backported it to 3.8, but I'm not sure that this is the issue

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-monitoring/pull/1521
