### ISSUE TITLE
Go back to 15s scrap interval 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#147]
In 
https://github.com/scylladb/scylla-grafana-monitoring/commit/2c8c475e9d1aa2201f2ca8c85ca3a3e42b7d3ec5 we moved from the default 15s scrap value to 1s.
With the increasing number of metrics and monitored nodes, this value proved to be too low as a default for customers, and we should go back to 15s

**Comment by tgrabiec** [comment]
@tzach Why is it too low?

**Comment by tzach** [comment]
> @tzach Why is it too low?

Not sure about "too" low, but increasing the value to 15s will:
- reduce the pressure on the DB, especially on servers with many cores (and metrics)
- reduce CPU usage on the monitoring server
- reduce require disk space on the monitoring server

Clearly, it's a tradeoff and one loose information in the process.

**Comment by tzach** [comment]
@avikivity any comments?

**Comment by glommer** [comment]
My 2 cents here:

We don't have to chose between 1s and 15s. Why not 5 seconds? For a VM with 64 vCPUs - think Amazon i3.16xlarge, prometheus at every 1s generates a ton of data. That puts a lot of load in a lot of components - like network, not only storage.

I believe 5s is a good balance. In parallel, we should have an easy way (maybe through a command line parameter for start-all.sh ?) to move that back to 1 second  - or 15 seconds - for folks going away from the default.

**Comment by avikivity** [comment]
What's wrong with 15s?

**Comment by avikivity** [comment]
@tgrabiec on a large node each scrape is 1.2MB of data + lots of activity. We are working to reduce the cpu load, but it's still high, and there is an associated latency spike.

**Comment by glommer** [comment]
nothing wrong with 15s per se. Those things are empirical in nature, IMHO. We switched from 15s because it was too coarse - and this was actually customer driven. So while it's true that we can always change, the quest for a good default is one that will balance this. I think 5s is a good default because it matches grafana's minimum granularity.

**Comment by tgrabiec** [comment]
@avikivity If current scrape period is hurting regular operation, I agree we should increase it. But if it's causing latency spikes, then I guess this is something we should fix, a spike every 15 sec is undesirable as well.

**Comment by glommer** [comment]
in agreement with @tgrabiec. There are many problems in the field recently - latency being one of them - that are coming from prometheus. We should stop and take a look at those to make sure things are in shape.

But I'll keep my recommendation to move the scrape period to 5s regardless.

**Comment by tzach** [comment]
5s vs 15s is the new Spaces vs Tabs ;)
Let's look at what similar DBs are using:
1.  [Prometheus default](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus.yml): 15s 
2. [Outbrain/Cassibility](https://github.com/outbrain/Cassibility): 15s

We are biased by mostly looking at fault systems. In most cases, the system is running smoothly, and 15s is good enough. Users can always change the value if required.

**Comment by tgrabiec** [comment]
@avikivity 15s is not good enough when you need to see evolution of gauges which vary with higher frequency. Reads time out after 2s. It's easy to correlate that with gauges, e.g. virtual dirty, queue lengths, if sampling is at 1s. With 15s it's not that obvious, the queues could be gone by then.

**Comment by tzach** [comment]
Set to 5s in #238
