### ISSUE TITLE
 re-organization of the panels in the details dashboard

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla-monitoring#1470]
@amnonh 
I have a small request for reordering some view in the details dashboard:

in the read writes graph - I feel  that a better view would be a line of write and a line of reads. (I also got the same feedback from several customers I talked to.)

So now it's  (like the screenshot):
FG write, FG reads , AVG write latency,  AVG read latency
P95th  write, P99 write, p95reads, p99 reads

and I feels that it should be:
FG write,  AVG write latency,  P95th  write, P99 write
FG reads, AVG read latency,  p95reads, p99 reads

tnx, guy

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-monitoring/pull/1479
