### ISSUE TITLE
Docs: Add an overview section, including high level architecture diagram

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1471]

**Comment by amnonh** [comment]
There is such an overview page (the main index) it should be updted and add the diagram

**Comment by tzach** [comment]
You mean this one https://monitoring.docs.scylladb.com/stable/ ?
its out of date (only 3 docker), and give very little info on the architecture.
I suggest to fix it, and add an architecture page

**Comment by nyh** [comment]
I think the overview on https://monitoring.docs.scylladb.com/stable/ is much too short. If someone comes to it familiar witth Scylla but not already having a good mental image what "prometheus", "grafana" or "alert manager are", he will not understand anything. I think what is needed is text - not a diagram.

Some text (doesn't have to be very long) explaining that:
Scylla publishes various **metrics**, such as number of requests, disk activity, memory use, and a lot lot more (here you could have a link to a document or user guide or something with better list). All of these metrics are true to the moment they are requested. **Prometheus** is a time-series database which collects these metrics over time, and also collects them from multiple nodes and all their shards. Prometheus then allows querying and graphing these saved metrics. **Grafana** is a UI which further improves this graphing abilities, by showing multiple graphs in nice easy-to-use panels (see example below). Now explain also Loki (?), alert manager, advisor, etc.

https://github.com/scylladb/scylla/blob/master/docs/design-notes/metrics.md is my developer-oriented explanation of the same thing, but it has too much detail for users, and also predates the Loki, Alert manager, and Advisor stuff which isn't described there.
