### ISSUE TITLE
Incorrect Read latency metrics on 3.8.0 and 3.7.2

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla-monitoring#1472]
This test has been executed on Scylla Monitoring **3.8.0** and **3.7.2**. 

Scylla release was **2021.1.2-0.20210620.7bb9428ae**, the same can be reproduced in **2020.1.9-0.20210614.32332f8df**.

# Steps to reproduce

## Monitoring 3.8.0
1) Load 30 million records to Scylla cluster with C-S:
```
$ cassandra-stress write n=30000000 -pop seq=1..30000000 -node 172.17.0.2
(Let it run...)
```

Scylla Average and 99% **Write** metrics will start showing up:
![image (3)](https://user-images.githubusercontent.com/82817126/124688865-e2295480-dead-11eb-9f45-a06e1d9cba31.png)

2) Perform a read test:
```
$ cassandra-stress read n=30000000 -pop seq=1..30000000 -node 172.17.0.2
(Let it run)
```

After reading over 5 million records, the Read metrics will still be empty, both on the Overview as well as in the Detailed dashboards:
- Overview Dashboard
![image (4)](https://user-images.githubusercontent.com/82817126/124688952-0be27b80-deae-11eb-949d-aea2d59f873f.png)
- Detailed Dashboard
![image (5)](https://user-images.githubusercontent.com/82817126/124688991-18ff6a80-deae-11eb-894b-3f9eec1b6359.png)

## Monitoring 3.7.2
1) Load 30 million records to Scylla cluster with C-S:
```
$ cassandra-stress write n=30000000 -pop seq=1..30000000 -node 172.17.0.2
(Let it run...)
```
Scylla Average and 99% **Write** metrics will start showing up:
![image (6)](https://user-images.githubusercontent.com/82817126/124689248-8dd2a480-deae-11eb-8846-aca65335d18b.png)

2) Perform a read test:
```
$ cassandra-stress read n=30000000 -pop seq=1..30000000 -node 172.17.0.2
(Let it run)
```

After reading over 5 million records, the Read **99%** and **Read latencies** panels will still be empty on the Overview dashboards **only**:
![image (7)](https://user-images.githubusercontent.com/82817126/124689368-c7a3ab00-deae-11eb-8177-a4f245beffd1.png)

The Detailed dashboard will show up the correct metrics:
![image (8)](https://user-images.githubusercontent.com/82817126/124689420-e43fe300-deae-11eb-8d95-a514127fecbf.png)

# Prometheus data
It looks like that `scheduling_group_name=~"statement|$"` is not properly returning the correct values when in use along with **scylla_storage_proxy_coordinator_read_latency_sum**. A quick inspection at Prometheus will reveal that no data has ever been collected:

![image (9)](https://user-images.githubusercontent.com/82817126/124689677-4ac50100-deaf-11eb-899b-a3ba30f27556.png)

Whereas if we simply remove *scheduling_group_name* filter, it will reveal some metrics:
![image (10)](https://user-images.githubusercontent.com/82817126/124689705-5dd7d100-deaf-11eb-9222-24f0ee30037c.png)

# (TLDR) Summary
- 3.8 is fully affected by this, whereas 3.7.2 is partially
- The test was done using a freshly spun cluster via Docker without any related customization
- It seems that this is caused by a regression either when *scheduling_group_name=~"statement|$"* was introduced, or it may be that Scylla is reporting these incorrectly.

cc @amnonh

**Comment by amnonh** [comment]
Scylla enterprise uses `scheduling_group_name="service_level_sg_0"` instead of `statement` because of work load priorization, there could be other service level, need to rethink how to show it in the dashboard

@eliransin @tzach I would appriciate your input here

**Comment by eliransin** [comment]
I have just submitted a or that will name all scheduling groups for service levels with a prefix of `service level:` followed by the service level name.
I guess that if we will need to: add `|service level:.*` to the end of the expression (?).
Either way it is not interesting to show latencies as a whole because workload prioritization whole point is to have different 
latencies per workload.
How this input is what you were looking for @amnonh :slightly_smiling_face:
