### ISSUE TITLE
Issue in page Scylla Monitoring Stack Support Matrix

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla-monitoring#1473]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-3.8/reference/matrix

### Problem
version 3.8 is missing 
###  Suggest a fix

**Comment by lauranovich** [comment]
@amnon please backport https://github.com/scylladb/scylla-monitoring/pull/1460 to the 3.8 branch

**Comment by amnonh** [comment]
Seems like a duplication of #1468

**Comment by lauranovich** [comment]
seems to be working
