### ISSUE TITLE
 Latency graphs based on each workload

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/scylla-monitoring#1477]
@amnonh 

Is there any chance for: 

1. Include latency graphs based on each workload
2. right now, there is not a better way to distinguish the service_level_ roles when multiple workloads/services are created. can we name the dashboards in a way we can identify the right workload. (from the attached screenshot, it is difficult to identify which service_level corresponds to our OLTP/OLAP workload)
![image](https://user-images.githubusercontent.com/11996012/124957172-15d4bd80-e019-11eb-8d9a-f897f5edeb08.png)

**Comment by amnonh** [comment]
@AdamStawarz please fill all relevant information first, second the request is not clear

**Comment by AdamStawarz** [comment]
@amnonh 
generally customer asking if there is chance to add names for each service_level dashboards. For example now when I create new service level: eg. `CREATE SERVICE_LEVEL IF NOT EXISTS OLAP WITH SHARES = 100;`
I see generic dashboard name like: service_level_sg_1 
![image](https://user-images.githubusercontent.com/11996012/125288447-71a38d00-e31e-11eb-80f2-a6e562af1907.png)

so for better identify it could contain also real name of service level like: service_level_sg_1(OLAP)

Second feature request is to add latency dashboard per each service_level metric.

**Comment by amnonh** [comment]
Please take a look at the PR https://github.com/scylladb/scylla-monitoring/pull/1479

**Comment by amnonh** [comment]
@AdamStawarz just for clearity, dahboard is the entire page, a specific graph is called panel (you can call it a graph as well) I don't think we expose the names, but you can open a scylla issue for that.
