### ISSUE TITLE
Node exporter is failing for openshift

### ISSUE THREAD

**Issue by gautam-borkar** [scylladb/scylla-monitoring#1494]
**Describe the bug**
Trying to install scylladb monitoring on Openshift using helm. However the installation of node-exporter is failing.

**To Reproduce**
1. helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
2. helm repo update
3. helm install monitoring prometheus-community/kube-prometheus-stack --values examples/common/monitoring/values.yaml --create-namespace --namespace scylla-monitoring

**Expected behavior**
node-monitoring successfully installed on Openshift.

**Logs**
```
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m15s  default-scheduler  0/2 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match Pod's node affinity.
  Warning  FailedScheduling  2m14s  default-scheduler  0/2 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match Pod's node affinity.
```

**Environment:**
 - Platform: Openshift 
 - Kubernetes version: 
 ```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+2817867", GitCommit:"2817867655bb7b68215b4e77873a8facf82bee06", GitTreeState:"clean", BuildDate:"2021-06-02T22:14:22Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```
 - Scylla version: 4.4.3
 - Openshift version: 4.7.16

**Comment by amnonh** [comment]
Closing for no progress over two years
