### ISSUE TITLE
Incorrect disk size metric in 3.6.1

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylla-monitoring#1495]
*Installation details*
Panel Name: Disk Size by DC
Dashboard Name: Overview
Scylla-Monitoring Version: 3.6.1 and 3.7
Scylla-Version: 2020.1.7

Panel Disk Size by DC showing wrong information in **Size** and **AVG usage** (a negative value):
![image](https://user-images.githubusercontent.com/31359297/127065172-4d2e6d6b-d115-42f7-ad03-2be200a1992b.png)

As a reference, in Alternator dashboard it's showing the correct metrics according to the disk space used by DC:
![image](https://user-images.githubusercontent.com/31359297/127065069-177f8dc5-2b4e-449c-b508-e91bf4361495.png)

Customer in 3.6.1 version is complaining about this bug, but I checked in another customer with 3.7 version in order to compare and it's reporting the same behavior

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-monitoring/pull/1481 in 3.8.1
