### ISSUE TITLE
CPU Frequency does not show data

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1499]
Scylla Cloud Cluster on GCP
scylla-version=2021.1
monitoring-version=3.8.1
dashboard=OS-2021-1

![image](https://user-images.githubusercontent.com/170200/128080129-f6f3b33c-bd22-419b-b216-d06b03859863.png)

**Comment by amnonh** [comment]
And Does the OS dashboard works?

**Comment by tzach** [comment]
Yes, the rest of the charts in the OS dashboard do work

**Comment by amnonh** [comment]
Node exporter reports `node_cpu_frequency_hertz` and or `node_cpu_scaling_frequency_hertz` It seems that in the cloud it reports the second.
It's not 100% consistent, so some twicking will need to be done

**Comment by tzach** [comment]
@amnonh note that each "cloud" or even region of VM type might send different metrics
