### ISSUE TITLE
avg high latency alerts not reported because of invalid PromQL expression

### ISSUE THREAD

**Issue by sbhattiprolu** [scylladb/scylla-monitoring#1504]
because of a minor typo there seems to be a monitoring lapse in avg high latency alerts which were using non-existent PromQL metric

In `prometheus.rules.yml` file which defines the rules to alert on , the metric expr `wlatencypa` is not defined , it should be `wlatencya` which records `sum(rate(scylla_storage_proxy_coordinator_write_latency_sum{}[60s])) by (cluster, dc, instance,scheduling_group_name, shard)/sum(rate(scylla_storage_proxy_coordinator_write_latency_count{}[60s])) by (cluster, dc, instance, scheduling_group_name, shard)`

Same issue for average read latency rule `rlatencya`

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-monitoring/pull/1500
