### ISSUE TITLE
start-all.sh unexpected hyphen

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1507]
*Installation details*
Scylla-Monitoring Version: 3.6.3
Scylla-Version: 4.4.3

I'm passing an extra argument to 'start-all.sh' to enable the Prometheus admin API using:

```
./start-all.sh -b --web.enable-admin-api
```

The problem is that the Prometheus container fails with the following message:
```
Error parsing commandline arguments: unknown long flag '---web.enable-admin-api'
prometheus: error: unknown long flag '---web.enable-admin-api'
```

As you can see, there are 3 hyphens, and I only passed 2.

If I change my startup command to
```
./start-all.sh -b -web.enable-admin-api
```
It will add an extra hyphen and the containers start fine.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla-monitoring/blob/78a7b738b9335493fe6446dea5b7422bda51bbe8/start-all.sh#L357-L359

**Comment by amnonh** [comment]
@pveentjer  This was done on purpose to support older version of prometheus, we should probably need to change it.
