### ISSUE TITLE
alerts when large* gets changed

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#1509]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 2021.1.2
- Are you willing to contribute it (Yes/No): depends :-)

**Describe the feature and the current behavior/state.**

can we have a rule for alerting when new rows get to large* in CQL dashboard?

**Who will benefit with this feature?**

developers will figure out when there is data, that might cause probs

**Any Other info.**

**Comment by amnonh** [comment]
This is already supported by the Loki alerts (alerts that are based on logs)
