### ISSUE TITLE
Compaction Y axis should be integrer

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#152]
Current view is confusing.
![image](https://cloud.githubusercontent.com/assets/170200/24353875/5c13f966-12f8-11e7-830c-7887a80f1e8a.png)

**Comment by tzach** [comment]
Grafana https://github.com/grafana/grafana/pull/6051 might fix this in Grafana 4.x

**Comment by amnonh** [comment]
@tzach 
I've switched to integer, because it's 0 or 1, it looks like:
![image](https://user-images.githubusercontent.com/2118079/56721652-0295ea00-674e-11e9-9411-d1cffc21c1cd.png)

Do you want to proceed with it
