### ISSUE TITLE
Missing latencies panels in Detailed Dashboard

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylla-monitoring#1536]
Hi @amnonh, 
A kindly request for adding latencies panels (at least 99% write latencies and 99% read latencies) back in Detailed dashboard.

On Scylla Monitoring 3.8 (I have checked it on 3.8.1 and 3.8.2) I am not seeing latencies panels as I can see on 3.7 version

How it was on 3.7, Detailed Dashboard:
![image](https://user-images.githubusercontent.com/31359297/131731989-843a3623-7645-4850-ba6a-8f6888ffedc7.png)

How it is on 3.8, Detailed Dashboard:
![image](https://user-images.githubusercontent.com/31359297/131733723-4929d407-c7b7-4ae7-8e3e-a49cc012e7b9.png)

I could find it only in Overview Dashboard:
![image](https://user-images.githubusercontent.com/31359297/131732365-11af6266-87af-46f6-a89b-a222efc02e4f.png)  ![image](https://user-images.githubusercontent.com/31359297/131732393-8b2023fc-f121-4dfc-a25b-e2fbd32c3564.png)

Keeping only 2 charts merged in 1(95% and 99%)  in a smaller panel in Overview Dashboard doesn't help much when troubleshooting issues.

Thank you
Noelly

Cc. @gnumoreno

**Comment by amnonh** [comment]
We actually moved to a more detailed latncies graphs, now it's per scheduling group at the bottom of the detailed dashbaord.
Note that for performance reasons it is folded by default, and you will need to open them.

See #1479
