### ISSUE TITLE
Update to Grafana 8.x

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-monitoring#1551]
**QA Team** is using **table-old** panel to display annotations, but it has bug when it is not displaying content until you get into edit mode.
We also tried **annolist** panel, which is also have bug of not updating it's time ranges and as result you see no annotations.

So basically at the moment we have no way to textually display annotations.
It was confirmed that **annolist** panel on **Grafana 8.x** working properly, so it would be great to move monitoring stack to top notch Grafana version.

**Comment by amnonh** [comment]
Monitoring is already using grafana 8
