### ISSUE TITLE
percentage of used and free disk space on OS metrics

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#1553]
*Installation details*
Panel Name: Total Storage
Dashboard Name: OS metrics
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) 3.9.0
Scylla-Version: 2021.1.5

please, get back the percentage of used/free disk space, it's crucial to see how bad is the current usage and the pie shows it better than panels below

**Comment by amnonh** [comment]
Why not both?
![image](https://user-images.githubusercontent.com/2118079/135760898-55745754-46cd-45f1-a2a0-246704bc25bb.png)

luckily grafna's new pie-chart panel comes with this great feature
