### ISSUE TITLE
Monitoring Stack docs - add info about setting swap (and more) for monitoring instances.

### ISSUE THREAD

**Issue by Pawel-Kr** [scylladb/scylla-monitoring#1554]
**System information**
- link to the documentation page and section
https://monitoring.docs.scylladb.com/stable/troubleshooting/monitor_troubleshoot.html, https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#
- Are you willing to contribute it (Yes/No):
No

**Describe the situation now**
In those places there should be mentioned (extra chapter or additional notes) that prometheus is very memory-hungry and it's required to configure swap on monitoring machines to avoid prometheus going OOM. Maybe going even further and note that when OOM crashes are getting more frequent, we recommend to change instance type for bigger one. We're facing more and more issues with prometheus going OOM (especially with newer monitoring stack releases), so it'd be useful to add this valuable info into our documentation. Because as for now - it's not documented at all.

**What needs to be there**
Add necessary info to our docs. @amnonh could you help with some overall recommendations when it comes to swap size and new info content?

**Comment by tzach** [comment]
https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#minimal-production-system-recommendations sizing is not realistic, as it does not update the RAM and cores of the monitoring server as a function of the cluster size.

**Comment by amnonh** [comment]
@tzach I think the updated version already covers it

**Comment by tzach** [comment]
> @tzach I think the updated version already covers it

Please point to a relevant PR / Commit

**Comment by amnonh** [comment]
@tzach https://github.com/scylladb/scylla-monitoring/pull/1574

**Comment by tzach** [comment]
LGTM
