### ISSUE TITLE
Keyspace/Table dashboard - how to enable metrics 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1560]
Explain why you might not see data and link to doc on how to enable it

**Comment by amnonh** [comment]
@tzach we need a scylla documentation about it so I can link from a warning to the documentation, theoretically we can add it to scylla monitoring, but it's a scylla configuration

**Comment by tzach** [comment]
Indeed, please update Scylla Docs

**Comment by amnonh** [comment]
I couldn't find a place for something like that in the documentation, can
you point me in the right direction?
