### ISSUE TITLE
Show evictions and insertions rates of prepared statements

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#1561]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 4.4
- Are you willing to contribute it (Yes/No): not sure, likely no

**Describe the feature and the current behavior/state.**

prepared statement cache is static size (10k size I think) per node
we already gather prepared cache evictions and insertions, we could just show them in CQL dashboard (in same panel?)

people sometimes see
```
Query <cq_query> is not prepared on property_notice, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
```
and this points out they have queries that either generate new hash when they get sent or just too many clients
with those metrics this can be proven

**Who will benefit with this feature?**

people who have bugs in client and reinsert same prepared query over again (due to some dynamic part of it) or too many prepared queries just by sheer size of their app(s)

**Any Other info.**

**Comment by amnonh** [comment]
This is close to #1401

**Comment by tarzanek** [comment]
yes, sorry, I only searched in open issues, if it's a dup feel free to close, if it can be graphed it'd be good
