### ISSUE TITLE
Write latencies missing shard id

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1562]
scylla-version=4.3
monitoring-version=3.6.3
dashboard=overview-4-3

On the overview page, the write latencies graph doesn't include the id of the shard.

![image](https://user-images.githubusercontent.com/105243/135986254-0e0b1ed8-b417-4ab4-9824-5f8c11d146df.png)

**Comment by amnonh** [comment]
This is an old version, the behaviour is now different, and in later releases, to get the latencies you can look at the detailed dashboard per scheduling group.
