### ISSUE TITLE
systemd service to keep monitoring running even after reboot

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#1564]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 2021
- Are you willing to contribute it (Yes/No): not sure

**Describe the feature and the current behavior/state.**

Can we have a systemd service wrapper for start-all script (or docker compose)
that will make sure service is on even after reboot?

**Who will benefit with this feature?**

Everybody who is fed up with kill-all and start-all and wants to keep the stack up and control it in a systematic way

**Any Other info.**

**Comment by tzach** [comment]
we can have a one time monitorig_setup script, similar to manager and scylla

**Comment by amnonh** [comment]
> we can have a one time monitorig_setup script, similar to manager and scylla

#1073

**Comment by amnonh** [comment]
On one hand it sounds like a real good idea, on the other hand it's a bit customer specific, so it need some thinking

**Comment by ebenzecri** [comment]
There's a way to do this without changing anything:

1. Docker service should be **enabled** thus it will be started automatically in case the node is rebooted.
2. `start-all.sh` script has an argument called `-D` who is defined as "Encapsulate docker param, the parameter will be used by all containers.", so you should run `start-all.sh -D --restart=always (all the remaining arguments here)` and all done.
