### ISSUE TITLE
CQL Croos DC Information dashboard

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla-monitoring#1571]
Hi Amnon,

In the CQL dashboards there is a cross DC section where I see seen CL ONE and Quorum queries happening even when we have a single DC cluster.  

scylla-version=2021.1
monitoring-version=3.9.0
dashboard=cql-2020-1

![image](https://user-images.githubusercontent.com/13367089/138231671-5528e841-b925-4300-9016-797d977daa59.png)

**Comment by amnonh** [comment]
This could be confusing, but it's not a bug, it means that you have traffic with CL ONE and QUORUM, this is fine because you only have one DC.
I'll see if I can add something to the description to make it clearer

**Comment by gcarmin** [comment]
@amnonh   - I still don't understand why is it under "Cross DC  Information"

**Comment by amnonh** [comment]
because it's an issue only if you have cross DC traffic, I'll see if I can make it clearer in the description
