### ISSUE TITLE
1.7 board some metrics seem bogus

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#158]
Per Server has at the bottom 4 graphs under CQL

CQL Insert / CQL Reads / CQL Deletes / CQL Updates

the grpahs should not be commulative to be meaningful they should use rate instead 

instead of sum(scylla_cql_updates{}) by (instance) should probably be (rate(scylla_cql_updates{}) by (instance)

**Comment by tzach** [comment]
@amnonh please take a look

**Comment by tzach** [comment]
@amnonh ping

**Comment by tzach** [comment]
@amnonh please take a look
