### ISSUE TITLE
Cluster reaches its limit

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1580]
**Describe the issue logically**
The system works as expected but reaches its limit.
It could be disk, CPU, network or hardware.

**Describe the condition when the issue happens**
Need more information for that

**What the user should do when this happens**
Add more hardware
**Any Other info or Links.**

**Comment by slivne** [comment]
@psarna where is the presentation you prepared on overload ?

Which metric(s) should we look at to check if a system is overloaded

**Comment by amnonh** [comment]
scylla_transport_requests_shed

**Comment by slivne** [comment]
@psarna
 - on a different thread we concluded that scylla_transport_requests_shed is an indication of overload / load shedding happening 
 - Is there any other metric we should look at to conclude node / shard are overloaded ?

**Comment by slivne** [comment]
@psarna ping

**Comment by psarna** [comment]
Hm, I didn't receive **any** of these notifications even though I'm pinged directly... I need to check my github preferences, sorry for the delay. Looking at it now.

**Comment by psarna** [comment]
> I'm implementing it now, is it true that when derivative(scylla_transport_requests_shed) >0
> The cluster is overloaded? 

@amnonh Positive derivative would mean that some requests are currently getting shed, which is a symptom of overload protection firing, so it isn't strictly overload yet, but it does mean that the cluster is actively fighting against overload.

> to prevent false positives, what would you say a safe threshold would be?

Does this threshold need to be a constant or can it use other inputs? Ideally, we could say that if X percent of all requests are getting shed, then the cluster is getting overloaded. I.e. if we hit 1% then it's a good state to show a warning in the montoring, and anything > 10% and rising should mean an alert, where somebody should immediately take a look on how to reduce the pressure.

(I just made these numbers up, but they sound reasonable to me)

> Is there anything else we should look at?

The usual symptoms of overload that we probably monitor even now - e.g. large latencies, quota violations, a rise to 100% cpu where it wasn't even close to that before, etc.

**Comment by psarna** [comment]
> Hm, I didn't receive **any** of these notifications even though I'm pinged directly... I need to check my github preferences, sorry for the delay. Looking at it now.

Indeed, for some reason scylla-monitoring was marked as "ignored" in my settings, so I wasn't notified even when mentioned directly. I have no idea why it was set...

**Comment by amnonh** [comment]
@psarna I want to create some graphs for the release notes, how can I test this?

**Comment by psarna** [comment]
Test what precisely? For instance, you want to observe the `requests_shed` metrics going up, the simplest way is to set a low value for `max_concurrent_requests_per_shard` in scylla.yaml, e.g. 100, and then run a program which sends substantially more than 100 concurrent requests at a time - that can be scylla-bench, cassandra-stress or whatever else.
