### ISSUE TITLE
Heavy compaction Indication

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1582]
**Describe the issue logically**
Compaction takes lots of memory  and CPU

**Describe the condition when the issue happens**
- Not clear, compaction runs for a long time, shares are high, queus are getting filled.
- For how long:

**What the user should do when this happens**
Not clear, change the compaction strategy, set static compaction shares.

**Any Other info or Links.**

**Comment by slivne** [comment]
compaction shares stuck at 1000 are an indication that this is happening.

there are multiple issues related to this and we are working to fix that (its varied between compaction strategies).

When this happens - on the field we set the compaction shares to a static value 100 (--compaction-static-shares 100)

**Comment by tzach** [comment]
@slivne how do you define stuck? 1m? 5m?

**Comment by slivne** [comment]
stuck 30m

**Comment by slivne** [comment]
@amnonh ^^
