### ISSUE TITLE
Full scan warning

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1584]
**Describe the issue logically**
A full scan happens when a user perform a scan that would have better be done without the cache.
It doesn't have to be an entire scan of the table, it's enough that range or limitition or not strict.

**Describe the condition when the issue happens**
- Cache is beeing evicted with lots of cache misses.

It would be best if we can get an inidcation with the actual query details.

**What the user should do when this happens**
Add bypass cache and think if this is what is needed.

**Any Other info or Links.**

**Comment by slivne** [comment]
there are metrics showing partition scans 

```
# HELP scylla_cql_select_partition_range_scan Counts the number of SELECT query executions requiring partition range scan.
# TYPE scylla_cql_select_partition_range_scan counter
scylla_cql_select_partition_range_scan{shard="0"} 1
# HELP scylla_cql_select_partition_range_scan_no_bypass_cache Counts the number of SELECT query executions requiring partition range scan without BYPASS CACHE option.
# TYPE scylla_cql_select_partition_range_scan_no_bypass_cache counter
scylla_cql_select_partition_range_scan_no_bypass_cache{shard="0"} 1
# HELP scylla_database_clustering_filter_fast_path_count Counts number of times bloom filtering short cut to include all sstables when only one full range was specified.
# HELP scylla_sstables_range_partition_reads Number of partition range flat mutation reads
# TYPE scylla_sstables_range_partition_reads counter
scylla_sstables_range_partition_reads{shard="0"} 77
```

So we have an indication if scan is being done by the user or not and it its bypassing the cache or not
