### ISSUE TITLE
Scylla monitoring overview dashboard no read/write latencies result for enterprise version

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylla-monitoring#1586]
Dashboard Name: Overview
Scylla-Monitoring Version: 3.7.2
Scylla-Version: Enterprise 2020.1.11, 2020.1.8

Sample prometheus data: 
`scylla_storage_proxy_coordinator_write_latency_bucket{cluster="segp_stg", dc="ap-southeast-1-segp", instance="segp_scylla_stg1-001.segp.data-platform.myteksi.net", job="scylla", le="+Inf", scheduling_group_name="statement", shard="0", type="histogram"}`

![image](https://user-images.githubusercontent.com/33821205/141091099-23ae499f-8ee3-40b3-bd48-e8ed29243d80.png)

**Comment by codingcuisg** [comment]
It's working fine with open source cluster, sample of open source cluster prometheus data
`scylla_storage_proxy_coordinator_write_latency_bucket{cluster="prd-scylla", dc="datacenter1", instance="10.0.66.14", job="scylla", le="+Inf", scheduling_group_name="statement", shard="0"}`

**Comment by amnonh** [comment]
duplication of #1472 please upgrade to resovle the issue
