### ISSUE TITLE
AWait metrics is not correct

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1587]
![image](https://user-images.githubusercontent.com/2118079/141679805-2ef1bbb3-972b-4ebb-b8a6-279c51358123.png)

**Comment by amnonh** [comment]
probably something is off with: https://www.robustperception.io/mapping-iostat-to-the-node-exporters-node_disk_-metrics

**Comment by slivne** [comment]
Amnon suggested looking at scylla's end - e.g. does scylla see latency from the requests sent to the disk

@xemul do we have such a metric - I tried to look at the io-queue metrics and only found io-queue delay (which is the amount of time the requests are pending on scylla end in the queue before being submitted to the disk).

**Comment by amnonh** [comment]
Closing as no change on the subject for two years
