### ISSUE TITLE
./start-grafana.sh: line 143: [: -v: binary operator expected

### ISSUE THREAD

**Issue by rossengeorgiev** [scylladb/scylla-monitoring#1591]
Scylla-Monitoring Version: 3.8.3

# reproduce

This bug exist on latest too. To reproduce simply specify location for grafana data.

 `./start-all.sh -G /my/data/path ...`

Then you'll see the error message then it executes `./start-grafana.sh`. No grafana container will get created

# issue

`EXTERNAL_VOLUME` is set to the parameter for `docker run`:

https://github.com/scylladb/scylla-monitoring/blob/6f742e6c8c37c6c89d5338b0b190a8b1b9d9faec/start-grafana.sh#L44

Then these lines expect `EXTERNAL_VOLUME` to be just path to directory and single word:

https://github.com/scylladb/scylla-monitoring/blob/6f742e6c8c37c6c89d5338b0b190a8b1b9d9faec/start-grafana.sh#L142-L145

**Comment by rossengeorgiev** [comment]
Don't think this works:

https://github.com/scylladb/scylla-monitoring/blob/6f742e6c8c37c6c89d5338b0b190a8b1b9d9faec/start-grafana.sh#L165-L167

**Comment by amnonh** [comment]
Duplication of #1569

**Comment by rossengeorgiev** [comment]
Looking at #1569, this is not duplicate. Separate issues

**Comment by amnonh** [comment]
It seems that commit https://github.com/scylladb/scylla-monitoring/commit/02ef002b102f98c54a565b289d676ce5694de68a broke the external Grafana directory support
