### ISSUE TITLE
Tag scylla-monitoring-3.9.2 is missing

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-monitoring#1620]
We (scylla-cloud) want to let to upgrade monitoring to version 3.9.2 following latest announcement, but the tag 3.9.2 for scylla-monitoring is missing.
It's required by scylla-cloud to have it to support migration.

**Comment by amnonh** [comment]
Are you sure there is a 3.9.2 release?

**Comment by amnonh** [comment]
There is no 3.9.2 yet
