### ISSUE TITLE
The installation should take the version from the parameters

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1633]
Specifically in the installation without docker part there are still specific version in the document, it should be moved to use parameters

**Comment by amnonh** [comment]
@tzach I'm assigning it to you because I'm unable to assign it to @dgarcia360

**Comment by tzach** [comment]
@dgarcia360 please take a look

**Comment by dgarcia360** [comment]
You can use [conf.py -> rst_prolog](https://github.com/scylladb/scylla-monitoring/blob/master/docs/source/conf.py#L65) to define substitutions:

```
# Adds version variables for monitoring and manager versions when used in inline text
rst_prolog = """
.. |version| replace:: 3.10.0
.. |mon_root| replace::  `Scylla Monitoring Stack </>`__
"""
```
Then, you can use this substitutions in the text as follows:

```
This document is a step by step procedure for upgrading |mon_root| from version 2.x to 3.x
```

To use substitutions within a code block, add the option ``:substitutions:`` to the directive. For example:

```
.. code-block:: bash
   :substitutions:

   echo "|moon_root| released version |version|"
```
