### ISSUE TITLE
show deviation / variance for key metrics 

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#164]
For key metrics like load, knowing the average doesn't tell us the whole story. In all fairness, it never does - but for some metrics (load being an example), it is extremely useful to be able to detect imbalances among CPUs.

Most sources of imbalances will manifest themselves in load, so it should be enough to start with that.

prometheus has stddev / stdvar functions that we can use for that.

**Comment by tzach** [comment]
related to #173

**Comment by tzach** [comment]
@glommer can we close this? #206 #193 gives similar functionality.

**Comment by glommer** [comment]
Yes

On Aug 10, 2017 2:16 AM, "Tzach Livyatan" <notifications@github.com> wrote:

@glommer <https://github.com/glommer> can we close this? #206
<https://github.com/scylladb/scylla-grafana-monitoring/pull/206> #193
<https://github.com/scylladb/scylla-grafana-monitoring/pull/193> gives
similar functionality.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla-grafana-monitoring/issues/164#issuecomment-321461189>,
or mute the thread
