### ISSUE TITLE
"node restarted" event shown at incorrect point in time

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#1646]
*Installation details*
Panel Name: ALL
Dashboard Name: General / Detailed
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) 3.8.0
Scylla-Version: eba4a4fba4

The "node restarted" even is marked too late. It should be when the load is 0, between the two humps:

![Screenshot from 2022-01-07 21-17-59](https://user-images.githubusercontent.com/283695/148602062-0118327e-e134-407e-8b8f-740c8587a982.png)

**Comment by amnonh** [comment]
The restart is actually when the node is back up and report the gosip metric again, but that should also should have been earlier, I've tried to reproduce it
but a simple test brought something that looks ok
![image](https://user-images.githubusercontent.com/2118079/148688206-141116bd-ae0b-4218-8b89-f09b78a4c3fa.png)

I'm keeping the issue open, what scylla version are you testing?

**Comment by tgrabiec** [comment]
> what scylla version are you testing?

It's in the report form.

**Comment by tgrabiec** [comment]
Could it matter that I'm using 1s scrape period?

**Comment by amnonh** [comment]
I've tried it again with 1s scrap and still get a reasonable result:
![image](https://user-images.githubusercontent.com/2118079/148773402-8bf89c7b-4d13-40d1-a68c-10c40a795aa3.png)

From you image it's clear that the CQL is working so the node is probably up again, is there a possibility that 
scylla_gossip_heart_beat for some reason was not available?

if you can reproduce it on your system, can you show the graph of:
`scylla_gossip_heart_beat`

**Comment by amnonh** [comment]
Closing for no new data, re-open if needed
