### ISSUE TITLE
Scylla monitoring 3.9 image doesn't contain grafana dashboard for manager 2.6

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-monitoring#1656]
Even tough scylla-monitoring 3.9.x supports manager in version 2.6, it doesn't contain grafana dashboard for it:
https://github.com/scylladb/scylla-monitoring/blob/master/versions.sh

Monitor upgrade CLI command does a monitor sync, but sync is not generating dashboards, it just outputs the info that dashboard must be generated.

Please regenerate monitor image and add grafana dashboard for monitor 2.6 (generate-dashboard.sh)

**Comment by amnonh** [comment]
This is not related to the scylla monitoring project, closing
