### ISSUE TITLE
bad rendering on small screens

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#166]
"Unreachable nodes" sounds indeed better than dead, but it is too big of a term. In smaller screens, it ends up line-wrapping, and the end result looks ugly

![unreachable](https://cloud.githubusercontent.com/assets/331197/25680603/70fb1992-301f-11e7-873b-44e605da0ae1.png)

**Comment by tzach** [comment]
Agree. 
@amnonh can you please take a look? 
I guess we can either widen the boxs or add wording (or whitespace) to the "Total Node"

**Comment by amnonh** [comment]
How about rename to "Unreachable"?
I think it is clear from the context

**Comment by tzach** [comment]
Good idea.
"The Unreachables" can be a good movie title ;)

**Comment by glommer** [comment]
Fine by me
