### ISSUE TITLE
schema change events are not visible

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1661]
scylla-version=4.6
monitoring-version=3.10.0
dashboard=detailed-4-6

looking at the metric

```
scylla_database_schema_changed
```

its clear there were changes (its also clear from the logs and what QA reported doing to the cluster

![Screenshot from 2022-02-04 18-31-52](https://user-images.githubusercontent.com/3465480/152566379-56302cff-9e6f-4be7-9b5a-75bbb556a47b.png)

![Screenshot from 2022-02-04 18-31-28](https://user-images.githubusercontent.com/3465480/152566403-23a075b0-b8ab-495e-927e-731bf3dd7e09.png)

**Comment by slivne** [comment]
as a reference this is the scylla issue that has the info on the actual test https://github.com/scylladb/scylla/issues/10028

**Comment by amnonh** [comment]
It seems like a grafana issue https://github.com/grafana/grafana/issues/43454
I'm going to update grafana to version 8.3.4 that should solve it
