### ISSUE TITLE
Time spent in task quota violations needs to be a time value not a percentage

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1666]
scylla-version=4.6
monitoring-version=3.10.0
dashboard=advanced-4-6

![Screenshot from 2022-02-08 14-51-01](https://user-images.githubusercontent.com/3465480/152990523-cdbb7118-b2ee-468b-a8b4-221eb9ad62c3.png)

**Comment by amnonh** [comment]
Not according to @avikivity and #1573 which was fixed by #1595

**Comment by slivne** [comment]
OK - we can close

I don't know how todo this - percent of 1 second - and if you look on the graphs you will see that quota violation looks like the time spent in % for the intresting shards - so the graphs are the same.

**Comment by avikivity** [comment]
It's not percent of one second. It's percent of the time shown in the graph. If the graph shows one hour and 10% task quota violations, then it spent 6 minutes in task quota violations.
