### ISSUE TITLE
Cloud Monitoring: Templating warnings

### ISSUE THREAD

**Issue by omrivardi** [scylladb/scylla-monitoring#1670]
@tzach commented on [Sun Jan 23 2022](https://github.com/scylladb/siren-frontend/issues/2074)

From time to time I get ping pop up warning about templating.
Unfortunately, they disappears in a few seconds, before I can screen capture them.

---

@tzach commented on [Sun Jan 23 2022](https://github.com/scylladb/siren-frontend/issues/2074#issuecomment-1019494726)

@amnonh 

---

@omrivardi commented on [Tue Feb 01 2022](https://github.com/scylladb/siren-frontend/issues/2074#issuecomment-1026644973)

@tzach Can we move it to the monitoring repo? It want make any progress in the frontend repo

**Comment by amnonh** [comment]
I think with the latest monitoring release assuming that there are scylla servers running this issue is solved. closing, re-open if needd
