### ISSUE TITLE
New alert - cluster in split brain state

### ISSUE THREAD

**Issue by d-helios** [scylladb/scylla-monitoring#1677]
**System information**
- Scylla version (you are using): ANY
- Are you willing to contribute it (Yes/No): YES

**Describe the feature and the current behavior/state.**

We faced with situation when scylla was in "split brain" state, see the nodetool output bellow, but no alerts were generated because each node report that it in UN state

**Node: 192.168.1.108**
```
Datacenter: DC_1
=========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  192.168.2.211  137.59 GB  256          ?       ce76be2b-d1d6-46ce-96fc-606d5818bdfc  eu-west-1c
DN  192.168.0.177  142.47 GB  256          ?       01fbfdbb-389f-4458-aff6-2b0f3fe9a7bd  eu-west-1a
UN  192.168.1.108  135.46 GB  256          ?       fe2b70a0-dcac-496f-a045-da557895b5c0  eu-west-1b
```

**Node: 192.168.0.177**
```
Datacenter: DC_1
=========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  192.168.2.211  137.59 GB  256          ?       ce76be2b-d1d6-46ce-96fc-606d5818bdfc  eu-west-1c
UN  192.168.0.177  142.47 GB  256          ?       01fbfdbb-389f-4458-aff6-2b0f3fe9a7bd  eu-west-1a
DN  192.168.1.108  135.46 GB  256          ?       fe2b70a0-dcac-496f-a045-da557895b5c0  eu-west-1b
```

**Node: 192.168.2.211**
```
Datacenter: DC_1
=========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  192.168.2.211  137.59 GB  256          ?       ce76be2b-d1d6-46ce-96fc-606d5818bdfc  eu-west-1c
DN  192.168.0.177  142.46 GB  256          ?       01fbfdbb-389f-4458-aff6-2b0f3fe9a7bd  eu-west-1a
UN  192.168.1.108  135.46 GB  256          ?       fe2b70a0-dcac-496f-a045-da557895b5c0  eu-west-1b
```

**Who will benefit with this feature?**

Monitoring should handle the split brain cases, because it impact cluster stability

**Any Other info.**

**Comment by slivne** [comment]
I don't think we can detect split brain.

We should generate alerts based on gossip / failure detection information - or trigger node down alert by multiple triggers.

**Comment by amnonh** [comment]
@slivne I think I have an idea, the metrix of what each node see is problematic (quadratic in the number of nodes).
We can add a metrics with an aggregate number of nodes in each status.
That will be a minimal addition to the number of metrics but enough for alerts

**Comment by slivne** [comment]
I was sure you are going to say no problem if we had loki configured I
could tell you that :)

I don't think we need additional metrics.

I think we need the loki integration and alert on events in the log

**Comment by amnonh** [comment]
@slivne I think this is a relative `cheap` metric (in the sense that it's per host - not even per shard) and it could identify situations that even a node cannot see i.e. a new node joining a split brain cluster may not even know there is a problem, but the monitoring would say, we have a 6 nodes cluster, but this node only sees 3.

Regardless, if there is already a log for it, no problem in adding an alert
