### ISSUE TITLE
Show scylla_io_queue_queue_length metrics

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-monitoring#1678]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 4.0+
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

There's a per-priority-class gauge called `scylla_io_queue_queue_length`. It's good to have it next to IO queue latency, bandwidth and IOPS.

**Who will benefit with this feature?**

FAE team, developers. This metrics helps understanding large IO delays.

**Any Other info.**

**Comment by amnonh** [comment]
@xemul it sounds reasonable, can you describe in a few words how would you use such a metrics?

**Comment by xemul** [comment]
It's good to compare queue length with (large) delay, e.g. estimate the delay/length value. If the result is large, it means that it's either kernel or disk slowing individual requests down, or reactor being not responsive enough. If the result is small, then there's likely no problem with the in-kernel IO processing, but requests accumulate for some other reason.

**Comment by amnonh** [comment]
@xemul I'm trying to push it a bit further, can you formalize your description? what do you mean by `estimate the delay/length value`, when you say `If the result is large` what is large or small?

**Comment by xemul** [comment]
For IO the expected latency value is tens of ms and less. If it's not such, this needs to be explained. Looking at the queue length metrics gives you several options where to dig further. If you e.g. divide queue delay by the queue length and get values of 1ms or less, this means that IO is processed as proper speed, just it's too many of them in the queue than the disk can handle. So the problem is likely up the stack -- scylla is slow or generating too much IO or too may clients out there etc. If the delay/length value is large, e.g. tens of ms and more, this means that individual requests take long to proceed, so the problem is likely at or below seastar, e.g. reactor is not polling queues often enough or kernel is slowing IO down or disk is delaying requests (e.g. due to some unwanted background activity), etc.
