### ISSUE TITLE
Show scylla_io_queue_total_exec_sec metrics

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-monitoring#1679]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 4.6+
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Starting from 4.6 there's a metrics called `scylla_io_queue_total_exec_sec`. It's a counter similar to the one from #1570 and demonstrates the total time requests spend in disk. It would be nice to have this graph plotted next to (or even on the same graph with) the IO queue delay one.

**Who will benefit with this feature?**

FAE team, developers. This metrics helps understanding if the kernel/disk operates the way we expect it or is it causing unwanted/unexpected delays in IO processing.

**Any Other info.**

**Comment by amnonh** [comment]
@xemul can you add a few words on how would you use such a metrics?

**Comment by xemul** [comment]
We [have](https://github.com/scylladb/diskplorer/tree/master/latency-matrix-results) some expectations from how disks behave. Also there's seastar "assumption" that requests put into disk take around `1.5*latency_goal` time to complete. If we're right with both, then this metrics should stay within few milliseconds. If it grows big, this means we're wrong somewhere, or the disk/filesystem is misbehaving (or there's a bug).
