### ISSUE TITLE
Show scylla_io_queue_disk_queue_length metrics

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-monitoring#1680]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 4.6+
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Starting from 4.6 there's a gauge called `scylla_io_queue_disk_queue_length`. It's similar to the queue length gauge from #1678 and it's very handy to have it nearby.

**Who will benefit with this feature?**

FAE team, developers. Normally the scheduler mustn't put too many requests into disk. Also, on new scheduler, there's an inter-shard capacity sharing that balance submission limits between shards. This metrics will show if (and how) the scheduler respects it.

**Any Other info.**

**Comment by amnonh** [comment]
@xemul it's not clear if this metric  is helpful for a user or for a scylla developer, how would you use such a metric?

**Comment by xemul** [comment]
It's more for developer or FAE team. Normally IO scheduler shouldn't put "too many" requests into disk and should maintain a certain balance between different classes. If this metrics grows large this points to misconfigured queue.

**Comment by amnonh** [comment]
@xemul can you formalize it? what is `too many`, what do you mean by `if this metrics grows large`, what is `large`?

**Comment by xemul** [comment]
There's `io_properties.yaml` file that says how many requests/bytes per second a disk can do. Newer scheduler also has a "rate_factor" parameter that scales this numbers. Using it seastar limits itself in the amount of simultaneously executing requests in the disk. Then this number is shared between shards and classes.

When I say "too many" and "large" I mean -- comparing to the numbers from io-properties.yaml. I don't mean that we're going to validate if the io-properties.yaml is correct (though we can do it). The intention is to check which shard/class is getting more disk capacity compared to others. This skew can explain why the IO delay in some classes grows large.
