### ISSUE TITLE
Grafana incorrectly showing notifications about newer version

### ISSUE THREAD

**Issue by rossengeorgiev** [scylladb/scylla-monitoring#1682]
*Installation details*
Scylla-Monitoring Version: 3.10.1

On `General / Overview` dashboard I see this:

![image](https://user-images.githubusercontent.com/2720787/155135807-1a46486f-709a-4939-ac4f-b4f37d8f3454.png)

**Comment by amnonh** [comment]
Resolved

**Comment by rossengeorgiev** [comment]
I see it 70d24a21eec441be659271da3dac704634405d15 thanks
