### ISSUE TITLE
"Number of files by Instance" metrics doesn't shows current state 

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/scylla-monitoring#1684]
*Installation details*
Panel Name: Number of files by Instance
Dashboard Name: OS Metrics
Scylla-Monitoring Version: 3.10.0
Scylla-Version: 2021.1

Number of files by Instance is always different from the actual value on node and does not change. 
I've already checked it on few clusters. 

![image](https://user-images.githubusercontent.com/11996012/155174093-921af9eb-7ee6-48d8-b302-199a77ee9117.png)

```
[~]$ sudo find /var/lib/scylla/ | wc -l
364
[~]$ sudo lsof /var/lib/scylla/ | wc -l
46
[~]$ sudo lsof | wc -l
4153
```

**Comment by AdamStawarz** [comment]
@amnonh @tarzanek

**Comment by fee-mendes** [comment]
The formula should likely be:
`sum(node_filesystem_files{mountpoint="$mount_point", instance=~"$node"} - node_filesystem_files_free{mountpoint="$mount_point", instance=~"$node"}) by ([[by]])`

`node_filesystem_files` basically describes the maximum number of inodes, whereas `node_filesystem_files_free` is the number of unallocated inodes. `total - free == used`

**Comment by fee-mendes** [comment]
@AdamStawarz also keep in mind that there is no relation between `lsof` and the number of inodes in a filesystem. So only the first `find` command is what's of interest in your output. ;-)
