### ISSUE TITLE
Cache metrics are not shown

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla-monitoring#169]
Cache metrics on master changed from scylla_cache_(hits. misses...) to scylla_cache_total_operations_(hits. misses...). Dashboard should change accordingly. Alternatively this is Scylla bug in master and metric names should be changed back.

**Comment by tzach** [comment]
@gleb-cloudius what dashboard are you using?

**Comment by gleb-cloudius** [comment]
On Wed, May 10, 2017 at 02:47:49AM -0700, Tzach Livyatan wrote:
> @gleb-cloudius what dashboard are you using?
> 
master

--
			Gleb.

**Comment by tzach** [comment]
@gleb-cloudius @avikivity ping

**Comment by gleb-cloudius** [comment]
On Mon, Jul 03, 2017 at 06:28:25AM +0000, Tzach Livyatan wrote:
> @gleb-cloudius @avikivity ping
> 
Ping what? What do you expect from me?

--
			Gleb.

**Comment by tzach** [comment]
Look like the metrics name has changed from `scylla_cache_hits` in master dashboard to `scylla_cache_total_operations_hits` in Scylla master, maybe when moving to row cache

**Comment by gleb-cloudius** [comment]
On Mon, Jul 03, 2017 at 11:48:27PM -0700, Tzach Livyatan wrote:
> Look like the metrics name has changed from `scylla_cache_hits` in master dashboard to `scylla_cache_total_operations_hits` in Scylla master, maybe when moving to row cache
> 
> 
That happen much, much earlier than row cache was committed. The bug
itself is older than that.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Tue, Jul 04, 2017 at 09:49:58AM +0300, Gleb Natapov wrote:
> On Mon, Jul 03, 2017 at 11:48:27PM -0700, Tzach Livyatan wrote:
> > Look like the metrics name has changed from `scylla_cache_hits` in master dashboard to `scylla_cache_total_operations_hits` in Scylla master, maybe when moving to row cache
> > 
> > 
> That happen much, much earlier than row cache was committed. The bug
> itself is older than that.
> 
By "the bug" I mean this issue about the bug.

--
			Gleb.
