### ISSUE TITLE
Monitoring 3.10 -- Os dashboard shows 29 panels in disk usage instead of 54 

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/scylla-monitoring#1696]
*Installation details*
Panel Name: total storage
Dashboard Name: OS Metrics 
Scylla-Monitoring Version: 3.10.0
Scylla-Version: 2020.1.8 

### Problem description 

/prometheus/scylla_servers.yml configuration contains 54nodes in total, but we can see only 27 panels under OS Metrics dashboard.
All rest dashboards shows proper 54 nodes. 

Please let me know if you need any logs

**Comment by amnonh** [comment]
It means there's a problem with the node_exporter scraping, the question is what.
If you have an access to the the prometheus server, can you check the targets tab (under status)

**Comment by AdamStawarz** [comment]
@amnonh 
![image](https://user-images.githubusercontent.com/11996012/159264114-8bb038d5-1732-446a-ab40-f8fbc95901bd.png)

41 nodes is still different than 27, and I'm curious why other dashboards shows correct number of nodes

**Comment by AdamStawarz** [comment]
@amnonh ^^

**Comment by amnonh** [comment]
The os dashboard is based on node_exporter while other dashboards uses scylla's information.

Can you add a capture of the entire os dashboard so I can see what is missin?

**Comment by mykaul** [comment]
@AdamStawarz  ?

**Comment by amnonh** [comment]
Closing, re-open if needed
