### ISSUE TITLE
HWLB should be based on cache not row_cache

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1702]

**Comment by nyh** [comment]
The motivation for changing this is https://github.com/scylladb/scylla/issues/10258 - it appears that the `scylla_cache_row_hits` which we use today is incorrect or doesn't do what we think it does, while `scylla_cache_reads` and `scylla_cache_reads_with_misses` are more correct.

Moreover, the HWLB code itself uses something similar to the latter two metrics, not the `scylla_cache_row_hits` (it actually uses per-table counters, but those are updated in the same place that the global counters are updated - whereas `scylla_cache_row_hits` is updated in a completely different place).
