### ISSUE TITLE
Update scylla_io_queue_total_delay_sec metrics dispay (if possible)

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-monitoring#1714]
After fixing the #1570 there appeared an inconvenience. The problem is that the `..._total_delay_sec` metrics shows the sum of individual requests delays over some priod of time. And, for example, if there had passed 1k of requests with 50us delay each the metrics would report delta of `1k * 50us = 50ms`. Thus when looking at the metrics it's always needed to make the reverse division (reported delay / reported IOPS) to get the idea of individual request latency.

If that's possible the dashboard should draw the `rate(total_delay_sec) / rate(IOPS)`.

**Comment by amnonh** [comment]
@xemul is this only relevant to 5.0 and 2022.1 ?

**Comment by xemul** [comment]
No, the `..._total_delay_sec` appeared earlier. It's exported in 4.5.3 and 4.5.6
