### ISSUE TITLE
Monitor node open file descriptors and compare against max

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla-monitoring#1719]
**System information**
- Scylla version (you are using): 4.6.2

**Describe the feature and the current behavior/state.**
`node_exporter` provides a nice way for us to get an overview of the node's consumed FDs via the `node_filefd_allocated` metric. Moreover, it may also warn us whenever the node may be close to reaching its limits when used in conjunction via the `node_filefd_maximum`  metric. (keep in mind this is `fs.file-max` and has no relation to `fs.nr-open`: See https://github.com/scylladb/scylla/pull/9461)

Do notice, however, that these metrics alone will not provide how many open FDs the Scylla process itself is consuming, rather, it will provide the details of all processes, in such a way that it is generally a good idea to also explain and document this fact.

Finally, the metric `process_open_fds` **COULD BE** used to report Scylla open FDs, but this would require changes to seastar monitoring and - therefore - are not relevant to this issue.

**Who will benefit with this feature?**
Users who want to monitor their cluster state in general and avoid the database from running out of FDs, specially during high streaming/repair activities.

**Comment by amnonh** [comment]
Looks like a duplication of #726 please close or state the difference

**Comment by amnonh** [comment]
@fee-mendes please comment

**Comment by fee-mendes** [comment]
You're right, its actually the same. I'll bump the other one instead :-)
