### ISSUE TITLE
Standard deviation metric for the reactor load

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#173]

**Comment by amnonh** [comment]
also #328

**Comment by amnonh** [comment]
@tzach looking back at it, the issue is not clear, what type of graph do you want to show, how will it be helpful?

**Comment by amnonh** [comment]
@tzach ping

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
The suggestion is in the subject: add a "Standard deviation metric for the reactor load"

**Comment by amnonh** [comment]
That shallow green line down the bottom, that's the stddev.

![image](https://user-images.githubusercontent.com/2118079/70713506-d20bbc00-1cee-11ea-8069-d29c72b4fa59.png)

I don't understand graphically or logically what do you want to show

**Comment by tzach** [comment]
The motivation is presenting a summary view of the variance between nodes / cores
- Not relevant if we show the nodes themselves
- Need to be presented as Candlestick

does this make sense? possible?

**Comment by amnonh** [comment]
What you are talking about seems like avg +/- std

**Comment by amnonh** [comment]
@tzach This is an example of adding avg +/-std:
![image](https://user-images.githubusercontent.com/2118079/79200510-3bd3d800-7e3f-11ea-96bd-5cf94bb08f5f.png)
I'm not sure this is helpful, but let me know what you think
