### ISSUE TITLE
There should always be a way to control the sorting order in the "mouse tip" table

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1742]
**System information**
- Scylla version (you are using): 2021.1.10
- Are you willing to contribute it (Yes/No): No but I have a lot of ideas

**Describe the feature and the current behavior/state.**
There should always be an easy way to change the sorting order of entries appearing in the "mouse tip" table (below is a screenshot of a :

![image](https://user-images.githubusercontent.com/6103981/169093132-04cebc56-7d93-4ff6-94a0-69e93a1391f4.png)

As you may see in the screenshot above the order in the table is just random and this not very useful to say the least.

What makes it more annoying is that once there was an easy way to change this via "Edit" menu of a specific graph. But the currently used "Time series" graph kind doesn't seem to have this ability. So, you have to change it do something like "Graph (old)" and after that you can force it into making some sense:

![image](https://user-images.githubusercontent.com/6103981/169093869-1792aadf-e49c-474b-b75d-cee63b5adb07.png)

**Request**
It would be really great NOT to have to modify separate graphs but rather have a corresponding selector that would apply the change to all graphs on a given dashboard.

**Who will benefit with this feature?**
Everybody who uses Monitoring for debugging

**Comment by amnonh** [comment]
Luckily https://github.com/grafana/grafana/discussions/38861 was fixed

**Comment by vladzcloudius** [comment]
@amnonh the idea of this GH issue is NOT to have to modify each separate graph.
4.1.0 has a very annoying default sorting - ascending.

This GH issue suggests to add a ticker on every dashboard that would allow flipping the sorting order of all graphs on the dashboard in a single click.

**Comment by amnonh** [comment]
I'm closing based on https://github.com/scylladb/scylla-monitoring/issues/2055
