### ISSUE TITLE
Manager tasks in a weird appearance

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylla-monitoring#1746]
*Installation details*
Panel Name: everyone that shows manager tasks
Dashboard Name: everyone that shows manager tasks
Scylla-Monitoring Version:  3.10.1

Manager tasks started showing a weird appearance:
![image](https://user-images.githubusercontent.com/31359297/169843516-24c2b15a-25dc-462f-a0da-f13945fb4212.png)

![image](https://user-images.githubusercontent.com/31359297/169843937-029dd99f-28df-4fe2-9222-cabb21e3055f.png)

I'm aware that we have an option to disable the appearance of the tasks, but sometimes it's useful to have it enabled to check metrics that correlate with repair/backup time. 

Just as a comparative, in the past, we were used to seeing a green beam instead of several vertical lines:
![image](https://user-images.githubusercontent.com/31359297/169845210-5fd3125f-48e1-4e8b-9450-428b6752e43a.png).

I was wondering whether it's a bug and we can figure out how to go back to the old good way. 

FYI, as we've talked today @amnonh 
Thx!

**Comment by noellymedina** [comment]
Let me know if it's needed further information

**Comment by amnonh** [comment]
can you show a graph of ``scylla_manager_task_active_count{type=~"repair|backup"}``

**Comment by noellymedina** [comment]
![image](https://user-images.githubusercontent.com/31359297/170049325-9ac2802a-797b-4de2-9ed4-af67929edab0.png)

**Comment by amnonh** [comment]
I've opened https://github.com/grafana/grafana/issues/49515

**Comment by amnonh** [comment]
@noellymedina do you know if the issue persist?

**Comment by amnonh** [comment]
@noellymedina I'm closing the issue, from what I see it's most likely a matter of zooming in and out from a dashbaord
