### ISSUE TITLE
schema change events are not reported correctly

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1756]
https://github.com/scylladb/scylla/issues/10497

focus on 3 May 2022 10:20 - 10:30 - there are schema change events yet the 
![Screenshot from 2022-06-13 11-54-54](https://user-images.githubusercontent.com/3465480/173317334-c653e9f6-d02e-4727-a2b2-4903b6d58900.png)

this is from the raw metric

yet when enabeling the schema change slider it does not report correctly the events

![Screenshot from 2022-06-13 11-55-46](https://user-images.githubusercontent.com/3465480/173317467-4e0c0a07-4a6b-4529-a745-8cd9436a50b2.png)

**Comment by amnonh** [comment]
@slivne can you be more specific, what the are the time of the schema changed and what are the time of the annotations?

**Comment by slivne** [comment]
@amnonh the forground writes in the graph is not displaying writes its using the database_schema_change metric - as you can see there are schema changes hapening and they are not highlighted correctly in graphana using annotations.

To reproduce download the metrics and upload zoom in to the specific time range I gave and compare what annotation does to the data_schema_change_event metric we have.

**Comment by amnonh** [comment]
I've checked, it's a bug with grafana, their anotations implementation is broken, I've also checked with the newest 9.0.0 release, it's still broken, but in a different way.

I've already opened https://github.com/grafana/grafana/issues/49515 I would update it or add another issue
