### ISSUE TITLE
Trying to debug some 500 errors and no per-table stats

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylla-monitoring#1757]
Installation details: scylla-monitoring 4.0.0, Grafana 9.0, rest of stack also at latest versions. All manually installed via the Scylla "install without Docker" instructions.
Panel Name: Connection, Large Rows, etc.
Dashboard Name: Scylla CQL and Keyspace dashboards
Scylla-Version: 5.0 rc7

Recently I wanted to upgrade my scylla-monitoring setup to enable the parts of these 2 dashboards that say they need the plugin configured, so I followed the instructions on that regarding setting up the CQL user for the system tables, modified the Grafana config files, and also addedd the "enable-keyspace-column-family-metrics: true" line to scylla.yaml on each node.

I then restarted Grafana and when I got to view those CQL dashboard panels that use the plug, I see they have 500 errors. In the server's syslog I see entries like:

> Jun 14 18:45:21 ip-172-31-112-5 grafana-server[16542]: logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-14T18:45:21.617685772-04:00 level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=xx.xx.xx.xx time_ms=2 duration=2.152599ms size=75 referer="http://xx.xx.xx.xx:3000/d/cql-5-0/scylla-cql?orgId=1&refresh=30s" traceID=00000000000000000000000000000000

 
(IP addresses removed)

And then on the Keyspace dashboard it still has the red warning text saying I need to enable enable-keyspace-column-family-metrics.

What have I missed in my configuration, or how can I best debug it?

**Comment by amnonh** [comment]
You are describing two unrelated issues.
About the Scylla Plugin configuration, it would be helpful to get more of the grafana logs to try and understand why it fails.

About the per-table metrics did you add a keyspace and table?

**Comment by A-Posthuman** [comment]
Hi, thanks for pointing me to look more into the logs. I found this further up in the Grafana logs:

> Jun 15 21:20:47 ip-172-31-112-5 grafana-server[20378]: logger=plugin.manager t=2022-06-15T21:20:47.601532644-04:00 level=error msg="Could not start plugin" pluginId=scylladb-scylla-datasource err="fork/exec /var/lib/grafana/plugins/scylla-plugin/dist/gpx_scylla-datasource_linux_arm64: no such file or directory"

So yeah, I didn't realize there was no arm64 support on Scylla Monitoring. Most other Scylla projects have arm64 support, is there a way it can be added to Monitoring? Is there a way for me to compile the plugin on my instance? I'd like to stay on arm64 if possible, as the entire rest of the stack seems to work ok on arm64 and the instance is cheaper to run.

I also found the camptocamp-prometheus-alertmanager-datasource plugin wasn't loading, it needed to be added to the unsigned plugins list in grafana.ini, but I guess that isn't the main issue here.

**Comment by amnonh** [comment]
@A-Posthuman Have you tried using containers? Maybe it would be easier.

The scylla plugin is repository can be found here:
https://github.com/scylladb/scylla-grafana-datasource

**Comment by A-Posthuman** [comment]
It would probably be easier, but I am trying to learn more about all these various pieces.

I have attempted to compile the plugin for arm64, but am getting stuck near the end of the process, probably because I know little about Go.

After getting through all the yarn install stuff (required I use a very old node 12.x version to work, and python 2.7), while in the plugin's main directory I execute these commands:

> sudo apt install golang
> go get -u github.com/grafana/grafana-plugin-sdk-go
> wget https://github.com/magefile/mage/releases/download/v1.13.0/mage_1.13.0_Linux-ARM64.tar.gz
> tar -xvf *.gz
> export GO111MODULE=off
> ./mage -v

then I get this error which I am currently stumped on:

> Error parsing magefiles: error running "go list -f {{.Dir}}||{{.Name}} github.com/grafana/grafana-plugin-sdk-go/build": exit status 1
> can't load package: package github.com/grafana/grafana-plugin-sdk-go/build: cannot find package "github.com/grafana/grafana-plugin-sdk-go/build" in any of:
>         /usr/lib/go-1.13/src/github.com/grafana/grafana-plugin-sdk-go/build (from $GOROOT)
>         /home/ubuntu/go/src/github.com/grafana/grafana-plugin-sdk-go/build (from $GOPATH)

if I do: go env |grep GOPATH
then:
GOPATH="/home/ubuntu/go"

I can see in /home/ubuntu/go there is a pkg dir that seems to contain the github.com/grafana/grafana-plugin-sdk-go stuff, but there is no "src" dir.

Any help appreciated!

**Comment by A-Posthuman** [comment]
As an update I never was able to get the plugin compiled for arm64 architecture. I really would like to, because running arm64 instances on AWS is cheaper than amd64. And with AWS graviton3 chips and future iterations, arm64 becomes even more compelling in terms of price/performance.

Should I add an Issue to the scylla-grafana-datasource repo to request arm64 support? Or is this something you never plan to add?

**Comment by amnonh** [comment]
closing this issue, reopen if you think it is needed
