### ISSUE TITLE
Need to run generate dashboards script not mention in page Install Scylla Monitoring Stack

### ISSUE THREAD

**Issue by guy9** [scylladb/scylla-monitoring#1759]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-4.0/install/monitoring_stack

### Problem
This page does not mention the need to run generate-dashboards.sh before running the start-all script
Also, it's not clear to me when to run ./start-all.sh -v 2021.1 -M 2.0
and when to run ./start-all.sh -L <Manager IP>

###  Suggest a fix
Fix the above

**Comment by amnonh** [comment]
Typically you don't need to run generate-dashboards.sh (only if you are using  the master brunch which you shouldn't and then you'll get a notification about it).

Have you checked [the start_all](https://monitoring.docs.scylladb.com/branch-4.0/install/start_all.html) page?

**Comment by amnonh** [comment]
@guy9 I'm closing, please reopen if you think it is needed
