### ISSUE TITLE
Provide an option to disable alter and loki

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-monitoring#1763]
When starting a scylla monitor locally to analyses existing cluster data, e.g., looking at monitor data from SCT test from QA. 
```
$ ./start-all.sh -s ./config/scylla_servers.yml  -d ../20220624T015727Z-70ebac547b525c7b
Wait for alert manager container to start
Wait for Loki container to start.
```

It took time to start alter and loki container. I doubt we really need them for such use case.

So can we provide an option to disable them?

**Comment by amnonh** [comment]
you can disable loki with ```--no-loki``` it's not trivial to disable alert manager both prometheus and garafa are looking for it.
I'm closing the issue as already supported, re-open if you think it's needed
