### ISSUE TITLE
Wrong permissions on /home/centos on new Monitor 4.0.0 image

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-monitoring#1765]
We wanted to introduce support for Monitor 4.0.0 stack in scylla-cloud.
Looks that user `centos` has no rights to his home directory on the instance created out of provided monitoring stack image. See `ls -la ~` output 
```
drwxr-xr-x 5 root   root   4096 Jun 29 09:59 .
drwxr-xr-x 6 root   root   4096 Jun 29 10:00 ..
drwx------ 2 centos centos 4096 Jun 29 09:59 .ssh
drwxr-xr-x 9 centos centos 4096 Jun 20 13:16 scylla-grafana-monitoring-scylla-monitoring
drwxr-xr-x 3 root   root   4096 Jun 20 13:16 scylla-monitoring
```

We use ~ to save config of traefik here (theoretically we could use ` scylla-grafana-monitoring-scylla-monitoring`, as I see centos is the owner, and write here).

Is this lack of permissions done for some purpose ?

I'll keep this issue as a blocker for "Monitor 4.0.0 in cloud".

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I have created a new image scylla_monitoring_2022-07-05T09-53-02Z that chown to centos the entire home directory

**Comment by karol-kokoszka** [comment]
@amnonh I confirm the problem is solved for AWS. Can you create new image for GCP as well ?

**Comment by amnonh** [comment]
GCP image: scylla-monitoring-cloud-ubuntu-4-0-0-2022-07-06t06-45-42z

**Comment by karol-kokoszka** [comment]
Fixed. New images are correct.
