### ISSUE TITLE
Mac OS compatibility 

### ISSUE THREAD

**Issue by malah-akh** [scylladb/scylla-monitoring#1768]
Hi, 

Currently is not possible to run scylla-monitoring on MAC OS, we should make the start-all.sh compatible with Mac. 

`versions.sh: line 8: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 9: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 10: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 11: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 12: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 13: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 14: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 15: 3.8: syntax error: invalid arithmetic operator (error token is ".8")
versions.sh: line 19: 3.11.0: syntax error: invalid arithmetic operator (error token is ".11.0")
versions.sh: line 21: 3.11.0: syntax error: invalid arithmetic operator (error token is ".11.0")
versions.sh: line 120: 3.11.0: syntax error: invalid arithmetic operator (error token is ".11.0")
readlink: illegal option -- m
usage: readlink [-fn] [file ...]
readlink: illegal option -- m
usage: readlink [-fn] [file ...]
readlink: illegal option -- m
usage: readlink [-fn] [file ...]
Warning: without an external Prometheus directory, Prometheus data will be deleted on shutdown, use the -d command line flag for data persistence.
Wait for alert manager container to start
versions.sh: line 8: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 9: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 10: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 11: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 12: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 13: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 14: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
versions.sh: line 15: 3.8: syntax error: invalid arithmetic operator (error token is ".8")
Error: Alertmanager container failed to start
For more information use: docker logs aalert`

**Comment by amnonh** [comment]
@ricardoborenstein was that fixed by #1982 ? if so, please close
