### ISSUE TITLE
Docs: Update use hyphens (-) instead of underscores (_) in doc URLs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1772]
Google recommend using use hyphens (-) instead of underscores (_) in doc URLs
https://developers.google.com/search/docs/advanced/guidelines/url-structure

We have a few docs with underscores, like `install/monitor_without_docker.rst`
We should rename it to `install/monitor-without-docker.rst` and set a redirection from the old to the new path.

**Comment by amnonh** [comment]
@dgarcia360 how renaming the files would work across brances?

**Comment by nyh** [comment]
@tzach I wonder how up-to-date this recommendation is. I see folklore dating back to 20 years ago (!) - http://weblog.philringnalda.com/2004/04/22/underscores-are-bad-mmkay - that when google sees the url "monitor_without_docker" it doesn't index the individual words, just the whole thing, but with hyphens it does index the individual words. I see it was repeated I think it would have been extraordinarily silly for them not to have fixed this issue in the 20 years that have passed. Wikipedia is an example of a site that uses underscores exclusively in URLs (e.g., https://en.wikipedia.org/wiki/Main_Page), and they don't exactly do badly on Google ;-)

Hyphens have several other minor advantages over underscores in URLs, but going to rename old pages also has its own downsides, include SEO downsides that the whole rename thing was supposed to improve.

**Comment by tzach** [comment]
We got this advice (a year ago) from a SEO "expert".
Also the Google link above with this recomendation is still alive.

> rename old pages also has its own downsides

True, but we do :
- redirect all the old URLs to the new ones
- update all internal links

**Comment by nyh** [comment]
> We got this advice (a year ago) from a SEO "expert". Also the Google link above with this recomendation is still alive.

I know, but it smells like an urban legend. Why would Google know this for 20 years (!) and not solve it?
It would be interesting to check this, but I'm too lazy, maybe we can ask our SEO expert to do it ;-)
Or you can just change the underscores to hyphens - I'm not against it. I just wondered if there is a real reason to do it, or it's just an urban legend.

**Comment by amnonh** [comment]
@tzach @dgarcia360 what about this issue?

**Comment by tzach** [comment]
> @tzach @dgarcia360 what about this issue?

Still valid.

**Comment by amnonh** [comment]
@dgarcia360 can you handle this? @tzach says it is still valid
