### ISSUE TITLE
Alert manager is not starting with the right user permissions

### ISSUE THREAD

**Issue by YvanDaSilva** [scylladb/scylla-monitoring#1785]
Hello,

When storing the data of the alert_manager, I realized it was changing the directory owner.
For now we have a fix on SC side to deal with it.

But if we look at the grafana script, we can see it does use the right permissions
https://github.com/scylladb/scylla-monitoring/blob/master/start-grafana.sh#L232

But on the alert manager the permissions seem to not be used
https://github.com/scylladb/scylla-monitoring/blob/954c97560b348d10520f43c4ee266f8ca7899f31/start-alertmanager.sh#L117

Is there a specific reason for this, or is it really a bug ?

**Comment by amnonh** [comment]
There was simply no need to change the user permission when the continer did not use external directory

**Comment by amnonh** [comment]
@YvanDaSilva I've looked at the ```start-alertmanger.sh``` code did you use the ```-f``` flag to set the external directory to alertmanager?

From the code it seems to set the right user permission.

**Comment by YvanDaSilva** [comment]
Forgot to answer @amnonh . This is now fixed and addressed on our side with the use of `-f`, thank you.
