### ISSUE TITLE
See a streaming progress

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1788]
*Description*
We want to be able to see the current progress of the streaming similarly to how we see a progress of a backup or a repair today.

**Comment by tzach** [comment]
Note we currently have two types of streaming:
- For replace node (RBNO)
- Add / remove node (not RBNO just yet)
I suggest a forward looking RBNO implemntion.

**Comment by vladzcloudius** [comment]
> Note we currently have two types of streaming:
> 
>     * For replace node (RBNO)
> 
>     * Add / remove node (not RBNO just yet)
>       I suggest a forward looking RBNO implemntion.

We need both as long as we have both.

**Comment by amnonh** [comment]
Seems like a duplication of #921
We already have anotations for repair operation.
@asias can you add your feedback?

**Comment by vladzcloudius** [comment]
> Seems like a duplication of #921 

The above seems to be completely about RBNO.
I clarified a posts earlier that we need old streaming visibility as along as we use and we are likely going to continue using it for at least some operations at least mid-term (e.g. bootstrapping). @asias Could you, please, clarify this one:
* If and when "classic streaming" is no longer going to be used?


> We already have anotations for repair operation. 

Our existing repair annotations are only showing that the repair is running - not how much has been processed or anything #921 is asking for. Only SM dashboard has a more useful data for a regular repair however this data is collected from SM and not all customers are using SM, and clearly this is not going to cover RBNO.

@amnonh @tzach All relevant info for a "classic streaming" can be found in scylla syslog quite from the beginning of times.

I even wrote a quick demo: 

[streaming_progress.zip](https://github.com/scylladb/scylla-monitoring/files/9616922/streaming_progress.zip)

So, all it takes is to pick this info and given Loki - we have all relevant framework for that.

**Comment by asias** [comment]
I have sent a PR here https://github.com/scylladb/scylladb/pull/11601 to implement the metrics for classic streaming.
