### ISSUE TITLE
add an alert for scylla_reator_aio_errors

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#1789]
We need to add a an alert related to aio errors

**Comment by amnonh** [comment]
We have an alert for ```scylla_reactor_aio_errors```

**Comment by slivne** [comment]
https://github.com/scylladb/scylla-monitoring/blob/0603af7431ad7c010dcaad4c4938d6c085f47288/prometheus/prom_rules/prometheus.rules.yml#L270

Ok thanks

**Comment by amnonh** [comment]
close as not a bug
