### ISSUE TITLE
docs: Issue in page Install Scylla Monitoring Stack

### ISSUE THREAD

**Issue by shivamarora1** [scylladb/scylla-monitoring#1792]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-4.0/install/monitoring_stack

### Problem
In the very first line of [**Install Scylla Monitoring Stack**](https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#install-scylla-monitoring-stack), link on **Scylla Prometheus API** is broken

**Comment by tzach** [comment]
should probably point to reference/monitoring_apis.html#prometheus
