### ISSUE TITLE
No progress on backup and repair gauges

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-monitoring#1796]
*Installation details*
Panel Name: Backup %, Repair %
Dashboard Name: Scylla Manager Metrics
Scylla-Monitoring Version: 3.10.1
Scylla-Version: 2021.1.12

*Issue*
Backup and Repair progress bar gauges shows 1% the whole time a task is active. It should increase the % as the tasks progresses.
![image](https://user-images.githubusercontent.com/1693866/191803222-8294493a-426f-42ac-9c0f-286c03b6789d.png)

When looking into the formula, the current query returns a decimal to represent the progress of the task. 1.0 meaning 100%. I think the number is also rounded up (that's why it's always at 1%). If I change the formula to multiply by 100 the issue is fixed:
![image](https://user-images.githubusercontent.com/1693866/191803762-9bd96590-0894-4858-86b5-345129b1dcff.png)

**Comment by hopugop** [comment]
@amnonh the issue affects both Backup (fixed by #1803) and Repairs. Could you please look into fixing the Repair progress bar gauge as well?

**Comment by amnonh** [comment]
Fixed by #1805
