### ISSUE TITLE
docs: Issue in page Scylla Monitoring Datadog Integration

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#1802]
I would like to report an issue in page https://monitoring.docs.scylladb.com/master/procedures/datadog/index

### Problem
We are upgrading SC customers to Monitoring 4.0.2 for the DD integration fix, and some Ent customers will do the same.
But this doc exists only in Master and not in the office Monitoring 4.0 (or 4.0.2 if that will be created).

###  Suggest a fix
Please post in the official 4.0 monitoring docs: https://monitoring.docs.scylladb.com/stable/index.html
Under Procedures section.

cc @amnonh @annastuchlik @tzach

**Comment by annastuchlik** [comment]
@amnonh You added the DataDog integration section on master, but I can't see it on branch-4.0. Can you add that section to version 4.0?

**Comment by amnonh** [comment]
It will be part of the next 4.1 branch, the documentation is now there:
https://monitoring.docs.scylladb.com/branch-4.1/procedures/datadog/index.html

**Comment by annastuchlik** [comment]
@tomer-sandler The DataDog integration page was not available in version 4.0.0, so it was added to version 4.1. 
This is expected behavior because the documentation is published with major releases (x.y), not patch releases (x.y.z).

**Comment by amnonh** [comment]
@tomer-sandler closing as not a but, please re-open if needed
