### ISSUE TITLE
Fix the warning in the documentation for version 4.1 

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla-monitoring#1806]
When you select the unstable (unreleased) version of Monitoring Stack, the message tells you that you're viewing the documentation for a **previous** Monitoring:
![image](https://user-images.githubusercontent.com/37244380/194513924-3b9fb4f6-0684-44f7-b27a-fe1330794138.png)
 
For such versions, the following message should be displayed:
![image](https://user-images.githubusercontent.com/37244380/194514950-37b14d41-db88-458c-9b4d-6231dc31118b.png)

Fix:
Add version 4.1 to unstable versions in https://github.com/scylladb/scylla-monitoring/blob/master/docs/source/conf.py.

`UNSTABLE_VERSIONS = ['master', 'branch-4.1']`

**Comment by annastuchlik** [comment]
@amnonh When are you releasing 4.1?
If it's very soon, like tomorrow, we can skip this issue and set `LATEST_VERSION = 'branch-4.1' `on the release day.
If the release is later, we should specify 4.1 as an unstable version, as described above.

**Comment by amnonh** [comment]
it's not going to be release soon, should the change be both in master and in 4.1 branch?

**Comment by annastuchlik** [comment]
It's enough to make the update on master.
