### ISSUE TITLE
Scylla Monitoring's CQL Non Token Aware Queries panel shows incorrect values when using batches

### ISSUE THREAD

**Issue by ljgonzalez37** [scylladb/scylla-monitoring#1809]
*Installation details*
Panel Name:  Optimization/Non-Token Aware Queries
Dashboard Name: General/Scylla CQL 
Scylla-Monitoring Version: 4.0.2
Scylla-Version: 2021.1.12

When using batches, the CQL Non Token Aware Queries panel in Scylla Monitoring shows incorrect values.  We would appreciate clarification if this is a bug; if not, we would appreciate a rationale for this behavior.  Attached screenshot for your reference.

![Optimization-Non-Token-Aware](https://user-images.githubusercontent.com/73360941/198090518-f20a4fba-5bff-4cf0-87c6-b6c7cc3119ed.png)

cc @amnonh

**Comment by ljgonzalez37** [comment]
Hello @amnonh, please let us know whether you have any update about this issue.

**Comment by amnonh** [comment]
@lujogre if you look at the description, non-token aware are not accurate when batches are used
![Screenshot from 2022-11-03 11-38-15](https://user-images.githubusercontent.com/2118079/199688592-439289d6-d72a-4c31-bc71-b3a35c9264d4.png)

**Comment by ljgonzalez37** [comment]
Hello @amnonh , thanks for your response.  That note was known to us; however, we opened the ticket to understand why the metric shows incorrect values when batches are used.

**Comment by vladzcloudius** [comment]
@lujogre I guess the answer lies in the underlying promQL query:

```
scalar(sum(rate(scylla_storage_proxy_coordinator_cas_total_operations{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]|$^"}[1m])) <=bool 0)*scalar(sum(rate(scylla_storage_proxy_replica_received_counter_updates{cluster=~"$cluster|$^"}[1m]))<=bool 0) *clamp_min(sum(rate(scylla_cql_reads{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval])) by ([[by]]) - sum(rate(scylla_storage_proxy_coordinator_reads_local_node{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval])) by ([[by]]) + sum(rate(scylla_cql_inserts{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval]) + rate(scylla_cql_updates{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval]) + rate(scylla_cql_deletes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval])) by ([[by]]) - sum(rate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval])) by ([[by]]),0)
```

The part that relates to writes is this one:
```
sum(rate(scylla_cql_inserts{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval]) + rate(scylla_cql_updates{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval]) + rate(scylla_cql_deletes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval])) by ([[by]]) - sum(rate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[$__rate_interval])) by ([[by]]),0)
```

This query simply doesn't cover BATCH statements:
* BATCH statements are accounted by `scylla_cql_batches`
* The amount of statements in BATCHes is accounted by `scylla_cql_statements_in_batches`.

And those are not part of the panel in question (unless I miss something).

So, I believe that's what stands behind that comment - because statements in BATCH are going to impact `scylla_storage_proxy_coordinator_total_write_attempts_local_node` but not any of the CQL-level metrics currently present in the expression.

Whether this can be improved - that's a different story. But it is what it is right now.

**Comment by ljgonzalez37** [comment]
Great thanks @vladzcloudius for the analysis and explanation.
