### ISSUE TITLE
Write docker instances logs to host journal

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1810]
**Describe the feature and the current behavior/state.**

Docker instances logs are lost after a host restart.

**Who will benefit from this feature?**
When debugging production issues, it's helpful to have the docker instances (e.g., Grafana, Prometheus) logs after restarts.
One way to do so is to write the logs automatically to the host journal using the `docker run --log-driver=journald ...` option [1].

[1] https://docs.docker.com/config/containers/logging/journald/

**Any Other info.**

Some systems do not use journal; this might break the start-all script on such systems.

**Comment by amnonh** [comment]
As you pointed out, it is possible to set the docker driver from the command line, start-all.sh already supports general and specific docker command line.
For example to set the log drivers to all containers you can do:
```/start-all.sh -D "--log-driver=journald"```

I'm not sure adding additional `start-all.sh` command line flag is the option, it should probably be a documentation issue

**Comment by tzach** [comment]
Fair enougth. No need for yet one more option.
