### ISSUE TITLE
Different value of metric of calculate by recording rules of prometheus and on-fly calculate

### ISSUE THREAD

**Issue by ViperRu** [scylladb/scylla-monitoring#1815]
Scylla-Monitoring Version: 4.0.2
Scylla-Version: 4.6
For example I plot two grafics:
1. wlatency95 {by="cluster", scheduling_group_name="statement"} - green
2. histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{scheduling_group_name="statement"}[60s])) by (cluster, scheduling_group_name, le)) - yellow

![изображение](https://user-images.githubusercontent.com/4677246/200413604-45ad45e6-e696-4340-95bd-d4fb424e5893.png)
wlatency95 value is changing each ~2 minutes only
What is the reason for this result?

**Comment by amnonh** [comment]
The recording rules are evaluate once every minute (`evaluation_interval`) and it then looks at the prevoius minute.
The next Scylla releases will remove most of the recording rules calculation, we can then increase the evaluation interval if it will be useful.

**Comment by amnonh** [comment]
Fixed by #1859

**Comment by ViperRu** [comment]
The problem is deeper than it seemed. The rules in the group are executed sequentially step-by-step. There is only one group, but because there is a lot of data for on large clusters all the rules in the group scylla.rules do not have time to be executed in 20 seconds.

**Comment by amnonh** [comment]
I believe the problem is temporarly and will be resolve by moving to 2023.1 and 5.4
