### ISSUE TITLE
Use the right units for each chart

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#182]
For example:
* Load (`avg(scylla_reactor_utilization{} ) ` unit should be **percent**
* Requests Served (`sum(irate(scylla_transport_requests_served{}[30s])) + sum(irate(scylla_thrift_served{}[30s]))`) unit should be **bytes/sec**
etc
Using the right unit allow Grafana to scale the charts nicely moving from kBps to mBps dynamically.

**Comment by tgrabiec** [comment]
2017-06-18 17:17 GMT+02:00 Tzach Livyatan <notifications@github.com>:

> For example:
>
>    - Load (avg(scylla_reactor_utilization{} ) unit should be *percent*
>    - Requests Served (sum(irate(scylla_transport_requests_served{}[30s]))
>    + sum(irate(scylla_thrift_served{}[30s]))) unit should be *bytes/sec*
>    etc
>
>
requests_served counts the number of requests, so bytes/sec doesn't seem
appropriate.

**Comment by tzach** [comment]
Good catch, the right unit for requests_served is `ops/sec(ops)`
