### ISSUE TITLE
Proemtheus should be stoped Gracefully

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-monitoring#1832]
*Installation details*
Panel Name: -
Dashboard Name: -
Scylla-Monitoring Version: 4.0.2
Scylla-Version: -

### Problem (which happens time to time)
When your current Scylla Monitoring version is upgraded to 4.0.2, it's pretty possible that you will hit a data corruption scenario (`aprom` container won't start because of that).

These were extracted running `docker logs aprom`:
```
ts=2022-12-05T18:11:55.525Z caller=main.go:1112 level=error err="opening storage failed: found unsequential head chunk files data/chunks_head/023904 (index: 23904) and data/chunks_head/023961 (index: 23961)"
```
```
ts=2022-12-05T19:05:41.069Z caller=db.go:752 level=warn component=tsdb msg="Encountered WAL read error, attempting repair" err="read records: corruption in segment data/wal/00114017 at 127598658: unexpected full record"
ts=2022-12-05T19:05:41.206Z caller=main.go:1112 level=error err="opening storage failed: repair corrupted WAL: delete segment:114018: remove data/wal/00114018: operation not permitted"
```

**Comment by amnonh** [comment]
@ebenzecri What version did you upgraded from?
did you try to delete the WAL?

**Comment by tarzanek** [comment]
I saw this also when going from 3.10 to 4.0.2

I had to delete data/chunks_head/
and wal, too

**Comment by ebenzecri** [comment]
Most of the upgrades happened from 3.10.1, but we have several versions running. If you have 4.0.2 installed and you reinstalled it, it will lead you to a data loss scenario always.

**Comment by ebenzecri** [comment]
Removing `wal` and `data/chunks_head` will solve the problem, but maybe the real issue is how the containers are removed when you want to reinstall based on `kill-all.sh` content. As far as I know, the containers are killed (instead of being stopped and removed). Maybe that's the problem.

**Comment by amnonh** [comment]
I'm not really sure what's the right approach.
Current implementation sends ```kill 1``` to Prometheus, wait for up to two minutes to see if it shutsdown and if it does not
kill the container anyhow.
I have a vague memory that 4 years ago, that was the way to gracefully shutdown Prometheus.

https://prometheus.io/docs/prometheus/latest/management_api/
