### ISSUE TITLE
load_dashboard.sh is not working properly

### ISSUE THREAD

**Issue by malah-akh** [scylladb/scylla-monitoring#1837]
Scylla-Version: 2022.1.3

Customer is not able to load the dashboards through load_graphana.sh

Data store is installed correctly
When loading the Graphs manually works

It is just not loading the JSON into graphana

**Comment by mykaul** [comment]
No logs available whatsoever?

**Comment by malah-akh** [comment]
Working on it.

**Comment by malah-akh** [comment]
As this is not a typical case for me, the customer is using his own installation of graphana and prometheus. 

What are the logs needed? 
I'll need the customer to generate, i'm not sure if he can share things that has other things on top that might be sensitive

**Comment by amnonh** [comment]
@ricardoborenstein 
Though load_dashboard.sh may still be working, we have stop supporting it and it's not tested.
We are loading dashboards from files.
I believe you can also import a dashboard from with in Grafana

**Comment by malah-akh** [comment]
Yeah, at this moment they're loading it manually. 

But as they are using K8S deployment, they will require the script to work, in order to automate things. 
Is it something that we can fix easily?

**Comment by youngpabl0** [comment]
guyz, hello
this WHOLE repository with name scylla-monitoring DOESNT have any exportation-ready dashboard json
i think it's a **main** issue of whole rep, can u add export-ready dashboards please?
thank u!

**Comment by amnonh** [comment]
@youngpabl0 master branch doesn't have the dashboards, it's only part of the brances, 
for example: https://github.com/scylladb/scylla-monitoring/tree/branch-4.1/grafana/build
you can see the dashboard per version.

If that's the issue, please close it as not a bug

**Comment by youngpabl0** [comment]
i'm sorry, i think it will be very nice to have a link in readme on this builds)
thank u, it's not my issue, i'v just dont find any other about dashboards

**Comment by amnonh** [comment]
@youngpabl0 have you looked at the documentation? the link to it is on the main page

**Comment by youngpabl0** [comment]
```
/load-grafana is not currently being maintained, please follow the instruction in the documentation.

Some users who already have grafana installed can just upload the Scylla dashboards into your existing grafana environment. This is possible using the load-grafana.sh script.
```
thats all about grafana dashboards in readme.md, sorry, i dont find anything else in documentation

**Comment by amnonh** [comment]
@youngpabl0 two different things, first, load-dashboard.sh is not being maintained. Second, the generated dashboard are only part of the release, and that describe in the documentation.
