### ISSUE TITLE
'Active sstable reads' is misleading

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla-monitoring#1839]
I suggest renaming the label and also the description.

People are misinterpreting it as if it shows the number of sstables being read from at a given point in time.

but that's not true. It means database reads gone to disk.

It's not even active, because it may account inactive reads. @denesb tried to rename it to ongoing reads, but he faced objections due to backward compatibility I guess.

Perhaps the label should be: Ongoing database reads gone to disk (or perhaps something more succint), which is pretty clear and descriptive

**Comment by amnonh** [comment]
@raphaelsc can you add a longer description, one that would fit the information?

**Comment by denesb** [comment]
> Perhaps the label should be: Ongoing database reads gone to disk (or perhaps something more succint), which is pretty clear and descriptive

That is not accurate either. After 5.0, this metric includes all reads, cache and memtable too.

**Comment by raphaelsc** [comment]
> > Perhaps the label should be: Ongoing database reads gone to disk (or perhaps something more succint), which is pretty clear and descriptive
> 
> That is not accurate either. After 5.0, this metric includes all reads, cache and memtable too.

Weren't we going to fix it? I thought we considered this a bug. If we're not planning to fix it, then we indeed need to remove the 'gone to disk' part :-)

**Comment by denesb** [comment]
I'm working on a fix right now. Stay tuned.

**Comment by denesb** [comment]
https://github.com/scylladb/scylladb/pull/12437

**Comment by mykaul** [comment]
> [scylladb/scylladb#12437](https://github.com/scylladb/scylladb/pull/12437)

If the PR is on scylladb and not scylla-monitoring, shouldn't this issue move as well to scylla? (I can move it, let me know).

**Comment by denesb** [comment]
We already have a scylla issue: https://github.com/scylladb/scylladb/issues/10065.
This problem will require work in both scylla.git and scylla-monitoring.git.
I don't know what is the procedure in the monitoring repo, do we need an issue here for the monitoring part?

**Comment by amnonh** [comment]
> We already have a scylla issue: [scylladb/scylladb#10065](https://github.com/scylladb/scylladb/issues/10065). This problem will require work in both scylla.git and scylla-monitoring.git. I don't know what is the procedure in the monitoring repo, do we need an issue here for the monitoring part?

We do, hopefully with enough information that the dashboards can be updated by someone who didn't write the sstable code

**Comment by amnonh** [comment]
@denesb I assigned the issue to you. You don't need to do anything in the monitoring repository, just add the information of what needs to be change:
metrics, panel headers and panel help.
Feel free to push some/all of it on @raphaelsc :) I'll take it from there.

Also, please comment what version the chagnes are relevent to, and what needs to be done on prior version

**Comment by denesb** [comment]
Ok, I will add a comment with detailed instructions, once https://github.com/scylladb/scylladb/pull/12437 goes in. Until then things can still change.

**Comment by denesb** [comment]
We have two metrics in the "Detailed" dashboard:
* Active sstable reads - displaying the `scylla_database_active_reads` metric
* Queued sstable reads - displaying the `scylla_database_queued_reads` metric

Since 5.0 there is a mismatch between the underlying metric and the panel displaying it. The metrics refer to *all* reads, while the panel talks about sstable reads. We need to make a decision here:
1) Change panels to match metrics
2) Change metrics to match panels
3) Fix existing panels and add new ones so both all reads and sstable reads have their corresponding panels

Note that we have nothing to plug to the queued sstables panel, there is no sstable queue anymore. So for that only option (1) is viable.

I think we should ask the field's input on this too, @vladzcloudius.

https://github.com/scylladb/scylladb/pull/12437 did the following:
* fix `scylla_database_active_reads` to exclude inactive reads and waiters
* fix `scylla_database_active_reads_memory_consumption`  metric, use a more accurate
* add `scylla_database_disk_reads` and `scylla_database_sstables_read` counting the current number of reads gone to disk and the current amount of sstables read respectively.

So we now have a metrics to do (2), by using `scylla_database_disk_reads` instead of `scylla_database_active_reads`. We can also create a panel for sstables read if field wants it.

**Comment by vladzcloudius** [comment]
> We have two metrics in the "Detailed" dashboard:
> 
>     * Active sstable reads - displaying the `scylla_database_active_reads` metric
> 
>     * Queued sstable reads - displaying the `scylla_database_queued_reads` metric
> 
> 
> Since 5.0 there is a mismatch between the underlying metric and the panel displaying it. The metrics refer to _all_ reads, while the panel talks about sstable reads. 
> We need to make a decision here:
> 
>     1. Change panels to match metrics
> 
>     2. Change metrics to match panels
> 
>     3. Fix existing panels and add new ones so both all reads and sstable reads have their corresponding panels
> 
> 
> Note that we have nothing to plug to the queued sstables panel, there is no sstable queue anymore. So for that only option (1) is viable.
> 
> I think we should ask the field's input on this too, @vladzcloudius.

Panels should match metrics in general so (1) above is not exactly optional.
What we have today is a clear bug in Monitoring that needs to be fixed ASAP.

On top of that loosing the visibility about sstables reads is going to be very unfortunate. However it was far from ideal even before.

Maybe it's time to improve it.

All we had before in regards to sstables access was:
* Active/queued sstables gauge graphs. 

These have their use but still don't allow getting a full picture unless tools like CQL Tracing are used.

IMO they needs to be paired with rate graphs:
* SStable data reads per second
* SStable data bytes reads per second
* SStable Index reads per second
* SStable Index bytes reads per second

Having the above, for example, can help when deciding about enabling index caching.
Or they can help identifying issues with a compaction.

@denesb ^ 

> 
> [scylladb/scylladb#12437](https://github.com/scylladb/scylladb/pull/12437) did the following:
> 
>     * fix `scylla_database_active_reads` to exclude inactive reads and waiters
> 
>     * fix `scylla_database_active_reads_memory_consumption`  metric, use a more accurate
> 
>     * add `scylla_database_disk_reads` and `scylla_database_sstables_read` counting the current number of reads gone to disk and the current amount of sstables read respectively.
> 
> 
> So we now have a metrics to do (2), by using `scylla_database_disk_reads` instead of `scylla_database_active_reads`. We can also create a panel for sstables read if field wants it.

**Comment by denesb** [comment]
> On top of that loosing the visibility about sstables reads is going to be very unfortunate. However it was far from ideal even before.

We don't have to loose the visibility into sstable reads. As I already explained, I just added metrics to get visibility into sstable reads again.
The only thing we are going to loose (we lost it a long time ago in fact) is queued sstable reads. There is no way to get this back: this queue ceased to exist. We now queue reads before they start, not when they go to disk.

> 
> Maybe it's time to improve it.
> 
> All we had before in regards to sstables access was:
> 
>     * Active/queued sstables gauge graphs.
> 
> 
> These have their use but still don't allow getting a full picture unless tools like CQL Tracing are used.
> 
> IMO they needs to be paired with rate graphs:
> 
>     * SStable data reads per second

Is this IOPS or reads gone to disk?
We can already extract the latter from `scylla_database_disk_reads`, which is in fact counting just data reads.

> 
>     * SStable data bytes reads per second
> 
>     * SStable Index reads per second
> 
>     * SStable Index bytes reads per second
> 
> 
> Having the above, for example, can help when deciding about enabling index caching. Or they can help identifying issues with a compaction.

We didn't export any semaphore metrics for compaction before. Compaction does have a semaphore so we can export these if we want to.

**Comment by vladzcloudius** [comment]
> > On top of that loosing the visibility about sstables reads is going to be very unfortunate. However it was far from ideal even before.
> 
> We don't have to loose the visibility into sstable reads. As I already explained, I just added metrics to get visibility into sstable reads again. The only thing we are going to loose (we lost it a long time ago in fact) is queued sstable reads. There is no way to get this back: this queue ceased to exist. We now queue reads before they start, not when they go to disk.

@denesb This discussion has to cover our Enterprise product too and your latest patches are not going to make there any time soon. So, we have to work with what we have there *now*. And based on your explanation earlier we effectively lost the visibility of not only queued sstables (which ceased to exist) but "Active sstables" too.

And this is what I was referring.

And our dashboards have to be adjusted correspondingly ASAP.

> 
> > Maybe it's time to improve it.
> > All we had before in regards to sstables access was:
> > ```
> > * Active/queued sstables gauge graphs.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These have their use but still don't allow getting a full picture unless tools like CQL Tracing are used.
> > IMO they needs to be paired with rate graphs:
> > ```
> > * SStable data reads per second
> > ```
> 
> Is this IOPS or reads gone to disk? 

The former.

> We can already extract the latter from `scylla_database_disk_reads`, which is in fact counting just data reads.

We can see the later via "reads with misses" too.

> 
> > ```
> > * SStable data bytes reads per second
> > 
> > * SStable Index reads per second
> > 
> > * SStable Index bytes reads per second
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Having the above, for example, can help when deciding about enabling index caching. Or they can help identifying issues with a compaction.
> 
> We didn't export any semaphore metrics for compaction before. Compaction does have a semaphore so we can export these if we want to.

Compaction semaphore metrics wouldn't hurt either ("pending reads" I'd guess).
However when we debug compactions issues we are mainly interested to identify the situation when compaction has to process many (usually small) sstables. So, IOPs + bytes read is critical to identify that.

Having a compaction semaphore queue length can help identifying the "compaction falling behind" case, right, @raphaelsc ?

I guess not. To see that we need to see the queue of pending compactions units.
And those are not going to issue IO till they start running.

**Comment by denesb** [comment]
The compaction semaphore doesn't queue reads ever. It just keeps track of resource usage.
In fact, this semaphore exists for a very mundane reason: I wanted to make it impossible to create "null permits" because people were using them everywhere as they were the most convenient to use. So permits can only be created via semaphores and permits are mandatory parameters to readers. So now we have a kind of a dummy semaphore for compaction too.

**Comment by denesb** [comment]
> Compaction semaphore metrics wouldn't hurt either ("pending reads" I'd guess).
However when we debug compactions issues we are mainly interested to identify the situation when compaction has to process many (usually small) sstables. So, IOPs + bytes read is critical to identify that.

We already have these from the seastar I/O metrics, which are exported per scheduling-group.

**Comment by vladzcloudius** [comment]
> The compaction semaphore doesn't queue reads ever. It just keeps track of resource usage. In fact, this semaphore exists for a very mundane reason: I wanted to make it impossible to create "null permits" because people were using them everywhere as they were the most convenient to use. So permits can only be created via semaphores and permits are mandatory parameters to readers. So now we have a kind of a dummy semaphore for compaction too.

Hmmm... So, what happens if there comes a compaction reader and the semaphore doesn't have enough permits to satisfy it?

**Comment by vladzcloudius** [comment]
> > Compaction semaphore metrics wouldn't hurt either ("pending reads" I'd guess).
> > However when we debug compactions issues we are mainly interested to identify the situation when compaction has to process many (usually small) sstables. So, IOPs + bytes read is critical to identify that.
> 
> We already have these from the seastar I/O metrics, which are exported per scheduling-group.

Not exactly - these don't distinguish between data and index reads.

**Comment by denesb** [comment]
> > The compaction semaphore doesn't queue reads ever. It just keeps track of resource usage. In fact, this semaphore exists for a very mundane reason: I wanted to make it impossible to create "null permits" because people were using them everywhere as they were the most convenient to use. So permits can only be created via semaphores and permits are mandatory parameters to readers. So now we have a kind of a dummy semaphore for compaction too.
> 
> Hmmm... So, what happens if there comes a compaction reader and the semaphore doesn't have enough permits to satisfy it?

The compaction semaphore has infinite (well maxint) permits. They don't run out. Also, the compacting readers don't go through admission, they create a tracking only permit and get going.

**Comment by vladzcloudius** [comment]
> > > The compaction semaphore doesn't queue reads ever. It just keeps track of resource usage. In fact, this semaphore exists for a very mundane reason: I wanted to make it impossible to create "null permits" because people were using them everywhere as they were the most convenient to use. So permits can only be created via semaphores and permits are mandatory parameters to readers. So now we have a kind of a dummy semaphore for compaction too.
> > 
> > 
> > Hmmm... So, what happens if there comes a compaction reader and the semaphore doesn't have enough permits to satisfy it?
> 
> The compaction semaphore has infinite (well maxint) permits. They don't run out. Also, the compacting readers don't go through admission, they create a tracking only permit and get going.

Very interesting. And how is the compaction readers memory consumption controlled then? Is it controlled at all?

**Comment by denesb** [comment]
> Very interesting. And how is the compaction readers memory consumption controlled then? Is it controlled at all?

No, controlling the concurrency of compaction is the job of the compaction controller. The semaphore is there only for bureaucratic reasons you could say.

**Comment by vladzcloudius** [comment]
> > Very interesting. And how is the compaction readers memory consumption controlled then? Is it controlled at all?
> 
> No, controlling the concurrency of compaction is the job of the compaction controller. The semaphore is there only for bureaucratic reasons you could say.

I see.
Then we are more interested in metrics from a compaction controller than from this semaphore.

**Comment by denesb** [comment]
> Then we are more interested in metrics from a compaction controller than from this semaphore.

Note that even though the semaphore has no say in how many reads do what, it still tracks resource usage and knows about all ongoing reads. So it is still the natural place to export read metrics about compaction.

**Comment by vladzcloudius** [comment]
> > Then we are more interested in metrics from a compaction controller than from this semaphore.
> 
> Note that even though the semaphore has no say in how many reads do what, it still tracks resource usage and knows about all ongoing reads. So it is still the natural place to export read metrics about compaction.

I won't stop you from exporting new metrics you think can be useful.

**Comment by denesb** [comment]
Well, the thing is I don't want to export metrics willy-nilly, because @amnonh just talked about us having too much metrics just recently. So I want to add only what we really need.

So to sum up what new metrics was added/requested:

In https://github.com/scylladb/scylladb/pull/12437 I added the following metrics:
1) reads gone to disk
2) sstables read

Looks like (1) is a duplicate of the missed in cache metric?
Is (2) useful?

As I understood you want IOPS and bytes read for data and index components, for all semaphores exported.

**Comment by amnonh** [comment]
@denesb @raphaelsc @vladzcloudius I'm looking for a bottom line for the current versions.
If I need to change, what exactly and on what versions.

**Comment by amnonh** [comment]
@denesb @raphaelsc @vladzcloudius I'm going to release 4.2.1 with a few bug fixes, if there's a buttom line that something in the monitoring can be changed, let's agree on it and I'll change that, if not, it will wait for 4.3

**Comment by denesb** [comment]
So, with the code we have *right now* we have the following options.

We have two graphs:
1) "Queued sstable reads" - this graph is completely misleading at this point. We either rename it to "Queued reads" or replace it with something else.
2) "Active sstable reads" - this graphs is also very misleading. We can either rename it to "Active reads" or replace the underlying metric with `scylla_database_disk_reads` and keep the current name. On the other hand according to @vladzcloudius this number can already be obtained from the cache misses metric.

Maybe this entire section needs to go and be replaced by something else (or nothing).
We might need a new section dedicated to the reader concurrency semaphore instead, which makes it clear what the graphs refer to. I feel like I'm out of my depth here, this is a product decision.

**Comment by amnonh** [comment]
@denesb @raphaelsc @vladzcloudius is there anything else we need to do with this issue?
I'm closing issues towards a release of 4.5 and would like to close this one if possible

**Comment by denesb** [comment]
> @denesb @raphaelsc @vladzcloudius is there anything else we need to do with this issue? I'm closing issues towards a release of 4.5 and would like to close this one if possible

I think this issue can be closed. @vladzcloudius sugested new metrics, which is outside the scope of this issue.

**Comment by raphaelsc** [comment]
Closed
