### ISSUE TITLE
Upgrade to newer Prometheus (2.3.9 or newer) 

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#1846]
Mainly hoping it'll reduce memory usage of Prometheus (especially in large clusters)

**Comment by mykaul** [comment]
@gmizrahi - this is waiting for some confirmation from the DevOps team that it indeed improves the memory usage for our use cases.

**Comment by gmizrahi** [comment]
@d-helios - as per my question in Slack...
