### ISSUE TITLE
consider adding an alert or advisor alert for when large* are found

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#1857]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 2022
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.**

right now you have to fetch from system.large* just to see if there are large partitions/cells/rows/...
if there would be an alert about new additions to that table, it'd be a push way (not pull) and it can likely be beneficial
(we have a customer interested into that)

**Who will benefit with this feature?**
admin of Scylla / data model team

**Any Other info.**

**Comment by amnonh** [comment]
It's there from scylla monitoring 3.7.0 :) , it's based on Loki alerts
