### ISSUE TITLE
"Load" value is very confusing when rate limiting is used

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1880]
*Installation details*
Panel Name: "Load"
Dashboard Name: "Detailed"
Scylla-Monitoring Version: 4.1.0

*Description*
When we use a new compaction rate limiting feature "Load" graph shows 100% when compaction is rate limited:

![image](https://user-images.githubusercontent.com/6103981/216840153-89850455-0f3a-4bb6-a6d1-27f9a6892237.png)
![image](https://user-images.githubusercontent.com/6103981/216840175-e991a3b9-3327-4a3f-ad41-0b4cc687c823.png)

![image](https://user-images.githubusercontent.com/6103981/216840117-9a3530db-2ef4-4b14-baeb-de7c4acf5f39.png)

As we can see, there isn't any scheduling class busy doing anything.

I guess (@xemul, please, confirm) reactor is spinning waiting for an I/O queue budget and hence the high reactor utilization.

I think it makes sense not to include such a reactor spinning time in the value shown on the "Load" graph.

Alternatively we should show this "spin time" on some graph.

However I personally  think that it would be better to exclude this time from the "Load" value.

**Comment by xemul** [comment]
> I guess (@xemul, please, confirm) reactor is spinning waiting for an I/O queue budget and hence the high reactor utilization.

In fact, it arms a timer and ~~doesn't~~ shouldn't spin at all.

**Comment by amnonh** [comment]
@xemul Is there a bug and if there is, where?

**Comment by amnonh** [comment]
@xemul ping

**Comment by xemul** [comment]
In fact there can be a bug of that kind:
https://github.com/scylladb/seastar/pull/1722

**Comment by amnonh** [comment]
@xemul should we change something in the monitoring, or can we close this issue?

**Comment by xemul** [comment]
It's not an issue in the monitoring, so I think we can close it
