### ISSUE TITLE
Scylla CQL instance all filter should list all nodes

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1895]
Commit 9ec6f374a00fa4a9716c5251ea4251c4630b56ae changed the default all to use ```.*``` notation, this does not work with with the scylla cql that needs the actual list of nodes.

**Comment by vladzcloudius** [comment]
@amnonh I'm still reproducing the issue even after applying #1897

**Comment by vladzcloudius** [comment]
Reverting the supposedly offending "All filter" change doesn't help either.

**Comment by tomer-sandler** [comment]
We need this fix kind of urgently as we have some users already complaining about this issue. The `CQL system tables` is an important section in the `CQL` dashboard, used by many.
So if we could get a quick fix out for Monitoring `4.2.<next>` that would be great.
cc @DoronArazii @amnonh

**Comment by amnonh** [comment]
@vladzcloudius did you apply the change and re-generate the dashboard?

**Comment by amnonh** [comment]
@tomer-sandler the workaround is to manually select the nodes from the dropdown list

**Comment by vladzcloudius** [comment]
> @vladzcloudius did you apply the change and re-generate the dashboard?

I `kill-all.sh` and the `start-all.sh` - which AFAIK regenerates dashboards.
At least I did saw other changes I was applying.

So, yes, @amnonh, I did.

**Comment by amnonh** [comment]
@vladzcloudius it's not enough, dashboards are not generated without calling ```./generate-dashboards.sh```.

For example, to use it with 2021.1 call: ```./generate-dashboards.sh -F -v 2021.1```, note the ```-F```

**Comment by amnonh** [comment]
I assume that this is closed, if you run generate-dashboards.sh and it still doesn't work, reopen
