### ISSUE TITLE
Allow grouping per rack in dashboards

### ISSUE THREAD

**Issue by martin-sucha** [scylladb/scylla-monitoring#1896]
**System information**
- Scylla version (you are using): 2022.1.5
- Are you willing to contribute it (Yes/No): Depends on what are all the things that need to be done.

**Describe the feature and the current behavior/state.**

Currently you can aggregate in dashboards by:

* `Cluster`
* `DC`
* `Instance`
* `Instance,shard`

I would like to be able to additionally aggregate by `DC,rack` as well.

**Who will benefit with this feature?**

Anyone who has multiple racks in a cluster.

**Any Other info.**

**Comment by amnonh** [comment]
It sounds reasonable, it will require configue rack and add some load on the Prometheus server, but all in all make sense

**Comment by tzach** [comment]
Aggregating metrics on another level (Rack) adds more load on the monitoring stack, even if it's not actively used.
We need to see if this is relevant to more users.

**Comment by amnonh** [comment]
@tzach can we close this issue?

**Comment by tzach** [comment]
> Aggregating metrics on another level (Rack) adds more load on the monitoring stack, even if it's not actively used.

Agree. The cost of adding a grouping level is not worth the value in this case.

@amnonh, how can someone (like @martin-sucha ) add such a dashboard for his deployment?

**Comment by martin-sucha** [comment]
If there was info metric for the `rack`, you could do join on `instance` to get the `rack` in a query and aggregate based on that. No need to add a rack label to every metric.

But I personally no longer need this feature.
