### ISSUE TITLE
"Connecting Scylla-Monitoring to Scylla" section requires a heavy rework

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1906]
**System information**
- link to the documentation page and section: https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#connecting-scylla-monitoring-to-scylla
- Are you willing to contribute it (Yes/No): No

**Describe the situation now**
Today the text looks as follows:
```
Scylla-Manager version 3.5 and higher can read tables from a Scylla node using CQL.
```

**What needs to be there**
```
Scylla-Monitoring version 3.5 and higher can read tables from a Scylla node using CQL. 
```

**Comment by vladzcloudius** [comment]
@amnonh Please, review and confirm the above.

**Comment by vladzcloudius** [comment]
On a second glimpse - this whole section requires a heavy rework and is no longer relevant.

In particular the file referenced there doesn't have the section the text refers.

**Comment by tomer-sandler** [comment]
I think the file that needs to be configured, changed
from this (for Monitoring 3.x): `grafana/provisioning/datasources/datasource.yaml`
to this (for Monitoring 4.x): `./grafana/datasource.scylla.yml`
