### ISSUE TITLE
[Regression]: CQL plugin stopped working in 4.2 while works nicely with 4.0

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1907]
*Installation details*
Panel Name: Connections
Dashboard Name: Scylla CQL
Scylla-Monitoring Version: 4.2.1
Scylla-Version: 2022.2.0

*Description*
CQL plugin fails to work in 4.2.1 while works fine with 4.0.2 on the same cluster:

4.0.2:
![image](https://user-images.githubusercontent.com/6103981/220453888-eaed0908-a102-4589-b608-047c38cd13df.png)

4.2.1:
![image](https://user-images.githubusercontent.com/6103981/220455170-994779c6-6538-40b4-a663-f447f30d27e9.png)

![image](https://user-images.githubusercontent.com/6103981/220455395-504d3d01-2dae-409a-a1e4-168ba0f372db.png)

**Comment by vladzcloudius** [comment]
@tomer-sandler @noellymedina FYI

**Comment by amnonh** [comment]
Looks like a duplicate #1894

**Comment by vladzcloudius** [comment]
Maybe or maybe not. It looks like nodes IPs are resolved just fine.

**Comment by vladzcloudius** [comment]
> Maybe or maybe not. It looks like nodes IPs are resolved just fine.

Actually - not sure:

![image](https://user-images.githubusercontent.com/6103981/220461740-d272c15a-880e-4da1-9f57-17d1b48c97a3.png)

So, maybe indeed a regression.
Let me check the fix from https://github.com/scylladb/scylla-monitoring/issues/1894

**Comment by amnonh** [comment]
Closing as duplicate
