### ISSUE TITLE
docs: Typo in page Scylla Monitoring Datadog Integration

### ISSUE THREAD

**Issue by andre-lfa** [scylladb/scylla-monitoring#1910]
I would like to report an issue in page https://monitoring.docs.scylladb.com/master/procedures/datadog/index

### Problem

Typo in https://monitoring.docs.scylladb.com/master/procedures/datadog/index.html#other-scylla-users 

![image](https://user-images.githubusercontent.com/33098462/221301442-23cf7b76-582c-4462-a686-3444ef82d6e2.png)

(I don't know if there are other typos)

###  Suggest a fix

Prometheus =)

**Comment by tzach** [comment]
PR sent.

@andre-lfa note the Edit button to quickly fix such issues
![image](https://user-images.githubusercontent.com/170200/222116037-85e209ba-02a2-4c2f-97b5-468df0843fb1.png)
