### ISSUE TITLE
Extreemely useless pop-up sumamries

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-monitoring#1916]
![image](https://user-images.githubusercontent.com/4498177/221823338-442f65ec-adf3-454d-b5e4-f2b408323ac9.png)

Check the screenshot above. It shows the pop-up summary over a metrics for a node with 48 shards. There are three problems with it

1. The list is too long and doesn't fit the screen. Zoom-in/out in browser helps, but the font may become unreadable
2. The list is sorted in the uninteresting direction -- ascending -- while most likely I need the largest values from it first (it would workaround previous item)
3. The list doesn't show metric labels, so I cannot guess which, e.g. shard is the interesting one

![image](https://user-images.githubusercontent.com/4498177/221825408-02762613-e856-4df0-8e47-85e0b24010b5.png)

**Comment by amnonh** [comment]
@xemul please add the full detailes as describe in the opening bug section

**Comment by xemul** [comment]
*Installation details*
Panel Name: any
Dashboard Name: any
Scylla-Monitoring Version: v8.5.10 (9bdf1b6847)
Scylla-Version: 2022.2.1

**Comment by amnonh** [comment]
This is not true to all panels an dashboards, so please be specific

**Comment by xemul** [comment]
Panel Name: e.g. IO queue information or Information by Task Group
Dashboard Name: e.g. Advanced

**Comment by amnonh** [comment]
you didn't add the monitoring version, it seems like an old release

**Comment by amnonh** [comment]
> _Installation details_ Panel Name: any Dashboard Name: any Scylla-Monitoring Version: v8.5.10 (9bdf1b6847) Scylla-Version: 2022.2.1

8.5.10 is Grafana version

**Comment by xemul** [comment]
Well, I'm now looking at monitoring of 4.2.1 and don't see any difference in the way this pop-up is displayed
