### ISSUE TITLE
docs: Issue in page Scylla Monitoring Datadog Integration - Cloud instruction are not clear

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1943]
I would like to report an issue in page https://monitoring.docs.scylladb.com/stable/procedures/datadog/#scylla-cloud-users

### Problem
The instrction for Cloud users are not clear:

> Scylla Cloud users, download the configuration file conf.yaml

Download to which server?

###  Suggest a fix

Break ScyllaDB Cloud and ScyllaDB Open source / Enterprise to two different **pages**.
Each user typicaly only use one.

Adding a digram to show the cloud deployment, for example

```mermaid
sequenceDiagram
    DataDog->>Server: Read Subset of Metrics
    Server->>Prometheus: Read All Metrics
    Prometheus->>ScyllaNodes: Read All Metrics
```

**Comment by amnonh** [comment]
@tzach Cloud instruction should be in the cloud and should come with quick download link for pre-defined templated files.
This is a work around until it will be that way

**Comment by tzach** [comment]
Its fine to document a workaround, but I find the doc unclear.

**Comment by amnonh** [comment]
The documentation itself is the workaround, the cloud instructions should be in the cloud API, not here!

**Comment by tzach** [comment]
Again, I find the docs unclear.
Feel free to close the issue if you do not plan to fix.
