### ISSUE TITLE
Update Scylla Manager dashboard to include 3.1 feature: restore

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1946]
Manager 3.1 include new metrics for restore (from backup). The process have 3 steps:
- Download progress
- Restore (streaming) progress
- Repair progress

https://github.com/scylladb/scylla-manager/pull/3331

**Comment by tzach** [comment]
@amnonh @karol-kokoszka FYI

**Comment by amnonh** [comment]
@karol-kokoszka @Michal-Leszczynski
I've looked on the new PR https://github.com/scylladb/scylla-manager/pull/3349

Is there a bottom line about the metrics?
If we want to know if we are in each of the stages and our progress in that stage (either percentage 0-100 or a value 0-1)

**Comment by karol-kokoszka** [comment]
@amnonh there is no bottom line.
`remaining_bytes` shows how many bytes are still pending to be restored and this metric is the most important one. This metric is labelled with `location`, `dc`, `node`, `keyspace`, `table`.

Other two metrics - `state` and `batch_size` are not so important for simple observability.
`batch_size` shows how batches of SSTables are propagated between nodes.
`state` shows what the node is doing right now (idle, downloading, load&stream).

**Comment by amnonh** [comment]
Is there a way we can convert it to a progress bar?
So we can make it similar to other manager operations

**Comment by karol-kokoszka** [comment]
> Is there a way we can convert it to a progress bar?
So we can make it similar to other manager operations

Sure. I can change it to show progress, or I can introduce a second metric
that will show progress in percentages.
Let me introduce a second metric with progress, I would prefer to keep the
bytes related metric.

**Comment by amnonh** [comment]
@karol-kokoszka is batch_size and remaining_bytes are of the same value?
The question, is 

$$ 1 - {\text{remaining bytes}\over{\text{batch size}}} $$ 

a value between 0 and 1?

**Comment by amnonh** [comment]
@karol-kokoszka @Michal-Leszczynski do we have tests for manager 3.1? I would like to make some changes and test the monitoring, but hopefully without spending too much time setting up and running the tests themselves

**Comment by karol-kokoszka** [comment]
@amnonh This is the most valuable test in terms of monitoring.
https://jenkins.scylladb.com/job/manager-3.1/job/sct-feature-test-restore-multiple-snapshot-restoring/

It restores 2TB of data.

You can pickup this logs as well https://cloudius-jenkins-test.s3.amazonaws.com/9e8caf37-38eb-4593-a503-a3259b4df2ab/20230416_134357/monitor-set-9e8caf37.tar.gz and copy timeseries from `prometheus-data-....tar.gz` to your prometheus-data folder.
It will show metrics from the test execution then.

**Comment by amnonh** [comment]
I've seen nagtive values in remaining_bytes which is probably a bug, also will the new progress metric would make it into 3.1?

**Comment by karol-kokoszka** [comment]
Negative values are not the bug.
All manager metrics can have -1 value, what basically means "undefined".
-1 appears when metrics are reset.
