### ISSUE TITLE
Empty alert manager rules when using consul

### ISSUE THREAD

**Issue by roy3861** [scylladb/scylla-monitoring#1951]
*Installation details*
Panel Name: NA
Dashboard Name: NA
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard): 4.2
Scylla-Version: 5.1

As we are exploring with opensource scylla, we have setup a single 5 node cluster and then scylla-monitoring as per : https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html [ we used consul based setup]
We see an issue with Prometheus does not show any alert rules and Grafana also only has loki rules.
![image](https://user-images.githubusercontent.com/59607985/233660948-0284fe68-5b07-4a0e-a4a5-a374293979c3.png)

![image](https://user-images.githubusercontent.com/59607985/233661035-5674fc36-0979-4932-baf6-e5dbd9790051.png)

Upon deep dive, i saw the prometheus.yaml used by aprom container mounts and use this prometheus.yaml: /<base_location>/scylla-monitoring/prometheus/build/prometheus.yml
{this most probably is being created from template: /<base_location>/scylla-monitoring/prometheus/prometheus.consul.yml.template}
and it has reference to rule files as :
rule_files:
  - /etc/prometheus/prometheus.rules.yml
However if we try to see in the container that file is not mounted at all:
# docker exec -it aprom cat /etc/prometheus/prometheus.rules.yml
cat: can't open '/etc/prometheus/prometheus.rules.yml': No such file or directory
Is this a bug? Can you please confirm.

**Comment by amnonh** [comment]
That seems to be an issue with the consul installation, that wasn't updated to accomodate for the latest changes
