### ISSUE TITLE
Grafana and prometheus reports the cluster name "my-cluster" always(consul based setup)

### ISSUE THREAD

**Issue by roy3861** [scylladb/scylla-monitoring#1963]
*Installation details*
Panel Name: NA
Dashboard Name: All
Scylla-Monitoring Version: 4.2
Scylla-Version: 5.1.5

The Grafana Dashboards reports the Cluster name as always "my-cluster" in variables, although we have our our cluster name setup in scylla.yaml.
We are collecting cluster monitoring data from Scylla-Manager via Consul based setup.

![image](https://user-images.githubusercontent.com/59607985/234280766-8b2f94ab-3098-4237-9be8-6a413f7ec891.png)

It picks up the value from Prometheus via query: label_values(scylla_reactor_utilization, cluster)

and in prometheus also we found the value is incorrect: 
![image](https://user-images.githubusercontent.com/59607985/234334472-ca37f7b1-2fbb-47d8-bcc9-13e97a1b9351.png)

Here's snipped from scylla.yaml
`cat /etc/scylla/scylla.yaml | grep cluster_name
cluster_name: 'Scylla Prod 01`

**Comment by amnonh** [comment]
This look like a mis-configuration, you need to configure the cluster/dc name in the scylla_server.yaml under the monitoring configuration, See: 
https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#configure-scylla-nodes-from-files

I'm closing the issue as not a bug, re-open if you think it is a bug

**Comment by roy3861** [comment]
But we are using Consul based setup and hence no files to setup cluster name. https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#configure-scylla-nodes-using-scylla-manager-consul-api
