### ISSUE TITLE
Re: Grafana and prometheus reports the cluster name "my-cluster" always(consul based setup)

### ISSUE THREAD

**Issue by roy3861** [scylladb/scylla-monitoring#1967]
Installation details
Panel Name: NA
Dashboard Name: All
Scylla-Monitoring Version: 4.2
Scylla-Version: 5.1.5

The Grafana Dashboards reports the Cluster name as always "my-cluster" in variables, although we have our our cluster name setup in scylla.yaml.
We are collecting cluster monitoring data from Scylla-Manager via Consul based setup.

![image](https://user-images.githubusercontent.com/59607985/235656668-caff1fd2-d01a-44b0-9bca-bf6d971bd13e.png)

It picks up the value from Prometheus via query: label_values(scylla_reactor_utilization, cluster)

and in prometheus also we found the value is incorrect:

![image](https://user-images.githubusercontent.com/59607985/235656775-f3cd8a7f-95f2-4c18-9543-4ebae4cd21e1.png)

 We are using Consul based setup and hence no files to setup cluster name. https://monitoring.docs.scylladb.com/stable/install/monitoring_stack.html#configure-scylla-nodes-using-scylla-manager-consul-api

This is re creation of https://github.com/scylladb/scylla-monitoring/issues/1963 as i cant reopen it. Feel free to re-open it (and close this) if that's intended.

**Comment by amnonh** [comment]
It looks like a duplication of:
https://github.com/scylladb/scylla-monitoring/issues/1890

Can you use the latest Scylla Monitoring version and see if the problem persists?

**Comment by roy3861** [comment]
Yep latest version has the required fix. Thanks.

`    - source_labels: [__meta_consul_service_metadata_cluster_name]
      target_label: cluster
`
