### ISSUE TITLE
Reduce the number of collected histograms: do not collect "internal" scheduling groups latency histograms

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1971]
**System information**
- Scylla version (you are using): irrelevant
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Today we show all latency histograms Scylla exposes.
However histograms are per Scheduling Group and there are 9 internal scheduling groups (defined in `cql_transport::non_cql_scheduling_classes_names`) which don't serve CQL, and therefore CQL latency metrics are completely irrelevant for these SGs.

Since histograms are very heavy on Prometheus there is a good motivation to reduce their amount.

Ideally Scylla should not send these (will create a separate GH issue).  However in the meantime and in order to support older scylla version let's not record these on the Prometheus level.

**Who will benefit with this feature?**
Everybody

**Comment by vladzcloudius** [comment]
@amnonh FYI

**Comment by mykaul** [comment]
Do we wish to backport this to 4.3.x as well?

**Comment by amnonh** [comment]
I don't think so, I'm planing to branch 4.4 this week, I can always patch specific systems if needed.
