### ISSUE TITLE
Per-service-level Latency Percentiles and aggregate throughput

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#1976]
The idea behind service levels is to separate requests into different classes, so that the server can dedicate more resources to the important classes. The way this is measured is by looking at the throughput and latency of the important service levels, but this isn't visible in monitoring now.

We can start by making the latency percentile report per service level, and later add the throughput counters.

**Comment by mykaul** [comment]
I think this was implemented in https://github.com/scylladb/scylla-monitoring/issues/1939 (so 4.4 material).

**Comment by amnonh** [comment]
@avikivity I'm wondering what needs to be added in the per scheduling group section in the detailed dashboard.
You have read/write requests per sec (throughput) and average, p95, and p99 latencies.

Maybe I'm missing what this issue is about

**Comment by avikivity** [comment]
Maybe I'm missing the latest version. Or I don't look enough in detailed.

**Comment by amnonh** [comment]
> I think this was implemented in #1939 (so 4.4 material).

#1939 actually removes some of the scheduling group, this is a performance enhancement not added functionality

**Comment by amnonh** [comment]
> Maybe I'm missing the latest version. Or I don't look enough in detailed.

I'm working on making it easier to use, from 4.4 there will also be a scheduling group filter in the overview dashboard

**Comment by amnonh** [comment]
Closing as already implemented

**Comment by avikivity** [comment]
So latency is there already (even for the cluster I was complaining about), I'm just not used to it.

It's hidden, so it's a little harder to see. The per-service-level throughput isn't there, but with a filter it will be easy to use.
