### ISSUE TITLE
Missing monitoring-4-3-4 image for cloud on GCP

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-monitoring#1981]
We want to add support for scylla-monitoring stack 4.3.4 in cloud.

There is an image available in AWS -> ami-02eb2e3220e6e2ed9 https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-02eb2e3220e6e2ed9

But the one for GCP is missing.

**Comment by karol-kokoszka** [comment]
The one mentioned here https://github.com/scylladb/siren/issues/8950#issue-1703773090 is missing

**Comment by amnonh** [comment]
it's under scylla project

**Comment by karol-kokoszka** [comment]
I got it. Everything is fine.
