### ISSUE TITLE
Instance (node) template assume host names without dots (.)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#200]
This break the dashboard when the host name includes dot, like ip-192.17.8.3 or similar.

**Comment by tzach** [comment]
Look like the problem is not in the template, but in the way Prometheus handle hostnames with dot.
Currently, metrics from such hosts are not visible in Prometheus.

**Comment by tzach** [comment]
@glommer FYI, can you please test if the metrics from such host appears on Prometheus (port 9090)?

**Comment by glommer** [comment]
I sent a pull request for this

**Comment by tzach** [comment]
fixed by #202
