### ISSUE TITLE
Streaming Reads I/O Queue delay is Identical to Streaming Reads I/O Queue bandwidth on version 1.7.2

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-monitoring#201]
On version 1.7.2, the Streaming Reads I/O Queue bandwidth query is:
`sum(irate(scylla_io_queue_streaming_read_delay{}[30s])) by (instance)
`
instead, it should be:
`sum(irate(scylla_io_queue_streaming_read_total_bytes{i}[30s])) by (instance)
`
![bug1](https://user-images.githubusercontent.com/15847218/28158267-dc965908-67c1-11e7-8361-b6cd5bf7175a.png)
![bug2](https://user-images.githubusercontent.com/15847218/28158085-3d7c0ce6-67c1-11e7-97e7-7521c5574a2a.png)
![bug3](https://user-images.githubusercontent.com/15847218/28158084-3d76b7b4-67c1-11e7-88ae-72add4cb98eb.png)

**Comment by amnonh** [comment]
@tzach 1.7 is no longer supported, can we close this?

**Comment by tzach** [comment]
@harelassayag is this issue still relevant?

**Comment by tzach** [comment]
Closing. Scylla 1.7 is not supported anymore.
