### ISSUE TITLE
sl:default is chosen by default

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-monitoring#2013]
Scylla-Monitoring Version: 4.4.0

### Issue
_Note: This issue was reported by one of our customers._

By default, a single scheduling group sl:default is chosen. This is really really bad! In our case, we've eliminated using `sl:default` for good, and so we will see latencies that are completely off. I can change the selection and save the dashboard, but these user-defined settings are temporary AFAIU.

Then, AFAIU: Scylla Monitoring should have an option to set the default scheduling group to be used.

**Comment by amnonh** [comment]
Parameters are not part of the consitent state of Grafafana, they are part of the URL query parameters.
What we can do, now that we removed the internal priority group, is to set the default to all user group.

cc @vladzcloudius

**Comment by amnonh** [comment]
Fixed by #2022
