### ISSUE TITLE
[4.5] ./start-all.sh won't start: open /etc/prometheus/prometheus.yml: permission denied

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla-monitoring#2037]
OS: Fedora 37
podman version: 4.5.0

The command:
```shell
/start-all.sh -d ~/ScyllaDB/storage/e3214/f836c367-ce26-4ce5-b848-19dfb95706a9/var/lib/scylla -s prometheus/scylla_servers.yml
```
Fails:
```shell
$ podman logs aprom
ts=2023-07-31T14:11:47.440Z caller=main.go:482 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: permission denied"
```
The same works fine with 4.4.

**Comment by michoecho** [comment]
@amnonh https://github.com/scylladb/scylla-monitoring/pull/2038 isn't a full fix. It rewrites selinux labels for prometheus.yml, but there are other files which have the same problem, for example scylla_servers.yml. They just don't cause prometheus to hang, so it's less visible.

We could patch all of them with the `z` relabeling, but maybe the better direction is to disable selinux label separation for the entire container?

**Comment by amnonh** [comment]
I'm not sure what's the best approach, I tried aoviding disable selinux, but not sure it's the best decision.

**Comment by mykaul** [comment]
relabeling is much better than disabling.
