### ISSUE TITLE
Add unit to metics if possible

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-monitoring#204]
There is no unit in a lot of metrics while it should have, e.g. the disk read per second should use the IOPS unit. 

If we are serious about the unit. We should follow:

https://en.wikipedia.org/wiki/Data_rate_units

E.g. Use MiB/s not MB/s

**Comment by tzach** [comment]
Adding unit to cluster level dashboard
Should be completed for the rest of the dashboards 
https://github.com/scylladb/scylla-grafana-monitoring/pull/183
