### ISSUE TITLE
CQL Non prepared statement metrics - percentage over 100%

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/scylla-monitoring#2040]
*Installation details*
Panel Name: Scylla CQL
Dashboard Name: CQL Non prepared statement
Scylla-Monitoring Version: 4.4.2
Scylla-Version: 2022.2.0

Problem: percentage over 100%
![image](https://github.com/scylladb/scylla-monitoring/assets/11996012/ffb8cbb6-3c0f-4b47-96a9-ff1d324849bd)

**Comment by mykaul** [comment]
Reminds me of https://github.com/scylladb/scylla-enterprise/issues/3227

**Comment by amnonh** [comment]
@AdamStawarz closing as duplicate

**Comment by amnonh** [comment]
I'm reopening becasue it's a different metric than https://github.com/scylladb/scylla-enterprise/issues/3227

**Comment by amnonh** [comment]
@AdamStawarz Is this issue still relevant, if so, can you open an enterprise issue with all the relevant details?
