### ISSUE TITLE
Repair and Backup status in centralize monitoring 

### ISSUE THREAD

**Issue by d-helios** [scylladb/scylla-monitoring#2043]
When you have multiple clusters running it's nice to have a place to observe following metrics / alerts
- NoSuccessRepair - no success repair for X days 
- NoSuccessBackup - no success backup for X days
- ManagerIsSuspended - manager suspended for X days
- LongRunningBackup - backup running too long (X days) 
- LongRunningRepair - repair running too long (X days)

**Comment by amnonh** [comment]
@karol-kokoszka can you please comment with the relevant manager metrics?

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski @dkropachev 
Guys, please take a look. I'm ooo until 30th of August.

You can find another set of prom rules here https://github.com/scylladb/scylla-monitoring/blob/7068779dd3a048df970b3eb0109b04aadbf98ebc/prometheus/prom_rules/prometheus.latency.rules.yml#L38-L61

**Comment by amnonh** [comment]
Hi @Michal-Leszczynski @dkropachev @karol-kokoszka ping, I want it to be part of 4.5.0 release

**Comment by dkropachev** [comment]
- `NoSuccessRepair` -  "(sum by (cluster) (changes(scylla_manager_scheduler_last_success{type=""repair""}[{{ .threshold_in_days }}d])) == 0) and on() (max(time() - node_boot_time_seconds) > {{ .node_uptime_in_days }}*24*3600)"
- `NoSuccessBackup` - "(sum by (cluster) (changes(scylla_manager_scheduler_last_success{type=""backup""}[{{ .threshold_in_days }}d])) == 0) and on() (max(time() - node_boot_time_seconds) > {{ .node_uptime_in_days }}*24*3600)"
- `ManagerIsSuspended` - have no metric so far https://github.com/scylladb/scylla-manager/issues/3567
- `LongRunningBackup` - "scylla_manager_scheduler_run_indicator{type="backup"} == 1"
- `LongRunningRepair` - "scylla_manager_scheduler_run_indicator{type="repair"} == 1"

**Comment by amnonh** [comment]
@dkropachev scylla_manager_scheduler_last_success seems to return a timestamp, so:
```max(scylla_manager_scheduler_last_success{type=~"repair|backup"}) by(type)``` Would return the timestamp of the last repair and backup

For long running repair, we're in a tight corner, the best would have been if the manager would have reported repair/backup duration.
It's possible to add a warning if a repair took more than some predefine value, like:
```min_over_time(scylla_manager_repair_progress[10h])>0``` 

But it's not a as good, and to my opnion less suitable for a centralized monitoring

**Comment by Michal-Leszczynski** [comment]
> ManagerIsSuspended - have no metric so far https://github.com/scylladb/scylla-manager/issues/3567

This metric (`scylla_manager_scheduler_suspended` labeled by `clusterID`) has been added to master and will be part of SM 3.2.2. It shows 1 when cluster is suspended and 0 otherwise (or there might be a missing value for a cluster that hasn't ever been suspended).

**Comment by Michal-Leszczynski** [comment]
> For long running repair, we're in a tight corner, the best would have been if the manager would have reported repair/backup duration.

We can add a metric like `scylla_manager_scheduler_last_start` that would show the timestamp of the last started run.

But isn't it possible to create this alert with suggested `scylla_manager_scheduler_run_indicator` (labeled by `clusterID`, `type`, `taskID`)? This metric is set to 1 when given task is running. So for checking long running repairs/backups, we would just need to check if the value of this metric has been set to 1 for some predefined amount of time.

**Comment by amnonh** [comment]
@Michal-Leszczynski we can also add a metric with the duration of the last repair, this will be the simplest and most accurate

**Comment by Michal-Leszczynski** [comment]
> @Michal-Leszczynski we can also add a metric with the duration of the last repair, this will be the simplest and most accurate

Do you mean the last, successfully completed repair? So that it can be used as some benchmark to compare currently running repair? Then it can be done without any problem.

**Comment by amnonh** [comment]
@Michal-Leszczynski I'm saying, the code that update the timestamp of the last repair, can update a gauge with that repair duration.
It would allow us look at repair duration history and show the last repair duration

**Comment by amnonh** [comment]
#2078 Adds ```scylla_manager_scheduler_last_duration``` for datadog integration and for centralized monitoring, which is the last missing part, closing
