### ISSUE TITLE
./generate-dashboard.sh should generate dashboards for all versions

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#2048]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): many
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.**

./generate-dashboards.sh without any options will do nothing, and not complain. That's a bug.

But we can teach it to generate dashboards for all versions, making it a feature.

**Who will benefit with this feature?**

People who run or observe many different ScyllaDB versions - support, R&D.

**Any Other info.**

The Sun is the second warmest place in the solar system, after fusion research labs on its third planet.

**Comment by amnonh** [comment]
note, that typically, users should not use generate_dashboard.sh, you are probably facing the issue because you are using the master branch (and get warning about it)  instead of a release branch.

For each release there is a list of supported versions that comes with that release (found in versions.sh) when creating a release all the supported versions are created.

**Comment by avikivity** [comment]
Ah, why not make master branch behave the same?

**Comment by amnonh** [comment]
Following how many libraries work, the templates are part of master but the generated dashboards are only part of a release.
The alternative is that dashboards keep being generated and changed and there are conflicts when moving from one version to another, this is how it used to be and removing the generated dashboards from master made it easier.

When committing the generated dashboard as part of the release, regular users don't need to generate them (No Python dependencies, for example)

So, users should just work with a release, and then they know what they get. The brave of hurt can use master but then it's up to them to take care of generating the dashboards.

**Comment by avikivity** [comment]
Ok, but why not generate dashboards for all versions when -v is not given?

**Comment by amnonh** [comment]
Two reasons, first, what versions? When you are running on a branch, we know what versions to generate. This is how the script that generates the release knows what versions are needed.

The second is that the script also generates the files for loading the dashboards, which behave differently. If you only need one specific version or multiple, for multiple versions, there are folders, and for a particular version, there's no need, and it's clearer what is the default version (for the home dashboard).

I can maintain a list of supported versions for master and have the no version take it from there. It was just not needed until now. But a user group of size 1 is still a user group.

**Comment by mykaul** [comment]
If '-v' is not given, why not fail and ask the user to specify the version?

**Comment by amnonh** [comment]
> If '-v' is not given, why not fail and ask the user to specify the version?

That's what this issue is about, @avikivity wants that if no version is specify, create a given set of versions

**Comment by avikivity** [comment]
Yes, my workflow is while (true) { download some metrics dump; examine it; sleep random()*1d }. The fewer things I have to look up, the easier it is for me.

**Comment by mykaul** [comment]
```
<uncooked idea>
metrics dump should be a container with both the metrics and the relevant monitoring stack
</uncooked idea>
```

**Comment by amnonh** [comment]
> ```
> <uncooked idea>
> metrics dump should be a container with both the metrics and the relevant monitoring stack
> </uncooked idea>
> ```

I think the problem is correct, but I'm not sure that's the best approach forward, because there are multiple containers and by default we should use the same Monitoring version as the data came from.
I think I can create a script that would take some information from the metric dump, check out the right monitoring version and run a start-all.sh command with the correct scylla/manager vesions

**Comment by amnonh** [comment]
Covered by #2177
