### ISSUE TITLE
Graph pop up should be sorted in the optimal way for analyzing issues

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2055]
See below - the better way to sort this specific graph would be from the highest values to the lowest, not as it is right now:

![Screenshot from 2023-09-09 09-54-47](https://github.com/scylladb/scylla-monitoring/assets/4655593/c12d37d6-108a-4030-b329-320d91497424)

**Comment by amnonh** [comment]
The default sorting order is based on #1742. Unfortunately, there's no good way to add a toggle sorting order.

What we can do is, on a panel basis, set the the sorting order to something else

**Comment by mykaul** [comment]
> The default sorting order is based on #1742. Unfortunately, there's no good way to add a toggle sorting order.
> 
> What we can do is, on a panel basis, set the the sorting order to something else

I guess we should. In almost all cases, we need higher values before lower values (so descending order) I reckon.

**Comment by mykaul** [comment]
@vladzcloudius - from your own experience, should we change the default sorting order?

**Comment by vladzcloudius** [comment]
> @vladzcloudius - from your own experience, should we change the default sorting order?

Yes, please!
Ideally it should also be configurable via some dropdown at the top of the dashboad like other things we have there.

Most of the time we want thing to be sorted in a descending order (as you are requesting here) but on rare occasions we want the acceding one. So, being able to change it without having to "Edit" would be nice.

**Comment by amnonh** [comment]
@vladzcloudius unfortunatly, Grafana does not support it, I tried a few tricks and it didn't work, hopefully I'll be able to add it in future version, I'll start by changing the sorting order to desc
