### ISSUE TITLE
CQL payload size metrics are in the wrong dashboard? should be under CQL, but are somewhere under Detailed -> Latencies

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2057]
I expect CQL payload panels to be under the CQL dashboard - was (am) surprised to see them under the 'detailed' panel, under 'latencies' ? Could they be per service level?

**Comment by amnonh** [comment]
Removing the bug label.

The metrics is per schdeduling group, that's why it's under detailed. 
Theoretically, it can be moved (or copied to the cql dashboard).
