### ISSUE TITLE
Wrong metrics used for "Estimated read message size" graph

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#2062]
*Installation details*
Panel Name: Estimated read message size
Dashboard Name:  Detailed
Scylla-Monitoring Version: 4.4.4
Scylla-Version: 2022.2

*Details*
This graph should have used `scylla_transport_cql_response_bytes` in a numerator.
However it has `scylla_transport_cql_request_bytes` instead.

**Comment by mykaul** [comment]
Do we need a 4.4.5 for this (unless we release 4.5 quickly) ?

**Comment by vladzcloudius** [comment]
> Do we need a 4.4.5 for this (unless we release 4.5 quickly) ?

We need 4.4.5 for other reasons too: e.g. for a repair progress fix: https://github.com/scylladb/scylla-monitoring/issues/2019

I have at least one customer complaining about that.

From my perspective we need the fix out. How the fixed version is going to be called (4.5 or 4.4.whatever) is not really important for me.

cc @tomer-sandler
