### ISSUE TITLE
Track UJ node progress

### ISSUE THREAD

**Issue by d-helios** [scylladb/scylla-monitoring#2076]
# Motivation

Monitoring should be able to identify nodes that are too slow to join the cluster, or perhaps simply stuck.

# Possible implementation

Once new node is created and scylla is started, monitoring stack should start scrapping metrics from scylla and operating system.
If new node in UJ state.
- verify network traffic  - scylla_node_network_receive_bytes_total
- verify disk space utilisation - scylla_node_filesystem_total_avail_bytes

if diff for the last X minutes lower then Y over the Z minutes, trigger an alert.

**Comment by amnonh** [comment]
@d-helios luckily, I've added a metrics for a node state, ```scylla_node_operation_mode``` so we can check if a node is in joining mode for more than X minutes

**Comment by amnonh** [comment]
@d-helios note that this is monitoring only and if it's cloud related, there should be a cloud issue
