### ISSUE TITLE
allow grafana to be updated independently of prometheus

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#208]
Currently, if we need to update the dashboards in grafana, the best way is to kill the containers and span a new one. 

For people not using -d to create prometheus, that means prometheus data will be gone. We should maybe have a way to update grafana independently of prometheus.

**Comment by tzach** [comment]
@glommer you can kill and start the Grafana container (agraf)

**Comment by glommer** [comment]
restart won't bring new dashboards. What's the easy/best way to bring in
the new dashboards?

**Comment by tzach** [comment]
You can delete the dashboards from the UI, 
![image](https://user-images.githubusercontent.com/170200/29022571-9ba2c8ea-7b72-11e7-8a1d-7dc3aa783fc2.png)
and then use 
```
./load-grafana.sh
```

**Comment by glommer** [comment]
Good point. I forgot about load-grafana - > and that's because I wrote it!

I maybe need a checkup...

**Comment by tzach** [comment]
With #212 #213 you can now use
```
./kill-grafana.sh
./start-grafana.sh
```

To restart only the Grafana docker instance

**Comment by glommer** [comment]
That's great.

Nir, let's please update nayden about it.

**Comment by tzach** [comment]
I already did
