### ISSUE TITLE
Add logged/unlogged batches graphs

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#2081]
Please make sure that this is a feature request. 
Any scylla version has relevant metrics.
A dashboard that should have new graphs is "Scylla CQL"

**Describe the feature and the current behavior/state.**
Today we don't have a graph that would show the information about the type (logged or unlogged) of BATCH CQL statements that were issued.

Metrics that count logged/unlogged batches are these: `scylla_cql_batches_pure_logged` and `scylla_cql_batches_pure_unlogged` correspondingly.

The usage of logged batches is already a big red flag and in addition to having a graph that counts them we probably want to have something about them on the "Overview" dashboard as well.

**Who will benefit with this feature?**
Everybody

**Comment by amnonh** [comment]
I'll add metrics to the CQL dashbaord, about the overview, it's just one of this features (we have a few of them in the cql optimization section).
It's something the user can use, but we advice against it. like allow filtering, or non paged queries.
That used to be the advisor section, but we end up removing it as it caused more confusion than help
