### ISSUE TITLE
The actual interval for calculating metrics is greater than the one specified in evaluation_interval.

### ISSUE THREAD

**Issue by ViperRu** [scylladb/scylla-monitoring#2087]
The problem is deeper than it seemed. The rules in the group are executed sequentially step-by-step. There is only one group, but because there is a lot of data for on large clusters all the rules in the group scylla.rules do not have time to be executed in 20 seconds.

_Originally posted by @ViperRu in https://github.com/scylladb/scylla-monitoring/issues/1815#issuecomment-1767978197_

**Comment by amnonh** [comment]
@ViperRu What Scylla Version you are refering to?

**Comment by amnonh** [comment]
@ViperRu can we close this?

**Comment by amnonh** [comment]
@ViperRu I'm closing, re-open if you need to
