### ISSUE TITLE
docs: Issue in page Deploying Scylla Monitoring Stack Without Docker

### ISSUE THREAD

**Issue by stefanofornari** [scylladb/scylla-monitoring#2089]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-4.4/install/monitor-without-docker

### Problem
This page requires review, there are formatting bugs and probably some missing information

###  Suggest a fix

**Comment by tzach** [comment]
Thanks @stefanofornari 

> .. there are formatting bugs 

It would be useful to share an example, best with a screen capture.

> and probably some missing information

What information is missing?

**Comment by amnonh** [comment]
@stefanofornari ping, can you add the missing information?

**Comment by stefanofornari** [comment]
I am not the best person to do it. I think you should review the page and follow the steps as I have done and makes sure the outcome is as expected. When I have done it, it was not, you can pick the issues easily if you try it out.
