### ISSUE TITLE
Use Heatmap panel to represent Tablets status

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#2111]
Real time status of tablets, similar to [tablet-mon.py](https://github.com/scylladb/scylladb/pull/15512) but as part of a dashboard.
![image](https://github.com/scylladb/scylla-monitoring/assets/170200/176849b5-42da-4713-9bac-bb6257a8f50a)

**Comment by tzach** [comment]
@tgrabiec FYI

**Comment by amnonh** [comment]
@tzach beside being a cool representation, can you describe a scenario that this is useful?

**Comment by tzach** [comment]
It would be beneficial to see, for a specific table, how it is distributed between the nodes.
See tablet-mon.py an in-terminal tool already in use.

**Comment by tgrabiec** [comment]
Sending detailed tablet metrics may be too much. We disable per-table stats by default, and per-tablet stats will be heavier than that.

We can present aggregate metrics for migrating tablets per shard.

**Comment by amnonh** [comment]
I was thinking, if we can show the number of tablets per shard/node we can show bars that would show the distribution.
Naturally, showing all tablets in a real cluster is too much

**Comment by tzach** [comment]
> Sending detailed tablet metrics may be too much. We disable per-table stats by default, and per-tablet stats will be heavier than that.

Even if too much for production, it would be helpful for debuging and demos.

**Comment by tgrabiec** [comment]
@tzach So what would you like the heat map to show exactly?

**Comment by tgrabiec** [comment]
I feel that the thing provided by grafana is too limited in its presentation and update frequency. What tablet-mon is generally useful for is getting an intuition about the behavior of the system in real time, by observing movement of parts, and for that you need (1) high frequency of updates (2) animation. Grafana has neither, it's good at presenting coarse-grained statistics.

**Comment by tgrabiec** [comment]
For example, with tablet-mon I was able to immediately identify that there are stalls in tablet phase transitions which shouldn't be there. That would be lost in the noise in grafana. I think the two tools serve different purposes.

**Comment by amnonh** [comment]
closed by #2170
