### ISSUE TITLE
Screenshot is not working anymore

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#2117]
*Installation details*
Panel Name: n/a
Dashboard Name: Detailed
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) 4.5.0
Scylla-Version: 2023.1.1

after pushing Screenshot button I get attached pic
![dashboard_detailed-2023-1-2023-11-08T14 28 55 202Z](https://github.com/scylladb/scylla-monitoring/assets/504773/84fda648-6eb7-42ae-9497-3d685552ef4f)

so it seems we stopped bundling some plugin, or grafana did? @amnonh ?

**Comment by amnonh** [comment]
Closing as duplicate of #2097
