### ISSUE TITLE
Tablets support

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2119]
- [ ] Developer-oriented metrics
- [ ] User-oriented metrics

**Comment by amnonh** [comment]
@tgrabiec do you have a list of tablet related metrics that will be useful for both users and field?

**Comment by tgrabiec** [comment]
I have, but we need to implement them on the scylla side first before we move on with grafana support.

**Comment by tzach** [comment]
https://github.com/scylladb/scylladb/issues/16131

**Comment by amnonh** [comment]
Removing from 4.6, it would wait until we'll have metrics inside Scylla
