### ISSUE TITLE
4.6.0 - By Instance, doesn't work on any of the dashboards

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-monitoring#2138]
*Installation details*
Panel Name: All panel that can show data by instance
Dashboard Name: Os Metric (but it apply to all other dashboards)

Scylla-Monitoring Version: 4.6
Scylla-Version: 2024.1-rc2

all of the dashboards that need to show data per instance, so all of the data together: 
![image](https://github.com/scylladb/scylla-monitoring/assets/340979/48515391-5d3c-4e1e-94bd-38f9002e9914)

example of such run:
```
hydra investigate show-monitor 065fe747-1a6d-4f96-8dad-2b0648201bd3
``

here is example of such query:
```
sum(node_memory_MemAvailable_bytes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc"}) by ([[by]])/sum(node_memory_MemTotal_bytes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc"}) by ([[by]])
```
![image](https://github.com/scylladb/scylla-monitoring/assets/340979/d85ad58e-4ef8-499d-b287-da676dde4a34)


replacing it `[[by]]` with `instance` 
```
sum(node_memory_MemAvailable_bytes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc"}) by ([[by]])/sum(node_memory_MemTotal_bytes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc"}) by (instance)
```

![image](https://github.com/scylladb/scylla-monitoring/assets/340979/d5d3d0a7-d765-48ab-b81b-6451cf162bcd)

**Comment by amnonh** [comment]
@fruch I still cannot reproduce, this is how the OS dashboard looks like:
![image](https://github.com/scylladb/scylla-monitoring/assets/2118079/919fe24a-49aa-4c84-9045-69f5a83ddcca)

**Comment by fruch** [comment]
I still see it on any run uses monitoring 4.6.0

![image](https://github.com/scylladb/scylla-monitoring/assets/340979/70f34524-1532-4b37-b5ea-0368fdd26c1c)

as you can see the query is using capital `Instance` and doesn't sure what I would expect.

**Comment by amnonh** [comment]
Because I'm using your example, I assume this is due to os/browser differences.
