### ISSUE TITLE
OS Metrics - Disks - should by default check all disks

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2142]
On few setups (namely, i3en.xlarge), we have the following setup:
![image (3)](https://github.com/scylladb/scylla-monitoring/assets/4655593/c0efead3-f32a-4f33-aefc-e2d531a2d82b)

And by default, we were showing the root disk (nvme0n1) and not Scylla's disk (nvme1n1) stats, which of course confused me, as I've seen very few IOPS on that disk...
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/e3f0a932-cb8e-454e-ac00-852ae072fdb1)

**Comment by amnonh** [comment]
@mykaul can you open an enterprise issue with all the relevant information, I would like to look at the actual data and find what are the best options

**Comment by mykaul** [comment]
> @mykaul can you open an enterprise issue with all the relevant information, I would like to look at the actual data and find what are the best options

https://github.com/scylladb/scylla-enterprise/issues/3753
