### ISSUE TITLE
Scylla 2.0 dashboards

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#215]

**Comment by eyalgutkind** [comment]
With 2.0 Scylla metrics have an IP/instance name attached to the mouse over information, for the collcetd information (Network and disk) that information is missing see below examples:

![image](https://user-images.githubusercontent.com/17868115/30444326-6d0eae4e-9937-11e7-9b56-574506253c07.png)

![image](https://user-images.githubusercontent.com/17868115/30444371-9565a30c-9937-11e7-9e57-ad40b1c7df43.png)

**Comment by tzach** [comment]
The node_exporter metrics does not use the same hostname notation is scylla metrics
@amnonh can we fix it using tags?

**Comment by tzach** [comment]
related to #244

**Comment by amnonh** [comment]
@tzach I think we can close that

**Comment by amnonh** [comment]
@tzach
