### ISSUE TITLE
dashboard switcher no longer works

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#2159]
*Installation details*
Panel Name: n/a
Dashboard Name: any
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) 81733e9a859ecc4dbab06c291864caab4e1679e5
Scylla-Version: 2024.1

Clicking on the dashboard switcher (upper right) doesn't do anything

**Comment by avikivity** [comment]
06eae347 works.

**Comment by amnonh** [comment]
Are you looking, by any chance, at the QA dashboard? Their main dashboard doesn't have the same hamburger switcher

**Comment by avikivity** [comment]
No I switched to other dashboards and can't switch back.

**Comment by amnonh** [comment]
It seems to be broken in Grafana 10.2.2 and works in Grafana 10.2.3 without any mention in the Grafana release notes

**Comment by amnonh** [comment]
Fixed by #2161
