### ISSUE TITLE
Overview page - no data [write latency, Read timeout by DC]

### ISSUE THREAD

**Issue by d-helios** [scylladb/scylla-monitoring#2162]
scylla-version=2022.2
monitoring-version=4.5.1
dashboard=overview-2022-2

<img width="547" alt="image" src="https://github.com/scylladb/scylla-monitoring/assets/16616414/675bcf80-28b4-4e90-9487-bfa607c42cb1">

**Comment by amnonh** [comment]
If that's a cloud cluster, can you open an issue on enterprise/siren with the the actual details, so I can take a look?

**Comment by amnonh** [comment]
@d-helios ping

**Comment by amnonh** [comment]
@d-helios I'm trying to understand if that's a real issue, you can contact me directly (or using an enterprise issue) with the cluster details

**Comment by amnonh** [comment]
@d-helios ping

**Comment by amnonh** [comment]
Closing as not a bug
