### ISSUE TITLE
Add ethtool metrics to datadog integration

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#2163]
The following potential metrics should be exported to datalog:
HELP node_ethtool_bw_in_allowance_exceeded Network interface bw_in_allowance_exceeded
HELP node_ethtool_bw_out_allowance_exceeded Network interface bw_out_allowance_exceeded
HELP node_ethtool_conntrack_allowance_exceeded Network interface conntrack_allowance_exceeded
HELP node_ethtool_linklocal_allowance_exceeded Network interface linklocal_allowance_exceeded 
HELP node_ethtool_pps_allowance_exceeded Network interface pps_allowance_exceeded

**Comment by mykaul** [comment]
Are you sure it is called 'ethtool_...' ? See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-network-performance.html - "When the CloudWatch agent imports these metrics into CloudWatch from Linux instances, it prepends ethtool_ at the beginning of each of these metric names."

**Comment by amnonh** [comment]
The above metrics are taken from the node_exporter metrics, this issue is about mark them with a label so that datadog agent would pick them up
