### ISSUE TITLE
Unit for queue-length might not properly in production

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylla-monitoring#2168]
When I applied scylla-advanced.json, there is something improperly set for queue-length metrics, such as `scylla_io_queue_queue_length`, it's type is `gauge` and description is `Number of requests in the queue` , then it displayed unit `s`  

- I guess it's unit is better to be int or number.

**Comment by amnonh** [comment]
I didn't understand the issue. Can you add a screenshot of what you see that explains what is wrong?

**Comment by amnonh** [comment]
@qiuqiu-007 ping

**Comment by qiuqiu-007** [comment]
@amnonh Please take a look here 
![d78a](https://github.com/scylladb/scylla-monitoring/assets/143240433/d3a8b4b0-372d-4005-a291-3bb0baf89ed9)

**Comment by qiuqiu-007** [comment]
I've found where the matter is, in panel json, it's yaxes was set to be "μs"

![屏幕截图 2024-02-19 100310](https://github.com/scylladb/scylla-monitoring/assets/143240433/500efe64-71af-4fb0-990a-f94b4be6cf96)

**Comment by amnonh** [comment]
@qiuqiu-007 Where did you get the dashboard from? This does not look like the latest monitoring dashboard:
![image](https://github.com/scylladb/scylla-monitoring/assets/2118079/558d48c5-224e-41b0-a4ad-8238a21a9d36)

**Comment by qiuqiu-007** [comment]
> @qiuqiu-007 Where did you get the dashboard from? This does not look like the latest monitoring dashboard

I get the version 4.4.4

**Comment by amnonh** [comment]
Please update to the latest version.

**Comment by qiuqiu-007** [comment]
> Please update to the latest version.

Got it. Thanks a lot.

**Comment by amnonh** [comment]
Closing, please-reopen if you are facing any issue
