### ISSUE TITLE
Reads panel does not reflect shards

### ISSUE THREAD

**Issue by susiesolis** [scylladb/scylla-monitoring#2171]
*Installation details*
Panel Name:  Reads panel
Dashboard Name: Dashboards -> Overview -> Reads panel
Scylla-Monitoring Version: Scylla Monitoring version - 4.6.0
Scylla-Version: Scylla Enterprise 2023.1.4

Lines in Reads view always reflect DC level metrics in the Dashboards -> Overview -> Reads panel. They don't change to reflect Instance or Shard level metrics based on the dropdown.
![Screenshot 2024-02-08 at 2 38 26 PM](https://github.com/scylladb/scylla-monitoring/assets/52222826/250833c4-9e52-468c-9fa4-9b18b682de7f)

**Comment by tzach** [comment]
@amnonh FYI
