### ISSUE TITLE
The explenation for the unified class group graph is not clear

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-monitoring#2178]
This is what I see on the Explore:
![image](https://github.com/scylladb/scylla-monitoring/assets/4498177/da9c07e3-d56d-42dc-a696-b6892ec77199)

And this is what I see in View (and dashboard too)
![image](https://github.com/scylladb/scylla-monitoring/assets/4498177/4407ff77-a4e8-4f44-a629-d42d2ec14ab4)

In the latter case legend doesn't match the plot -- legend shows blue compaction to consume 60% and other classes to be minor, while on the plot itself there are two -- purple and orange -- plots that consume 80%+, which is not quite true. The explore page shows coordinated legend and plots

Scylla Monitoring version - 4.6.0

**Comment by amnonh** [comment]
@xemul, have you noticed that in the dashboard, it's both group and class?
your Prometheus query should be:
```
sum(rate(scylla_io_queue_consumption[1m])) by (cluster,class, iogroup)
```

**Comment by amnonh** [comment]
I've opened https://github.com/grafana/grafana/issues/82417 we should try to upgrade and see if the problem get solved in Grafana

**Comment by amnonh** [comment]
Sorry, I forgot that it's a stack graph, the idea here is to see how it all adds up to 100% The documentation should be better
