### ISSUE TITLE
docs: Issue in page Some queries use reverse order

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylla-monitoring#2188]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-3.8/use-monitoring/advisor/cqlReverseOrder

### Problem
Documentation link
https://docs.scylladb.com/troubleshooting/reverse-queries/
is redirecting to a not found page
###  Suggest a fix
couldn't find the corresponding page

**Comment by tzach** [comment]
Its safe to remove this from the dashboard and doc 
reverse quieries are not an issue since https://www.scylladb.com/product/release-notes/scylladb-enterprise-release-2022-1-0/

**Comment by amnonh** [comment]
closing
