### ISSUE TITLE
Version information is cut - although there's plenty of space available in the panel

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2189]
See attached screenshot: why wouldn't the table expand to bring the complete version information in?

![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/228647f7-d848-417a-827e-9970639dff2f)

Version: 4.4.5

**Comment by amnonh** [comment]
~~I'm unable to reproduce this, I've checked at cluster that runs 2022.2 can you share with me the cluster id you are looking at?~~

Found it, it breaks when the patch release is two digits long
