### ISSUE TITLE
Regex for empty string |$^ in dashboards

### ISSUE THREAD

**Issue by Rikkuru** [scylladb/scylla-monitoring#2192]
*Installation details*
Panel Name: node variable and other
Dashboard Name:os-metrics  and other 
Scylla-Monitoring Version: master (4.6.1)
Scylla-Version: 5.0.13

Many regex in templates use this expr `|$^`
For example node variable in os metrics 
`label_values(node_filesystem_avail_bytes{cluster=~"$cluster|$^", data_center=~"$data_center"}, instance)`

so we filter all nodes with selected cluster but also all nodes with missing cluster for some reason 

It makes it harder  to alter dashboards if your  datasource is not exclusively used for scylla metrics and there are nodes without cluster label from other deployments.

Maybe this suffix is not needed ? Why would we want to filter out specific value of label AND also empty value

**Comment by amnonh** [comment]
The reason for accepting data without a cluster label is to support customers who did not configure the cluster label, we may remove it in a future release as it's a breaking changes
