### ISSUE TITLE
Add more dashboards, with server drill down

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#22]
Scylla provides many more metrics which are currently not presented
Adding a "drill down" dashboard (or many) with more metrics will be very useful for Scylla debugging

**Comment by tzach** [comment]
3 main dashboards:
- Custer 
- Per DC
- Per Server

Cluster, DC dashboard should include:
- [Node status: Alive, Dead, bootstrapping, etc](https://github.com/scylladb/scylla/issues/1067)
- Disk space
- write tps
- write latency 
- read tps
- read latency

A user can select which DC / server to watch at any time

Server Dashboard (drill down) should include [ALL available metrics](https://github.com/scylladb/scylla/issues/1410), ordered by topic: disk, networking, errors, etc

Example dashboard below, including node status and space (other parts of this dashboard are not necessarily relevant)

![image](https://cloud.githubusercontent.com/assets/170200/16449894/a6dc1508-3e02-11e6-80bc-4a30dfd8e7ce.png)

**Comment by tzach** [comment]
@amnonh can we have a template drop-down list, similar to what you did for interfaces,  with link to each server drill down dashboard?

**Comment by amnonh** [comment]
We can have a dashboard for specific server with a dropdown for the server, that will be ok as long as there are not too many servers, or it will be unusable.

**Comment by tzach** [comment]
> We can have a dashboard for specific server with a dropdown for the server, that will be ok as long as there are not too many servers, or it will be unusable.

a dropdown is not so bad, as most of the users have <= 30 size clusters.
Also, servers are groups into DC, where the user first choose DC, then a server.

For larger deployments, a table of servers per DC, each with a link to its dashboard will be more useful. Is it doable?

**Comment by amnonh** [comment]
On Mon, Nov 28, 2016 at 8:53 AM, Tzach Livyatan <notifications@github.com>
wrote:

> We can have a dashboard for specific server with a dropdown for the
> server, that will be ok as long as there are not too many servers, or it
> will be unusable.
>
> a dropdown is not so bad, as most of the users have <= 30 size clusters.
> Also, servers are groups into DC, where the user first choose DC, then a
> server.
>
> For larger deployments, a table of servers per DC, each with a link to its
> dashboard will be more useful. Is it doable?
>
You are the graffana expert, I can look for something

**Comment by tzach** [comment]
An attempt to create a clickable list of nodes is on branch [list-targets](https://github.com/scylladb/scylla-grafana-monitoring/tree/list-targets)

This is how it looks like
![image](https://user-images.githubusercontent.com/170200/27863452-dcb705c0-6192-11e7-8747-63c61a520f78.png)

@amnonh thoughts?

**Comment by dorlaor** [comment]
Good idea!
Naming nodes by dns or IPs will be better.

**Comment by tzach** [comment]
Names are coming from the hosts. In most cases its IP by default, not so for Docker.

**Comment by amnonh** [comment]
@tzach can we close this?

**Comment by tzach** [comment]
Why closing?
As far as I know, the server list with the drill down is not implemented

**Comment by amnonh** [comment]
We have a per-server dashboard with additional metrics.

If this is not what you mean, please update the issue

**Comment by amnonh** [comment]
@tzach how this differs from the per-server dashboard?

**Comment by amnonh** [comment]
@tzach can we close this?

**Comment by amnonh** [comment]
@tzach ?
