### ISSUE TITLE
[RFE] Re-implement cross-shard metrics

### ISSUE THREAD

**Issue by pogzie** [scylladb/scylla-monitoring#2204]
**System information**
Scylla Enterprise 2023.1.4
Scylla Monitoring version - 4.6.2
Dashboard Tags: 2023.1 + 3.2 (Scylla Manager Metrics) 

**Describe the feature and the current behavior/state.**
> Is there any metrics at scylla server side to represent cross-shard communication happens for a CQL request?

On an inquiry about cross-shard communication, we have found that the metrics endpoint is already providing `*_cross_shard_ops` metrics through the `/metrics` endpoint. Upon digging further, we had found a merge tagged for `scylla-monitoring-4.6.2` https://github.com/scylladb/scylla-monitoring/commit/300f22255ae2beb4a63c203a3b46d3993bdf9756 

An upgrade to Scylla Monitoring from 4.6.0 to 4.6.2 was done but upon checking, the metrics are not graphed. Further inquiry led us to https://github.com/scylladb/scylla-monitoring/pull/658 where it was apparently pulled due to incorrect values. 

Customer is requesting to have the graph implementation revisited as it provides useful information regarding cross-shard operations which they are highly interested in.

**Comment by amnonh** [comment]
@pogzie I didn't understand if the issue was with a missing metric, a missing panel, or a problem with an existing panel.

**Comment by pogzie** [comment]
@amnonh there is an internal issue (3983) discussing this. but to answer your question, there was a merged PR in https://github.com/scylladb/scylla-monitoring/commit/300f22255ae2beb4a63c203a3b46d3993bdf9756 which implemented the graph. then it was pulled out in https://github.com/scylladb/scylla-monitoring/pull/658 

> Customer is requesting to have the graph implementation revisited as it provides useful information regarding cross-shard operations which they are highly interested in.

So in summary: it was implemented, then removed, and customer wants it implemented again.

**Comment by mykaul** [comment]
> So in summary: it was implemented, then removed, and customer wants it implemented again.

@pogzie - customer issues should be discussed in enterprise repo, please.

**Comment by amnonh** [comment]
There was a reason it was removed, it's off and confusing. the PR in question was actually 4 years ago, it's not part of 4.6.x

**Comment by amnonh** [comment]
@pogzie I tend to close this issue. Apparently, the metrics in question are off and confusing.  The enterprise issue was closed. 
Please re-open if needed
