### ISSUE TITLE
scylla_monitoring_install_ami: the installation relies on tag prefix scylla-monitoring-

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-monitoring#2212]
The `scylla_monitoring_install_ami` script (used by cloud-images setup) accepts `--version` parameter,
The version parameter is added to `scylla-monitoring-` prefix, ex. scylla-monitoring-4.3 and use it to download the project as a tarball,

https://github.com/scylladb/scylla-monitoring/blob/382da47bf624713f1240bebc6d680265e010d64d/packer/files/scylla_monitoring_install_ami#L119-L127

The problem with this implementation is that we can't install the cloud images from a certain commit or branch but only a tag in a certain format,

We should adjust the script to one of the two:

- The script assumes that the repo is already cloned locally (preferred)
- The script can clone any git ref

**Comment by amnonh** [comment]
Fixed by #2252
