### ISSUE TITLE
Make all plugins local

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#222]
Currently, Grafana docker downloads the pie plugin on every ./start-all.sh
A better way is to download the plugin as part of the project (as a submodule?) and upload it to Grafana from a local repo
http://docs.grafana.org/plugins/installation/#installing-plugins-manually

**Comment by amnonh** [comment]
@tzach I think we can close this, we move to a solution where we specify the plugin version

**Comment by tzach** [comment]
Reopen since the original issue is not fixing the version rather avoid the need for external network when using start_all

**Comment by asias** [comment]
There is no point down load all the time when we start scylla monitor. 
I hit the following problem. It failed to start scylla monitor from time to time. It turned out sometimes the docker instance failed to get something from grafana.com. 
It is best to avoid any internet access when starting the scylla monitor. 

```
$ sudo ./start-all.sh -v 3.0 -s scylla_servers.hj.yml

aprom
aprom
agraf
aalert
aalert

*****************************************************
* WARNING: You are using the unstable master branch *
* Check the README.md file for the stable releases  *
*****************************************************

Wait for alert manager container to start.7f51dbccf4d85604a62e093bd963f42d10a41c73c081653d0bba6a12246e6543
Wait for Prometheus container to start..944182f9c364027743a16336bb24051febb2495cbcefe065aaeb120dcdf67736
Waiting for Grafana container to start........Error: Grafana container failed to start
```
```
$ sudo docker logs 944182f9c364
Failed to send requesterrorGet https://grafana.com/api/plugins/repo/grafana-piechart-panel: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/grafana-piechart-panel: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>
USAGE:
   Grafana cli plugins install [arguments...]
```
