### ISSUE TITLE
set the default dashboard refresh configurable

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#2220]
Dashboard default refresh is too short, we should set it to something longer

**Comment by tzach** [comment]
> Dashboard default refresh is too short

Why?

**Comment by amnonh** [comment]
A refresh causes a change to a dashboard, making it harder when going over a large dashboard @mykaul Raised the issue originally.
I may make it configurable and have different values for the cloud

**Comment by tzach** [comment]
Thanks. Please provide the motivation and user effect in the issue, or we will have a list of random updates, each time in a different direction.
