### ISSUE TITLE
Alternator: counts create table is not exactly or properly

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylla-monitoring#2224]
metrics: `scylla_alternator_operations`
When I use aws `create-table` or `update-table` it plus one whatever it done successfully or failed.

![屏幕截图 2024-03-14 174551](https://github.com/scylladb/scylla-monitoring/assets/143240433/2a4f378a-052d-4382-b429-e5b572b05920)

Maybe it is better to count the successful operations.

**Comment by amnonh** [comment]
@nyh can you take a look, if it's a real issue, maybe we should open it under ScyllaDB repository

**Comment by nyh** [comment]
This is definitely NOT a monitoring issue, but Scylla monitoring showing what Scylla core is giving it, so I'm closing this issue - @qiuqiu-007 please reopen it in the Scylla core project (github.com/scylladb/scylladb) if you want, but before you do, you should know that this was done intentionally:

All the Alternator (DynamoDB API) counters count the number of times the operation was called, not whether it succeeded. This is true for CreateTable, as you noticed but also other operations like GetItem: The GetItem counter is incremented as the first thing this operation does - regardless of whether the operation found the item, didn't find the item, or even encountered some error in the request's format.

If you want to change this deliberate implementation, please explain why in the issue you will create.

@amnonh how do the CQL operation counters work? Do they count all requests, just successes, or what?
