### ISSUE TITLE
Promethues continues to trigger alerts for a node which has already been removed from scylla_servers.yml

### ISSUE THREAD

**Issue by igorribeiroduarte** [scylladb/scylla-monitoring#2227]
*Installation details*
Scylla-Monitoring Version: 4.6.1
Scylla-Version: `2024.1.2-0.20240228.2c85a811d0be`

Description:
I'd expect that if I removed a node from `scylla_servers.yml`, this node would stop being tracked by the scylla-monitoring stack. However, I continue receiving alerts for this node for a few minutes until alertmanager finally changes the alert status to resolved.

How to reproduce:
* Stop scylla-server in one of the nodes. Alerts will start being triggered, as expected:
```
Mar 19 16:05:41 igor-test2-node-us-east1-c-3 scylla[21737]:  [shard 0:main] init - Scylla version 2024.1.2-0.20240228.2c85a811d0be shutdown complete.
Mar 19 16:06:54 igor-test2-node-us-east1-c-3 systemd[1]: scylla-server.service: Succeeded.
Mar 19 16:06:54 igor-test2-node-us-east1-c-3 systemd[1]: Stopped Scylla Server.

```
* Remove this node from `scylla_servers.yml` and restart the monitoring stack.
```
./kill-all.sh && ./start-all.sh  -d /opt/scylla-monitoring/data  -f /opt/scylla-monitoring/alertdata  -v 2022.2  -s /opt/scylla-monitoring/config/scylla_servers.yml  -N /opt/scylla-monitoring/config/scylla_manager_servers.yml  -r /opt/scylla-monitoring/config/rule_config.yml  -R /opt/scylla-monitoring/config/prom_rules/  -b
```

* Now look at the alertmanager logs. After being restarted without the stopped node, it continues triggering alerts for it and the alert is only marked as resolved after a few minutes.
```
ts=2024-03-19T16:09:27.556Z caller=main.go:245 level=info msg="Starting Alertmanager" version="(version=0.26.0, branch=HEAD, revision=d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)"
```

```
ts=2024-03-19T16:11:27.414Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][active]
ts=2024-03-19T16:13:27.414Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][active]
ts=2024-03-19T16:14:27.415Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:16:27.414Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:18:27.414Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:20:27.414Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:22:27.413Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:24:27.413Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:26:27.413Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]
ts=2024-03-19T16:28:27.414Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[d1721ea][resolved]

```

**Comment by amnonh** [comment]
Prometheus is the one generating the alerts; you keep seeing them because the Prometheus alert continues to fire. I'm not sure if it's a bug or not, so I'm keeping it open for now

**Comment by vladzcloudius** [comment]
@amnonh it is a bug because the expected behavior described in the issue is absolutely reasonable.

We need to have a way to remove nodes from the cluster.

This is a basic functionality and it's not optional. So, by no means this is an "enhancement"! 

Please, consider giving this issue a high priority.

We either need a fix in the Monitoring or a "fix" in the procedure that would allow us removing nodes without creating alerts for removed nodes.

**Comment by amnonh** [comment]
I will try to reproduce it. With future alert-related issues, please include the relevant information from within Prometheus e.g. the alert screen.

If you have access to the Prometheus server and you can get the data from it, it would help

**Comment by vladzcloudius** [comment]
> I will try to reproduce it. With future alert-related issues, please include the relevant information from within Prometheus e.g. the alert screen.
> 
> If you have access to the Prometheus server and you can get the data from it, it would help

Sure. @igorribeiroduarte could you, please, provide the missing info?

**Comment by amnonh** [comment]
@igorribeiroduarte, if you can upload the Prometheus data and send me a link to where I can download it, it would be helpful.

**Comment by igorribeiroduarte** [comment]
> @igorribeiroduarte, if you can upload the Prometheus data and send me a link to where I can download it, it would be helpful.

Sure: [data.tar.gz](https://github.com/scylladb/scylla-monitoring/files/14669102/data.tar.gz)

The alert being fired:
![image](https://github.com/scylladb/scylla-monitoring/assets/12210553/7674d709-12cf-4739-9756-f38550f33aa8)

**Comment by tzach** [comment]
Maybe its https://github.com/prometheus/prometheus/issues/12007 ?

**Comment by igorribeiroduarte** [comment]
Can we backport this, @amnonh ?

**Comment by amnonh** [comment]
I'll backport it to 4.6. I've already branched 4.7, so I'm not sure it's worth releasing a new 4.6 but we may do that if we see that 4.7 gets delayed

**Comment by igorribeiroduarte** [comment]
> I'll backport it to 4.6. I've already branched 4.7, so I'm not sure it's worth releasing a new 4.6 but we may do that if we see that 4.7 gets delayed

Do we have an ETA for the backport or for 4.7, @amnonh ?
We're still hitting this in the field.

**Comment by amnonh** [comment]
4.7 is branched and is currently in pre-release; if nothing unexpected would happened, it will be released this week
