### ISSUE TITLE
scylla plugin executables are making the repo 153mb 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-monitoring#2246]
seems like those were added in:
https://github.com/scylladb/scylla-monitoring/commit/fb1c9d1be7a6f152bf659866c58153bb14fc2e24

and at least for SCT how it's operate today, it pulling all of that from github, and slowing it down quite considerably

do we really need the executables in the repo ? can't we use github artifacts for that ?

**Comment by mykaul** [comment]
Probably need to switch them to use git-lfs

**Comment by fruch** [comment]
@amnonh 

is there anything we can do with this one ? in any case we still need to clone this repo, it's slows it down considerably

**Comment by amnonh** [comment]
The artifacts need to be in the repository, or the plugin will not work. Technically, I can remove some of them and add comments to the documentation.
I'll start with that. It's a breaking change so it will be part of the master and the next release

**Comment by fruch** [comment]
> The artifacts need to be in the repository, or the plugin will not work. Technically, I can remove some of them and add comments to the documentation. I'll start with that. It's a breaking change so it will be part of the master and the next release

Thanks, it would help speeding up some of the test cases (and local development in SCT)
