### ISSUE TITLE
Requests shed panel doesn't seem to properly add up numbers

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2248]
Per DC:
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/264355c4-f558-4990-bead-a068988dd53d)

Per instance:
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/7590fd7e-cd02-43a6-b414-3ef0abe8403d)

Per shard:
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/68feec84-32eb-4f75-8b85-55a978ca453d)

I expected the per DC to sum up the 'per instance' and obviously the 'per shard' numbers, but that's far from what's going on here. I assume it's averaged across all shards per node, and so on?

Ver 4.6.2, against 2023.1.4 cluster.

**Comment by mykaul** [comment]
Single node:
Per shard:
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/1033f368-3b82-4a65-a969-67370055271c)

Per node:
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/ee933f7a-3f8a-411a-b078-0daf23cac041)

Per DC:
![image](https://github.com/scylladb/scylla-monitoring/assets/4655593/4d74e879-cb99-4476-a1bd-c86ae0acd775)

**Comment by amnonh** [comment]
@mykaul i've looked a the code it is seems ok, can you validate:
1. the monitoring version
2. your aggregation function

**Comment by mykaul** [comment]
Note to self: check again - why was it on avg and not sum?
