### ISSUE TITLE
Hints manager sent annotation, uses the wrong metric

### ISSUE THREAD

**Issue by ViperRu** [scylladb/scylla-monitoring#2250]
https://github.com/scylladb/scylla-monitoring/blob/f25d76d4dbc5984305e576a422c0e239ed7afa6b/grafana/types.json#L4462
Please correct to "scylla_hints_manager_sent"

**Comment by mykaul** [comment]
But those seem to be two different metrics:
https://github.com/scylladb/scylladb/blob/8550a38a8baab074a1b1b5f66ad321c9c5d669d9/db/hints/manager.cc#L151
https://github.com/scylladb/scylladb/blob/8550a38a8baab074a1b1b5f66ad321c9c5d669d9/db/hints/manager.cc#L160

**Comment by ViperRu** [comment]
> But those seem to be two different metrics: https://github.com/scylladb/scylladb/blob/8550a38a8baab074a1b1b5f66ad321c9c5d669d9/db/hints/manager.cc#L151 https://github.com/scylladb/scylladb/blob/8550a38a8baab074a1b1b5f66ad321c9c5d669d9/db/hints/manager.cc#L160

Just now scylla_hints_manager_written is used both for the annotation_hints_sent and for the annotation_hints_writes.
