### ISSUE TITLE
Grafana dashboards fail with AnnotationQueryRunner failed Query error: 400 Bad Request

### ISSUE THREAD

**Issue by kocic11** [scylladb/scylla-monitoring#2261]
*Installation details*
Panel Name: Home
Dashboard Name: Home
Scylla-Monitoring Version: 4.7.0
Scylla-Version: 5.4.3

Stopping and starting the monitoring stack on MacOS Sonoma (14.4.1) results in the following error:
```
AnnotationQueryRunner failed
Query error: 400 Bad Request
```

After further investigation, the issue is with the Prometheus container IP address, which changes after each restart.

**Comment by amnonh** [comment]
@kocic11 when you are resting containers (e.g. docker restart) they keep their IP address. If you want to start and stop completely, you have three options:
1. use the start-all.sh and kill-all.sh
2. use the host network (using the -l command line flag to start-all.sh)
3. use docker-compose

**Comment by amnonh** [comment]
I'm closing, please re-open if you think it's needed

**Comment by kocic11** [comment]
1. Start-all/kill-all resets everything, and it is not the best way to stop and start containers.
2. The -l flag didn't work either, and the localhost:3000 no longer works.
3. I see a docker-compose template file. It doesn't work without the env file. Do you have the ENV file for it?

**Comment by amnonh** [comment]
- if you just want to restart, you can use ```docker restart``` it will not change the IPs
- if you want to shut down and start again, kill-all.sh/start-all.sh  is a good option
- we are using the local network host all the time, it should work.
-  For the ```.env``` file. An easy way to create it, is using the experimental ```--compose``` flag to start-all.sh it will generate a comose file and ```.env``` file for you.

for example:
```
./start-all.sh -v 2024.1 --compose
```

**Comment by kocic11** [comment]
The --compose option worked!

However, I don't see the Prometheus data folder in the .env file.

Is there a variable for it?

**Comment by amnonh** [comment]
If you are using the - - compose option, you need to supply it with the -d
command line option.

You run start-all.sh with - - help for all command line options

**Comment by kocic11** [comment]
Yes, I did that and expected it to finish in the .env file. However, when using docker-compose, that information is gone.

**Comment by amnonh** [comment]
Then it should be part of the docker-compose.yml file under 
```
 promotheus:
    volumes:
     - path/to/data/dir:/prometheus/data

```

**Comment by kocic11** [comment]
That works, but I would like a variable like PROMETHEUS_DATA that aligns with how the other volumes are configured.

**Comment by amnonh** [comment]
The given docker compose file is a suggestion, you can add such a variable
to it, just don't erase it
