### ISSUE TITLE
track keyspace or table sizes in graph

### ISSUE THREAD

**Issue by nopzdk** [scylladb/scylla-monitoring#2271]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 2024.1.2
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
I would like to have a graph that displays keyspace and/or table size over time so I can identify if a table to keyspace is growing too fast

**Who will benefit with this feature?**
Admins will be able to know what tables have grown the most over time and advice developers if there is issues. 

**Any Other info.**
ubuntu@scylla-server:/var/lib/scylla/data$ sudo du  -h -d1 | grep -v "^0" | sort -h
392K    ./system_schema
1.3M    ./system_auth
2.4M    ./system_distributed_everywhere
2.9M    ./system_distributed
4.0M    ./system
16G     ./keyspace1
372G    ./keyspace2
420G    ./keyspace3
1.3T    ./keyspace4

maybe the system keyspaces can be left out or moved to separate graph.

**Comment by amnonh** [comment]
@nopzdk did you check the keyspace dashboard?

**Comment by nopzdk** [comment]
@amnonh where can I find that dashboard?

**Comment by amnonh** [comment]
Use the latest ScyllaDB monitoring stack (4.7.1), it's one of the available dashboards

**Comment by amnonh** [comment]
@nopzdk ping, can you validate and comment if it's missing or close?

**Comment by nopzdk** [comment]
You can close it I saw it on 4.7.1, thanks
