### ISSUE TITLE
increase nodes:instance column width to display full ip by default

### ISSUE THREAD

**Issue by nopzdk** [scylladb/scylla-monitoring#2302]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): scylla monitor 4.7.1
- Are you willing to contribute it (Yes/No):yes

**Describe the feature and the current behavior/state.**
increase the column width of instance in the nodes view, to 120, this will allow the full ip to be displayed all the time. 

**Who will benefit with this feature?**
everyone using the dashboard
**Any Other info.**
<img width="1769" alt="Screenshot 2024-05-24 at 09 38 09" src="https://github.com/scylladb/scylla-monitoring/assets/7662003/b6b47fa3-399c-4f0f-90d3-0e6e44ec9d39">
<img width="1769" alt="Screenshot 2024-05-24 at 09 38 19" src="https://github.com/scylladb/scylla-monitoring/assets/7662003/4da93df2-722e-4cd4-93f8-7d713b482ed3">

**Comment by mykaul** [comment]
Very similar to https://github.com/scylladb/scylla-monitoring/issues/2189
