### ISSUE TITLE
Add a graph for scylla_io_queue_flow_ratio

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#2306]
**System information**
- Scylla version (you are using): 2022.x+

**Describe the feature and the current behavior/state.**
In light of fixing https://github.com/scylladb/seastar/issues/1641 there was a new metric add: `scylla_io_queue_flow_ratio`.
Here is a patch with its description: https://github.com/scylladb/seastar/pull/1766/commits/dd6b20d484de54ea846dc036ebefd61acf29ec1d

Correlating with this value may be helpful when debugging I/O related performance issues.

cc @xemul

**Comment by amnonh** [comment]
it has both mountpoint and iogroup labels, do you want just everything on the same panel?
This is an example from a three nodes cluster
![image](https://github.com/scylladb/scylla-monitoring/assets/2118079/6c643a70-8363-4063-9ae2-4f33767cc22b)

What about aggregation? Naturally, the sum is meaningless, but do we want to have an option to aggregate?

**Comment by vladzcloudius** [comment]
> it has both mountpoint and iogroup labels, do you want just everything on the same panel? This is an example from a three nodes cluster ![image](https://private-user-images.githubusercontent.com/2118079/337728736-6c643a70-8363-4063-9ae2-4f33767cc22b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODAzNzQsIm5iZiI6MTcxNzc4MDA3NCwicGF0aCI6Ii8yMTE4MDc5LzMzNzcyODczNi02YzY0M2E3MC04MzYzLTQwNjMtOWFlMi00ZjMzNzY3Y2MyMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTcwNzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdjY2M3YmNiZjRiMTBmNGQ4MzQ2NzRhZmQ3MzUzZTA3MGE4YmEyNzk0N2EyYzc0NjhiZTAyNmUwOGQ0ZTk0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TnH-HjB3g6JDs8YZBJT89wCOrUc8PBP59KFLYyIRTZg)
> 
> What about aggregation? Naturally, the sum is meaningless, but do we want to have an option to aggregate?

AFAIU for this metric any aggregation is meaningless. 
@xemul, could you, please, confirm?

**Comment by amnonh** [comment]
@vladzcloudius Naturally, there is no point in summing over it, will Max? Min be helpful?  Do you want to filter out values that equal to 1?
I'm thinking about a cluster with a few hundred cores. How will you make sense of a graph like this?

**Comment by vladzcloudius** [comment]
> @vladzcloudius Naturally, there is no point in summing over it, will Max? Min be helpful? Do you want to filter out values that equal to 1? I'm thinking about a cluster with a few hundred cores. How will you make sense of a graph like this?

Good point. 
A special thing about this metric is that we want to see "outliers" - mins and maxes. 
However seeing a single maximum or minimum value is also not very useful.
Ideally we'd be able to toggle a sorting order: this way one case see first all maximum and then all minimum values.

**Comment by amnonh** [comment]
> 
> Good point. A special thing about this metric is that we want to see "outliers" - mins and maxes. However seeing a single maximum or minimum value is also not very useful. Ideally we'd be able to toggle a sorting order: this way one case see first all maximum and then all minimum values.

Sorry, still no easy way to play with the sort order in Grafana.

I want to include this panel in the next release, but I'm afraid as is, it will not be useful with so many lines in the graph. If we do not have a good idea, I will do it anyhow, but I hope we can come up with something better.

If you only care about the outliers I can show the average of everything as a base (maybe per  mount point and iogroup) and anything that is outside of let's say two standard deviations (plus some minimal threshold to remove noise)

![image](https://github.com/scylladb/scylla-monitoring/assets/2118079/58d0b8e9-6a6a-4ed1-b2c7-9d9aae7c64f8)

**Comment by amnonh** [comment]
@vladzcloudius take a look at my latest comments, if we can't find something better, I'll include a panel with all graphs in it, I'm afraid it will not be useful with clusters with many cores

**Comment by vladzcloudius** [comment]
We probably should think about it a bit more - having a graph for all shards will be quote a hassle indeed.
Probably we should show some statistical function expressing a level of noise in this metric, e.g. the SD itself.

**Comment by amnonh** [comment]
I think we should filter all values that are close to 1 (i.e., close to 100%). I'm not sure what the threshold should be but, no point in scrolling throw few hundreds values all of them 1.
