### ISSUE TITLE
Measure performance overhead

### ISSUE THREAD

**Issue by GeoffMontee** [scylladb/scylla-monitoring#2308]
A customer wants to know how much performance overhead is added to Scylla caused by exporting prometheus metrics. Have we measured that?

If not, would you expect the impact to be minimal, significant, or somewhere in between?

**Comment by mykaul** [comment]
> A customer wants to know how much performance overhead is added to Scylla caused by exporting prometheus metrics. Have we measured that?
> 
> If not, would you expect the impact to be minimal, significant, or somewhere in between?

Hi @GeoffMontee . This is a public repository, not suitable for enterprise customer issues.
(Also, questions - please just ask us on slack/email/etc. If needed, we'll ask you to open a GH issue).
