### ISSUE TITLE
docs: Issue on page Troubleshoot Scylla Monitoring Stack

### ISSUE THREAD

**Issue by faizalrf** [scylladb/scylla-monitoring#2316]
I would like to report an issue on page https://monitoring.docs.scylladb.com/branch-4.7/troubleshooting/monitor-troubleshoot

### Problem
The node tool exporter upgrade link isn't working. 
###  Suggest a fix

**Comment by mykaul** [comment]
Are you referring to the link https://monitoring.docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-2.3-to-3.0/ ? It is indeed no working and should be removed. Very outdated.

**Comment by faizalrf** [comment]
Yup, that’s the one

Faisal Saeed,
Principal Solution Architect @ MariaDB
https://www.mariadb.com
Cell: +65 9386 5771
