### ISSUE TITLE
CQL Batches by Instance is in LWT Section

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#2318]
Scylla Monitoring version - 4.7.2
Scylla Enterprise 2024.1

Why is the CQL Batches under the LWT section?
![image](https://github.com/scylladb/scylla-monitoring/assets/170200/f48dffac-0ea5-4be9-9090-6aaa53f34d57)

**Comment by tzach** [comment]
Same question for CQL Insert and CQL Deletes - are they specific to LWT?

**Comment by amnonh** [comment]
Those are cql commands that use LWT (i.e., conditional command)
PS, please add a dashboard when opening an issue
