### ISSUE TITLE
[4.7] getting screenshot with height=-1 is broken

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-monitoring#2324]
Recently we switched to monitor 4.7

And we noticed our screenshots are not complete, and the overview dashboard screenshot is completely unusable 

After few trails seems like the automatic height feature isn't working, and if you specify height, things are working, and looking better.

I've trying moving to newer versions of the renderer, and also to exact version use and working in monitor 4.6, that didn't help.

So my assumption it's cause by incompatibility with grafana version itself, but couldn't pinpoint that, or find references to issues about. (I e. I don't have enough info to raise it with grafana)

**Comment by amnonh** [comment]
Did you get a partial screenshot or none at all?
I'll release 4.8 with the latest releases of grafana and grafana renderer, it seems to work

**Comment by fruch** [comment]
here's an example of how the overview looks:

![grafana-screenshot-overview-20240615_040552-longevity-100gb-4h-master-monitor-node-892914d3-1](https://github.com/scylladb/scylla-monitoring/assets/340979/641aa47f-0031-4d6d-a8ea-fee5ce3d3923)

and in our dashboard, it didn't had all of it, as expected:

![grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20240615_040659-longevity-100gb-4h-master-monitor-node-892914d3-1](https://github.com/scylladb/scylla-monitoring/assets/340979/b4f3bbc6-de5c-4acd-83e5-694795656598)

I can try 4.8 branch when it's ready, and see if it improved.

meanwhile I need to specify the exact resolution of the output

**Comment by mykaul** [comment]
The 'screenshot' button seem to be broken as well - it downloads a file but then Chrome complains that nothing was downloaded... I don't know if it's the same issue as this one or a different issue.

**Comment by fruch** [comment]
> The 'screenshot' button seem to be broken as well - it downloads a file but then Chrome complains that nothing was downloaded... I don't know if it's the same issue as this one or a different issue.

It might, if you really see it's broken on 4.7 

You can take the url, and replace the height=-1, with some actual size, and see if it's working or not

For me it was generating images all the time, but not completely usable or just part of the dashboard

**Comment by amnonh** [comment]
Pending on https://github.com/grafana/grafana-image-renderer/issues/538
