### ISSUE TITLE
Add panels for network compression

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#2325]
Scylla Enterprise has metrics for network compression, we should show that

**Comment by amnonh** [comment]
@michoecho I'm not expecting you to add anything, I need an example of those metrics

**Comment by michoecho** [comment]
> @michoecho I'm not expecting you to add anything, I need an example of those metrics

You can use https://argus.scylladb.com/test/560830b0-a699-4028-8278-7d88d50a2693/runs?additionalRuns[]=5f1c8ee7-7df1-4969-b2aa-eecee660312f as an example workload run with compression metrics scraped.

Compression metric names start with `scylla_rpc_compression_`.

**Comment by tzach** [comment]
@zseta FYI

**Comment by mykaul** [comment]
The panels should show compression ratio (per my discussion with @amnonh )

**Comment by amnonh** [comment]
Fixed by #2369
