### ISSUE TITLE
Move all node_exporter metrics to a new dashboard

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#233]
node_exporter metrics are per server, not per shard, so they do not fit in the current scylla-dash-per-server.master.json (which can become scylla-dash-per-server-per-shard.master.json after this change)

**Comment by tzach** [comment]
@glommer this also means breaking the IO dashboard, keeping the Scylla metrics, and moving the node metric to a new dashboard.

Among other, it will simplify the template parameters (appears as drop-down menus at the top of the page):
monitor_disk and network only on the node dashboard
by server and by shard only on the scylla dashboard

**Comment by glommer** [comment]
It doesn't have to mean breaking the dashboard. We already have a space for networking stuff, from the node.

But of course I am not oppose it - > I support it.
