### ISSUE TITLE
[4.7] Latency Read operations by shard also shows by instance ops

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-monitoring#2353]
*Installation details*
Panel Name: Latency / Reads by shard
Dashboard Name: Detailed
Scylla-Monitoring Version: 4.7.2
Scylla-Version: 2024.1.4

Under Detailed/Latency sections, Read operations panels show both shard and instance ops when `By: Shard` is selected. Write ops, on the other hand, behaves as expected and only shows the correct view as selected on `By` selector.

![image](https://github.com/scylladb/scylla-monitoring/assets/1693866/412b77e7-afa6-4264-b980-9f035dd1527c)

![image](https://github.com/scylladb/scylla-monitoring/assets/1693866/e4d21244-7a97-4a6c-8f07-3957d0159843)

**Comment by mykaul** [comment]
Isn't it a sum of all shards? Maybe not desirable, but not wrong either?

**Comment by amnonh** [comment]
I'll take a look. It's probably a side product of the different ways shard metrics are calculated
