### ISSUE TITLE
Show all CQL Consistency Levels

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-monitoring#2361]
**System information**
- Scylla version: any

**Describe the feature and the current behavior/state.**
Currently we use metric `scylla_query_processor_queries` to display `ONE` and `QUORUM` CLs under Scylla CQL dashboard. It contains metrics about all CLs, so it should be used as a separate panel to demonstrate all CLs across the cluster. This is very useful to see the ratio of CLs.

**Who will benefit with this feature?**
Anyone that uses CQL.

**Comment by amnonh** [comment]
Can you please include a scenario of who will be using this and how?

**Comment by hopugop** [comment]
Whenever one needs to identify the ratio of CLs used on a cluster, per granularity offered on Monitoring. 
Apart from cross-DC information which is already reported on the ONE/QUORUM panels, we should also be able to look at all CLs.

Is my workload doing LOCAL_ONE or LOCAL_QUORUM? Is LOCAL_SERIAL being used at all? etc...

**Comment by amnonh** [comment]
@hopugop This is the wrong repository for ScyllaDB functionality; new metrics are under ScyllaDB.
Regardless, this kind of extra cardinality is an overhead to the system, and I would consider before adding it.

**Comment by hopugop** [comment]
@amnonh metrics are already generated and scraped. We even use some of them on the cross-DC panels (for non-LOCAL CLs). My ask is to just leverage these metrics to demonstrate what are the ratios of all CLs, not only on the cross-DC context.

**Comment by amnonh** [comment]
@hopugop so are you talking only about scylla_query_processor_queries?

**Comment by hopugop** [comment]
Yes
