### ISSUE TITLE
Alternator OPs are not representative of real ops - in case of BatchGetItem and similar batch ops

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2374]
A customer is running BatchGetItem with 100 items in each batch. It looks as if they have less <1K OPs of batch items, but the overall result is 100K OPs... The visualization is correct per OPs, but is misleading somewhat in terms of how many OPs are actually being run against the cluster. Did not look at the code of where we count such OPs, but I'd argue we should count the overall OPs, not 1 per batch.
@tzach , @nyh , @nuivall - thoughts?

**Comment by mykaul** [comment]
Perhaps instead of counting it here:
https://github.com/scylladb/scylladb/blob/849856b96407f3a79811c6aa4be98a38b6b2df8f/alternator/executor.cc#L3332
we should look at requests.size around https://github.com/scylladb/scylladb/blob/849856b96407f3a79811c6aa4be98a38b6b2df8f/alternator/executor.cc#L3386

**Comment by nuivall** [comment]
New metrics were added in https://github.com/scylladb/scylladb/commit/390e01673be1f365e42f826490ed95aeede1a259

**Comment by amnonh** [comment]
I'm going to add a batch size with the batch count

**Comment by amnonh** [comment]
Closed as completed by c418823ebb3333a470d1eacc584582be9ca8cac9
