### ISSUE TITLE
AWS AMIs: we should share them exactly like scylla images

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-monitoring#2375]
Images should be shared exactly like scylla images
see:
https://github.com/scylladb/scylla-machine-image/commit/f6400eccef465a932daee593cbd2c1d2df130970

for us to be able to consume them

**Comment by Annamikhlin** [comment]
I see that the scylladb-monitor AMIs shared via **organization path** 
```
arn:aws:organizations::978072043225:organization/o-o561yy1rs6
arn:aws:organizations::978072043225:ou/o-o561yy1rs6/ou-nfe9-40dtbmzs
arn:aws:organizations::978072043225:ou/o-o561yy1rs6/ou-nfe9-pcouwaqn
```
first one main RND account, not sure what are the others.

and addition, is also shared with 2 account IDs:
```
400694452550
871738363549
```
example from `scylladb-monitor-4-8-0-2024-07-11t06-07-22z` AMI
![image](https://github.com/user-attachments/assets/ad43d00d-7d64-44c1-bc0f-21785a98f720)


In addition, the snapshot shared as well with 2 accounts:
```
AWS account ID
400694452550
871738363549
```

@fruch @amnonh - are all of these needed?

**Comment by Annamikhlin** [comment]
Following the work done with @karol-kokoszka, the account of scylla cloud LAB (734708892259) was added as well to snapshot shared.
The full snapshot shared account list for now is:
```
AWS account ID
400694452550
797456418907  //awsAccountId - required by SCT
871738363549
734708892259  //Cloud Lab
```
It was confirmed by @karol-kokoszka that it worked for him.

Need to check if other accounts are still relevant

**Comment by fruch** [comment]
> Following the work done with @karol-kokoszka, the account of scylla cloud LAB (734708892259) was added as well to snapshot shared. The full snapshot shared account list for now is:
> 
> ```
> AWS account ID
> 400694452550
> 797456418907
> 871738363549
> ```
> 
> It was confirmed by @karol-kokoszka that it worked for him.
> 
> Need to check if other accounts are still relevant

797456418907 is needed by SCT

**Comment by mykaul** [comment]
I'm not sure why we are sharing account IDs publically. They are not secret, but there's no reason to share them broadly.

**Comment by karol-kokoszka** [comment]
I think it’s enough to share it with LAB. We are making the copy of it
later on LAB, sharing with stage and prod + copy to supported regions.

W dniu pon., 26.08.2024 o 20:17 Yaniv Kaul ***@***.***>
napisał(a):
