### ISSUE TITLE
OS metrics shows incorrect disk utilization information

### ISSUE THREAD

**Issue by paszkow** [scylladb/scylla-monitoring#2376]
During the investigation of the storage utilization metrics, I noticed the information is differently reported depending how I enter the OS metrics dashborad. Take for instance the hydra command: `hydra investigate show-monitor 7a521de4-c838-4614-8dc4-2a72efe75c70` 

Opening OS metrics dashbord and selecting an absolute time range to `2024-08-14 08:36:39 - 2024-08-14 09:46:53` I get the following graphs (note the flat lines in `used bytes per instance` and the incorrect unit MiB):
![Screenshot from 2024-08-14 15-27-52](https://github.com/user-attachments/assets/c8914d96-474e-4daf-8aab-07f5f742a1c0)

However, when I enter the OS metrics dashbord and instead of selecting time range I append the timestamps `&from=1723624599000&to=1723628793000` directly to the url, then I get the correct statistics:
![Screenshot from 2024-08-14 15-28-18](https://github.com/user-attachments/assets/e564dac2-c4e3-4627-94a4-701a8113865b)

In both cases, the urls are exactly the same but the results are different.

scylla-version=master
monitoring-version=4.7.2
dashboard=OS-master

**Comment by amnonh** [comment]
I've opened https://github.com/grafana/grafana/issues/93471

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-monitoring/pull/2422/commits/7fbafc004b5e5cd43c8a3a3226a5675bbdabf825
