### ISSUE TITLE
Is 4.8.0 released?

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylla-monitoring#2377]
I saw in the Scylla 6.1.0 release notes it says Monitoring 4.8.0 is released, but I don't see a release for it here on github, so wondering what the status is, thanks!

**Comment by amnonh** [comment]
[Release 4.8.0](https://github.com/scylladb/scylla-monitoring/releases/tag/4.8.0) is in pre-release and will be officially released in the next few days
