### ISSUE TITLE
The latencies Legend format confusing

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#2383]
Panel Name: P95 P99 latencies
Dashboard Name: detailed
Scylla-Monitoring Version: 4.8

Following the change of supporting multiple function for latencies, the graph tooltip (legend format) looks confusing

**Comment by mykaul** [comment]
Same also here?  (not latencies)
![image](https://github.com/user-attachments/assets/7305f24b-2f40-498d-80f8-d108f826dd22)
