### ISSUE TITLE
Using stack graph for active read is confusing

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#2389]
The active reads panel uses stack graph, this is confusing:
![image](https://github.com/user-attachments/assets/98fe097c-b503-434a-8fc6-9c0c43b46a01)

There are two alternatives, switch to bars:
![image](https://github.com/user-attachments/assets/98fab549-9f4d-42a9-8d5a-581636b89c8c)

Or drop the stack graph:
![image](https://github.com/user-attachments/assets/31b9f255-c37f-47c8-b86e-3aba2973839e)

**Comment by amnonh** [comment]
@vladzcloudius I'll appreciate your opinion

**Comment by vladzcloudius** [comment]
> @vladzcloudius I'll appreciate your opinion

I vote for dropping the stack - the last option.

**Comment by amnonh** [comment]
@vladzcloudius thank you!
