### ISSUE TITLE
Unknown Alternator OP - BatchGetItemSize?

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-monitoring#2393]
*Installation details*
Panel Name: Operations/S
Dashboard Name: Alternator
Scylla-Monitoring Version: 4.8.0
Scylla-Version: 2024.1.9

![image](https://github.com/user-attachments/assets/7faf46ba-7239-4b5d-b3a7-abd19414c7aa)

There's no such OP, I believe?

**Comment by mykaul** [comment]
I *think* it's how many GetItems we have in total, if we count what we have within the various BatchGetItem?

**Comment by nyh** [comment]
It was introduced in Scylla commit 8bad4b44f87912ffdb9d0b66f463f8b4f6939d2b last month (@amnonh wrote it in https://github.com/scylladb/scylladb/pull/20190, @avikivity merged, I was on vacation.).

I looked at the code and indeed as you guessed, it counts the number of items in BatchGetItem (it's not the "size" of items, it's the number of items). I don't know why it was introduced like that or what was the motivation for these "Size" variables. I think it's confusing that this is NOT the name of the op yet pretends to be one. I think its naming was a mistake (both the fact it pretends to be an op, and the using the ambiguous word "Size"). @amnonh please reconsider.

**Comment by amnonh** [comment]
I'm taking care of it on the dashboard side; it will be solved in the coming 4.8.1 release

**Comment by nyh** [comment]
I don't understand why it's related to the "dashboard side", or what the solution actually is :-(
I opened an issue https://github.com/scylladb/scylladb/issues/20571 for the Scylla side, where the problem really lies...

**Comment by amnonh** [comment]
Now the dashboard shows the wrong graph, so I'll make sure it shows the right ones

**Comment by nyh** [comment]
@amnonh But if we consider "BatchGetItemSize" an "operation", it should be on the operations dashoard. If it's not an operation, it shouldn't be on this dashboard (but it will be in a different dashboard, rightt?) but it also shouldn't be named `alternator_operation[BatchGetItemSize]`. I wonder if we could leave it in alternator_operation but just replace the word "size" by something clearer. But I have the feeling that alternator_operation[] should be reserved for real operation counts, and we could have in parallel other counters for different metrics for these operations (total number of items in a batch, total size in bytes of items, and so on).

**Comment by amnonh** [comment]
Closed as completed https://github.com/scylladb/scylladb/commit/6496eab5ee8bed821531b42982739015ef4b6c30
