### ISSUE TITLE
Materialized views: View local update description

### ISSUE THREAD

**Issue by vreniers** [scylladb/scylla-monitoring#2403]
*Installation details*
Panel Name: View Local Update
Dashboard Name: Detailed
Scylla-Monitoring Version: 4.7.2
Scylla-Version: 2024.1.4

While investigating a certain dashboard, I was under the impression that "**view local update**" actually reflected all updates that are happening on a given replica for that materialized view. Its description mentions for example: 

**View local update - description:** "Number of view update locally"

However, it seems this is not true, and that this is a coordinator-side metric. It does not encompass all updates that are happening locally on that replica with regards to a materialized view.

For example, one could assume that all remote view updates that are being sent out (e.g. 200 remote view updates), would show many local view updates (across other shards, of which the sum could amount to 200) - but that is not what this graph shows. It only seems to show the portion of the updates that remain on the coordinator - and that update a view locally there.

I suggest to perhaps mention or clarify in the description that this is a coordinator-side metric.

**Comment by amnonh** [comment]
The relevant Scylla code is https://github.com/scylladb/scylladb/blob/c17d353718464bae230331d7e77d4901281fc017/replica/database.cc#L618

I would like someone from MV to have a look and give their input

**Comment by amnonh** [comment]
@mykaul can we have someone from MV comment on the issue?

**Comment by mykaul** [comment]
> [@mykaul](https://github.com/mykaul) can we have someone from MV comment on the issue?

@piodul - please assign.

**Comment by piodul** [comment]
I suggest changing the panels' names and descriptions in the following way:

```
Local view updates
Counts the number of view updates generated and then applied locally on the same node.

Remote view updates
Counts the number of view updates generated and then sent to be applied on a remote replica.
```

@vreniers does this sound good?

**Comment by vreniers** [comment]
```
Local view updates
Counts the number of view updates generated locally and applied on the same node.
```
A small change perhaps to "local view updates" description. What do you think @piodul? Otherwise, looks good.

**Comment by piodul** [comment]
> What do you think [@piodul](https://github.com/piodul)? Otherwise, looks good.

@vreniers looks good to me after your change.
