### ISSUE TITLE
Set name for each row and panel

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#243]
The names are invisible for users, but make it easier to maintain and update the dashboard JSON file

**Comment by amnonh** [comment]
We can do it part of the migration to grafana 4

**Comment by tzach** [comment]
Do you mean Grafana 5?
Current Grafana release is 4.6.3
https://github.com/scylladb/scylla-grafana-monitoring/blob/master/start-grafana.sh#L10

**Comment by amnonh** [comment]
yes, I meant grafana 5

**Comment by amnonh** [comment]
@tzach grafana 5 no longer support rows, we can probably close this

**Comment by amnonh** [comment]
Closing it based on all panels have descriptions, rows are no longer supported
