### ISSUE TITLE
Add Code Formatters

### ISSUE THREAD

**Issue by f9n** [scylladb/scylla-monitoring#2430]
Can we add code formatters for the project?

## Formatters 
- [Ruff](https://docs.astral.sh/ruff/) for Python scripts
- [Shfmt](https://github.com/mvdan/sh) for Bash scripts

## Which way should we follow?

Github Actions can be added for checking code quality. Also tools like Makefile or pre-commit can be used by developers to make this process work or we can describe this process in DEVELOPMENT.md.

**Comment by mykaul** [comment]
@f9n - there's not a lot of either shell or Python code in this project, but a PR to add (and perhaps fix first of all) the formatting, would be welcome. Let's see first what the gaps are.
