### ISSUE TITLE
Unify instance name for node_explorer and Scylla metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#244]
Currently, Scylla metrics looks like:
```
scylla_reactor_utilization{instance="ip-172-31-43-23",job="scylla",shard="2",type="gauge"}
````

node_exporter looks like:
```
node_cpu{cpu="cpu2",instance="54.202.75.234:9100",job="node_exporter",mode="nice"}
```

in particular `instance` is `ip-172-31-43-23` for the first and `54.202.75.234:9100` for the second.
this makes it hard to aggregate one server metrics, from both Scylla and node_exporter to one dashboard

**Comment by tzach** [comment]
The problem is node_exporter does not use hostname for the instance label, as Scylla do.

**Comment by tzach** [comment]
Its possible to update extract the hostname from `node_uname_info`, and to use group_left and label_replace to set this host name to the instance lable.

For example:
replace
```
irate(node_network_receive_packets{device="$monitor_network_interface"}[30s])
```

with
```
label_replace(irate(node_network_receive_packets{device="$monitor_network_interface"}[30s]) * on(instance)  group_left(nodename) node_uname_info,  "instance", "$0", "nodename", ".*" ) 
```

will give the same chart, with hostname value for the `instance` lable

**Comment by tzach** [comment]
The following is an example of using the instance temlpate, used to select scylla node, for a node_exporter varible 
```
irate(node_network_receive_packets{device="$monitor_network_interface"}[30s]) * on(instance)  group_left(nodename) node_uname_info{nodename="[[instance]]"}
```

**Comment by tzach** [comment]
@amnonh can you take a look?

**Comment by amnonh** [comment]
I've played with it a bit, it seems a much better approach than the one we are currently using, it's not bulletproof. 
Currently, scylla can set its own instance label, so there's no promise the values will be the hostname.
because node_exporter guys insist on not allowing to set a label, we are left with your approach, or add static configuration to the prometheus  file.
I think I'll go with what you suggest but title it: use hostname instead of ip address so it will reflect what is going on

**Comment by amnonh** [comment]
When I check the dashboard, it seems that none of the node metrics (disk, io, etc') is set per server, and that the alerts in the alert manager are per instance

**Comment by tzach** [comment]
> When I check the dashboard, it seems that none of the node metrics (disk, io, etc') is set per server, and that the alerts in the alert manager are per instance

This is what we need to fix...
We can also fix it from node_exporter side, changing the setup to match what we need

**Comment by amnonh** [comment]
@tzach I think another thought need to be given to the issue.
Right now, all the node related metrics are basically make no sense.
For example the disk name, or network card name could be identical between nodes, or could be different.
Maybe we should split between compare of total nodes and the per server would force the users to pick a node.

The pie chart of the disk is misleading (and assume the scylla partition)

**Comment by tzach** [comment]
> Right now, all the node related metrics are basically make no sense.
> For example the disk name, or network card name could be identical between nodes, or could be different.

Possible, but not likely. Most clusters are running with symmetric nodes. 

> Maybe we should split between compare of total nodes and the per server would force the users to pick a node.

Not sure what you mean.
We can extract all OS level metric to a different dashboard, with a different drop down selection.
The current state of a mix dashboard, with drop down, apply to a subset of panels is confusing at best


> 
> The pie chart of the disk is misleading (and assume the scylla partition)

#293

**Comment by slivne** [comment]
@amnonh - please provide a reference to why prometheus are not willing todo this - I want to resolve this - you mentioned that they are suggesting a solution - please provide the solution they are providing as well

**Comment by amnonh** [comment]
I think it can be closed by:
d6d8bda7dbb62f0d1a40496f42d635c77b6d3aae

**Comment by tzach** [comment]
> I think it can be closed by:
> d6d8bda

@amnonh look like irrelevant commit

**Comment by amnonh** [comment]
Look at: prometheus/prometheus.yml.template
prometheus now removes the port from the instance and change the honor label to false.
