### ISSUE TITLE
Split the per serer dashboard by subsystem

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#245]
This issue is a result of discussions on #22 #242 #234 
scylla-per-server-metrics-master has become too big and hard to use.
The following will be metrics removed, duplicate the cluster view:
* total and unreachable nodes
* total storage

The rest will be split into the following dashboard
### Operations
  - Requests Served
  - All of the Proxy metrics: read, write, timeouts and error
  - CQL
  - All of the replica metrics: read/write etc (should we move this to storage?)  
  - compaction
### Memory
  - cache
  - LSA
  - OS level memory
### Storage
  - Scylla Disk metrics
  - Disk activity (currently in the IO dashboard)
  - IO Qouue (currently in the IO dashboard)
  - OS level disk metrics (free space)
### Networking
  - CQL connection #241 
  - OS level network (NIC) Rx, Tx
  - Future: streaming metrics

Each of the dashboards above will have the same templating as the current per server dashboard: per cluster, per node and per shard.

Once complete, we can have a table of all nodes, with links to each node dashboard in the cluster dashboard.

**Comment by tzach** [comment]
@glommer @amnonh @eyalgutkind please comment

**Comment by tzach** [comment]
@glommer @amnonh @eyalgutkind any comment?

**Comment by tzach** [comment]
@glommer @amnonh @eyalgutkind  last attempt for a feedback before I send a PR ;)

**Comment by glommer** [comment]
I agree with the proposed split. I need to see the actual graphs that land into each to comment if they are complete or not.

**Comment by tzach** [comment]
One problem with this approach, is you lose the time range when moving from a dashboard to the other

**Comment by glommer** [comment]
I still think that the lack of automation in generating these dashboards is
one of our biggest problems.

If we *did* have automation, it would be easier to generate all of those
dashboards plus one with all of them together in a single screen for those
who prefer it and / or want to correlate them.
It would also make it easier to take screenshots, since we now have to take
screenshot of just one page.

**Comment by amnonh** [comment]
@tzach is this still relevant?
