### ISSUE TITLE
Easy way to capture the entire dashboard, or even all the dashboards, in one click

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#248]

**Comment by tzach** [comment]
Suggested by @glommer

**Comment by amnonh** [comment]
Please explain what you mean

**Comment by tzach** [comment]
one button to capture and share the entire dashboard

**Comment by amnonh** [comment]
@tzach The description is still unclear, what do you want to capture? the image the data?
do you want to share the dashboards to an external service?

See: http://docs.grafana.org/reference/sharing/

**Comment by glommer** [comment]
The image of the data.

I currently use Fireshot browser plugin for that, but it would be nice if we could embed something into our monitor

**Comment by tzach** [comment]
Which plugin?
Does it take a screen capture or more than that?

**Comment by amnonh** [comment]
Have you tried the shard button on the top of the dashboard?
![image](https://user-images.githubusercontent.com/2118079/44727063-d1431c80-aae1-11e8-86b8-0d628ae32f9a.png)

**Comment by glommer** [comment]
I am assuming you mean "share"

![f](https://user-images.githubusercontent.com/331197/44740357-44d83000-aac8-11e8-8599-988da1fb1246.png)

which of those three would generate an image file ?

**Comment by amnonh** [comment]
share of course (too much time spent today on working on the dashboard by shard).

unfortunately, I couldn't find an option to create an image from the entire dashboard, it is possible to export the dashboard with the data.

BTW saving a panel as an image is available per panel (on a panel choose: share/link/Direct link rendered image)

But it does not cover what you want
