### ISSUE TITLE
Compact representation of dashboard JSON

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#252]
Current JSON format is verbose and hard to maintain
It would be much better if we can have a more compact language, including only the non-redundant parts.
Maybe with a templating tool like [mustache](https://mustache.github.io/ )

**Comment by tzach** [comment]
torke from the Grafana community form direct me to 
https://github.com/grafana/grafonnet-lib

**Comment by tzach** [comment]
@amnonh are you looking into that?
there are many other issues waiting, but I planned to keep them till after this refactoring

**Comment by amnonh** [comment]
I started to, grafonnet is not applicable, in linux it needs to be built from source. I'm checking other ways

**Comment by amnonh** [comment]
I have a suggestion for a new format:
I'll add a  key to the json objects "class" when the key is present it will complete the items from a dictionary:
{
	"dashboard": {
		"class": "dashboard",
		"title": "Scylla Per-Server Disk I/O 1.5",
		"tags": [
			"1.5"
		],
		"rows": [
			{
				"class": "row",
				"panels": [
					{
						"content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">",
						"class": "text_panel"
					}
				],
				"title": "Head row"
			},
			{
				"class": "row",
				"panels": [
					{
						"rangeMaps": [
							{
								"from": "null",
								"text": "N/A",
								"to": "null"
							}
						],
						"span": 1,
						"targets": [
							{
								"expr": "count(up{job=\"scylla\"})",
								"intervalFactor": 1,
								"legendFormat": "",
								"refId": "A",
								"step": 240
							}
						],
						"title": "Total Nodes",
						"class": "graph_panel"
					}
				]
			}
		]
	}
}

**Comment by tzach** [comment]
Look reasonable, but its hard to say from such small example
Is there a way to generate a compact view (with classes) from the current dashboard?

**Comment by amnonh** [comment]
@tzach I think we can close this one
