### ISSUE TITLE
Basic Alerts with Prometheus

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#257]
Add alert for non-reachable nodes via 
https://prometheus.io/docs/practices/alerting/
and 
http://docs.grafana.org/alerting/rules/
This is the first step toward more sophisticated alerts for Scylla.

**Comment by tzach** [comment]
@amnonh can you take a look, please?

**Comment by amnonh** [comment]
See: http://docs.grafana.org/alerting/rules/#rule-config
Currently only the graph panel supports alert rules but this will be added to the Singlestat and Table panels as well in a future release.

**Comment by tzach** [comment]
@amnonh take a look at Prometheus alerting

**Comment by amnonh** [comment]
I think we can close this one
