### ISSUE TITLE
Attach external disk to prometheus

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#26]
Docker default disk does not have much space.
It is better to expose a larger disk on the host for metric data.

**Comment by slivne** [comment]
this is what I do to start the prometheus using an external directory

```
sudo docker run -v /home/shlomi/Downloads/asias-dev-pdata-grow/data:/prometheus -v /home/shlomi/scylla-grafana-monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z -p 9090:9090 --name aprom prom/prometheus:v1.0.0  
```

**Comment by amnonh** [comment]
The code is already there, I'll update the README
