### ISSUE TITLE
RFC: monitor with user(application)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-monitoring#262]
Scylla users would use different account for different application, can we monitor the cluster by login user?

eg:
- total users, login users
- served request from user1 / user2
- load from user1 / user2

@tzach @slivne

**Comment by tzach** [comment]
@amoskong are you referring to Scylla users or Grafana users (or both?)

**Comment by amoskong** [comment]
scylla users.

**Comment by tzach** [comment]
I do not think we have per users metrics in scylla, so there is no way to graph it

**Comment by amnonh** [comment]
@amoskong @tzach can we close this?

**Comment by amoskong** [comment]
I'm fine to close it.
