### ISSUE TITLE
Add Apache Licence to the project

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#263]

**Comment by amnonh** [comment]
@tzach  Is this correct? why apache?

**Comment by amnonh** [comment]
@tzach ?

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
It is correct, and suggest by @dorlaor

**Comment by amnonh** [comment]
@tzach do you have an example or even better a PR for such a license file?
