### ISSUE TITLE
Grafana containers add the default port to the container name

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#265]
Following commit 1e48532e4586bd46db6126d2b037eae7ac3b0569 the logic in start-grafana.sh was modified, so now the container name always contain the port number.

This also breaks the killall logic

**Comment by tzach** [comment]
> This also breaks the killall logic

what else?

**Comment by amnonh** [comment]
On Mon, Jan 8, 2018 at 11:16 AM, Tzach Livyatan <notifications@github.com>
wrote:

> This also breaks the killall logic
>
> what else?
>
it has the wrong name to begin with

**Comment by tzach** [comment]
> it has the wrong name to begin with

Why is it wrong? why does the name relevant? please explain the problem
