### ISSUE TITLE
metrics for disk reads / writes are not very useful

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#269]
Aside from the issue of the selector not working with them, the legend for those metrics say just things like "Disk Writes Bps per Server".

That isn't very useful, because not all lines will have the same name.

Replacing it with something like `Disk Writes Bps per Server {{instance}}` makes it better, because now it at least show us which instance we are looking at when hovering the mouse over.

**Comment by tzach** [comment]
@glommer is the problem with the metric or the chart title?

**Comment by glommer** [comment]
Chart. Just the legend needs to change

**Comment by amnonh** [comment]
Also related to:
https://github.com/scylladb/scylla-grafana-monitoring/issues/187
