### ISSUE TITLE
Remove sudo usage

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-monitoring#270]
Each docker invocation is preceded by `sudo` https://github.com/scylladb/scylla-grafana-monitoring/search?utf8=%E2%9C%93&q=sudo&type=

To use docker user should be docker group, `sudo` can be removed.

**Comment by EmMerry** [comment]
Also the base image for the containers is Debian and sudo is useless. If you log in via root, and no need of sudo and if you login through normal user, sudo is not found.
