### ISSUE TITLE
Grafana Alerting

### ISSUE THREAD

**Issue by EmMerry** [scylladb/scylla-monitoring#271]
I am unable to setup alerts and notifications in Grafana dashboard. This is the error i get when i create a notification and alerting channel.

`Failed to send alert notifications.`

Any guide on this.

**Comment by tzach** [comment]
@amnonh ?

**Comment by EmMerry** [comment]
I solved it with setting the environment variables while creating the docker container.

**Comment by tzach** [comment]
@EmMerry can you please share your solution so others can use it if they have the same issue?

**Comment by EmMerry** [comment]
Yes sure. Here are the changed lines in **start-grafana.sh** line 75-83.

`sudo docker create $LOCAL -i -p $GRAFANA_PORT:3000 \`
`-e "GF_AUTH_BASIC_ENABLED=$GRAFANA_AUTH" \`
`-e "GF_AUTH_ANONYMOUS_ENABLED=$GRAFANA_AUTH_ANONYMOUS" \`
`-e "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin" \`
`-e "GF_INSTALL_PLUGINS=grafana-piechart-panel" \`
`-e "GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD" \`
`-e "GF_SMTP_ENABLED=true" \`
`-e "GF_SMTP_HOST=email.server.com:465" \`
`-e "GF_SMTP_USER=abc.def@emailserver.com" \`
`-e "GF_SMTP_PASSWORD=secret" \`
`-e "GF_SMTP_FROM_ADDRESS=test123@emailserver.com" \`
`$GRAFANA_ENV_COMMAND \`
`"${proxy_args[@]}" \`
`--name $GRAFANA_NAME grafana/grafana:$GRAFANA_VERSION`
`sudo docker start $GRAFANA_NAME`

**Comment by amnonh** [comment]
I have opened an issue to add that to grafana:
https://github.com/scylladb/scylla-grafana-monitoring/issues/274

**Comment by EmMerry** [comment]
I will push the code, you can review it and merge that to master.
