### ISSUE TITLE
Replace bash scripts with docker-compose

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-monitoring#273]
The idea is to remove all the bash files and replace them by a docker compose file. The variables should be put to `.env` file (auto read by docker-compose) other things can be directly rewritten do docker-compose file.

Benefits:

* more standard, easier to read, port or include in an containerized environment
* single control point (docker-compose)
* more control
* easier to use

**Comment by tzach** [comment]
Make sense @rusher81572 already made a similar effort in scylla-code-example
Even with a small bash wrapper, it should still simplify the stack.
Who volunteers to send a PR?
