### ISSUE TITLE
Add SMTP information to grafana start to support grafana alerting

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#274]
Based on #271 

Need to have an option to pass SMTP credentials to grafana on start

**Comment by tzach** [comment]
@amnonh it will be easier to pass *any* parameter to the Grafana container
We already have a similar option with `-b Prometheus command line options`

**Comment by EmMerry** [comment]
I created the grafana container with some SMTP related parameters. It would also be simple to add the variables to the **start-grafana.sh** code. In fact, i can push the code if you want.

**Comment by EmMerry** [comment]
I passed the SMTP related parameters with the **start-all.sh** script and it went well. But its not practical to pass the email related options on the command line. May be we can create a config file to load these variables.

**Comment by tzach** [comment]
Thanks @EmMerry 
We can now propagate parameters to the docker instances. If you can use it instead of extending (the already too complex) start_all, it will be useful. We can add it as an example.

**Comment by amnonh** [comment]
@tzach i think we can close this, as you mentioned we have a general way of passing command lines to the images.
ae8e2260be0b0336de43bb93a27a5845df05016d
