### ISSUE TITLE
Do not use sudo in bash scripts

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#288]
PR #270 remove the use of sudo in the scripts, PR #267 add it back in ./start-alertmanager.sh

**Comment by tzach** [comment]
@amnonh please fix

**Comment by amnonh** [comment]
@tzach you can close this

**Comment by tzach** [comment]
@amnonh please add commit reference

**Comment by amnonh** [comment]
ae8e2260be0b0336de43bb93a27a5845df05016d
