### ISSUE TITLE
Dashboard disk and network interface default are not always right 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#29]
Current dashboard assumes eth0 as network interface and md0 as drive.
Clearly this is not alway the right choice, and we need an easy way to set it up, maybe in grafana.yml.

**Comment by tgrabiec** [comment]
We could at least use template variables in dashboard definition so that disk names can be easily changed by editing one variable.

**Comment by tzach** [comment]
fix by #84
