### ISSUE TITLE
Dashboard should includes CQL reads and writes

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#30]
Extracted from metrics:
collectd_database_total_operations.total_writes
collectd_database_total_operations.total_reads

**Comment by amnonh** [comment]
We have CQL metrics: 
seastar_cql{instance="localhost",job="prometheus",metric="batches",shard="0",type="total_operations"}	0
seastar_cql{instance="localhost",job="prometheus",metric="inserts",shard="0",type="total_operations"}	11
seastar_cql{instance="localhost",job="prometheus",metric="deletes",shard="0",type="total_operations"}	6
seastar_cql{instance="localhost",job="prometheus",metric="reads",shard="0",type="total_operations"}	13
seastar_cql{instance="localhost",job="prometheus",metric="updates",shard="0",type="total_operations"}

To which dashboard you want to add it?

**Comment by tzach** [comment]
I suggest moving the foreground and background chart to a drill down, per server dashboard (#22) and replace them with the more intuitive CQL charts on the main dashboards (scylla-dash-per-server.json, scylla-dash.json)

**Comment by tgrabiec** [comment]
Cql stats are not a replacement for storage proxy stats. I'm for keeping foreground and background graphs.

**Comment by tzach** [comment]
@tgrabiec my problem with foreground and background graphs is they require an understanding of the internal architecture. We should still have them but, not in the default users dashboard, rather in the advance, deep dive dashboard.
CQL requests are something all Scylla users knows.

**Comment by tgrabiec** [comment]
@tzach Isn't the current "per-server" dashboard a deep dive dashboard? It looks like one. I think it should be extended further with whatever information is relevant for understanding system's behavior, rather than trimmed down. We can create a separate "overview" dashboard with only high-level throughput metrics.

**Comment by tzach** [comment]
@tgrabiec my view is the per server is this overview dashboard
We need (at least)
- overview dashboard - high level, user-facing dashboard
- per server dashboard
- deep dive for each server (one server per dashboard using templates)

We are going out of the scope of the origin issue.
I'm fine with adding the CQL metrics to the per server first and doing a rehash for better UX second.

**Comment by tgrabiec** [comment]
The single-server dashboard would certainly be useful, but I would still want to see some "expert level" metrics (like fg/bg writes) on the per-server dashboard to correlate among all nodes.

If we think that current per-server dashboard is too complex for users, we should create a new one. Just subtracting from current one would be a step backwards. 

+1 for adding CQL metrics.
