### ISSUE TITLE
New 2.1 Overview Dashboard has some graphics issue, in the CPU-reactor graph

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#301]
he missing lines are only on the overview dashboard, while in the per-server Dashboard it looks OK.

![image](https://user-images.githubusercontent.com/25585995/37950654-13ea86a4-31a2-11e8-8ab7-d0738ed2ee5d.png)

**Comment by tzach** [comment]
@tomer-sandler can you edit the problematic panel and extract the expression?

**Comment by tzach** [comment]
The problem is with the Axis, Left Y, Y-Max value. When the axis is 0-100, values of 100 are not always presented. Setting the value to 101, as is it in the per server dashboard solve the problem.
