### ISSUE TITLE
Make monitoring OS agnostic

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#317]
Users want to use Scylla monitoring stack on Mac and Windows, and with Docker, it's almost possible.
The main limitation is the start_all.sh script which does not work with Mac (#313 #308) and Windows.
We can either improve it, move to pure Python or Docker compose #273 or a combination.

**Comment by amnonh** [comment]
if we can go with the idea of adding the created dashboard to the repositories, it would remove the need for python for most users.

**Comment by amnonh** [comment]
python is no longer a dependency in Scylla monitoring 2.3
