### ISSUE TITLE
pass different parameters to different docker instances

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#321]
The new `-D` option is useful when passing the same parameter to all docker instances.
It will be useful to allow to pass a parameter to Grafana docker only, for example, upload a plugin.

Since the command line is already crowded, using Docker compose might be a solution.

**Comment by amnonh** [comment]
@tzach 
There is a command line that we can pass specific parameters to grafana/prometheus the -D passes a command line to docker.

The question do we need something specific for it?

**Comment by amnonh** [comment]
@tzach is this relevant?

**Comment by amnonh** [comment]
@tzach ping
