### ISSUE TITLE
wrong metric for 2018.1 streaming dashboard

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#322]
Streaming reads and writes bandwidth have the wrong query.

They read:

`
sum(irate(scylla_io_queue_streaming_write_delay{instance=~"[[node]]", shard=~"[[shard]]"}[30s])) by ([[by]])
`

and

```
sum(irate(scylla_io_queue_streaming_read_delay{instance=~"[[node]]", shard=~"[[shard]]"}[30s])) by ([[by]])
```

That is just a duplicate of the delay graph and also it is not, of course, the bandwidth

The right metrics are the `total_bytes` ones, instead of `delay`

**Comment by tzach** [comment]
@amnonh can you please fix? Also, is this issue across all dashboards?

**Comment by amnonh** [comment]
The same bug exists in master, 2.1 and 2.2
Sending a patch soon

**Comment by tzach** [comment]
@amnonh can we close this? with which PR?

**Comment by amnonh** [comment]
there's an open pull request for it

**Comment by slivne** [comment]
@amnonh  which PR ?

**Comment by amnonh** [comment]
@tzach should be closed by 
e95eff6c53b4ebe7748773ee3de192633237395d
