### ISSUE TITLE
Upgrade to the latest, stable, Grafana, Prometheus version  

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#324]

**Comment by amnonh** [comment]
Grafan 5 contains a redesign of it's layout engine, trying to switch to it breaks the dashboards.
It is not fully backwards compatible. the question is do we have users that uses older versions of grafana

**Comment by tzach** [comment]
> the question is do we have users that use older versions of grafana

Probably yes.
We can have two versions of the dashboards.
Prometheus is probably more urgent, more critical

**Comment by amnonh** [comment]
With prometheus the situation is even worse, starting at 2.0, they remove the protobuf (binary) support in favor of text-only format, it's not something we want.

**Comment by amnonh** [comment]
There is currently a bug in grafana 5 that I'm trying to work around
https://github.com/grafana/grafana/issues/14185
