### ISSUE TITLE
CPU / Scheduler dashboard

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#334]
With more and more CPU related metrics, we should introduce a new CPU dashboard, similar to the IP dashboard we already have.
As a start is can include:
- CPU Utilization per (Load)
- Foreground CPU Utilization
- Time spent in task quota violations
See https://github.com/scylladb/scylla-grafana-monitoring/pull/332 for description and query of each

**Comment by amnonh** [comment]
@tzach can be closed with 2fa144d466cc8db4647fb023ccf8b81e73b3e216
