### ISSUE TITLE
Connection chart

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#335]
Connection distribution is a key metric in Scylla performance.
Should be added to per server dashboard
(from @glommer PR https://github.com/scylladb/scylla-grafana-monitoring/pull/332)
```
{
    "class": "graph_panel",
    "pointradius": 1,
    "targets": [
        {
            "expr": "sum(scylla_transport_cql_connections{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])",
            "intervalFactor": 1,
            "legendFormat": "",
            "metric": "",
            "refId": "A",
            "step": 30
        }
    ],
    "title": "Client CQL connections by [[by]]",
    "description": "amount of CQL connections currently established\nTest"
}
```

**Comment by amnonh** [comment]
@tzach I think it can be closed with: 17dee16f7ecc4b4c00b1608eeaa0e1512b6a3431

**Comment by tzach** [comment]
@amnonh please backport to 1.x and 2.x

**Comment by amnonh** [comment]
@tzach it's already backported to 2.x, I'll backport it to 1.x but we should probably freeze it at some point
