### ISSUE TITLE
the group by shard is incorect

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#337]
There are many places we allow to do show the graph by shard.
But what we are doing is combining all shards from all the nodes.
I'm not sure this is correct.

Instead, we should display per instance per shard.

**Comment by tzach** [comment]
@amnonh agree its confusing, but I do not understand your solution.

**Comment by amnonh** [comment]
An example of the current situation, setting graph by shard (two nodes)
![image](https://user-images.githubusercontent.com/2118079/42311972-c543cb4c-8047-11e8-9a5c-0200bb449c74.png)
Same graph, but with a group by instance and shard (not just shard)
![image](https://user-images.githubusercontent.com/2118079/42312048-fa6148e0-8047-11e8-9696-f6b9bb7356a8.png)

**Comment by amnonh** [comment]
@tzach see my comments and example, let's decide, either to fix or to close the issue

**Comment by tzach** [comment]
Not sure its better, this will explode with a larger cluster of big machines. 
Thinks 10 nodes and 64 shards per each.

**Comment by amnonh** [comment]
@tzach In that case, don't choose view per shard with all instances, what does that mean to show the sum of all shards by instance?

why shard 0 on one instance should be added to shard 0 on another instance?

Also See #328

**Comment by amnonh** [comment]
Fixed by #606
