### ISSUE TITLE
start-all.sh: -d option doesn't work with the new (v2.3) Prometheus

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#346]
HEAD: 99041c403c932bf75e009bf26746d587e9ec5d23

*Description*
Prometheus doesn't store/read data in the directory given with `-d` option.

*Root cause*
Prometheus changed the root directory name in the docker from `prometheus-data` to `prometheus`.

**Comment by amnonh** [comment]
It was already solved with commit:
2f975de9d9df791266a0e1d81fcbd0016bc66373

your branch is not updated

**Comment by vladzcloudius** [comment]
@amnonh actually, it was. ;)
Like I mentioned in the description, the data directory inside the docker is `prometheus` and not `prometheus-data` as the patch above assumes:
```
$ sudo docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
2be59ac09856        grafana/grafana:4.6.3       "/run.sh"                4 hours ago         Up 4 hours          0.0.0.0:3000->3000/tcp   agraf
42907f375d0c        prom/prometheus:v2.3.2      "/bin/prometheus -..."   4 hours ago         Up 4 hours          0.0.0.0:9090->9090/tcp   aprom
0b556e0f81b0        prom/alertmanager:v0.12.0   "/bin/alertmanager..."   4 hours ago         Up 4 hours          0.0.0.0:9093->9093/tcp   aalert
$ sudo docker exec -it aprom sh
/prometheus $ pwd
/prometheus
/prometheus $ ls
data
/prometheus $
```

It looks like this patch actually a root cause of this (github) issue.

**Comment by amnonh** [comment]
@tzach can you confirm or deny the issue?

**Comment by tzach** [comment]
I can confirm the prometheus:v2.3.2 does not have a prometheus-data directory, and do have prometheus directory

**Comment by amnonh** [comment]
@tzach The question, can you confirm that version 2.0 worked for you with an external data directory (i.e. using -d flag)

**Comment by bentsi** [comment]
On latest branch-2.0 the issue persists. I checked inside the Prometheus container and the correct path for data dir is `/prometheus/data`
This is urgent since after restarting the container all the historical data is LOST!
```
/ $ [root@ip-172-16-99-139 scylla-grafana-monitoring-data]# docker exec -it fed3fc45a282 sh
/prometheus $ cd data
/prometheus/data $ ls -ltr
total 0
-rw-r--r--    1 nobody   nogroup          0 Sep 30 09:45 lock
drwxr-xr-x    2 nobody   nogroup         20 Sep 30 09:45 wal
/prometheus/data $ 

```

**Comment by bentsi** [comment]
The issue still exists!!!
Correct data dir volume mount should include ":Z":
`-v $DATA_DIR:/prometheus/data:Z`
Otherwise the container start fails.

**Comment by amnonh** [comment]
I think it's a permission issue on the data directory, but I can check the Z flag
