### ISSUE TITLE
Scylla Per Server Metrics shows wrong Client CQL connections

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla-monitoring#363]
The Client CQL connections is using the `scylla_transport_cql_connections` metric which is not what is intended by this metric (at least from my user perspective)

As seen with @glommer it should use ` scylla_transport_current_connections` instead.

EDIT: affected files are:

- scylla-dash-per-server.master.template.json
- scylla-dash-per-server.2.3.template.json

Cheers

**Comment by glommer** [comment]
@amnonh please fix.

@ultrabug is right: the metric we have now shows the cumulative connections over time and doesn't mean much (with irate we would see the rate at which connections are created, but that's not really the metric that we want)

We want current connections, to see how many connections the cluster has at the moment.

**Comment by amnonh** [comment]
I assume you meant that it should be:
`scylla_transport_current_connections`

**Comment by ultrabug** [comment]
yes @amnonh sorry, bad copy/paste indeed
