### ISSUE TITLE
(some) Metrics are wrong in overview dashboard

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#369]
See for example the Foreground queues:

```
sum(scylla_storage_proxy_coordinator_foreground_writes{}) by ([[by]])
```

The reason this is wrong is that it was historically copied from a time this was just the cluster dashboard. It does not have instance and shard parameters. As a result, some of those sums will provide the wrong values.

For example, let's assume we pick a node and aggregate by Shard:

The aggregation itself will work, but it will aggregate everything that has the same shard - from multiple instances. The expected behavior would be to show just the shards of that instance - as we do in the other dashboards.

**Comment by glommer** [comment]
@tzach @amnonh

**Comment by glommer** [comment]
@vladzcloudius spotted this, and he is right.

**Comment by amnonh** [comment]
@tzach let's merge the dc/cluster support and I'll clean everything together

**Comment by tzach** [comment]
@amnonh is this the same issue as #337 ?
@glommer please see @amnonh suggested solution and share your thoughts

**Comment by glommer** [comment]
I also don't understand what is Amnon's proposed solution there.

In the server dashboard it all works: if we select a specific instance, and by Shard, we see the correct thing.
If we select all instances, and then by Shard, we see the sum of all shards in all nodes. I would love to disabling selecting by shard if all instances are selected, since this view is rarely used.

But the metrics themselves, in the per-server dashboard, are all correctly written.

The metrics in the overview dashboard are just not correctly written.

**Comment by amnonh** [comment]
Those are two different issue, #369 is a bug with a simple fix.

#337 is something else, the combination of showing by shard for multiple instances is confusing, what is happening we sum all the information per shard, see my example inside the issue

**Comment by amnonh** [comment]
need backport to 2.2 and 2.1

**Comment by amnonh** [comment]
@tzach After merging it, please comment if you want it backported to 2.1, 2.2 as is, or only the fix to the overview dashboard that does not support instances

**Comment by tzach** [comment]
@amnonh ea820e1ea46354437b6d7371363e7e858d399fbd is an enhencmet, this is a bug
How are they related?
Lets not use the PR to solve unrelated issues

**Comment by amnonh** [comment]
Because when I added the enhancement it solved the problem

**Comment by amnonh** [comment]
@glommer  Can we close this?
