### ISSUE TITLE
Adding the monitoring version to the dashboard

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#374]
Moving to version 2.0 we are going to hit the question, what version a user is running.
Maybe it's better to add the version somewhere in the dashboard

**Comment by tzach** [comment]
Nice to have, not a must for the release

**Comment by eyalgutkind** [comment]
This is not solving the issue, the use still need to ssh to the monitoring machine and we assume she has access to the monitoring machine, it should be part of the dashboard, in the browser

**Comment by amnonh** [comment]
It's part of the dashboards at the buttom of the overview dashboard
