### ISSUE TITLE
scylla-per-machine-metrics dashboard when using -v 2.3 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#375]
starting with ``start-all.sh -v 2.3`` I get 4 dashboards, 3 are related to 2.3, except scylla-per-machine-metrics
![image](https://user-images.githubusercontent.com/170200/45017666-d4359400-b030-11e8-9610-6a997164fc80.png)

**Comment by amnonh** [comment]
closed by: add the version name to the dashboard #389
