### ISSUE TITLE
Removing of OS level metrics from per server dashboard have leftovers

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#376]
1. Non relevant drop down selections
![image](https://user-images.githubusercontent.com/170200/45017809-3ee6cf80-b031-11e8-81fe-f3ceb44517a2.png)

2. non relevant section headers
![image](https://user-images.githubusercontent.com/170200/45017849-532acc80-b031-11e8-8768-a5a6058e062d.png)

**Comment by amnonh** [comment]
@tzach can we close this?
