### ISSUE TITLE
Hard-to-understand phrase in README.md

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-monitoring#382]
README.md has the following phrase:

**For every server, there are two targets, one under scylla job which is used for the scylla metrics. Use port 9180.**

It was impossible for me to understand what this is supposed to say. What is "server" in this sentence - a Scylla server? prometheus server? A whole cluster? And why "every"? What does "scylla job" refer to, and how do you do something "under" it? I'm guessing that this is some sort of Prometheus terminology? And what is a "target"?

Maybe once I understand what you really meant here I'll come back and suggest different wording. But it would be nice to make this text readable for someone who has absolutely no prior knowledge of graphana or prometheus or anything, and just knows Scylla terminology like cluster or node.

**Comment by amnonh** [comment]
Thanks for the input, it's good to get feedback from someone outside of the specific domain.
We can probably do better
