### ISSUE TITLE
docker and sudo

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-monitoring#383]
The README.md describes how to run prometheus and friends using docker (I wish there was a way without it...) and mentions installing docker as a prerequisite but lacks some of the details on how to use it properly. Installing docker does not, out of the box, allows the user to user it. One also needs to start it, but this is a forgivable omission. 
The bigger problem I had is that out of the box, without creating a "docker" group and adding yourself to it and restarting both docker and your login, one needs to run docker under "sudo". So the instructions to run `./start-all.sh` will not work. One option is to run `sudo ./start-all.sh` and that should work. It would have been even nicer if the start-all.sh script itself could figure out whether docker works without sudo, and if it doesn't, try to run it with sudo (sudo is also not guaranteed to work, of course, maybe the user doesn't have sudo - but we can try).

**Comment by amnonh** [comment]
@nyh running docker with sudo considered bad practice, among other it will create files as root.

About using docker, it's not a must, you can install prometheus, grafana and the alertmanager by yourself and just load the dashboard to them.

I do not want start-all.sh to use sudo, not all system that we are going to run on even have sudo.

**Comment by nyh** [comment]
@amnonh using sudo from scripts is always a bad practice, but it never stopped us before :-)
I think README.md should be more helpful for people who are not experts on everything under the sun. In particular, if you already tell people they must install docker, it is likely that if they do they won't know they need to do something special to actually run it.

**Comment by amnonh** [comment]
I agree, I rather change the README than the script

**Comment by tzach** [comment]
@amnonh will you update the README?

**Comment by amnonh** [comment]
of course
