### ISSUE TITLE
scylla-per-server-disk-i-o-2-3 Dashboards - Some metrics have errors

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-monitoring#386]
grafana-monitoring-version: branch-2.0
Dashboard: scylla-per-server-disk-i-o-2-3
Metrics: 
Disk Reads per Server per Second
Disk Writes per Server per Second
Disk Reads Bps per Second
Disk Writes Bps per Second

Error: 
{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 158: could not parse remaining input \"by (instance)\"...",
  "message": "parse error at char 158: could not parse remaining input \"by (instance)\"..."
}

(Same thing when using by shard, DC, cluster).

![screen shot 2018-09-13 at 17 42 29](https://user-images.githubusercontent.com/20959584/45495692-6ac62b80-b77c-11e8-9a12-18c087b816c4.png)

**Comment by tzach** [comment]
@roydahan do you have other OS level metric working?
Could it be node_exporter is not reporting?

**Comment by roydahan** [comment]
No, it's a problem with the query syntax.
When you remove the "by" section it works.

**Comment by amnonh** [comment]
@roydahan can we close this?

**Comment by amnonh** [comment]
@roydahan ping

**Comment by roydahan** [comment]
Yes
