### ISSUE TITLE
Legend contains the name of the metric vs the name of the instance/shard

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-monitoring#387]
Monitoring 2.0 in some metrics in some dashboards the legend doesn't display the name of the instance / shard. instead it displays the name of the metric.

For example:
Dashboard: scylla-overview-metrics-2-3
Metric: Requests Served

![screen shot 2018-09-13 at 17 44 11](https://user-images.githubusercontent.com/20959584/45495929-f9d34380-b77c-11e8-8644-32f1b01230c4.png)

**Comment by amnonh** [comment]
@tzach @roydahan can we close this?

**Comment by roydahan** [comment]
Yes.
