### ISSUE TITLE
Failed opening file: grafana/scylla-dash-per-server.2.2.template.json

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-monitoring#399]
On latest branch-2.0 `scylla-dash-per-server.2.2.template.json` is not loaded due to error
```
{"slug":"scylla-overview-metrics-2-2","status":"success","version":1}Failed opening file: grafana/scylla-dash-per-server.2.2.template.json Expecting , delimiter: line 1066 column 17 (char 47548)
Warning: Couldn't read data from file 
Warning: "./grafana/build/scylla-dash-per-server.2.2.json", this makes an 
Warning: empty POST.
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json; charset=utf-8
Set-Cookie: grafana_sess=9802845fe5afd833; Path=/; HttpOnly
Date: Tue, 25 Sep 2018 16:47:21 GMT
Content-Length: 84
```
@amnonh 
CC: @roydahan

**Comment by amnonh** [comment]
@bentsi can we close this?

**Comment by bentsi** [comment]
When loading the dashboard I get:
![image](https://user-images.githubusercontent.com/5269241/48696358-64c05100-ebea-11e8-8e0f-64055fa2a668.png)

**Comment by amnonh** [comment]
The question, is this the same issue?
The original issue was the error when loading the dashboard, is it still the case?

**Comment by bentsi** [comment]
No, now loading succeeds but the dashboard looks messed
