### ISSUE TITLE
Node is unreachable

### ISSUE THREAD

**Issue by sahibzadafahad99** [scylladb/scylla-monitoring#403]
I have two nodes of scylla (version 2.2) which are running fine. Grafana shows me one node is unreachable as i have given correct targets in  **prometheus/scylla_servers.yml** and in **prometheus/node_exporter_servers.yml**. 

![scylla nodes](https://user-images.githubusercontent.com/36076256/46129024-d31e0e00-c24e-11e8-97a5-0151750a97cd.PNG)

**Comment by amnonh** [comment]
Please check the prometheus targets:
http://{ip}:9090/targets

see if any of the targets appears to be down, and if so what is the error

**Comment by sahibzadafahad99** [comment]
> Please check the prometheus targets:
> http://{ip}:9090/targets
> 
> see if any of the targets appears to be down, and if so what is the error


here my scylla_servers.yml settings
`# List Scylla end points

# An example with a single cluster and two DC
- targets:
       - 192.168.0.3:9180
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - 192.168.0.4:9180
  labels:
       cluster: cluster2
       dc: dc2
`
and here is node_exporter_servers.yml settings

`
# List end points with node exporter

- targets:
       - 192.168.0.3:9100
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - 192.168.0.4:9100
  labels:
       cluster: cluster2
       dc: dc2
`

here is prometheus targets
![grafana](https://user-images.githubusercontent.com/36076256/46128779-0f9d3a00-c24e-11e8-948b-88dbecfcc425.png)

**Comment by amnonh** [comment]
The screen shot is from gtafana, please check the prometheus targets, from
the prometheus setver

**Comment by sahibzadafahad99** [comment]
here is a screen shot from prometheus server 

![prom server](https://user-images.githubusercontent.com/36076256/46130358-8e947180-c252-11e8-86a8-3447efdb7ddf.PNG)

**Comment by amnonh** [comment]
Please login to the prometheus server typically on port 9090 and check the
target page (see my first reply)

**Comment by sahibzadafahad99** [comment]
Some targets are down
![prom targets](https://user-images.githubusercontent.com/36076256/46131684-b3d6af00-c255-11e8-9c61-37e34480e75f.PNG)

**Comment by amnonh** [comment]
That explains the unreachable on the dashboard, can you verify that the
metrics are reachable?

Also, if you are using containers maybe you need to use the local host
network (the - l flag)

**Comment by sahibzadafahad99** [comment]
Issue resolved
thank you 👍
