### ISSUE TITLE
start-all.sh: Error: Grafana container failed to start

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-monitoring#413]
SCT (scylla-cluster-tests) uses scylla-grafana-monitoring scripts to config prometheus/grafana in a single instance. start-all.sh fails sometimes in reconfigure scylla monitoring after new nodes is added.

I tried to run the follow script in a test instance (monitor) to reproduce this problem: 
```
while true; do 
    cd /var/lib/scylla/scylla-grafana-monitoring-branch-2.0
    sudo ./kill-all.sh
    sudo ./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -v 2.3 || break
done
```

Log:
```
....
aprom
aprom
agraf
agraf
aalert
aalert
Wait for alert manager container to start.Loading prometheus data from /var/lib/scylla/scylla-grafana-monitoring-data
2bf32d525ea9f85c5e6f2b23ef44fd5015717d5425b81f04deec26b75f017f3f
Wait for Prometheus container to start..518ca2b4829f272a2074c0bd9357bb57b404fa7dcb4d820333935dc7021edd59
Waiting for Grafana container to start........Error: Grafana container failed to start


[centos@ip-172-16-1-213 scylla-grafana-monitoring-branch-2.0]$ sudo docker logs agraf --details
 installing grafana-piechart-panel @ 1.3.3
 from url: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.3.3/download
 into: /var/lib/grafana/plugins
 ✔ Installed grafana-piechart-panel successfully
 Restart grafana after installing plugins . <service grafana-server restart>
 Failed to send requesterrorGet https://grafana.com/api/plugins/repo/camptocamp-prometheus-alertmanager-datasource: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
 Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/camptocamp-prometheus-alertmanager-datasource: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
 NAME:
    Grafana cli plugins install - install <plugin id> <plugin version (optional)>
 USAGE:
    Grafana cli plugins install [arguments...]
[centos@ip-172-16-1-213 scylla-grafana-monitoring-branch-2.0]$

```

It seems it failed for network issue. It's easy to retry if user runs it manually. We expect the script is more stable because we use it in automation script (SCT).

Can you retry it insider scylla-all.sh for network issue?

Related: https://github.com/scylladb/scylla-cluster-tests/issues/664

**Comment by glommer** [comment]
This is happening to @dyasny , and more recently with myself as well all the time.

this used to be extremely easy and we never saw those issues. Those are network issues, all right, but I wonder if there is something we're doing different now that is making those issues more common ?

**Comment by tzach** [comment]
The problem as I understand it is we download the pie char plugin when starting Grafana, which sometimes can fail
Alternative can be:
- Manage our own Docker with all plugin included
- Have the plugin as part of the project, maybe as submodules

You will still need an external network to clone the project and download Docker images, but not when running start_all or load_grafana

https://github.com/scylladb/scylla-grafana-monitoring/issues/222
