### ISSUE TITLE
Prometheus: Enable --web.enable-lifecycle by default 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#417]
Lifecycle is useful to refresh config file on runtime
In Prometheus 2.0 it is disable by default

**Comment by amnonh** [comment]
I don't think it's needed, promethues by default check if a file change. If you manage to bypass the container limitations, it would reload automatically with no need to call the API.

**Comment by amnonh** [comment]
@tzach please comment or close
