### ISSUE TITLE
Manager Dashboard: Repair progress gauge value is misleading

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#419]
`min(scylla_manager_repair_progress{cluster=~"[[cluster]]", host=~"$host"})`
Current function is using `min`, which does not make sense for Manager, which repair hosts one by one, so it is zero for the entire run till the last node and does not match sctool progress  result

**Comment by tzach** [comment]
@amnonh @mmatczuk thoughts?

**Comment by amnonh** [comment]
@mmatczuk can you supply some other metric that would indicate the entire progress?

**Comment by mmatczuk** [comment]
Sure we have that.

**Comment by amnonh** [comment]
@mmatczuk please add the relevant metric to the issue, assigned to you, waiting for the relevant metrics

**Comment by mmatczuk** [comment]
Sure we have that information, will expose as a metric. That's strange I thought we had done that before.

**Comment by mmatczuk** [comment]
Added in scylladb/mermaid#766

**Comment by amnonh** [comment]
@mmatczuk There is an issue with scylla_manager_repair_progress
It does not show what we expect it to show.

Currently, it shows the progress of all repair units.
But in practice, there is only one repair at the time, I think the overall experience is not clear

**Comment by mmatczuk** [comment]
@amnonh as you can see in https://github.com/scylladb/mermaid/pull/768 it show aggregated data for TASK broken out at various levels, note the labels...

We have `scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",task="faab0a52-4e88-489c-9598-98f840d85741"}	15`  - Grande total.

But also

`scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	92` - Total in a given keyspace

And 

`scylla_manager_repair_progress{cluster="test-cluster",host="192.168.100.11",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	100` - total in a given keyspace and host

What could be added is shard level, is that what you need?

```
scylla_manager_repair_progress{cluster="test-cluster",host="192.168.100.11",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	100
scylla_manager_repair_progress{cluster="test-cluster",host="192.168.100.12",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	100
scylla_manager_repair_progress{cluster="test-cluster",host="192.168.100.13",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	77
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf2",task="faab0a52-4e88-489c-9598-98f840d85741"}	0
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc1_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	92
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc2_rf2",task="faab0a52-4e88-489c-9598-98f840d85741"}	0
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_dc2_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	0
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_rf2",task="faab0a52-4e88-489c-9598-98f840d85741"}	0
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",keyspace="test_keyspace_rf3",task="faab0a52-4e88-489c-9598-98f840d85741"}	0
scylla_manager_repair_progress{cluster="test-cluster",instance="localhost:56090",job="scylla-manager",task="faab0a52-4e88-489c-9598-98f840d85741"}	15
```

**Comment by amnonh** [comment]
shard is nice, but not a must

The issue I have is that if I have a single gauge that shows the current progress, I need to map the metric to a 0-100 progress.

At any given time, only one of those units is active, the rest will be 100 even if they are not going to be repaird

**Comment by mmatczuk** [comment]
I see, on repair I can clear the metric so that you can see only one per cluster. WDYT?

**Comment by amnonh** [comment]
Maybe instead of clear the metric, add a metric that does not have a keyspace and task. so there will be one per cluster

**Comment by mmatczuk** [comment]
How about you use `scylla_manager_task_active_count` to figure out which one is currently running?

**Comment by amnonh** [comment]
Close by c8829202c178d1db6a717026aff3070044e2bdd3
