### ISSUE TITLE
Rename "Scylla Per-Server Disk" to "Scylla Per Server Disk"

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-monitoring#425]
I think it makes sense to s/Per-Server/Per Server/g. All the other "Per Server" metrics has no "-" in the middle.

$ git grep Per-Server
grafana/scylla-dash-io-per-server.1.5.json:        "title": "Scylla Per-Server Disk I/O 1.5",
grafana/scylla-dash-io-per-server.1.6.json:        "title": "Scylla Per-Server Disk I/O 1.6",
grafana/scylla-dash-io-per-server.1.7.json:        "title": "Scylla Per-Server Disk I/O 1.7",
grafana/scylla-dash-io-per-server.2.0.json:        "title": "Scylla Per-Server Disk I/O 2.0",
grafana/scylla-dash-io-per-server.2.1.template.json:        "title": "Scylla Per-Server Disk I/O 2.1"
grafana/scylla-dash-io-per-server.2.2.template.json:        "title": "Scylla Per-Server Disk I/O 2.2"
grafana/scylla-dash-io-per-server.2.3.template.json:        "title": "Scylla Per-Server Disk I/O 2.3"
grafana/scylla-dash-io-per-server.2017.1.json:        "title": "Scylla Enterprise Per-Server Disk I/O 2017.1",
grafana/scylla-dash-io-per-server.2018.1.template.json:        "title": "Scylla Per-Server Disk I/O 2018.1"
grafana/scylla-dash-io-per-server.3.0.template.json:        "title": "Scylla Per-Server Disk I/O 3.0"
grafana/scylla-dash-io-per-server.master.template.json:        "title": "Scylla Per-Server Disk I/O master"

**Comment by amnonh** [comment]
It's a good point but I think we don't need to bother with older versions, it's enough to change newer dashboard and master.

I'll do that after moving to grafana 5
