### ISSUE TITLE
The prometheus container doesn't start due to "permission denied" on /etc/prometheus/prometheus.yml

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#43]
```
time="2016-08-30T12:06:28Z" level=info msg="Starting prometheus (version=1.0.0, branch=master, revision=e2bb136)" source="main.go:73" 
time="2016-08-30T12:06:28Z" level=info msg="Build context (go=go1.6.2, user=root@98d6f366491c, date=20160718-15:12:02)" source="main.go:74" 
time="2016-08-30T12:06:28Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:206" 
time="2016-08-30T12:06:28Z" level=error msg="Couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): open /etc/prometheus/prometheus.yml: permission denied" source="main.go:218" 
```

**Comment by tgrabiec** [comment]
The fix is to modify the docker command line by appending `:Z` to the paths which are argument to `-v`.

**Comment by tzach** [comment]
@tgrabiec I fail to reproduce the problem
Maybe because I run the start_all.sh script as sudo?
(I also do not understand the fix)

**Comment by tgrabiec** [comment]
@tzach I doubt it's because of `sudo`, the script runs docker under sudo anyway. 

I didn't dig too much into details, but the problem seems to be similar to that described here:  http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

Appending ':Z' affects permissions for the mount.

**Comment by tzach** [comment]
> The fix is to modify the docker command line by appending :Z to the paths which are argument to -v.

@tgrabiec can you please send a PR?
