### ISSUE TITLE
per-server dashboard doesn't split the metrics if single collectd_exporter is used

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#44]
I have a setup with a single collectd sink instance and therefore single collectd_exporter. In such configuration all samples will fall under the same instance label - the collectd exporter IP. They do however have distinct `exported_instance` label, which is set from `instance` label as recorded by collectd. Perhaps we should modify the dashboard to group by that by default.

There is also something called `relabelling` in prometheus config which maybe could be used to set instance from exported_instance, but I had no success with it.

**Comment by tgrabiec** [comment]
There is a simpler solution. Setting `honor_labels: true` makes prometheus respect the `instance` label set by collectd_exporter:

``` patch
--- a/prometheus/prometheus.yml
+++ b/prometheus/prometheus.yml
@@ -1,5 +1,5 @@
 global:
   scrape_interval: 15s # By default, scrape targets every 15 seconds.

   # Attach these labels to any time series or alerts when communicating with
   # external systems (federation, remote storage, Alertmanager).
@@ -8,5 +8,6 @@ global:

 scrape_configs:
 - job_name: scylla
+  honor_labels: true
   static_configs:

```

**Comment by amnonh** [comment]
Can we close it as we moved to Prometheus API?

**Comment by tzach** [comment]
Yes with #59
