### ISSUE TITLE
Grafana graphs are jiggly with short scraping intervals

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#45]
When I set scraping interval to 1s I see graphs "jiggle" in a way that historical data points change values. After looking closer at this it turns out that graphs alternate on refreshes between showing samples from only odd and only even timestamp values.

Setting "resolution" parameter for queries from `1/2` to `1/1` fixes the problem. In dashboard JSON the change amounts to:

``` patch
           "targets": [
             {
               "expr": "avg(collectd_reactor_gauge{type=\"load\"} ) by (instance)",
-              "intervalFactor": 2,
+              "intervalFactor": 1,
               "refId": "A",
-              "step": 2
+              "step": 1
             }
           ],
           "timeFrom": null,
```

**Comment by tzach** [comment]
@tgrabiec is this values valid for the default 15s scraping interval ?

**Comment by amnonh** [comment]
Can we close this?

**Comment by tgrabiec** [comment]
They are still jiggly if your step is large enough due to time range.

**Comment by amnonh** [comment]
@tzach @tgrabiec can we close this?
