### ISSUE TITLE
Scylla 2.2 dashboards comes dark when deploying Scylla monitoring w/o docker

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#458]
Using the following procedure, we were able to see the metrics using 2.3 versioning. But, when using 2.2 version the dashboards comes dark w/o any metrics or panels.

1. wget https://github.com/prometheus/prometheus/releases/download/v2.6.0/prometheus-2.6.0.linux-amd64.tar.gz
2. wget https://dl.grafana.com/oss/release/grafana-5.4.2.linux-amd64.tar.gz
3. git clone https://github.com/scylladb/scylla-grafana-monitoring.git
4. tar -xvzf prometheus-2.6.0.linux-amd64.tar.gz
5. tar -xvzf grafana-5.4.2.linux-amd64.tar.gz
6. cd prometheus-2.6.0.linux-amd64/
7. mv prometheus.yml prometheus.yml.old
8. cp -p ../scylla-grafana-monitoring/prometheus/* .
9. cp -p prometheus.yml.template prometheus.yml
10. cd ../grafana-5.4.2/
11. cp -p -R ../scylla-grafana-monitoring/grafana .
12. cp -p ../scylla-grafana-monitoring/*.sh .
13. cp -p ../scylla-grafana-monitoring/make_dashboards.py .
14. cd ../prometheus-2.6.0.linux-amd64/
15. Edit the prometheus.yml 
Make sure that the following files are getting the right path in the prometheus.yml file
<your path>prometheus-2.6.0.linux-amd64/scylla_servers.yml
<your path>prometheus-2.6.0.linux-amd64/node_exporter_servers.yml
<your path>prometheus-2.6.0.linux-amd64/prometheus.rules.yml
<your path>prometheus-2.6.0.linux-amd64/scylla_manager_servers.yml

16. mkdir mydata
17. give read and write permissions to prometheus-2.6.0.linux-amd64/mydata
18. populate the information about your scylla node in the files : scylla_servers.yml and node_exporter_servers.yml
19. Start Prometheus: ./prometheus --config.file=prometheus.yml --storage.tsdb.path <mypath>/prometheus-2.6.0.linux-amd64/mydata/
20. Check that you can see metrics in your prometheus server at <yournode IP>:9090 for example
21. cd ../grafana-5.4.2/
22. Start Grafana with ./bin/grafana-server
23. load the dashnboards to the Grafana server : ./load-grafana.sh -p <yopurnodeIP>:9090 -g 3000 -a admin -v 2.2
24. Go to your node <yopurnodeIP>:3000 and see the dash boards

**Comment by amnonh** [comment]
I see that you are running grafana 5, we were not planning to support 2.2
for grafana 5 (the coming Monitoring 2.1 version).
In general, grafana 5 is only in master and not part of a release yet.

**Comment by eyalgutkind** [comment]
Got it, Please add to the non-docker version of 2.0 documentation, also the required Grafana and Prometheus version. 
Thank you.

**Comment by amnonh** [comment]
@eyalgutkind can we close this?

**Comment by eyalgutkind** [comment]
yes @amnonh
