### ISSUE TITLE
strange units for "foreground writes"

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-monitoring#463]
For the "foreground writes" metric we use the bizarre unit "pps". The "p" implies perhaps packets (?), the "ps" implies "per second", but both are wrong: "foreground writes" is actually the **current** number of active writes minus the background writes, it has nothing to do with packets and doesn't measure the rate per second os anything.

 As you can see in the screenshot below, other similar metrics do not have a unit at all, and have on the left a axis label "queue length". Foreground writes should perhaps get the same axis label, although it's not actually the length of a single queue but more a subtraction of two. 

![a](https://user-images.githubusercontent.com/584227/50738800-a29c2780-11e0-11e9-87bd-3260b9f0ea93.png)
CC: @gleb-cloudius @amnonh

**Comment by amnonh** [comment]
pps is packet per seconds.

while here we need ops for operation per seconds, or wps (writes per seconds), but according to the description, it should be a queue size, I'll switch to that
