### ISSUE TITLE
master I/O dashboard is broken

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#464]
HEAD: bbe74af7d9a5dfaed9ef9ec34d11a58b297d5f06

*Description*
All I/O queues graphs use a wrong (old) metric semantics. 
For instance, `scylla_io_queue_compaction_delay` instead of `scylla_io_queue_delay{class="compaction"}.

**Comment by glommer** [comment]
@amnonh please fix this before the 3.0 release

**Comment by amnonh** [comment]
thanks @vladzcloudius I'll take care of it

**Comment by amnonh** [comment]
@vladzcloudius using the class label is in seastar master, but not in 3.0

**Comment by vladzcloudius** [comment]
@amnonh You are right. Fixing the issue description. Sorry for a confusion.
