### ISSUE TITLE
Please create a storage panel that shows the usage variation across time. 

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-monitoring#466]
The pizza chart we have currently does not show the storage usage over time. It makes it hard for customer to make estimations about data growth and how much they are getting back with compactions.

**Comment by amnonh** [comment]
I believe you actually want a panel, not an entire dashboard just for storage.

**Comment by gnumoreno** [comment]
Correct. Sorry for using the wrong terminology.

**Comment by amnonh** [comment]
@tzach I have no objection, is there a dashboard you think we should place it?

**Comment by tzach** [comment]
The OS level dashboard, this is a node_exporter metric
