### ISSUE TITLE
grafana: some graphs are loaded with an empty selection list

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#475]
HEAD: 32d8944ff200c5ffa4762ad474f5dd69ea0cb1bf

*Description*
When we started our monitoring with the following command: ` ./start-all.sh -s ./myconf/scylla_servers.yml -n ./myconf/node_exporter_servers.yml -N ./myconf/scylla_manager_servers.yml -v 2018.1,2.1 -d /var/lib/scylla/metrics` some graphs had an empty selection list, e.g. `scylla_transport_requests_served{}`.

This naturally causes grafana display "No data points" message.

**Comment by amnonh** [comment]
@vladzcloudius can you be more specific, what dashboard and what panel?

**Comment by vladzcloudius** [comment]
@amnonh There were a few on a "Per Server" dashboard. "Request Served" panel was one of them.

**Comment by amnonh** [comment]
Are you testing it with Enterprise 2018.1?

**Comment by vladzcloudius** [comment]
@amnonh Unfortunately it happened at the customer site and, yes, he was using the enterprise scylla binaries. How is it related to the panel's query being screwed up?

**Comment by amnonh** [comment]
Queries are per-version, so I wanted to know what to check

**Comment by amnonh** [comment]
@vladzcloudius I've just used 2018.1 AMI and tried it both with 2.0 and 2.1 monitoring versions.
Both showed information.

Could it be that you are talking about the panels that show all requests and are not split by shard/host?

For examle, in the per-server dashboard, the topmost panel shows the total number of requests in the cluster.
The panel below it shows the requests by shard/host/cluster depends on the filter you are using.

You can see that the panel title is different.

If that is the case it was done on purpose, if you think it should be different, please change the title and description.

If you are facing something else, please let me know.

**Comment by vladzcloudius** [comment]
@amnonh No, the problem was seen in a few panels and one of them was "Requests Served". The issue doesn't reproduce every time. However I saw it a few time at other customers' before.

**Comment by amnonh** [comment]
@vladzcloudius The only example that I have is for a panel that is not supposed to be filter or split.

Can you please specify a dashboard/panel that you know that is supposed to have a selection list and isn't?

**Comment by vladzcloudius** [comment]
@amnonh "Requests Served" is supposed to have a selection and it didn't have it.

**Comment by amnonh** [comment]
No it's not

**Comment by vladzcloudius** [comment]
@amnonh It does. 
See below how it's supposed to be:

![image](https://user-images.githubusercontent.com/6103981/52221686-b3879980-286f-11e9-80c3-c238756a7e27.png)

**Comment by amnonh** [comment]
You're talking about different dashboards, in the overview it doesn't and
in the per server it does

**Comment by vladzcloudius** [comment]
@amnonh Did I mention an "Overview" dashboard at any point? Please, look at the third post at this issue.

**Comment by amnonh** [comment]
you're right, that I mixed the dashboard, but still in the per-server there are two panels, the one on top:
With the title: Total Requests
Don't contains selction.

The other panel: Requests Served per (cluster/host/shard) does contains the filter.

That was my original answer, if this is the only panel/dashboard, then this is ok, if you have anything else, please let me know

**Comment by vladzcloudius** [comment]
@amnonh Please, read the 3d post at this issue - it has it all. "Requests Served" on "Per Server" should have the filter and it didn't have it at the customer's.

**Comment by amnonh** [comment]
@vladzcloudius please read my answer, there are two panels in the per-server dashbaord.
One with filter and one without.

If you are saying that the panel that should have a filter didn't, please add a capture of how it looks.

**Comment by vladzcloudius** [comment]
@amnonh Please, read my answer - this *whole* issue is about the panel that (even according to you) should have a filter. 

I don't have a screenshot of it anymore - you'll have to take my word for that since I saw it with my own eyes.

**Comment by amnonh** [comment]
Fixed by #539
