### ISSUE TITLE
Prometheus docker couldn't handle very big scylla cluster (450 nodes)

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-monitoring#482]
There wasn't any error in docker logs, however HTTP to 9090 port doesn't work and grafana couldn't connect to Prometheus.

In addition, ./kill-all script wasn't able to kill aprom docker and even "docker rm -f" didn't work.
Only after restarting the docker service, the aprom docker was removed.

**Comment by amnonh** [comment]
The limitation is on hardware, it should be cover in the documentation for the right sizing.
