### ISSUE TITLE
"WARNING: You are using the unstable master branch" when downloading the released 2.1

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-monitoring#484]
Downloaded https://github.com/scylladb/scylla-grafana-monitoring/releases/tag/scylla-monitoring-2.1 from https://github.com/scylladb/scylla-grafana-monitoring/releases/tag/scylla-monitoring-2.1 as described in the Monitoring 2.1 blog and documetnation, running `./start_all.sh` I see:

```
*****************************************************
* WARNING: You are using the unstable master branch *
* Check the README.md file for the stable releases  *
*****************************************************
```
If I manually clone the git repo, and switch to `branch-2.1`, the warning is not shown. 

We need to either remove the warning or have the correct version in the releases, because this is what the customers are downloading and seeing.

**Comment by dyasny** [comment]
BTW, if I download the .tar.gz, there is no way to switch branches, since there is no git tree

**Comment by amnonh** [comment]
Thanks @dyasny There was an issue with the release. It didn't include the last commits.
I re-released and verified

**Comment by mailmahee** [comment]
@amnonh do we just need to download the next  .tar.gz version everytime we do the release?

**Comment by amnonh** [comment]
@mailmahee, yes, between minor releases or patch release, it's enough to download the tar again and copy the configuration.

**Comment by amnonh** [comment]
@dyasny can we close this?

**Comment by dyasny** [comment]
If it is fixed, I don't see why not
