### ISSUE TITLE
Monitoring + Manager deployment issue with one of our customers

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#485]
Related also to: https://github.com/scylladb/scylla-grafana-monitoring/issues/475

```
[root@scylla-a1 us-west-2 prod ~]# /usr/bin/node_exporter --version
node_exporter, version 0.14.0 (branch: master, revision: 840ba5dcc71a084a3bc63cb6063003c1f94435a6)
 build user:       root@bb6d0678e7f3
 build date:       20170321-12:12:54
 go version:       go1.7.5
```

The final version used:
```
./start-all.sh -s ./myconf/scylla_servers.yml -n ./myconf/node_exporter_servers.yml -N 
./myconf/scylla_manager_servers.yml -v 2018.1,2.1 -d /var/lib/scylla/metrics
```

Other notes:  running from master branch

Also, had to set actual ip address of manager host in the scylla_manager_servers.yml. 
The default of 127.0.0.1 did not work, even though monitoring stack runs on the manager instance.
And created the `/var/lib/scylla/metrics` directory and `chowned` it  to `nfsnobody:nfsnobody` with permissions `0755` to allow writes.

@tzach Are these actual issues to fix in the code, or we just need to better document them, or add them in troubleshooting / FAQ?

**Comment by tzach** [comment]
What Monitoring stack version is used?

**Comment by tomer-sandler** [comment]
Monitoring Stack version: 2.0
And also from Master branch -> HEAD: [32d8944](https://github.com/scylladb/scylla-grafana-monitoring/commit/32d8944ff200c5ffa4762ad474f5dd69ea0cb1bf)

**Comment by amnonh** [comment]
I don't understand what the issue is.
About node_exporter version, it's part of scylla installation, so the question what scylla insallation you are running.

About manager and monitoring stuck, to access the host 127.0.0.1 (which you tried to do) you need to use local flag (-l) or you are telling the container to use its own 127.0.0.1 (not what you want).

Consider switching to monitoring 2.1

**Comment by tomer-sandler** [comment]
@tzach / @amnonh  where is `-l` flag documented and how and where to use it?
They were using Scylla Enterprise 2018.1.9

Why did we have to use `chown` command and change permissions - again this is related also to the ticket @vladzcloudius opened which I referred to.

**Comment by amnonh** [comment]
I don't understand what the original issue is, aside from the word issue in the title.
@tomer-sandler Please read the issue itself, and make it clear what is the first issue you are referring to before the word **also**

about the -l you can see it here:
https://github.com/scylladb/scylla-grafana-monitoring

**Comment by tomer-sandler** [comment]
@amnon@scylladb.com 
The 1st issue was what Vlad described in ticket https://github.com/scylladb/scylla-grafana-monitoring/issues/475  , whichI also mentioned here in the description.
Other issues are the `chown` that was needed and the `127.17.0.1` that was needed to be specified as Monitoring + Manager were installed together on the same node. See ticket https://github.com/scylladb/scylla-docs/issues/1661 (scylla-docs).

**Comment by amnonh** [comment]
About #475 I'm not sure it's an issue, if you encounter a problem with a panel, please specify what dashboard and what panel.

About the chown, I'll take a look

**Comment by amnonh** [comment]
Closing
