### ISSUE TITLE
Update scylla-cql-optimization and use scylla's system table counters

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#490]
Since scylla metrics are global they include internall scylla system table + driver queries.

We need to remove those to provide user input only on his application queries (those are the only ones he controls).

1. Non Reversed CQL Reads
2. Paged CQL Reads

(everywhere with -10 probably :) ).

https://github.com/scylladb/scylla/issues/4182

**Comment by tzach** [comment]
We should remove the -10 parameter
Still, this dashboard has value even before we fix scylladb/scylla#4182
I suggest adding a disclaimer like:
"Metric include internal queries from system tables, which might be misleading under low traffic conditions."

**Comment by amnonh** [comment]
@slivne is this still relevant?
