### ISSUE TITLE
Show more information about compaction

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#491]
Our per-server dashboards show "compactions" as an absolute number but that means very little.
Users tend to think "my compactions are gone nuts, there are too many!" without understanding that this doesn't mean they use up a lot of resources (any more - after controllers)

I would like to augment the compaction row, dividing it in 3 or 4 graphs instead of the one big compaction graph we have today.

That would include:
- % of CPU time spent compacting
- % of I/O Bandwidth spent compacting (similar graph already in the I/O dashboards, but this is better and more localized)
- optionally -> compaction shares

**Comment by tzach** [comment]
> * % of CPU time spent compacting
> * % of I/O Bandwidth spent compacting (similar graph already in the I/O dashboards, but this is better and more localized)
> * optionally -> compaction shares

@glommer do you have the metric name for each?

**Comment by glommer** [comment]
There may not be a single metric for those and we may have to compose.

For % of CPU time:
--------------------------

`scylla_scheduler_runtime_ms` (irate of that), will tell you the time spent by a task group (`group=compaction`). From there we have two options:

1. divide that by 1000ms  - will give you the total CPU time in a top-like fashion (if you are using 150ms per 1000ms for compactions and nothing else runs, will give you 15%)
2. divide that by the sum of all classes. Will give you relative time between classes, which excludes idle and pollers. 

The first one seems better to me, agree?

For I/O
----------

We already have bandwidth information in the I/O Dashboard: `scylla_io_queue_compaction_total_bytes` (irate of)

To change this into a percentage we should divide by the other classes (in this case we don't have a clear baseline like for CPU). If it is too confusing (CPU using 1000ms as a baseline and IO using a relative percentage), we can leave I/O out.

Compaction shares
--------------------------

`scylla_scheduler_shares`

**Comment by amnonh** [comment]
@glommer can you please take a look at 2.3 and let me know if I can close this?

**Comment by glommer** [comment]
It's not great.
Starting with the low hanging fruits, there are three graphs, but they don't take the entire span of the screen. Compare that to the memory graphs, that do:

![c](https://user-images.githubusercontent.com/331197/57312689-0dd90600-70bc-11e9-9f52-d8ac6a60a920.png)

More importantly, the runtime graph is wrong. The query is ms / 1000 , which returns a number between 0 - 1. But the axis are a percentage (0 - 100), which means we have to multiply the output by 100 (or switch to axis to use percent (0 - 1) instead

I strongly prefer to keep the axis at 0 - 100, which means the query should be adjusted to 
```
(sum(rate(scylla_scheduler_runtime_ms{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]", group="compaction"}[30s])) by ([[by]]))/10
```

**Comment by amnonh** [comment]
@glommer I'm closing, if there is anything that is missing, please open with what you want to add
