### ISSUE TITLE
message in the server in non-default server

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#494]
```
$ sudo ./start-all.sh -g 3001 -p 9091 -m 8888 -s destination/scylla_servers.yml -n destination/node_exporter_servers.yml 
./start-all.sh: line 75: [: -p: binary operator expected
./start-all.sh: line 75: [: -g: binary operator expected
```

**Comment by glommer** [comment]
it seems to work despite the message.

**Comment by tzach** [comment]
@gleb-cloudius which version of monitoring are you using?

**Comment by glommer** [comment]
Yes Gleb. tell them the version of the monitoring you are using

I'll go ahead and say the one I am using just for reference: I used yesterday's clone, branch 2.1

**Comment by amnonh** [comment]
Not sure why it's shown now but it could be that we need to wrap the GRAFANA_PORT and PROMETHEUS_PORT in string quotes to protect it during -z if statement.

I'll run some tests

**Comment by gleb-cloudius** [comment]
On Thu, Feb 07, 2019 at 11:33:13AM -0800, Glauber Costa wrote:
> Yes Gleb. tell them the version of the monitoring you are using
> 
I use curl and build graphs in my imagination.

--
			Gleb.
