### ISSUE TITLE
"Read Timeouts per Minute per Server" et al graphs actually show per-second rates not per-minute

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#50]
The metric is calculated with irate function: `sum(irate(collectd_storage_proxy_total_operations{type="read timeouts"}[30s])) by (instance)`

`irate` calculates per-second rate:

> irate(v range-vector) calculates the per-second instant rate of increase of the time series in the range vector. This is based on the last two data points.

Which is supported by this graph:

![timeout](https://cloud.githubusercontent.com/assets/283695/18208967/f7c9bcec-7131-11e6-9f2f-d4647c033a12.png)

**Comment by tzach** [comment]
@tgrabiec look like the problem is with the header, not the data, right?

**Comment by tgrabiec** [comment]
@tzach I think we should change the header to just mention "Read timeouts" and reflect the unit (1/s) in the y-axis settings.
