### ISSUE TITLE
 /prometheus/data/lock: permission denied

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-monitoring#508]
### Steps to reproduce

Follow the instructions outlined on our monitoring documentation: 
[Scylla Monitoring Stack](https://docs.scylladb.com/operating-scylla/monitoring/monitoring_stack/)

Inside the monitoring dir (i.e. scylla-grafana-monitoring-scylla-monitoring-2.1) create a data dir to hold prometheus information

`mkdir data`

Run the monitoring passing the `-d` option with relative path:

`sudo ./start-all.sh -d data`

Error from `sudo docker logs aprom`:

`level=error ts=2019-02-19T21:12:56.793329751Z caller=main.go:625 err="opening storage failed: lock DB directory: open /prometheus/data/lock: permission denied"` 

### Workaround

It works if we pass the absolute path after changing the permissions, ex.:
`chmod -R 777 data`
`sudo ./start-all.sh -d /home/<user>/scylla-grafana-monitoring-scylla-monitoring-2.1/data`

### Permanent solution

I did some research and did not find the reason why it works with the workaround above.

Can we find a permanent solution that could be incorporated to our scriptology? 

I'm creating this issue mainly to document here in the case any users out there run into this problem.

#43 #296

**Comment by amnonh** [comment]
There are multiple issues here:
1. Running docker should not be done as root (you can but it's usually a bad idea)
2. We should document the full path to the directory (or modify the script accordingly)
3. There are changes in the user permission in 2.2 that would remove the need for chown and chmod

**Comment by gnumoreno** [comment]
1. Was fixed
2. Can you please elaborate? @amnonh 
3. Glad to hear it.

**Comment by amnonh** [comment]
@gnumoreno please verify that 2.2 solve the issue

**Comment by sicebi** [comment]
Workaround works

1 chmod -R 777 /home/xxx/data
2 sudo docker run -d -p 9090:9090  -v /home/xxx/data:/prometheus/data prometheus

**Comment by gnumoreno** [comment]
@amnonh please see #561 I believe we can close this one.

**Comment by alokhom** [comment]
make a config folder in the location of your docker-compose.yml. insert the files prometheus.yml and alert_rules.yml in the config folder. This code worked for me on v2.10 prometheus image
```
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - './config:/prometheus'
    restart: unless-stopped
    ports:
      - 9090:9090
```

**Comment by sreedharbukya** [comment]
Is there any other solution which can solve this issue?

**Comment by tadayosi** [comment]
Could be SELinux issue. `sudo setenforce 0` might help.

**Comment by athamour1** [comment]
i fixed it with `mkdir /data-agent` and `sudo chown -R prometheus:prometheus /data-agent/` for a bare-metal installation
