### ISSUE TITLE
Credentials management for Grafana

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#509]
We need to be able to manage credentials for Grafana, including:
- Creating a new admin user
- Creating a new regular user - without any ability edit/add/remove dashboards
    - Maybe even limit viewing access to some dashboard
- Removing a user
- Updating a user password

**Comment by amnonh** [comment]
@mykaul @gmizrahi This issue was opened a long time ago, technically, we can use Grafana team, but I think the cloud does not need it.
Let me know if I can close?

**Comment by gmizrahi** [comment]
I think it's safe to close it, this issue is 5 years old, much has changed since then...
