### ISSUE TITLE
Specify unit on the axis instead of in the title

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#51]
Before:

![timeout](https://cloud.githubusercontent.com/assets/283695/18209144/cba9dede-7132-11e6-9e0e-72cd2cb9418e.png)

After:

![ops](https://cloud.githubusercontent.com/assets/283695/18209146/cedd3efc-7132-11e6-9aba-cde70207c152.png)

**Comment by tzach** [comment]
@tgrabiec looks good, but is ops the right unit for timeouts per seconds?

**Comment by tgrabiec** [comment]
@tzach "ops" stands for operations per second. In the context of "read timeouts" it reflects how many read operations timeouted per second. I couldn't find a more specific unit.

**Comment by amnonh** [comment]
@tgrabiec can we close this?

**Comment by tgrabiec** [comment]
@amnonh What's the commit which fixes this?

**Comment by amnonh** [comment]
@tgrabiec It's just been fixed gradualy for the last two years, for example:
33cc238c20aeb51e1f0c3d6be80f80bd952abd70
660ec837059ed9f042dfbaf98915da83b6028ba1

**Comment by tgrabiec** [comment]
We should also drop the "per Second" from the title.
