### ISSUE TITLE
Add support for multi-dc in the genconfig.py script

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#513]
Currently the genconfig script gets only IP address and directory in which it should place the configuration files.

User story:
As a user I'd like to be able to get a server and node exported configuration file.
In the input to the script I should be able to provide the DC name and relevant IPs per DC. 
Or, if I already have the cluster up and running the output of `nodetool status` and the script will be able to create the adequate configuration file.

For example:
sudo ./genconfig.py -d mydir -s -n  -g dc1 10.0.0.1,10.0.0.2 -g dc2 10.0.1.1, 10.0.1.2 -g dc3 ....

or 
nodetool status > my_cluster_info.txt
sudo ./genconfig.py -d mydir -s -n -f my_cluster_info.txt

**Comment by amnonh** [comment]
Also need to remove node_exporter by default

**Comment by tzach** [comment]
Make sure to update https://docs.scylladb.com/operating-scylla/monitoring/monitoring_stack/#procedure
