### ISSUE TITLE
enhancement: allow changing aggregation modes

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#520]
Instead of average or sum of the shard data per node, allow replacing with min, max, or stddev. This allows finding nodes that have high shard load, or low shard connection count, or high variability between shards. Then the used can switch to shard view of that node to understand which shards are misbehaving.

**Comment by tzach** [comment]
@avikivity are you looking for a dashboard level option?

**Comment by amnonh** [comment]
@avikivity Trying to understand the request
Let's say that you have a problematic node.
if you pick that node and look at a by-shard view, you will see if there is a shard that is higher, lower or going banana compare to the other shards.

If you are talking about finding the problematic node, I think #337 is the right approach.

If you are talking about something else, please try and give an example

**Comment by amnonh** [comment]
#337 and #607 should cover this
