### ISSUE TITLE
Clearly state which metric are coordinator and which replica

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#521]
Coordinator and replica metrics should be clearly separated, each in its own section

**Comment by amnonh** [comment]
@tzach Please add more details

**Comment by amnonh** [comment]
@tzach ping

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
@amnonh not sure what information you need
Some of the metrics are captured in coordinator, some in the replica, the dashboard is not clear which is which and we need to fix it.

**Comment by amnonh** [comment]
Closed by #619
