### ISSUE TITLE
Switch to Grafana 6

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#526]
Grafana 6 is out, we should switch to it

**Comment by debojitkakoti** [comment]
Is these dashboards support on grafana 6 ?

**Comment by amnonh** [comment]
We didn't test it with Grafana 6, so it's not officially supported, but I expect it would work fine.

**Comment by debojitkakoti** [comment]
Just now I have tested with grafana v6.1.4, it is working fine. Thanks

**Comment by amnonh** [comment]
I encounter a problem in grafana 6:
https://github.com/grafana/grafana/issues/17684

I'm waiting with the new grafana version
