### ISSUE TITLE
CQL Optimiz... dashboard remove the graph under the gauge

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#531]
![graph under gauge](https://user-images.githubusercontent.com/3465480/54354369-17fffa80-465f-11e9-96e4-e10ec2de5722.png)

the blue graphs under the gauge are not clear ... lets remove them

**Comment by amnonh** [comment]
I think they give a history that match the actual graphs, so it can help

**Comment by slivne** [comment]
It doesn't you don't have a legend - so what does it mean ?
