### ISSUE TITLE
Make select cluster, DC, node selection more visable

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#533]
When monitoring multiple clusters DCs, its easy to get lost.
Adding the cluster and DC name on the header will be useful, as we already do in the Manager dashboard 

### Over View
![image](https://user-images.githubusercontent.com/170200/54486837-706d0d00-4896-11e9-91d2-50cb6852e35f.png)

### Manager
![image](https://user-images.githubusercontent.com/170200/54486827-5e8b6a00-4896-11e9-910a-2b9da19840c4.png)

**Comment by amnonh** [comment]
Fixed by #563
