### ISSUE TITLE
2018.1 'scylla-per-server-disk-i-o-2018-1' Disk activity can't be filtered by node

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-monitoring#539]
Running on syclla-cloud lab, when selecting a specific node on `Scylla Per Server Disk` everything is filter except the Disk activity section

**Comment by fruch** [comment]
![Screenshot from 2019-03-20 09-37-06](https://user-images.githubusercontent.com/340979/54666991-f6d25a80-4af3-11e9-9318-32e594d5ce0d.png)

**Comment by amnonh** [comment]
Closed by  #558
