### ISSUE TITLE
add hints related graphs 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#545]
HEAD: dd390a6d57c6b3d282682c7c2316b530a7440ce1

*Feature requests*
Add hints related graphs. 
Hints metrics are coordinator metrics however it also makes sense to have them not too far from the replica side metrics because they are correlated with these.

**Comment by tzach** [comment]
@vladzcloudius please include the relevant metrics names.

**Comment by vladzcloudius** [comment]
@tzach scylla_hints_for_views_manager_* and scylla_hints_manager_*

**Comment by vladzcloudius** [comment]
@amnonh ping.

I looked at the current dashboards state in the master: it seems to make sense to start with adding the `scylla_hints_manager_writes` and `scylla_hints_manager_sent` graphs in the Coordinator group on the Detailed dashboard and adding `scylla_hints_for_views_manager_writes` and `scylla_hints_for_views_manager_sent` graphs in the View section.
