### ISSUE TITLE
Add view dashboard

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#546]
HEAD: dd390a6d57c6b3d282682c7c2316b530a7440ce1

*Feature request*
Add a separate dashboard for view in addition to graphs that we have today.
This dashboard will have a lot more view specific graphs including view HH manager metrics.

**Comment by tzach** [comment]
@vladzcloudius can you please elaborate on which metrics will be useful?

**Comment by vladzcloudius** [comment]
@tzach All hints related metrics are useful: type "hint" in the Prometheus console to see their names. 
There are two classes of these metrics: for MV and for regular queries. Naturally they need to be clearly separated on dashboard(s).

**Comment by tzach** [comment]
@vladzcloudius please provide the name of the metrics you think are useful
We do not want to include **all** metric in the dashboards.

**Comment by vladzcloudius** [comment]
@tzach All metrics with a "view" in their name (there isn't very many) plus coordinator and replica side write/read requests metrics. This would be a good start.
