### ISSUE TITLE
Add drill down chart for Thrift and CQL

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#56]
https://github.com/scylladb/scylla-grafana-monitoring/pull/55 sum Thrift and CQL on the same chart.
In some cases, it will be useful to break the data in to two charts, one for CQL and one for Thrift

**Comment by amnonh** [comment]
@tzach is this still relevant?

**Comment by tzach** [comment]
No. Thrift is not popular enough to deserve its own panel
