### ISSUE TITLE
Adding the Bad-ness Dashboard

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#576]
Adding a Dashboard that is dedicated to things that goes bad

**Comment by tzach** [comment]
Isnt this the optimization dashboard?

**Comment by amnonh** [comment]
No, the optimization dashboard is a dashboard that helps users identify problems with their cql model or configuration.

This dashboard is similar in its nature, it shows things that are not supposed to happen, but it shows scylla errors.

See #577

**Comment by amnonh** [comment]
Closed by #577
