### ISSUE TITLE
per-server disk I/O graphs are empty

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-monitoring#578]
dashboards for 2019.1 using monitoring branch-2.2

I/O Queue graphs are all empty

[grafana snapshot](https://snapshot.raintank.io/dashboard/snapshot/RUQ010jUKrw0PyZoPiCTlnLmMxAzpL7R)

**Comment by fgelcer** [comment]
@amnonh

**Comment by amnonh** [comment]
Please specify the version of the dashboard you are using and scylla version you are monitoring.

**Comment by fgelcer** [comment]
dashboards for 2019.1 using monitoring branch-2.2

**Comment by amnonh** [comment]
I see that https://github.com/scylladb/seastar/commit/c19219ed0f336d4e58c264e05118d4d11955fc28 is missing from seastar enterprise

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-enterprise/commit/8a220859a4233c7450081c28203a0e0fe836b94d
