### ISSUE TITLE
2019.1 scylla-per-server-disk-i-o dashboard: All Memtable Flush I/O and Streaming Reads/Writes graphs are empty

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-monitoring#580]
2019.1 scylla-per-server-disk-i-o dashboard.
All Memtable Flush I/O and Streaming Reads/Writes graphs are empty.
For example, Streaming reads class name should be changed from "streaming" to "streaming_read"

**Comment by amnonh** [comment]
Seems like a duplication of #578

**Comment by juliayakovlev** [comment]
> Seems like a duplication of #578

Does the 578  change class label name?

**Comment by amnonh** [comment]
#578 was a result of missing backport, the metric name and label were changed on seastar-master and were updated accordingly on 2019.1 dashboards.

I know that the changes in seastar were backported, so it should be resolved

**Comment by roydahan** [comment]
It’s not a duplicate!
In #578 the source was missing backport in seastar.
Here the query is wrong, the class name and the metric has mistakes.

**Comment by amnonh** [comment]
In #578 the missing backport in seastar, made it look like there is a problem with the metric name and labels

**Comment by roydahan** [comment]
Right, that’s why it’s not a duplicate.
This bug is with a later Scylla release that contains the backport.
And now the metric is wrong.

**Comment by juliayakovlev** [comment]
This is the example of correct query:
```
sum(irate(scylla_io_queue_total_bytes{class="streaming_read", instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[30s])) by ([[by]])
```

instead of:
```
sum(irate(scylla_io_queue_read_total_bytes{class="streaming", instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[30s])) by ([[by]])
```

**Comment by amnonh** [comment]
ok, I see that there are some instances of the old metric format
