### ISSUE TITLE
Compactions I/O Queue delay by Shard should be filtered by mountpoint as well

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-monitoring#588]
Currently the query is:
1000000*max(scylla_io_queue_delay{class="compaction", instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"} ) by ([[by]])

We should add: mountpoint="/var/lib/scylla"

Otherwise, it always shows 1s.

**Comment by amnonh** [comment]
which dashboard, which scylla version and which monitoring version

**Comment by roydahan** [comment]
Disk I/O
2019.1 but I think applies also to 3.0
Branch-2.3

**Comment by amnonh** [comment]
Scylla 3.0 uses a previous version of the metrics, I don't think it is needed
