### ISSUE TITLE
Add the option to limit/refine number of metrics, and which metrics, Scylla server export 

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#600]
Some user would like to limit the number of metrics we expose to the prometheus server.
For example in the node_exporter you can enable/disable collectors.
On the first level user would like to limit the number of metrics they do not require.
On a more granular level, users would like to be able to expose a table/key space metrics. Users can use the granular table metrics for billing application users.

**Comment by amnonh** [comment]
If the request is to limit the number of metrics Scylla expose, it should be open on the scylla git not scylla-grafana-monitoring
