### ISSUE TITLE
I/O queue information is not available in Prometheus

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#601]
Using:
Scylla 3.0.6 AMI
https://github.com/scylladb/scylla-grafana-monitoring/archive/scylla-monitoring-2.3.tar.gz

When looking at the io queue metrics it shows no data.
Looking into the query on Grafana, the charts are querying:
scylla_io_queue_query_delay
scylla_io_queue_query_total_bytes
scylla_io_queue_query_total_operations

However, the above metrics are not  present in the Prometheus server.

**Comment by tzach** [comment]
@amnonh please take a look

**Comment by amnonh** [comment]
Looks like an issue with Scylla, I have opened
https://github.com/scylladb/scylla/issues/4494
