### ISSUE TITLE
Add Slack template for alerting

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla-monitoring#609]
FEATURE ENHANCEMENT.

We are seeing a lot of customers who don't check the monitoring every day but want to plugin a slack connector for all kinds of alerts. Currently, we just have Pager Duty and Email integration available as a template.
We need to include a code sample in our Prometheus and Alert manager template with SLACK Integration. Also, the template should have a few sample metrics that the customer can use and eventually extend.

**Comment by amnonh** [comment]
You are confusing the alerts that are generated by Prometheus, and for which we already have examples, and the alertmanger configuration that can point to slack.

About a slack template, @tzach I don't have anything against adding slack example beside that it's one more thing we'll need to support.
I'm assigning it to you to make a decision, ok it and reassign to me, or close.

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
@mailmahee is this is what you are looking for:
https://prometheus.io/docs/alerting/notification_examples/#customizing-slack-notifications

**Comment by amnonh** [comment]
@mailmahee closing, you can reopen if that's not what you need

**Comment by mailmahee** [comment]
Sorry, the notifications from this were getting redirected to my personal email.

**Comment by mailmahee** [comment]
This was something that Fanatics requested and I thought it would be a nice enahancement to have. If it is not too much work to maintain, I would prefer we include it in the templates that we provide as part of the default installation. But if it is very hard to maintain, then we don't have to. It is up to you @amnon , I think it is important to relay what the customer requested.
