### ISSUE TITLE
add a graph for ad-hoc queries in all time-based dashboards for grafana

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#610]
Using prometheus directly is bad for two main reasons:
- For some customers, it is not available to us.
- We can't see ad-hoc queries in time-correlation with other metrics.

To solve that, I propose we add an empty graph to the existing dashboards, and use the information hover and a good title to let people know that this is a graph for ad-hoc queries.

**Comment by tzach** [comment]
We can title it: "Your query here"

**Comment by amnonh** [comment]
closed by #618
