### ISSUE TITLE
per-group CPU utilization in main dashboard

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#612]
Users often see CPU utilization (reactor load) at 100% and think the cluster is maxed out. But in fact, the cluster uses the spare CPU bandwidth for compaction/repair/whatever and can take more load.

So I think we need prominent indication of _where_ the CPU time is going. Something like a stacked chart with statement/flush/compaction/streaming components. Since we can't present this per node, it will have to be summed across the entire datacenter (and we'll need one chart per datacenter).

So if the user sees 100% reactor utilization, but also sees that the statement group has low utilization, they will know they can push more load.

**Comment by tzach** [comment]
@avikivity do we have the metrics?

**Comment by amnonh** [comment]
I'm not sure about the visualization, the following is how it looks with 3 nodes:
![image](https://user-images.githubusercontent.com/2118079/58879613-bb9cfc00-86de-11e9-9af5-9887e183d336.png)

This is how it looks like when choosing a specific node:
![image](https://user-images.githubusercontent.com/2118079/58879635-c3f53700-86de-11e9-802a-5ca9e9dfec5d.png)

I can sum it up per DC from the beginning or let the display change as the user switch between cluster/dc/node

**Comment by tzach** [comment]
I do not think summing CPU usage makes sense. The chart should be in the 0-100% scale

**Comment by amnonh** [comment]
the metric I used is scylla_scheduler_runtime_ms and the units are in ms, what we do in load, is using the avg, which make sense.

@avikivity if this makes sense to you, I'll create a PR

**Comment by amnonh** [comment]
@avikivity ping

**Comment by amnonh** [comment]
@avikivity ping

**Comment by amnonh** [comment]
@avikivity ping

**Comment by amnonh** [comment]
Closing with the changes in the CPU dashboard
