### ISSUE TITLE
Add node table to Overview dashboard

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#616]
The tables can include IP, DC, Status, release

IP | DC | Status | Release
---|-------|----------|------------
1.2.3.4| EU-1| UN | 3.0.6
2.3.4.5|EU-1|UN|3.0.5

* The IP should link to the per server dashboard for this node, similar to alert
* If possible, column headers can be used for ordering, filtering (spreadsheet-like)
* Dashboard level filtering should filter the table row

See also #151

**Comment by tzach** [comment]
@amnonh ?

**Comment by nirmaayan** [comment]
Following

**Comment by amnonh** [comment]
@tzach please see that you are assigned to review #614

**Comment by amnonh** [comment]
closing with #614
