### ISSUE TITLE
Add Loki log collection service to the monitoring stack

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#617]
[Loki](https://grafana.com/loki) is a Prometheus-inspired logging service, which works well with Grafana. It is still very new but can be a simple, out of the box solution for log collection.

**Comment by avikivity** [comment]
Before loki (which is alpha), we should add support for ordinary rsyslog. This provides a central place for logs instead of having to go to each server for its logs. rsyslog is available on all distributions and is integrated with syslog.

**Comment by tzach** [comment]
Loki is now in GA, and provide good integration with Grafana.

**Comment by amnonh** [comment]
@tzach @avikivity @slivne I would like to try and integrate loki,
it uses an agent that runs on the host and can read form journalctl
can we try to integrate it and see the effect?

**Comment by avikivity** [comment]
Why do people insist on agents?

Is there no way for loki to use the rsyslog protocol?

**Comment by amnonh** [comment]
Loki is a push-based server the agents push towards it.
I found an experimental adaptor for rsyslog that can push the logs into loki. It's un-official but we can give it a try.

**Comment by avikivity** [comment]
Please do, and open an issue for them to interoperate with rsyslog.

**Comment by amnonh** [comment]
it's the other way around, Loki is the passive side here, it's up to rsyslog to be able to push to loki

**Comment by avikivity** [comment]
No, rsyslog sends the data in its own format. Loki should listen on the rsyslog socket and accept it.

rsyslog is about 7,812 years old, you can't expect it to send data on the loki protocol.

**Comment by amnonh** [comment]
it has an extension mechanism to support different targets
