### ISSUE TITLE
cpu dashboard doesn't work well with workload prioritization

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#656]
We have been show foreground CPU time for some time now, which has been a life saver.

To compose the query, we sum the cpu time of the `main` and `statement` groups. However, once we use Workload Prioritization, the `statement` group  isn't used anymore. Other, per-workload groups are used instead.

We should change that to reflect the usage of workload prioritization. One possibility is to show one graph per class, including the internal ones, or hide the internal ones.

**Comment by amnonh** [comment]
Seems like a duplication of: #612
If so, please close this one and comment there (which @avikivity is not, though he opened the issue)

**Comment by glommer** [comment]
That issue actually refers to our already existing per-CPU dashboard - maybe Avi wasn't aware of that.

However our dashboard currently only tracks foreground time.
This issue is about the fact that if we use workload prio, even foreground time doesn't work (because the statement class is no longer used). One possible solution is to stop tracking foreground time - and instead showing a separate graph per class for all classes. This would work with workload prioritization as well, and also include more information.

But that's not the only possible solution. 

And BTW, we will very likely have a similar issue in the I/O dashboards. So I'd like to keep this issue open so we make sure all of our dashboards work well with Workload Prioritization, regardless of what the solution is.

**Comment by amnonh** [comment]
I agree about the IO dashboard, I'd like to break the current functionality and combine both to a single dashboard
