### ISSUE TITLE
Issue #308 was improperly closed

### ISSUE THREAD

**Issue by miltieIV2** [scylladb/scylla-monitoring#664]
@amnonh

The proper solution is fix genconfig.py and make_dashboards.py the same way all the other scripts were fixed: **use /usr/bin/env**, for folks with python, python2, python3 in /usr/local/bin in their path (all the Mac OSX Homebrew users).

**Comment by amnonh** [comment]
@miltieIV2 thanks for raising the issue.
In the new release (3.0) we are moving to python3 and we will use the opportunity to make this change as well.
