### ISSUE TITLE
scylla-cql-optimization and scylla-errors added to generate-dashboards.sh but not load-grafana.sh

### ISSUE THREAD

**Issue by miltieIV2** [scylladb/scylla-monitoring#665]
@amnonh

For folks that use load-grafana.sh directly, the two latest dashboards are missing.

**Comment by amnonh** [comment]
We have moved away from loading dashboards using the API towards using files.
This also impacts how dashboards are generated and tested.

Do you have a use case for loading dashboards using the API?

**Comment by miltieIV2** [comment]
I have used load-grafana.sh in the past and it was easy to use with my pre-existing Grafana installation. I guess it makes sense for load-grafana.sh to be a distinct step after genconfig.py and not have it attempt generation.
