### ISSUE TITLE
Fractional values for "timeouts" and "unavailable" panels on the scylla-per-server-metrics

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-monitoring#680]
When looking at the "write timeouts per instance" panel, we see fractional values because of the scrape period (5s or more). This is confusing for users since they see things like 0.4, 0.3, 0.1 wps timeouts per shard or instance. The query formula should account for this and provide the actual values (maybe using scrape_duration_seconds?).

cc: @rjeczalik

**Comment by gnumoreno** [comment]
Example screenshot.

![Screenshot from 2019-07-08 16-43-30](https://user-images.githubusercontent.com/7240118/60837845-a7e22b00-a19f-11e9-84db-d5c955d0818b.png)

**Comment by rjeczalik** [comment]
Also it would be worth considering whether the graph type is correct for this kind of data - maybe histogram over time with timeout step would be more appropriate instead of line graph?
