### ISSUE TITLE
Need Dashboard for Scylla Manager 2.0

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#683]

**Comment by amnonh** [comment]
@ajankovic please add the relevant metrics here (or open a new issue) and I'll take it from there

**Comment by mmatczuk** [comment]
Please find the relevant info here https://github.com/scylladb/mermaid/commit/08e0346cd45746205fb376a0ee69cafe68c0f888

**Comment by amnonh** [comment]
Thanks

**Comment by amnonh** [comment]
Closed by #792
