### ISSUE TITLE
Grafana to display the monitor stack version

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#689]
Currently, the only way to view the monitor version you are working with is by running:
```
./start-all.sh --version
```

It would make it easier, especially for multiple deployment if you can view the monitor stack version on Grafana.

**Comment by tzach** [comment]
Good point
This should be injected to the dashboard somehow

**Comment by amnonh** [comment]
@tzach do we want to add an about page?

**Comment by tzach** [comment]
> @tzach do we want to add an about page?

Its a valid solution
A release number in each dashboard footer/header might be easier to find

**Comment by amnonh** [comment]
To begin the about dashboard would hold the Scylla Monitoring version, link to the documentation and to the git
