### ISSUE TITLE
Separate alerts for Node-Exporter-Down and Scylla-Service-Down

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#699]
For hours we received false alerts from AlertManager regarding 34.242.55.171 that was down.

We kept checking it's "nodetool status" only to realize it's working. There were no error logs both on the server or any of the other nodes on the cluster.

We tried resizing the monitor instance size, increase the alert times, check if it's due to backups. Nothing worked, we kept receiving false alerts.

Finally, I've noticed that one of the fields in the alert were "job = node_exporter" realizing that it was the "node_exporter" service down and not the Scylla service.

After 6 months of warnings, we are all wired to think of InstanceDown as Scylla server being down. 

Let's separate it to two separate alerts, one for "NodeExporterDown" and one for "InstanceDown" or "ScyllaServerDown".

**Comment by amnonh** [comment]
Solved by 00366fdc55622d376662e5f6c62bb3ec87d6aed2
