### ISSUE TITLE
Increase global scrapping timeout to at least 10s

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#704]
We experienced issues where remote servers (cross-region) with a lot of traffic would show as inactive even though they were fully operational. 

Increasing the scrapping to 10s solved the issue.

**Comment by tzach** [comment]
A previous iteration of this discussion in #147

**Comment by amnonh** [comment]
Following #147, I'm closing the issue, users can change the scrap interval if needed
