### ISSUE TITLE
Add values to the node table

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#709]
We can replace CPU with the reactor load, cql with the total number of queries etc'

**Comment by tzach** [comment]
I do not think values are very useful compared to graphs we already have

**Comment by amnonh** [comment]
It's in the node table, for example:
![image](https://user-images.githubusercontent.com/2118079/62540728-eb908900-b860-11e9-8bdc-8a3979167183.png)

**Comment by tzach** [comment]
I understand I do not think it adds much value
