### ISSUE TITLE
Does Prometheus have a phantom data directory?

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#71]
The system I use have 3 servers, I see all of them are working and active through Nodetool, still I get that I have a dead node. and the information on the metrics is way off.
I Can't get rid of a phantom data, that keeps creeping on the system.
After deleting the docker volumes, reinstalled docker, reinstalled the grafana tool. Some phantom data keeps coming back, cleared the browser cache and killed the collector exporters on the servers.
Is it possible to have a way to clear all history data the tool has accumulated in the past?
./kill-all.sh only removes the current docker nodes running, and it is not clearing the information.
![image](https://cloud.githubusercontent.com/assets/17868115/19064951/87848c3a-89c5-11e6-8236-09dbdb182329.png)

**Comment by tzach** [comment]
@eyalgutkind can you please try
`sudo docker rmi aprom agarf` after running `kill-all.sh`?
Thanks

**Comment by eyalgutkind** [comment]
In my case I had to remove the hash number for the images 
docker rmi e180d8c8c83c9e937cd53cd35441aff8afdcc675e8381841fccdaf1375a5cd11
By name it didn't work.
Also, the dead node insist it is there.... after deleting everything.
Also, what is the decision criterion for the name of the instance Prometheus decide to fetch data by?

On the network metrics, the information is taken by the host name (say: instance: "scylladb1")
![image](https://cloud.githubusercontent.com/assets/17868115/19101613/8fda3e98-8a7e-11e6-96b4-37c2a971845e.png)

However, on the load metric it doesn't capture the hostname (say: localhost.localdomain) :
![image](https://cloud.githubusercontent.com/assets/17868115/19101633/af4e87d4-8a7e-11e6-9add-7a3305395704.png)

**Comment by tzach** [comment]
The network metrics are reported directly from collectd interface plugin, while load metric is coming from scylla. 
Both are going to change on 1.4
@amnonh can you validate this point for 1.4?

**Comment by tzach** [comment]
@eyalgutkind could it be that the Scylla server report old data (not the monitoring present old data)?
Go to scylla server 9103 port, and look for out of date metrics

**Comment by amnonh** [comment]
prometheus does remember values and metric names between sessions

**Comment by tgrabiec** [comment]
@eyalgutkind Scylla exports metrics (e.g. load) using `$(hostname)` as host name. You can override it by passing `--collectd-hostname xxx` on Scylla's command line.

Alternatively, you can tell prometheus to ignore the hostname tag which comes with collectd metrics, and use the ip as configured for given source in `prometheus.yml`. To do that, change `honor_labels` to false in prometheus.yml. Downside of this change is that you can't have one exporter for a collectd instance which gathers metrics from multiple nodes.

**Comment by tgrabiec** [comment]
@eyalgutkind About the dead node counter, the query for it looks like this `count(up)-count(collectd_processes_ps_code{processes="scylla"}>0)`. It counts how many exporters are up and subtracts from that how many `scylla` processes there are. For counting processes it relies on some collectd plugin (tzach: which?). Maybe you don't have that plugin included on your Scylla nodes?

**Comment by tzach** [comment]
@tgrabiec you are right on the money.
The problem was with the processes plugin.

**Comment by tzach** [comment]
> About the dead node counter, the query for it looks like this count(up)-count(collectd_processes_ps_code{processes="scylla"}>0)

This is less than ideal, see #65 on the same subject

**Comment by amnonh** [comment]
Can we close this issue?

**Comment by tzach** [comment]
Closing since this issue no longer exist.
