### ISSUE TITLE
Graph to show server restarts over time

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#712]
Today if you want to have an indication if a server went through a restart over a big period of time (for example two weeks) it's hard to see it. 

An easy indication would be to have a graph of `scylla_gossip_heart_beat`. Then you would see a big drop and rise in the number and it would outstand over large periods.

**Comment by dorlaor** [comment]
Good idea!
If we can track beyond this (separately) to track the uptime of the cluster
it will be great (but hard)

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/1234

**Comment by amnonh** [comment]
A preview of the suggested panel
![image](https://user-images.githubusercontent.com/2118079/63222339-4c985500-c1af-11e9-85af-71a4144af88b.png)

**Comment by tzach** [comment]
@amnonh using a line chart looks weird here. It makes it look like there were 0.5 restarts at some point in time. Also, the Y-axis is basically 0 or 1
A bar graph will be better since it does not show 1/2 value.
The best will be to use annotation like markers, or [status map](https://grafana.com/grafana/plugins/flant-statusmap-panel)

**Comment by amnonh** [comment]
As you can see the legend is in integer numbers, values can be more than one if you group by DC or cluster.

This is how it looks with bar graph (accumulative to support multiple restarts)
![image](https://user-images.githubusercontent.com/2118079/63223173-38a62080-c1ba-11e9-9260-f2b6da267b2f.png)

**Comment by noamha** [comment]
Looks good to me. As long as it's sticking out.

**Comment by amnonh** [comment]
This is an example using annotations:
![image](https://user-images.githubusercontent.com/2118079/63224365-aa3a9a80-c1cb-11e9-9ce1-63f099f5f81b.png)

**Comment by tzach** [comment]
Can you add text to the annotation, as: "node 1.2.3.4 restart" ?

**Comment by amnonh** [comment]
There is a hover, and it looks like:
![Screenshot from 2019-08-18 15-34-46](https://user-images.githubusercontent.com/2118079/63224516-eec73580-c1cd-11e9-9d88-2e52ae3fd7bd.png)

**Comment by tzach** [comment]
Adding such annotation on the cluster view dashboard will be super useful
