### ISSUE TITLE
Illogical values in Compactions CPU Runtime

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-monitoring#718]
Version: 3.0
In the Detailed dashboard, The graph of `Compactions CPU Runtime` shows values in the hundreds of percents. Do those values make sense?

![Screenshot from 2019-08-22 14-45-47 (copy)](https://user-images.githubusercontent.com/40186893/63512461-90ab9280-c4ec-11e9-92c1-158b3bdf57a7.png)

**Comment by tzach** [comment]
Nice catch @ShlomiBalalis
