### ISSUE TITLE
After upgrading, all of the graphs of the I/O dashboard are empty

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-monitoring#719]
After upgrading from version 2.4 to 3.0, the graphs in the I/O dashboard are completely empty.
Image for clarification:
![Screenshot from 2019-08-22 14-56-01 (copy)](https://user-images.githubusercontent.com/40186893/63512720-2810e580-c4ed-11e9-8f52-227777077d30.png)

**Comment by amnonh** [comment]
Duplication of #716 716
