### ISSUE TITLE
Graph duplication issue after upgrade

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-monitoring#720]
After upgrading from version 2.4 to 3.0, for a few minutes after the upgrade, in the graph `Disk Size by Instance` there are 2 values for each of the instances:
![Screenshot from 2019-08-22 15-06-19 (copy)](https://user-images.githubusercontent.com/40186893/63514100-7ecbee80-c4f0-11e9-858c-e0211dd4bf31.png)

**Comment by amnonh** [comment]
It's a known thing during the upgrade and is documented
