### ISSUE TITLE
Data about the manager no longer appears after upgrade

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-monitoring#721]
After upgrading from version 2.4 to 3.0, the Scylla manager metrics dashboard no longer collects data from the manager: 
![Screenshot from 2019-08-22 15-37-32 (copy)](https://user-images.githubusercontent.com/40186893/63515258-192d3180-c4f3-11e9-8897-627ebd54b903.png)

**Comment by amnonh** [comment]
From the screenshot you posted, the manager is not connected, please make sure you are using the correct scylla_manager.yml file

**Comment by ShlomiBalalis** [comment]
The yaml file was not the issue, but it seems I needed to use the -l flag with start all. Now it seem to work fine. Closing!
