### ISSUE TITLE
Units "ops" is too ambigous

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-monitoring#737]
In many graphs, including in particular the "CQL - coordinator" panel (e.g., CQL Updates), the units are "ops". It's not clear what this means... Is this simply a shorthand of "operations"? Or perhaps an acronym of "operations per second"? It must be the latter given the context of these graphs, but the shorthand "ops" is needlessly ambiguous and confusing.

How about "op/s", i.e., "operation" per second? I think it will be much clearer.
Another common shorthand is "rps" - requests per second.

**Comment by amnonh** [comment]
ops - operation per seconds are one of the types that are supported natively by the Grafana.

for specific requests like read/write we can use specific types, we don't have that for CQL operations.

In general, when possible, it's best to use grafana types, so grafana would know how to format the graph for different values. (ie. see bytes for example)

**Comment by tzach** [comment]
https://github.com/grafana/grafana/issues/2968

**Comment by nyh** [comment]
Amnon, you are right that this is a Grafana bug - the commit: https://github.com/grafana/grafana/pull/3148/commits/b678daa744ea78cf4b3928a11080b8fd86aeb30e introduced this "ops" name. It contains this gem:
```
{text: 'ops/sec (ops)',       value: 'ops' },
```
This, in a nutshell, demonstrates how stupid and ambiguous this name is: What is "ops"? It's "ops/sec" !!!! (with "ops/sec" meaning operations per second, as any English-speaker will read "ops").

It's not "best to use grafana types" if they suck, are ambiguous and confusing, and if we have an option to use our own units.

I really think "ops" is a bad mistake, and I can't believe I'm the first user complaining about it.

**Comment by nyh** [comment]
I opened https://github.com/grafana/grafana/issues/18983
But I don't think we should wait for them to change it, if we can do it ourselves (can we? https://github.com/grafana/grafana/issues/2968 suggests users can't add units?).

One thing we could have done is to use the unit "rps" - for "requests per second" instead. However, Grafana officially says that "rps" means "reads per second" - so if this long form is shown anywhere, we cannot use it as "request per second".

**Comment by amnonh** [comment]
Grafana 6.6 will support custom units, so we can add that when it will be available and we'll update.

Depends on #801

**Comment by amnonh** [comment]
https://grafana.com/blog/2020/01/27/grafana-v6.6-released/#custom-data-units
