### ISSUE TITLE
Should we add Scylla datasource to grafana?

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#739]
Grafana has data source plugins for multiple databases, we can add our own

**Comment by tzach** [comment]
[KairosDB](https://kairosdb.github.io/) work with [Scylla backend](https://www.scylladb.com/2018/03/20/kairosdb-scylla-performance-scalability/) and used as [data source for Grafana](https://grafana.com/docs/v4.0/datasources/kairosdb/) (not sure its still is)

**Comment by amnonh** [comment]
https://grafana.com/docs/grafana/latest/developers/plugins/backend/

**Comment by amnonh** [comment]
Fixed by #1023
