### ISSUE TITLE
add count of large partitions to monitoring

### ISSUE THREAD

**Issue by yksdb** [scylladb/scylla-monitoring#747]
Is it possible to add the count of large partitions to Scylla Monitoring? The data comes from  system.large_partitions table. Ideally, the value of a threshold would be included as well.

This feature is requested in https://supportscylladb.zendesk.com/agent/tickets/834

**Comment by amnonh** [comment]
It's already been discussed, probably will end up in the CQL dashboard

**Comment by amnonh** [comment]
Closing as it is cover by the CQL large, rows, partitions and cells
