### ISSUE TITLE
Data moved from old monitoring (2.2) to new one (2.4) does not show any information on grafana

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-monitoring#748]
We moved all the prometheus data (monitoring 2.2) to a new server (monitoring 2.4) 

While prometheus clearly ingested the data, it does not show up in the grafana dashboards.

We've tried with both yaml versions (with and without labels):

```
- targets: ['10.152.43.158:9180', '10.152.44.18:9180', '10.152.40.35:9180']
``` 

```
- labels:
cluster: opscluster
dc: dc1
targets:
- 10.152.43.158
- 10.152.44.18
- 10.152.40.35
```

I'm attaching the prom and graf logs, and screenshots from both prometheus (showing the data) and grafana (without the data). Funny thing, grafana show total requests but nothing else. 

@amnonh  Please advise.
![FireShot Capture 006 - Grafana - Scylla Overview Metrics - 10 152 41 160](https://user-images.githubusercontent.com/7240118/65273025-9bab1000-daf6-11e9-8e8b-1ed16623faca.png)
![FireShot Capture 007 - Grafana - Scylla Per Server Metrics - 10 152 41 160](https://user-images.githubusercontent.com/7240118/65273026-9bab1000-daf6-11e9-8390-8d2691fd1e95.png)
![FireShot Capture 008 - Prometheus Time Series Collection and Processing Server - 10 152 41 160](https://user-images.githubusercontent.com/7240118/65273027-9bab1000-daf6-11e9-8dfa-1fc6d41bb94d.png)

[graf.txt](https://github.com/scylladb/scylla-monitoring/files/3632790/graf.txt)
[prom.txt](https://github.com/scylladb/scylla-monitoring/files/3632791/prom.txt)

**Comment by eyalgutkind** [comment]
@amnonh what can we do to help the user?

**Comment by amnonh** [comment]
Is there a cluster and DC configuration?
I don't see it is part of the metrics labels

**Comment by gnumoreno** [comment]
@amnonh it was tried with both as you can see on the yamls. (There are 2 yamls in the ticket in the case you missed that).

**Comment by amnonh** [comment]
It's unclear in the ticket if the labels are miss indent or is it just the
copy and paste.

**Comment by gnumoreno** [comment]
When the yaml is not parseable it throws an error, doesn't it? It is not throwing any errors.

**Comment by meenaven** [comment]
Hi any update on this

**Comment by meenaven** [comment]
I am the user facing the issue while moving monitoring from one server to another with the data, let me know if u have any questions

**Comment by amnonh** [comment]
In the ticket it seems there is an issue with the indentation of the
cluster and dc labels, can you please verify that it is indented correctly?

**Comment by meenaven** [comment]
u mean the new node ?

**Comment by meenaven** [comment]
[root@ip-10-152-41-160 scylla-monitoring-scylla-monitoring-2.4]# cd myconf/
[root@ip-10-152-41-160 myconf]# ls -ltr
total 8
-rw-r--r--. 1 root root 112 Sep 19 18:23 scylla_servers.ymlbkup
-rw-r--r--. 1 root root  76 Sep 19 18:24 scylla_servers.yml
[root@ip-10-152-41-160 myconf]# cat scylla_servers.yml
- targets: ['10.152.43.158:9180', '10.152.44.18:9180', '10.152.40.35:9180']
[root@ip-10-152-41-160 myconf]# cat scylla_servers.ymlbkup 
- labels:
    cluster: opscluster
    dc: dc1
  targets:
  - 10.152.43.158  
  - 10.152.44.18
  - 10.152.40.35 
[root@ip-10-152-41-160 myconf]#

**Comment by meenaven** [comment]
we are using the scylla_servers.yml now.

**Comment by amnonh** [comment]
It seems there is a missing indentation in the label part,
Can you please send me the scylla_servers.yml file, I want to see that it
is indented correctly

This is how it looks like in the ticket:

```
- labels:
cluster: opscluster
dc: dc1
targets:
- 10.152.43.158
- 10.152.44.18
- 10.152.40.35
```

This is how it should look like:

```
- labels:
    cluster: opscluster
    dc: dc1
  targets:
  - 10.152.43.158
  - 10.152.44.18
  - 10.152.40.35
```

**Comment by meenaven** [comment]
[root@ip-10-152-41-160 prometheus]# cat scylla_servers.yml 
- labels:
    cluster: opscluster
    dc: dc1
  targets:
  - 10.152.43.158
  - 10.152.44.18
  - 10.152.40.35
[root@ip-10-152-41-160 prometheus]#

**Comment by meenaven** [comment]
I just generated with genconfig

**Comment by meenaven** [comment]
its like this in my file
[root@ip-10-152-41-160 myconf]# cat scylla_servers.ymlbkup 
- labels:
    cluster: opscluster
    dc: dc1
  targets:
  - 10.152.43.158  
  - 10.152.44.18
  - 10.152.40.35

**Comment by meenaven** [comment]
when I paste it in the scylla zen desk ticket its changing. I just pasted again there and the indentation is messed there

**Comment by meenaven** [comment]
```[root@ip-10-152-41-160 myconf]# cat scylla_servers.ymlbkup 
- labels:
    cluster: opscluster
    dc: dc1
  targets:
  - 10.152.43.158  
  - 10.152.44.18
  - 10.152.40.35 
[root@ip-10-152-41-160 ```

**Comment by meenaven** [comment]
any update on this

**Comment by amnonh** [comment]
@meenaven from what I can see in your metrics, there is an issue with the labels.
I can't figure out why from what you sent.

In your Prometheus dashboard (the one on port 9090), under status can you check the targets tab and configuration tab?

I also have a hard time understanding how come you do see the cluster name in the dashboard but not in the metric.

one last thing, just to make sure we're debugging the right problem, can you check the in grafana under setting/datasource what is the Prometheus data source ip/port?

**Comment by meenaven** [comment]
where is datasource under Grafana settings

**Comment by meenaven** [comment]
![Screen Shot 2019-09-30 at 1 04 52 PM](https://user-images.githubusercontent.com/37941363/65912390-f78d5880-e382-11e9-980c-858eac3ecf5d.png)

**Comment by meenaven** [comment]
it looks good

**Comment by amnonh** [comment]
@meenaven I still can't find anything wrong, it all looks correct, but still the issue exists.

In your Prometheus dashboard (the one on port 9090), under status can you please add a snapshot of the targets tab and the configuration tab?

also, please make sure you only have one set of scylla monitoring running by running

`docker ps`

can you run `kill-all.sh` follow by `start-all.sh` and send me the full command line you used for `start-all.sh`

**Comment by meenaven** [comment]
[root@ip-10-152-41-160 scylla-monitoring-scylla-monitoring-2.4]# docker ps
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS                    NAMES
5d9fe63307cb        docker.repo.frg.tech/grafana/grafana:5.4.2       "/run.sh"                About an hour ago   Up About an hour    0.0.0.0:3000->3000/tcp   agraf
f58f84219790        docker.repo.frg.tech/prom/prometheus:v2.7.2      "/bin/prometheus -..."   About an hour ago   Up About an hour    0.0.0.0:9090->9090/tcp   aprom
163c85ef400f        docker.repo.frg.tech/prom/alertmanager:v0.16.0   "/bin/alertmanager..."   About an hour ago   Up About an hour    0.0.0.0:9093->9093/tcp   aalert
[root@ip-10-152-41-160 scylla-monitoring-scylla-monitoring-2.4]#

**Comment by meenaven** [comment]
./start-all.sh -s ./myconf/scylla_servers.yml -d /var/lib/scylla/scylla-mon/scylla-monitoring-scylla-monitoring-2.4/mydata -v 2019.1,3.0 -M 1.4

**Comment by amnonh** [comment]
Can you please add those two tabs from the prometheus status page?

**Comment by meenaven** [comment]
global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 1m
  external_labels:
    monitor: scylla-monitor
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.17.0.2:9093
    scheme: http
    timeout: 10s
rule_files:
- /etc/prometheus/prometheus.rules.yml
scrape_configs:
- job_name: scylla
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/scylla_servers.yml
    refresh_interval: 5m
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)
    target_label: __address__
    replacement: ${1}:9180
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*):.+
    target_label: instance
    replacement: ${1}
    action: replace
- job_name: node_exporter
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/node_exporter_servers.yml
    refresh_interval: 5m
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):\d+
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:9100
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: node_disk_read_bytes_total
    target_label: __name__
    replacement: node_disk_bytes_read
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_disk_written_bytes_total
    target_label: __name__
    replacement: node_disk_bytes_written
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_disk_reads_completed_total
    target_label: __name__
    replacement: node_disk_reads_completed
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_disk_writes_completed_total
    target_label: __name__
    replacement: node_disk_writes_completed
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_filesystem_avail_bytes
    target_label: __name__
    replacement: node_filesystem_avail
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_network_receive_bytes_total
    target_label: __name__
    replacement: node_network_receive_bytes
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_network_receive_packets_total
    target_label: __name__
    replacement: node_network_receive_packets
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_network_transmit_bytes_total
    target_label: __name__
    replacement: node_network_transmit_bytes
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_network_transmit_packets_total
    target_label: __name__
    replacement: node_network_transmit_packets
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: node_filesystem_size_bytes
    target_label: __name__
    replacement: node_filesystem_size
    action: replace
- job_name: scylla_manager
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/scylla_manager_servers.yml
    refresh_interval: 5m
  metric_relabel_configs:
  - source_labels: [host]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
- job_name: prometheus
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

**Comment by meenaven** [comment]
![FireShot Capture 009 - Prometheus Time Series Collection and Processing Server - 10 152 41 52](https://user-images.githubusercontent.com/37941363/65980733-96ba5a80-e42c-11e9-8531-01662af44d44.png)

**Comment by amnonh** [comment]
@meenaven 
Everything still looks correct, in your targets I see the right dc and cluster but it's not there when looking at the metrics you posted (the first image with the values).

@gnumoreno I contacted you directly about access, please see my email

**Comment by meenaven** [comment]
this is the scylla servers file in the old monitoring server. i am getting what u are saying 
here no DC is mentioned 

[root@ip-10-152-44-105 myconf]# cat scylla_servers.yml 
- targets: ['10.152.43.158:9180', '10.152.44.18:9180', '10.152.40.35:9180']
[root@ip-10-152-44-105 myconf]#

**Comment by meenaven** [comment]
so if this is the case we can never get the old data and new data together

**Comment by amnonh** [comment]
I'll see what I can do

**Comment by amnonh** [comment]
I've opened #752 to better capture the issue

**Comment by amnonh** [comment]
try the newer 2.4 release and see if it works

**Comment by meenaven** [comment]
what u mean try new release ? the old monitoring node is having the old version 2.2
the new monitoring node is having 2.4 version . we are trying to move data from 2.2 t0 2.4 

so what u mean by try newer 2.4 release

**Comment by gnumoreno** [comment]
@meenaven What he means is that he added some fixes to 2.4 release. 
See the commits here:
`https://github.com/scylladb/scylla-monitoring/compare/scylla-monitoring-2.4...branch-2.4`

So there is a new tar.gz of 2.4 that you can use and see if the fixes resolves the problem for you:

`https://github.com/scylladb/scylla-monitoring/archive/scylla-monitoring-2.4.tar.gz`

**Comment by meenaven** [comment]
is that there in the repo ?

**Comment by amnonh** [comment]
It is, I'm closing the issue
