### ISSUE TITLE
Scylla Monitoring matrix claims that Manager 1.3 is compatible but the 1.3 template is not there. Please add.

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-monitoring#749]
### Matrix

https://docs.scylladb.com/operating-scylla/monitoring/matrix/

### Missing Manager 1.3 template in 2.4 Monitoring

Scylla Monitoring matrix claims that Manager 1.3 is compatible but the 1.3 template is not there. Please add.

https://github.com/scylladb/scylla-monitoring/tree/branch-2.4/grafana

**Comment by amnonh** [comment]
I've added the dashboard
