### ISSUE TITLE
"Foreground reads" graph actually shows all active reads, including background reads

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#75]

**Comment by amnonh** [comment]
The graph is mapped to the read-queue length, should we change the title or the metric?

**Comment by tgrabiec** [comment]
I think the reads  counter shows what it should, all reads.  We should change the formula for fg reads to subtract background reads. There is no counter for foreground reads currently

**Comment by amnonh** [comment]
@tgrabiec  With the move to the new counters, can we close this?

**Comment by tgrabiec** [comment]
@amnonh Can you point to the commit which fixes the issue?

**Comment by amnonh** [comment]
https://github.com/scylladb/scylla-grafana-monitoring/commit/9cf4e19ab5d2ac8203067513d31ebe0026751582

**Comment by tgrabiec** [comment]
Fixed by https://github.com/scylladb/scylla-grafana-monitoring/commit/9cf4e19ab5d2ac8203067513d31ebe0026751582
