### ISSUE TITLE
query error for overview/nodes panel when multiple clusters are added to targets

### ISSUE THREAD

**Issue by rjeczalik** [scylladb/scylla-monitoring#750]
Multiple clusters are added to scrape_configs, nodes are added by a private IP, there can be two nodes from different clusters that have the same private IP, which makes the query for nodes panel to fail with the following error:

`found duplicate series for the match group {instance="172.31.0.11"} on the right hand-side of the operation: [{name="scylla_node_operation_mode", cluster="#1835", dc="AWS_EU_WEST_1", exported_instance="ip-172-31-0-11.eu-west-1.compute.internal", instance="172.31.0.11", job="scylla", monitor="scylla-monitor", shard="0", type="gauge"}, {name="scylla_node_operation_mode", cluster="#1834", dc="AWS_US_EAST_1", exported_instance="ip-172-31-0-11.ec2.internal", instance="172.31.0.11", job="scylla", monitor="scylla-monitor", shard="0", type="gauge"}];many-to-many matching not allowed: matching labels must be unique on one side"`

![ss](https://i.imgur.com/XmrU91A.png)

**Comment by amnonh** [comment]
@rjeczalik 
Just to validate are the clusters separated by cluster name?
