### ISSUE TITLE
Disk storage: show a red line per compaction strategy 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#756]
To stay in the safe zone, users need to keep their storage below ~50% for SCTS
and below ~80% for ICS.
We should present a watermark for each, letting them know how soon they should add storage.

**Comment by tzach** [comment]
@bhalevy FYI

**Comment by amnonh** [comment]
do we want a fixed-line all the time regardless of what compaction is used?

**Comment by amnonh** [comment]
@tzach see my last comment

**Comment by tzach** [comment]
> do we want a fixed-line all the time regardless of what compaction is used?

No. The idea is to reflect the fact different strategies needs more or less free space.

**Comment by amnonh** [comment]
ok, but CL is on the keyspace level, so what do you want to represent here?

**Comment by tzach** [comment]
> ok, but CL is on the keyspace level, so what do you want to represent here?

Do you mean RF? CL is set in the driver
How is it related? with SCTS one needs 50% of the storage free for compactions, with ICS, only 20% (@bhalevy please correct me here). How does the RF effect that?

**Comment by amnonh** [comment]
I meant compaction strategy

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
I do not understand what should I provide
See my answer above: the line should be base on compaction strategy.

**Comment by amnonh** [comment]
@tzach The question is what compaction strategy? one for each?

**Comment by tzach** [comment]
On second thought, this is only relevant per table dashboard which we do not have.

**Comment by amnonh** [comment]
right, that was my original comment, closing
