### ISSUE TITLE
Test Monitoring with IPv6

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#757]
In some deployment, Scylla will work with IPv6 for internal and external communication.
Need to validate the monitoring stack works correctly with these IPs

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/2027

**Comment by amnonh** [comment]
I've tested and it's working (both the monitoring and nodetool status), I'll list my findings below (but it's supposed to reach the documentation)

I have encountered the expected ipv6 problem that is not monitoring specific, so after that is working (it's not enough that scylla starts, it needs to be able to use the network).

# Configuration on Scylla side:
### setting Scylla address
in *scylla.yml*
Set the Prometheus to listen on the ipv6 address
```
prometheus_address: 2600:1f18:26b1:3a00:fac8:118e:9199:67b9
```
### setting node_exporter address
in */usr/lib/systemd/system/node-exporter.service* 

```
ExecStart=/usr/bin/node_exporter  --collector.interrupts --web.listen-address="[2600:1f18:26b1:3a00:fac8:118e:9199:67b9]:9100"
```
Restart both services
# On the monitor side
In the monitoring *scylla_server.yml* file

```
- targets:
    - "[2600:1f18:26b1:3a00:fac8:118e:9199:67b9]:9180"
```
Both the quote and the port is important for things to work.

## Prometheus side results
![image](https://user-images.githubusercontent.com/2118079/66938811-8b7d4680-f04a-11e9-8a60-057fc50e0749.png)

## Grafana side results
![image](https://user-images.githubusercontent.com/2118079/66939229-56252880-f04b-11e9-8d99-920e4af17349.png)

**Comment by amnonh** [comment]
@tzach Closing this one, we can open a documentation issue if you think it is needed

**Comment by tzach** [comment]
https://github.com/scylladb/scylla-docs/issues/2183
