### ISSUE TITLE
Ctor undefined template

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla-monitoring#764]
After upgrading from master

Message: 
```
Templating Init Failed

Cannot read property ctor of undefined
```

**Comment by amnonh** [comment]
Please add information, where did you see that error? what did you run?

**Comment by fggarcia** [comment]
Hi @amnonh this bug occur in any page.

![image](https://user-images.githubusercontent.com/1306596/67423071-fd551300-f5a9-11e9-9ee3-90ea7d3b8524.png)

I upgrade from commit (no bugs)

![image](https://user-images.githubusercontent.com/1306596/67423148-19f14b00-f5aa-11e9-98fd-7e95ee50f2ba.png)

to 

![image](https://user-images.githubusercontent.com/1306596/67423183-29709400-f5aa-11e9-98c5-0b1dedda1ca4.png)
