### ISSUE TITLE
30s is too short with larger scrap interval

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#767]
we used irate in many places with 30s
When the scrap interval plus timeout is near that value, it will no longer work.

We should change their time to 60s, so in case of a missing point, they would continue to report their value.

**Comment by tzach** [comment]
Can we make it scrap interval * 2?

**Comment by amnonh** [comment]
scrap interval is defined per target and not global. Because we are no longer generating the dashboard on the fly, it will be complicated to push that value from the prometheus configuration to the grafana dashboards
