### ISSUE TITLE
collectd disk metrics are showing distorted rates

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#77]
Example:

![disk_stats](https://cloud.githubusercontent.com/assets/283695/19811856/81cfee20-9d33-11e6-95cf-a86d61f572c7.png)

The actual rate is around 400 and doesn't vary as much in reality as it is shown on the graph.

The rates are calculated by taking difference between consecutive samples of monotonic counters. Collectd emits samples with 10 second period, while prometheus samples them by default with 15 second period. So half of the time the period between prometheus samples will cover 1 collectd sample and half of the time it will cover 2 samples. The former will underestimate the rate and the latter will over estimate it. 

To avoid this, the sampling period used by prometheus must be a multiply of collectd period. We can set the scraping interval to `10s`, or modify the collectd plugin to export stats with `1s` period. The latter approach is better because it gives better accuracy and works with any scrape period.

**Comment by tgrabiec** [comment]
Current value of `15s` scrape period is probably chosen so that there is no distortion in Scylla metrics, which are exported by default with `3s` period. So `10s` period wouldn't work with that.

**Comment by tgrabiec** [comment]
Related collectd_exporter issue https://github.com/prometheus/collectd_exporter/issues/24

**Comment by tzach** [comment]
Scylla 1.4 will not use collectd_exporter, so this issue might not be relevant looking forward

**Comment by amnonh** [comment]
Can we close that?
