### ISSUE TITLE
3.1 IO metrics Compactions I/O Queue IOPS by [[by]]

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#770]
not displaying anything - missing mount_point (I think)

![copactions_io_queue_iops](https://user-images.githubusercontent.com/3465480/67696130-f87bcf00-f9ae-11e9-871a-af55596079bd.png)

**Comment by amnonh** [comment]
@slivne what monitoring (not scylla) version are you using?

**Comment by slivne** [comment]
branch-3.0 115b7b0ef7d295d628b14f96ca1e9913f0b28030

**Comment by amnonh** [comment]
We need to decide if we want to backport it, or branch 3.1

**Comment by amnonh** [comment]
closed in 3.0.2
