### ISSUE TITLE
Add lightweight transaction metrics (aka CAS) to default dashboard

### ISSUE THREAD

**Issue by locker** [scylladb/scylla-monitoring#775]
Here's a list of metrics added for monitoring lightweight transactions performance:

1. Storage proxy layer.

   ```
   scylla_storage_proxy_coordinator_cas_read_latency
   scylla_storage_proxy_coordinator_cas_write_latency
   scylla_storage_proxy_coordinator_cas_read_timeouts
   scylla_storage_proxy_coordinator_cas_write_timeouts
   scylla_storage_proxy_coordinator_cas_read_unavailable
   scylla_storage_proxy_coordinator_cas_write_unavailable
   scylla_storage_proxy_coordinator_cas_read_unfinished_commit
   scylla_storage_proxy_coordinator_cas_write_unfinished_commit
   scylla_storage_proxy_coordinator_cas_write_condition_not_met
   scylla_storage_proxy_coordinator_cas_read_contention
   scylla_storage_proxy_coordinator_cas_write_contention
   ```

   See commit https://github.com/scylladb/scylla/commit/c27ab87410a03c57418494a522a909055caebbfc for more details.

2. CQL layer. New tag "conditional" has been added to a few CQL metrics. If set to "yes" for a particular metric, then the metric accounts statements that have IF conditions, otherwise - those that don't. Here's a list of metrics that now have the tag:

   ```
   scylla_cql_inserts
   scylla_cql_updates
   scylla_cql_deletes
   scylla_cql_batches
   scylla_cql_statements_in_batches
   ```

   See commits https://github.com/scylladb/scylla/commit/f0075ba8457268ef105bdd7f01b52bd1d48dc25c and https://github.com/scylladb/scylla/commit/9ea8114f8cfc9b67b17c7cd65591d93733acf01b for more details.

**Comment by amnonh** [comment]
@tzach what is your take about this metrics?
I'm not sure about the storage proxy layer, it's good for debugging but for users it's confusing.
Maybe we should add a dashboard for cas in general,

for the cql statements, I can add a filter, that would allow selecting: everything/cas_only/non_cas

**Comment by tzach** [comment]
CAS can be added to CQL page, these are CQL operations
The overview dashboard can include one summarise metric.

> I'm not sure about the storage proxy layer, it's good for debugging but for users it's confusing.

Why? we already present coordinator metrics

**Comment by amnonh** [comment]
But for the users, read/write are not clear, coordinator metrics are better taken from the CQL level.
