### ISSUE TITLE
non root monitoring startup does not work

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla-monitoring#780]
When I try to run monitoring as centos (non-root)  it fails to start as it has to create the build directory.

> [centos@ip-172-31-25-113 scylla-monitoring-scylla-monitoring-3.0]$ ./start-all.sh -d `pwd`/monitoring
Wait for alert manager container to start
mkdir: cannot create directory ‘/etc/scylla-monitoring-scylla-monitoring-3.0/prometheus/build/’: Permission denied
./start-all.sh: line 170: /etc/scylla-monitoring-scylla-monitoring-3.0/prometheus/build/prometheus.yml: No such file or directory
Loading prometheus data from /etc/scylla-monitoring-scylla-monitoring-3.0/monitoring
Error: Prometheus container failed to start
For more information use: docker logs aprom
[centos@ip-172-31-25-113 scylla-monitoring-scylla-monitoring-3.0]$

**Comment by mailmahee** [comment]
and when I try to run with sudo I see a different issue - not sure why is prometheus.yml getting created as a directory instead of a yml file

> [centos@ip-172-31-25-113 scylla-monitoring-scylla-monitoring-3.0]$ sudo ./start-all.sh -d `pwd`/monitoring
Running as root is not advised, please check the documentation on how to run as non-root user
Wait for alert manager container to start
./start-all.sh: line 170: /etc/scylla-monitoring-scylla-monitoring-3.0/prometheus/build/prometheus.yml: Is a directory
Loading prometheus data from /etc/scylla-monitoring-scylla-monitoring-3.0/monitoring
Error: Prometheus container failed to start
For more information use: docker logs aprom
[centos@ip-172-31-25-113 scylla-monitoring-scylla-monitoring-3.0]$

```
[centos@ip-172-31-25-113 scylla-monitoring-scylla-monitoring-3.0]$ docker logs aprom
container_linux.go:235: starting container process caused "container init exited prematurely"
```

**Comment by amnonh** [comment]
Did you start with the tar or with git?
was it a clean installation?

**Comment by mailmahee** [comment]
tar file - 
> wget https://github.com/scylladb/scylla-monitoring/archive/scylla-monitoring-3.0.tar.gz
tar -xvf scylla-monitoring-3.0.tar.gz

**Comment by mailmahee** [comment]
@amnonh were you able to replicate this issue?

**Comment by amnonh** [comment]
no I couldn't, I'll start with a new installation and see

**Comment by amnonh** [comment]
I've just tried it on a clean centos installation using the instruction from the site and had no issue.
Can you try again with a clean installation?
https://docs.scylladb.com/operating-scylla/monitoring/3.0/monitoring_stack/

**Comment by amnonh** [comment]
Closing as unreproducable
