### ISSUE TITLE
we should allow saving of provisioned dashboards from UI

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#802]
Grafana 6.5 allows saving provisioned dashboard.
See: https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-5/#allow-saving-of-provisioned-dashboards-from-ui
Should we allow this?
If we do, users may find themselves in a confusing situation.
As long as they are using an external database for grafana (i.e. outside of the container) things would work correctly.
If not or if they will change the dashboard externally, their changes will be overridden.

**Comment by tzach** [comment]
> As long as they are using an external database for grafana (i.e. outside of the container) things would work correctly.

Is this the default with start_all.sh ?

**Comment by amnonh** [comment]
Right now, users cannot change and save dashboards.
In grafana 6.5 (available from Scylla monitoring 3.1) it is possible to enable it.
It's disabled by default and to enable it, we should add a command-line option when starting grafana.

**Comment by amnonh** [comment]
No, you need to explicitly set an external directory

**Comment by amnonh** [comment]
After giving it some thoughts, I'm going to add it, it can be very helpful (though not perfect)
