### ISSUE TITLE
Default Latency Alerts

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#803]
Latency is probably the most critical metric to track, and first to report when it getting too high.
Its hard to set a threshold for every system out there, but we can have a built-in default user can change

My suggestion is: 
Avg: 10ms
99% : 100ms
For the last  last 1 min

Every user will be able to change this value base on his requirements and workload

**Comment by amnonh** [comment]
We actually had that at an early phase and removed it, because it wasn't helpful and it's hard to explain how to set values that will be useful.

We can have an alert based on the last 7 days avg.
or compare week 95% to the last minutes 99% or something on that logic
