### ISSUE TITLE
I/O metrics do not display anything

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#813]
scylla-version=2019.1
monitoring-version=3.1

**Comment by slivne** [comment]
@amnonh 
![nothing](https://user-images.githubusercontent.com/3465480/74098527-f256cc00-4b21-11ea-8f3b-0c3d40ee90b9.png)

**Comment by amnonh** [comment]
This is a version mismatch between node_exporter and scylla-monitoring, node_exporter 0.14 is no longer supported with Scylla Monitoring 3.0 and higher
