### ISSUE TITLE
Prometheus reaching out of memory and crashes (SCT)

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-monitoring#814]
In the few of the latest sct jobs, the Prometheus container crashed. It seems that it failed due to out of memory error:
```
level=info ts=2020-02-09T05:36:24.316Z caller=compact.go:496 component=tsdb msg="write block" mint=1581220800000 maxt=1581226563031 ulid=01E0M7576QZBHJNNHNNF55H0F5 duration=19.493285779s
fatal error: runtime: out of memory

```
The full logs of the monitor of one of those runs can be found here: https://cloudius-jenkins-test.s3.amazonaws.com/53d8d674-fffc-4916-bb68-ec0ca167db63/20200209_050141/monitor-set-53d8d674.zip

At the moment, the monitor is up: 34.244.95.219

The Prometheus log can be found here: 
[prometheus.log](https://github.com/scylladb/scylla-monitoring/files/4177046/prometheus.log)

**Comment by amnonh** [comment]
There is nothing that needs to be fixed, it's a normal Prometheus behavior, you should use a machine with more memory or larger swap.
