### ISSUE TITLE
Add graphs for CDC

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#819]
@haaawk please provide info of which counters we expose

**Comment by amnonh** [comment]
@piodul I want to add two panels for the next monitoring release, one for the current rate of cdc ops and one for the failure.
I went over the different metrics and I'm not sure what should I use, can you please add a comment with the metrics names?

**Comment by piodul** [comment]
@amnonh The following two metrics should be useful:

- `scylla_cdc_operations_total` - total count of CDC operations,
- `scylla_cdc_operations_failed` - the number of CDC operations that failed.

Both of the metrics above have a "split" label, which can be "0" or "1". If you do not want to differentiate operations that did/did not do splitting, then you should just should sum over this label.
