### ISSUE TITLE
Make it possible to run scylla-monitoring from the inside of the docker container

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-monitoring#821]
In SCT we start hydra to run scylla-monitoring, in case of docker backend it is going to be executed there there, i.e. from the inside of hydra.
It leads to having bad docker mount points (docker run -v .. ) since docker will use host environment, and container know nothing about them and uses paths from the container environment.

In order to metigate that we need to add docker mapping functionality wich will provide ability for map contianer mounting points path to host path.

**Comment by bentsi** [comment]
running monitoring stack from Docker (Docker inside Docker) is not common use case and involves complexity that can be solved by another means (like by giving exactly the same path inside the container as outside). @dkropachev / @amnonh  please close this
