### ISSUE TITLE
-b flag produces incorrect argument making aprom fail to start

### ISSUE THREAD

**Issue by rjeczalik** [scylladb/scylla-monitoring#838]
Tested on `scylla-monitoring-2.4` branch as well as `scylla-monitoring-3.1`.

The following command:

```
$ mkdir datadir
$ ./start-all.sh -b $PWD/datadir -v 2019.1
```

Fails with aprom container failure. The `docker logs aprom` shows:

```
ubuntu@ip-172-31-25-56:~/scylla-monitoring-scylla-monitoring-3.1$  docker logs aprom
Error parsing commandline arguments: unknown short flag '-/'
prometheus: error: unknown short flag '-/'
```

The relevant part from docker inspect aprom shows:

```
        "Args": [
            "--config.file=/etc/prometheus/prometheus.yml",
            "-/home/ubuntu/scylla-monitoring-scylla-monitoring-3.1/datadir"
        ],
```

The `-/home/ubuntu/scylla-monitoring-scylla-monitoring-3.1/datadir` is what breaks aprom to start.

**Comment by rjeczalik** [comment]
Source: https://scylladb-users.slack.com/archives/GTGGC8HTN/p1582918148019900

**Comment by mailmahee** [comment]
the command ran successfully once we switched to `-v`  i.e.

`$ ./start-all.sh -v $PWD/datadir -v 2019.1`

**Comment by rjeczalik** [comment]
Oh sorry my bad I used wrong flag. :man_facepalming: Closing.
