### ISSUE TITLE
show all possible classes for I/O

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#839]
We hardcode the name "query" for the query class, but if we are using workload prioritization, there won't be a query class and instead one class per service level.

I'd like to recommend we do that same black magic we've been doing for CPU to fill up the I/O classes with all possible values. That sounds better to me than having a special dashboard for Enterprise, because sometimes users end up using OSS dashboards with Enterprise software.

**Comment by slivne** [comment]
"[solutions] discord conf change, process improvement and product improvement"

**Comment by glommer** [comment]
@slivne I disagree with the label "enhancement". This is a bug, not a request for enhancement. Users using systems set up for workload prioritization see bogus and confusing metrics in the query class.

For those users, the dashboard is simply broken

**Comment by amnonh** [comment]
When using templating (i.e. repeat a panel for all possible values) we need to group by the metric.
That means that for every metric all the classes will be grouped together, for example:
![image](https://user-images.githubusercontent.com/2118079/76336646-fe8ba000-62fe-11ea-9925-7d09d3de105e.png)

**Comment by glommer** [comment]
The panels are we have today are obviously better in this sense because they show all metrics for the same class in correlation.

However the fact that some metrics are not shown is indeed a problem.

What can we do about it? I'd expect grafana to support some form of grouping

**Comment by amnonh** [comment]
They had a concept of rows and repeated rows, but it's long gone, maybe in a future release, it will resurrect.

**Comment by glommer** [comment]
I'll leave a solution up to you, I don't understand grafana well enough to suggest.
But not showing the classes that the user uses is obviously broken.

**Comment by amnonh** [comment]
Depends on #846 
I'll do it in stages for 3.2 I'll release a simple uglier solution and when I'll switch to panel-row we can make it nicer.
