### ISSUE TITLE
Where are the help strings?

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#841]
A while ago, I had added help strings to most of our dashboards.

In particular, things that are confusing and non-obvious like "foreground writes". As the graphs moved to other dashboards, the annotations are no longer, and the `i` corner is gone.

Please revert them back from older versions, these help strings are important.

Also please have the discipline of adding help strings to any dashboard that is added. We shouldn't have a single graph without a help string.

**Comment by amnonh** [comment]
@glommer can you point me to a point it was there (e.g. Scylla-monitoring version, dashboard name, Scylla version)

**Comment by glommer** [comment]
See this commit: 310bcfc13bd2df74095ef27bd17c9d1983dc7aeb

The foreground and background queues, for instance, all had tooltips. Now that they were moved to a different dashboard, they no longer have.

Looking at the tooltip text I wrote before will save you time, but the gist of this bug is: every graph, in every dashboard should have a tooltip.

**Comment by amnonh** [comment]
@glommer 
I found it already (that's why I deleted the comment) and sent a PR #842 ...
