### ISSUE TITLE
95p monitoring start on 2ms 

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla-monitoring#843]
@amnonh 
A Scylla Cloud customer monitoring on the 95p the graph starts from 2ms.
please see links + screenshot 

http://x.x.x.x:3000/d/overview-2019-1/scylla-overview-metrics?orgId=1&from=1583108541323&to=now-30m&refresh=30s
![image](https://user-images.githubusercontent.com/13367089/75887622-c1249f80-5e32-11ea-8938-810059406922.png)

**Comment by tzach** [comment]
@gcarmin I update the IP of the dashboard

**Comment by gcarmin** [comment]
@amnonh - did you had a chance to have a look into this one?

**Comment by amnonh** [comment]
@gcarmin I did and it is strange.
I have verified that this is the information Prometheus collected.
Those are reports from a single instance, and I cannot think of something that would cause this, I'm keeping it open so we can get more cases such as this

**Comment by gcarmin** [comment]
@amnonh  - thanks for the update. If you want since it is a cloud customer we have full access to it.

**Comment by amnonh** [comment]
From what I can see, it's a result of a low-resolution histogram.
After https://github.com/scylladb/scylla/pull/4828 will be merged it would give a higher resolution on all ranges.

I don't think we can do more about it on the monitoring side, closing
