### ISSUE TITLE
A node joining the cluster is not present in the metrics until it is fully joined

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-monitoring#845]
The metrics for the joining node is quite useful especially when we try to figure out boostrap  / replace operation performance issues.

**Comment by amnonh** [comment]
@asias I don't think this is the case, Prometheus API is open quite early so if you add the new node to the Prometheus configuration (whatever way you are using), it's metrics should be there.
Can you please describe what you did to have a situation that a node has no metrics?

**Comment by amnonh** [comment]
@tzach, please comment.
Do note that changing the repository name breaks any automation and older link, so it's not to be done lightly.

**Comment by asias** [comment]
> @tzach, please comment.
> Do note that changing the repository name breaks any automation and older link, so it's not to be done lightly.

Do you mean the other issue here:

https://github.com/scylladb/scylla-monitoring/issues/844#issuecomment-596847266

**Comment by asias** [comment]
> @asias I don't think this is the case, Prometheus API is open quite early so if you add the new node to the Prometheus configuration (whatever way you are using), it's metrics should be there.
> Can you please describe what you did to have a situation that a node has no metrics?

This happened during SCT bootstrap test. I guess the problem is due to the configuration of the monitor. E.g., 
- n1, n2 in the cluster
- There are only n1 and n2 get configured in the scylla_servers.yaml
- SCT bootstrapped n3 into the cluster, but scylla_servers.yaml is not updated to add n3

@amoskong @dyasny

**Comment by amoskong** [comment]
> > @asias I don't think this is the case, Prometheus API is open quite early so if you add the new node to the Prometheus configuration (whatever way you are using), it's metrics should be there.
> > Can you please describe what you did to have a situation that a node has no metrics?
> 
> This happened during SCT bootstrap test. I guess the problem is due to the configuration of the monitor. E.g.,
> 
> * n1, n2 in the cluster
> * There are only n1 and n2 get configured in the scylla_servers.yaml
> * SCT bootstrapped n3 into the cluster, but scylla_servers.yaml is not updated to add n3
> 
> @amoskong @dyasny

Currently SCT reconfigure grafana when the new node is UP. So it's after bootstrap.

@bentsi @fruch Can we try to reconfigure grafana when bootstrap of new node is started?

**Comment by fruch** [comment]
> > > @asias I don't think this is the case, Prometheus API is open quite early so if you add the new node to the Prometheus configuration (whatever way you are using), it's metrics should be there.
> > > Can you please describe what you did to have a situation that a node has no metrics?
> > 
> > 
> > This happened during SCT bootstrap test. I guess the problem is due to the configuration of the monitor. E.g.,
> > 
> > * n1, n2 in the cluster
> > * There are only n1 and n2 get configured in the scylla_servers.yaml
> > * SCT bootstrapped n3 into the cluster, but scylla_servers.yaml is not updated to add n3
> > 
> > @amoskong @dyasny
> 
> Currently SCT reconfigure grafana when the new node is UP. So it's after bootstrap.
> 
> @bentsi @fruch Can we try to reconfigure grafana when bootstrap of new node is started?

We already addressed this in SCT, the issue was in SCT. I think this ticket can be closed.
