### ISSUE TITLE
Need a flag to start Grafana with the White background

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#866]
cc @GalitElad @tzach

**Comment by tzach** [comment]
Have anyone looked at  White background grafana?
Does it looks good?
We need a Scylla Cloud like style, not just white background (especially if it does not look as good)

**Comment by noamha** [comment]
@GalitElad wrote in one of the emails she tried it and it looked good.

**Comment by tzach** [comment]
Can we get a quick demo, or at least a few screenshots?

**Comment by amnonh** [comment]
It is already supported, you can use `-c` flag to pass an environment variable to grafana.
For example use:
`./start-all.sh -v master -c "GF_USERS_DEFAULT_THEME=light"`
To start grafana with the light theme.
I'm not crazy about how it looks like, but that's your call.
![image](https://user-images.githubusercontent.com/2118079/77844495-0462fb80-71b0-11ea-95db-e7ec9a8defa9.png)

**Comment by tzach** [comment]
https://github.com/scylladb/scylla-monitoring/issues/867
