### ISSUE TITLE
New design to match Scylla Cloud look

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#867]
Redesign the dashboard colors, fonts, and style book to Scylla Cloud

**Comment by noamha** [comment]
@tzach Just to be clear should we continue implementing #866 solution for now or wait for a different design and stick with Grafan as is?

**Comment by tzach** [comment]
Move forward
I leave it to @GalitElad  to decide if the white theme (as is) is a better fit to Scylla Cloud then the current one. Maybe Guy can advice.

**Comment by amnonh** [comment]
Fixed by #1681
