### ISSUE TITLE
remove unrelevent stream panels

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#870]
in scylla 4.0 all streaming (like add node) are base on repair
This means some old metrics and dashboard are not relevant
we need to update the dashboard to reflect this.

**Comment by amnonh** [comment]
@asias can you comment on what need to be changed?

**Comment by asias** [comment]
Can you tell me the metrics you added in the dashboard in question?

**Comment by amnonh** [comment]
@tzach can you comment what panel you were referring to?

**Comment by tzach** [comment]
> @tzach can you comment what panel you were referring to?

No. I assume the new implementation  of topology change streaming made also include metric update. @asias please advise if this is the case.

**Comment by amnonh** [comment]
Closing
