### ISSUE TITLE
Scylla Manager 2.1 add agent and server system metrics

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-monitoring#874]
We need additional metrics for agents and server (all agents and server should be in one pane).

I'd like to have panes for:
* `process_resident_memory_bytes`
* `go_memstats_heap_inuse_bytes`
* `process_open_fds`
* `go_threads`

**Comment by zimnx** [comment]
Number of goroutines would be useful too, this allows to spot goroutine leaks.

**Comment by amnonh** [comment]
@mmatczuk we already collecting the metrics of both server and agent.
The question is it useful for the user?
Please add an explanation for the metrics, what does the value mean and what does high/low value mean.

**Comment by mmatczuk** [comment]
For agents let's use cgroups mem limits https://github.com/scylladb/mermaid/blob/master/dist/scripts/scyllamgr_agent_setup#L133

It's useful to see if it's not leaking memory, goroutines.

**Comment by amnonh** [comment]
@mmatczuk I want to add the panels to the next release, please add an explanation that would explain what the metric is measuring and what does it high/low values mean

**Comment by mmatczuk** [comment]
Let's go with only two:

* `go_memstats_heap_inuse_bytes` - Number of heap bytes that are in use
* `go_threads` -  Number of OS threads created

What is the meaning of min and max values here?

**Comment by amnonh** [comment]
@mmatczuk that's what I'm asking :) min is probably meaningless, do you have a limit on memory that above that you know something is wrong?

About the go_threads, is that the current number of threads? or is it an evergrowing counter (i.e. should we look at the value or the derivative).

If it's the latter, is it normal after the initial phase for new threads to be created?
