### ISSUE TITLE
Metrics to improve LWT dashboard

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla-monitoring#875]
1. Please fix a typo: Avrage -> Average
2. Please add a few more metrics related to the possible cause of trouble: 
* storage_proxy_coordinator_cas_failed_read_round_optimization - extra read rounds had to be issued because replicas had different view of data
* storage_proxy_coordinator_cas_dropped_prune - system.paxos pruning rounds that had to be dropped because of throttling limits
* storage_proxy_coordinator_cas_prune - current number of background pruning requests
* storage_proxy_coordinator_cas_write_contention - number of write retries due to contention
* scylla_storage_proxy_coordinator_cas_write_condition_not_met - how many writes did not proceed due to condition not met

Some metrics are less important but still nice to have:
* storage_proxy_coordinator_cas_read_contention - number of read retries due to contention
* scylla_storage_proxy_coordinator_cas_read_unavailable
* scylla_storage_proxy_coordinator_cas_read_unfinished_commit
* scylla_storage_proxy_coordinator_cas_write_timeout_due_to_uncertainty
* scylla_storage_proxy_coordinator_cas_write_unavailable
* scylla_storage_proxy_coordinator_cas_write_unfinished_commit

Thanks!

**Comment by amnonh** [comment]
@kostja can you please add some explanation (it will be added to the help section of each of those metrics) what those metrics mean to the user?
and what should they do based on high/low value

**Comment by kostja** [comment]
Sure, there is explanation though in the metrics definitions, it's also present in prometheus output. Is it not taken automatically or is it simply not good enough?

I can write a longer explanation or I can copy and paste existing comments present in http output, please clarify.

All of these metrics mean something bad, so it's not good when they are not zero. cas_prune is the only exception, it simply shows the number of prunes in flight, it should roughly match the number of LWT in flight.

**Comment by amnonh** [comment]
it's not automatically, but that's good cause it gives us a place to elaborate on metrics that user find hard to understand.

I've looked at the explanation that comes with the value and I think it's not clear to anyone that is not currently in the process of implementing LWT.
As an (extreme) reference look at the CQL optimization section in the CQL dashboard.
With a very specific metric, it should be clear what the meter means and **bad** meter what does it mean and what should you do if you see that it's not zero
