### ISSUE TITLE
Alternator Data Plane Actions break when switching "by"

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#878]
open Alternator view

in Data Plane Actions
you see:
BatchWriteItem, DeleteItem, GetItem, ...

then you switch from Instance view to Cluster view
and Data Plane Actions only has
GetItem view stretched from left to right and the other graphs are gone

**Comment by amnonh** [comment]
I have opened: https://github.com/grafana/grafana/issues/23364

**Comment by tarzanek** [comment]
**Workaround**: seems like the vars that got into URL break it, after removing them the page displays
(the ones with GetItem in them)
so if URL changes, remove
```
&var-alternator_ops=GetItem&var-alternator_item_ops=GetItem&var-alternator_latency_ops=GetItem
```
from the end of it
