### ISSUE TITLE
CQL Optimization dashboard gauges can be OFF for various time frames

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#881]
Scylla Monitoring: 2.3 (per our Cloud records).
Scylla core: 2019.1.5

I was looking in one of our Cloud customers monitoring (Cluster ID: 165) -> CQL optimization dashboard 
I see for last 5 / 15 / 30 min and for last 1 hr resolution similar info -> many gauges show high RED percentage for various panels

**Last 5 min.**
![image](https://user-images.githubusercontent.com/25585995/78934311-934cff00-7a5f-11ea-8964-7687c26146ba.png)

**Last 15 min.**
![image](https://user-images.githubusercontent.com/25585995/78934389-afe93700-7a5f-11ea-86aa-7c583f69c393.png)

**Last 30 min.**
![image](https://user-images.githubusercontent.com/25585995/78934438-c7282480-7a5f-11ea-8c19-d6c7aa442e27.png)

**Last 1 hr.**
![image](https://user-images.githubusercontent.com/25585995/78934490-de671200-7a5f-11ea-99c3-516c3faa749a.png)

But when moving to last 3 hrs, the panels become ALL good with 0% problems...

**Last 3 hrs.**
![image](https://user-images.githubusercontent.com/25585995/78934831-782ebf00-7a60-11ea-82a5-ccc8ed6a3012.png)

**Comment by gnumoreno** [comment]
@amnonh remember my question during your presentation? That's the type of thing I thought could happen. Please have a look whenever possible.

**Comment by amnonh** [comment]
From comparing the graphs and the gauge, I'm not sure what can cause this, I am going to switch between irate and rate for the gauges to make it less spiky, just in case.

If there is a machine you see with this behavior if you could try it manually (i.e. edit a faulty gauge and replace the irate with rate) it would be great.

@gnumoreno I don't think it relates to what you were talking about

**Comment by tomer-sandler** [comment]
@amnonh I'm not sure if the monitoring git repo is private or not, so I sent you a private message on Slack were you can see the problem and try your suggested fix.

**Comment by amnonh** [comment]
I had a look, thanks.

It seems that switching to rate does have an effect. it is still not consistent.
The version there is quite old, I think it would be best if you'll upgrade the monitoring version once 3.3 is out
