### ISSUE TITLE
Monitor and alert of schema version mismatches

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-monitoring#885]
https://docs.scylladb.com/troubleshooting/error_messages/schema_mismatch/ sometimes happens in production and if left uncaught for a while can cause serious service degradation. 

Would be great to monitor for more than one schema in a cluster, and if it persists for longer than X minutes, produce an alert

**Comment by dyasny** [comment]
@vladzcloudius @tomer-sandler

**Comment by amnonh** [comment]
closing as duplicate #707
