### ISSUE TITLE
LWT dashboard (Monitoring 3.2): Latency panels are not showing ms values, but rather `rps`

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#886]
![image (3)](https://user-images.githubusercontent.com/25585995/79598371-b0558380-8098-11ea-8d1d-0e320fd556eb.png)

**Comment by amnonh** [comment]
Those are reads/s
closing, if you think that there is an issue, please re-open

**Comment by tomer-sandler** [comment]
@tzach @eyalgutkind @amnonh latency is measured by time (ms units), not by `rps`
Please re-open and fix.

**Comment by tzach** [comment]
@amnonh Tomar is right. Latency can not be measured in read per second

**Comment by amnonh** [comment]
Same as #891 which is already closed, no need to re-open
