### ISSUE TITLE
LWT Latency metric and Title unit is wrong

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#891]
Latency metrics should be in ms, not rps
![image](https://user-images.githubusercontent.com/170200/79716549-af626300-82df-11ea-90e4-bb78cd1c663c.png)

All 4 latency metrics (read/write, Average/95%)

LWT **Avrage** Read latency --> LWT **Average** Read latency
same for Write

**Comment by amnonh** [comment]
it should be rps and wps
read-per-seconds and write-per-seconds.
But in the case of latencies maybe it should be seconds

**Comment by tzach** [comment]
> But in the case of latencies maybe it should be seconds

yes
