### ISSUE TITLE
LWT Counters should use irate

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#892]
LWT counters should be presented using irate, or it will grow for ever:
* LWT Writes `scylla_storage_proxy_coordinator_cas_read_latency_count`
* LWT Reads `scylla_storage_proxy_coordinator_cas_write_latency_count`
* LWT Write Timeouts `scylla_storage_proxy_coordinator_cas_read_timeouts`
* LWT Read Timeouts `scylla_storage_proxy_coordinator_cas_write_timeouts`

See scylla_transport_requests_served as an example.

**Comment by amnonh** [comment]
It's already fixed by #883
