### ISSUE TITLE
Get IO panel to its previous form.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla-monitoring#894]
IO graphs are grouped by metric type now (io delay, bandwidth, iops) where before it was grouped by io class (commitlog, compaction etc.) The old grouping made much more sense.

**Comment by amnonh** [comment]
@glommer can you comment

**Comment by amnonh** [comment]
@gleb-cloudius for future issues, please add:
Dashboard name, monitoring version and Scylla version

**Comment by amnonh** [comment]
@gleb-cloudius can you take a look maybe #869 already covers it?
if so, please close

**Comment by gleb-cloudius** [comment]
yes #869 looks better.
