### ISSUE TITLE
Adding a grafana-image-renderer to scylla-monitoring

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-monitoring#904]
grafana has a build-it plug that can help us capture panels or dashboards 
https://grafana.com/docs/grafana/latest/administration/image_rendering/#run-in-docker

up until now, we are doing all kind of hacks, using selenium and such to capture the dashboards as images.

this seems to work much better, and I think it would be a nice addition to scylla-monitoring

**Comment by fruch** [comment]
example of using it:
```bash
LOCAL_HOST_IP=192.168.1.14

docker run -d -p 8081:8081 grafana/grafana-image-renderer

./start-all.sh -c GF_RENDERING_SERVER_URL=http://${LOCAL_HOST_IP}:8081/render -c GF_RENDERING_CALLBACK_URL=http://${LOCAL_HOST_IP}:3000/ -c GF_LOG_FILTERS=rendering:debug

curl http://localhost:3000/render/d/cql-3-3/scylla-cql?orgId=1&refresh=30s&from=1587680332029&to=1587680632029&width=1000&height=2500 > dashboard.png

```

**Comment by amnonh** [comment]
It is nice, but it means running an additional container just for snapshots.

You can still add this to the QA testing without adding it by default to the monitoring stack.

**Comment by amnonh** [comment]
Relates to #248
https://grafana.com/grafana/plugins/grafana-image-renderer

**Comment by amnonh** [comment]
One annoying part is the configuration. Both containers need to know each other IPs, this can be done either using the host IP (not always clear) or with a docker-compose
