### ISSUE TITLE
CQL Page Monitor 3.3 on LWT operations (non LWT) CQL Operations are also updated

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#906]
![Screenshot from 2020-04-29 04-09-59](https://user-images.githubusercontent.com/3465480/80552558-af452000-89cf-11ea-83ba-7d8e7ff74fb2.png)

I have done some LWT inserts 

```

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x03,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x04,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x05,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x06,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x07,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x08,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x09,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

cqlsh> INSERT INTO keyspace1.standard1 (key, "C0") VALUES (0x10,0x00) IF NOT EXISTS;

 [applied] | key  | C0   | C1   | C2   | C3   | C4
-----------+------+------+------+------+------+------
      True | null | null | null | null | null | null

```

and as can be seen there are CQL INSERT, CQL UPDATE, CQL DELETE, CQL READ

all of those are internally generated to execute the CQL LWT OPERATION.

I think think this is misleading users (or at least they should be able to opt out and not see those internally generated ones).

There are other places in which this is not visible - materialzied views (we generate updates and do not have them visible) the reason for that is that those are generated via mutations and not via cql operations. 

The fact that LWT generates updates via CQL and  MV doesn't use CQL is an implementation detail in my view.

There are also other places that have that visible logged batches. 

I think that even if logged batches have this "problem" its less problematic then the LWT case.

To be clear - we need a way to measure the CQL operations generated by LWT - to make it clear to the user there is a "high" price for those, yet the user should allways have a way to hide those and view the inbound traffic from their apps into the cluster.

**Comment by slivne** [comment]
@gleb-cloudius  / @kostja please provide your view

@tzach / @amnonh this needs ot be sorted out before 3.3. goes out (at least in my view)

**Comment by kostja** [comment]
I believe we have to fix it on the server side, it's impossible to correctly fix it in scylla-monitoring only - CQL rounds may have varying number of CQL queries. We need to tag internal CQL rounds as such, so that monitoring can subtract them correctly.

**Comment by tzach** [comment]
@kostja please open correlating issue for Scylla than

**Comment by slivne** [comment]
a workaround solution for now


1. let the metrics for insert only count the non conditional inserts
2. subtract from the counters the internal created traffic

```
sum(irate(scylla_cql_deletes{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]", conditional="no"}[300s])) by ([[by]]) - sum(irate(scylla_cql_deletes_per_ks{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]",who="internal", conditional="no"}[300s])) by ([[by]])
```

```
sum(irate(scylla_cql_updates{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]", conditional="no"}[300s])) by ([[by]]) - sum(irate(scylla_cql_updates_per_ks{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]",who="internal", conditional="no"}[300s])) by ([[by]])
```

```
sum(irate(scylla_cql_inserts{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]", conditional="no"}[300s])) by ([[by]]) - sum(irate(scylla_cql_inserts_per_ks{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]",who="internal",conditional="no",}[300s])) by ([[by]])
```

**Comment by gleb-cloudius** [comment]
I do not think any workaround is needed or any problem exists. If CQL
graph will hide internal CQL requests it will be useless to analyze
performance problem. There is a way to see amount of operation commit
through a server - cql server request count.

It would be nice to tag internal cql requests with additional label (LWT
is not the only source of those), but it should be used to drill down
when investigating an issue not hide cql requests from a monitor.

--
			Gleb.

**Comment by slivne** [comment]
@gleb-cloudius 
- I do understand that, yet scylla users will not understand that (unless we explain that to them - and currently we don't)
- I also pointed out the MV create additional load (writing to the view) and that is not visible via cql requests.
- So while you are totally correct there are other "internal" sources generating those requests - they are not as "common" as LWT from the user standpoint.
- @amnonh / @tzach  maybe you have a solution
   - a toggle on/off to include them or not - or some other mean to make this clear to users as well.

**Comment by tzach** [comment]
IMHO its better to be transparent and present *more* data and explain it - than hiding useful info.
In other words: If LWT do a read - it should be presented as a read.
If user ask about it - we will explain.

If we do not present, reads are still stressing the system, but now its a mystery for the user and are support team.

**Comment by gleb-cloudius** [comment]
On Sun, May 03, 2020 at 01:28:23PM -0700, Shlomi Livne wrote:
> @gleb-cloudius 
> - I do understand that, yet scylla users will not understand that (unless we explain that to them - and currently we don't)
What are they use it for? Currently all internal users are shown there
(you can grep for some of them by "grep execute_cql") and users do not
complain. Also why would they? Why do they care? _They_ "know" what
their application is doing and are interested in total number of request
completed which do not include internal requests.

Those graphs are used to evaluate performance problems and hiding data
from there is not useful. Correlating them with storage proxy data and
database reads will stop making sense.

> - I also pointed out the MV create additional load (writing to the view) and that is not visible via cql requests.
Because it is not done throw cql interface? How is it relevant?

> - So while you are totally correct there are other "internal" sources generating those requests - they are not as "common" as LWT from the user standpoint.
Like with LWT deepened on a workload. If you have a lot of batch
writes you will have much more reads from the batch table.

> - @amnonh / @tzach  maybe you have a solution
>    - a toggle on/off to include them or not - or some other mean to make this clear to users as well.
>  
> 
>     
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla-monitoring/issues/906#issuecomment-623176324

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Sun, May 03, 2020 at 10:24:38PM -0700, Tzach Livyatan wrote:
> IMHO its better to be transparent and present *more* data and explain it - than hiding useful info.
> In other words: If LWT do a read - it should be presented as a read.
> If user ask about it - we will explain.
> 
> If we do not present, reads are still stressing the system, but now its a mystery for the user and are support team.
> 
> 
Exactly. We do need to tag internal reads as such to be able to drill
down. Preferably across all the stack, but this is not a small task.

--
			Gleb.

**Comment by amnonh** [comment]
@tzach @slivne @gleb-cloudius I'm not sure what is the right approach.
Shlomi suggestion is practically removing the internal CQL operation to the system table.
Which makes sense, but then, why the conditional="no", if it's internal, it's internal?

I can set a panel for CQL command without internal commands.

And a second row for Internal only commands, for example:
```
 sum(irate(scylla_cql_updates_per_ks{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]",who="internal"}[300s])) by ([[by]])

```
The other approach is to either move it to a documentation issue, or change the issue to reflect if it should appear in the dashboard (either a comment for the regular CQL or for the LWT).

**Comment by gleb-cloudius** [comment]
On Mon, May 04, 2020 at 12:11:45AM -0700, Amnon Heiman wrote:
> @tzach @slivne @gleb-cloudius I what is the right approach.
> Shlomi suggestion is practically removing the internal CQL operation to the system table.
> Which makes sense, but then, why the conditional="no", if it's internal, it's internal?
It does not make sense to me. Will make the panel useless for my use
case.

> 
> I can set a panel for CQL command without internal commands.
> 
> And a second row for Internal only commands, for example:
> ```
>  sum(irate(scylla_cql_updates_per_ks{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]",who="internal"}[300s])) by ([[by]])
> 
> ```
> The other approach is to either move it to a documentation issue, or change the issue to reflect if it should appear in the dashboard (either a comment for the regular CQL or for the LWT).
> 
Divide to two panels would be indeed better but show them both by
default.

--
			Gleb.

**Comment by tzach** [comment]
@amnonh its better to document in the dashboard itself (the extra info per metric)
For example, for CQL Reads
"CQL Reads, including LWT INSERTs reads before writes"

**Comment by amnonh** [comment]
It's not only that, LWT has multiple stages where it reads, write, and delete from system tables.

I think it should mean, it includes internal operations, like the additional operation generated by a LWT operation.

I'm not sure that LWT is the only internal operations, for example, what about reading from the client or schema table?

**Comment by gleb-cloudius** [comment]
On Mon, May 04, 2020 at 02:56:49AM -0700, Amnon Heiman wrote:
> I'm not sure that LWT is the only internal operations, for example, what about reading from the client or schema table?
> 
LWT is far from been the only one.

--
			Gleb.

**Comment by amnonh** [comment]
@slivne @tzach @gleb-cloudius I need some kind of conclusion.
I'm ok with the variant on Shlomi's suggestion that we'll have two sets of panels, one without internal (regardless if it's conditional or not) and one with only internal.

I'm also ok with adding a comment that it include internal command.
Either way, let's agree on something so I can continue

**Comment by amnonh** [comment]
@slivne @tzach @gleb-cloudius I'm going to close this tomorrow, so unless I'll hear some other conclusion, I will add a remark to the metrics. We need to release soon

**Comment by gleb-cloudius** [comment]
On Mon, May 04, 2020 at 10:35:57AM -0700, Amnon Heiman wrote:
> @slivne @tzach @gleb-cloudius I'm going to close this tomorrow, so unless I'll hear some other conclusion, I will add a remark to the metrics. We need to release soon
> 
Since we already have "who" label it would be best to split into two
sets of graphs internal/user and plot both sets on the same panel.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, May 04, 2020 at 08:41:17PM +0300, Gleb Natapov wrote:
> On Mon, May 04, 2020 at 10:35:57AM -0700, Amnon Heiman wrote:
> > @slivne @tzach @gleb-cloudius I'm going to close this tomorrow, so unless I'll hear some other conclusion, I will add a remark to the metrics. We need to release soon
> > 
> Since we already have "who" label it would be best to split into two
> sets of graphs internal/user and plot both sets on the same panel.
> 
Well, since drawing them on the same panel will break colour coding, two
separate panels will be better.

--
			Gleb.

**Comment by amnonh** [comment]
I'm against putting two graphs on the same panel, if one of them is much higher than the other it makes it unclear.
I'm fine with having two sets of panels for internal and external

**Comment by gleb-cloudius** [comment]
On Mon, May 04, 2020 at 10:46:05AM -0700, Amnon Heiman wrote:
> I'm against putting two graphs on the same panel, if one of them is much higher than the other it makes it unclear.
> I'm fine with having two sets of panels for internal and external
> 
Since they are both will plot the same metric (just different users) it
does not matter if one completely dwarfs the other, it only means that
the smaller one is not important. It may happen with one node having
much greater values than the other one as well.

Colours will be all wrong though.

--
			Gleb.
