### ISSUE TITLE
Need Panels for Scylla HWLB

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla-monitoring#907]
We had a presentation today from Amnon and Kostja about monitoring and LWT. 

During the presentation, we discussed various dashboards including dashboards for speculative retry,  while doing so we discovered that the speculative retry is mostly from the client POV and we don't have any dashboards that show information regarding HWLB (heat weighted load balancing). This could be handy while understanding the query performance on the server-side.

**Comment by amnonh** [comment]
HWLB is calculated per table, the actual value is reported as cache_hit_rate but is turn off by default (as all the per-table metrics). 

we can get an estimate by looking at the cache hit/miss ratio
