### ISSUE TITLE
RFE: Add support for LDAP auth in grafana

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-monitoring#912]
https://grafana.com/docs/grafana/latest/auth/ldap/

This is a request to add LDAP support to the authentication mechanism in Grafana instead of just supporting a user/pass auth mechanism.

**Comment by amnonh** [comment]
It could be just a configuration issue that should be cover in the documentation.
you can pass command line (that override the configuration) to grafana need to check if there is any special change that is required from the monitoring stack

**Comment by dyasny** [comment]
This is a customer request for a feature to make this work out of the box

**Comment by amnonh** [comment]
LDAP needs configuration, it cannot be out of the box, a user will need to configure it.
My comment was that it is probably already supported and what is missing is documentation on how to  configure it
