### ISSUE TITLE
Scylla 4.0 disk usage per total dc is not correlated to disk usage per node in the dc

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#914]
scylla-version=4.0
monitoring-version=3.3
When looking at disk usage per node, the load per node correspond to the amount of data in the nodes. However, when moving to DC view the numbers do not add up
![image](https://user-images.githubusercontent.com/17868115/81032227-eee29080-8e43-11ea-9c0d-ee64e5793e32.png)

```
[centos@ip-172-31-19-252 ~]$ nodetool status
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  172.31.21.158  1.76 TB    256          ?       528f40bc-34df-4f80-bf9a-70390e1b866d  1d
UN  172.31.19.252  1.92 TB    256          ?       02421558-5f30-48ae-9f7e-fb8b90e08d86  1d
UN  172.31.23.242  1.86 TB    256          ?       e1b15eff-35c0-4c1b-90ef-ad28095c5641  1d
UN  172.31.20.114  1.71 TB    256          ?       24813476-0181-4847-87f4-769592379883  1d

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

However in DC view, the results looks awkward, and do not add up:
![image](https://user-images.githubusercontent.com/17868115/81032307-310bd200-8e44-11ea-9e93-c2574c2dea24.png)

**Comment by amnonh** [comment]
I cannot reproduce, from the panel it seems that things were ok until some point something was wrong.

Do you have more information and what changed at around that time?

**Comment by eyalgutkind** [comment]
this node is going to be up for some time
You can see it here :http://54.84.186.142:3000/

**Comment by amnonh** [comment]
There is an issue with the prometheus connection:
![image](https://user-images.githubusercontent.com/2118079/81072147-6240dc80-8eee-11ea-9fcf-6b07b2cee7c4.png)
