### ISSUE TITLE
Scylla monitoring shows 4 nodes are up when we know 2 nodes are down

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#920]
scylla-version=4.0
monitoring-version=3.3
Hi Working with scylla 4.0 we had a case when 2 out of 4 nodes went down.
Metrics were missing from the dashboard. but the total nodes reported was still 4. all reachable.
![image](https://user-images.githubusercontent.com/17868115/81093245-a912e000-8eb6-11ea-952c-856232564dbd.png)

```
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  172.31.21.158  6.74 TB    256          ?       528f40bc-34df-4f80-bf9a-70390e1b866d  1d
DN  172.31.19.252  7.12 TB    256          ?       02421558-5f30-48ae-9f7e-fb8b90e08d86  1d
DN  172.31.23.242  6.89 TB    256          ?       e1b15eff-35c0-4c1b-90ef-ad28095c5641  1d
UN  172.31.20.114  6.55 TB    256          ?       24813476-0181-4847-87f4-769592379883  1d
```

**Comment by tzach** [comment]
Did it change after some time (to unreachable?)  or stay this way?

**Comment by eyalgutkind** [comment]
stayed that way until we went to the nodetool status... to fiigure out what
is wrong

**Comment by amnonh** [comment]
@eyalgutkind can you please check Prometheus target page?

**Comment by amnonh** [comment]
closing, please re-open if needed
