### ISSUE TITLE
Streaming status

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#921]
In Scylla 4.1 streaming operations are base on repair.
This hopefully allow us to present more useful information to the user:
- Active Streaming (repair, add node(s), remove nodes)
- Streaming bandwidth 30Mb
- Expected data transfer: 553Gb
- Streaming status: 75%

**Comment by tzach** [comment]
@asias do we have metrics for the above?

**Comment by tzach** [comment]
related to https://github.com/scylladb/scylla/issues/1825

**Comment by asias** [comment]
We will not work on the estimation for the old stream plan.
With repair based node operations, we estimate the progress with the percentage of ranges finished.
We have no control about the network bandwidth. We have no network controller.

**Comment by tzach** [comment]
> We will not work on the estimation for the old stream plan.

Yes. This issue refer to 4.1 (ne streaming)

> With repair based node operations, we estimate the progress with the percentage of ranges finished.

Can we separate between repair streaming to add node streaming to remove node streaming?
We need to show something like:
Adding node: streaming is 72% complete

> We have no control about the network bandwidth. We have no network controller.

This issue is not about control, rather monitoring.

**Comment by asias** [comment]
> > We will not work on the estimation for the old stream plan.
> 
> Yes. This issue refer to 4.1 (ne streaming)
> 
> > With repair based node operations, we estimate the progress with the percentage of ranges finished.
> 
> Can we separate between repair streaming to add node streaming to remove node streaming?
> We need to show something like:
> Adding node: streaming is 72% complete

Technically, there is no "streaming" any more. We can know progress of percentage for each repair request(started for node operation or plain repair). Each repair request uses multiple seastar streaming interface to sync data. It makes no sense to see the percentage of each stream.

There can be multiple repair requests in parallel. It is not easy to present the "global" progress. 

> 
> > We have no control about the network bandwidth. We have no network controller.
> 
> This issue is not about control, rather monitoring.

With no network controller/scheduler, we have no idea the bandwidth used by repair. However, we do have metrics
```
 147             sm::make_derive("rx_row_nr", rx_row_nr,
 148                             sm::description("Total number of rows received on this shard.")),
 149             sm::make_derive("tx_row_bytes", tx_row_bytes,
 150                             sm::description("Total bytes of rows sent on this shard.")),
```

Those can be used to show, the network bandwidth used by repair globally on this shard.

**Comment by amnonh** [comment]
@asias looking again at @tzach original list:
We would like to present the user with some more information if possible.
For example, if a node is joining, it would be great if we can show its progress (i.e. the percentage of streaming done) even an estimation would be good.

**Comment by amnonh** [comment]
@asias I'm assigning until we have a metric we can use to estimate the streaming, you can simply reply in the issue with the metrics (and what versions it is available) and I'll take it from there

**Comment by amnonh** [comment]
@asias are there any changes with relation to that?

**Comment by asias** [comment]
Hello Amnon, we do not have node operation (joining) progress metrics in 4.1.  
How about adding something like this:
```
Number of keyspaces finished / total 
Number of ranges finished / total. 
```
This way we can know the progress.

**Comment by amnonh** [comment]
@asias Do we have metrics for it? I've seen that we do have traces (BTW, it's the same trace line for success and failure so it probably should be changed).
But I didn't see any registered metrics for it.

**Comment by asias** [comment]
> @asias Do we have metrics for it? I've seen that we do have traces (BTW, it's the same trace line for success and failure so it probably should be changed).
> But I didn't see any registered metrics for it.

No. We do not have it in master nor 4.1 branch.

**Comment by amnonh** [comment]
@asias is there an issue for that? if not I'll open one

**Comment by asias** [comment]
Not yet. Please open it. Thanks.

**Comment by amnonh** [comment]
depends on https://github.com/scylladb/scylla/issues/6733

**Comment by amnonh** [comment]
depends on https://github.com/scylladb/scylla/issues/1244

**Comment by asias** [comment]
Patch posted: https://github.com/scylladb/scylla/pull/6842

**Comment by amnonh** [comment]
Depends on scylladb/scylla#8311

**Comment by amnonh** [comment]
With stream based repair, this is already shown
