### ISSUE TITLE
New LWT metrics for the dasboard

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#936]
- cas_total_operations - number of total paxos operations executed (reads and writes
- cas_foreground - how many paxos operations that did not yet produce a result are running
- cas_background -how many paxos operations are still running after a result was alredy returned 
https://github.com/scylladb/scylla/commit/d555fb60d73c2f5efe6df66b7bbfa13065a17f49

**Comment by amnonh** [comment]
@tzach @kostja to which scylla OS/enterprise this applies to?

**Comment by amnonh** [comment]
It's not part of 4.1

**Comment by amnonh** [comment]
@tzach @kostja what scylla version this applies to?

**Comment by amnonh** [comment]
Is cas_total_operations relevant? we show read/write

**Comment by kostja** [comment]
> @tzach @kostja what scylla version this applies to?

4.2+

**Comment by kostja** [comment]
> Is cas_total_operations relevant? we show read/write

It's a different metric, a single write could have multiple cas operations, it's the total sum for cas_background/foreground metrics.
