### ISSUE TITLE
Filter out Manager successfull health check annotation  

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-monitoring#941]
Manager executes health check task every 15s, successfull runs should be filtered out because it only creates a green background for every graph.
![Selection_078](https://user-images.githubusercontent.com/3951334/82456269-4d4e7680-9ab4-11ea-8668-8350da61e839.png)

**Comment by amnonh** [comment]
Please add the scylla-monitoring version and scyla manager dashboard you are using.
In the future, note that you can use the report an issue button that would fill this information for you

**Comment by zimnx** [comment]
scylla-version=2.1
monitoring-version=master

Actually it's 2.1 mangager dashboard from master

**Comment by amnonh** [comment]
Already fixed by: https://github.com/scylladb/scylla-monitoring/pull/938
