### ISSUE TITLE
scheduling group cpu metrics are summed across shards

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#945]
This shows that e.g. statement is consuming 8 seconds of CPU per second. You can only understand it if you know how many shards you have.

**Comment by amnonh** [comment]
Can you please include the panel, dashboard,Scylla version, and Scylla-Monitoring version you are looking at?

**Comment by amnonh** [comment]
@avikivity can you please add the info?

**Comment by avikivity** [comment]
It was 4.0, the CPU metrics.

**Comment by amnonh** [comment]
@avikivity what scylla monitoring version?

**Comment by amnonh** [comment]
I'll add an optional aggregation function like some other dashboard have and set the default to avg
![image](https://user-images.githubusercontent.com/2118079/83000841-9605b280-a013-11ea-954b-c75dcdefd854.png)

**Comment by avikivity** [comment]
@amnonh I don't know, I didn't start the system.
