### ISSUE TITLE
time selection lost when switching dashboards

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#946]
If you select a new dashboard, the time selection reverts to the last 30 minutes. This is annoying, you can to cut and paste the time selection from the url to work around it.

**Comment by amnonh** [comment]
We can use Dashbaord links, that appear at to the top-most filtering line, or just below it, if there is not enough space
![image](https://user-images.githubusercontent.com/2118079/82528744-23dc2c00-9b42-11ea-86c5-9557cd53383b.png)
Or
![image](https://user-images.githubusercontent.com/2118079/82528783-36566580-9b42-11ea-81db-5c4dd5ffcb8e.png)
@tzach what do you think?

**Comment by tzach** [comment]
@amnonh  look good, but I'm worried this will add a lost noise to the screen. 
We need to test a live version, can you please share a branch?

Possible variants 
1. link only to relevant dashboards (not all of them)
2. link to a Menu dashboard, with one panel of all the other dashboard\

(can be used together)

Found a similar request (who is this guy?)
https://community.grafana.com/t/switching-between-dashboard-while-keeping-the-time-range-selection/3262

**Comment by amnonh** [comment]
I saw your requests :)
An alternative is a dropdown menu.
![Screenshot from 2020-05-21 09-19-30](https://user-images.githubusercontent.com/2118079/82529758-5dae3200-9b44-11ea-9d41-10972ecb790a.png)
The dashboard link does not let pick which dashboard will be included.
What we can do together with #947 is to have one or two clear buttons (or graphs links) to switch between the user dashboard, and keep the dropdown to the advanced user

**Comment by tzach** [comment]
> An alternative is a dropdown menu.

Looks better. Is "master" a dashboard?

**Comment by amnonh** [comment]
@tzach master is a semi-dashboard, it's like an index dashboard that is created automatically whenever you are using folders.
I suggest we'll add a dropdown for Scylla-Monitoring 3.4 (next release) and look for a newer overall look after grafana 7 migration
