### ISSUE TITLE
Clearer separation between User and Advance dashboard

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#947]
Most users only care about (or can understand) two dashboards:
* Cluster Overview
* CQL
Other dashboard are usually for advanced users or for Scylla support / engineering

Three changes:
1. Separate between the groups, either in a folder, prefix naming 
2. Make the Overview the default dashboard  - open when visiting Grafana
3. Link between the User dashboards, so Cluster over view users can quickly find the CQL one and vice versa.

In the future, we will have ore items in each group, and probably more groups.

**Comment by amnonh** [comment]
What about Scylla-Manager and Alternator?
