### ISSUE TITLE
remove Scylla os 3.1 and 3.2, manager 1.3, 1.4

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#960]
Scylla OS 4.1 is in RC
Scylla manager 2.1 is in RC
we can drop the old dashboards from master, it will be easier to maintain

**Comment by amnonh** [comment]
@tzach please comment

**Comment by amnonh** [comment]
@tzach ping

**Comment by amnonh** [comment]
@tzach ping

**Comment by tzach** [comment]
Make sense to me.
