### ISSUE TITLE
Publish docs in github pages

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#963]
Monitoring docs are managed in scylla-docs project.
This is error prune, and does not work well with the project versions.

A better way will be to use the new https://github.com/scylladb/sphinx-scylladb-theme and publish in a new site, similar to https://scylladb.github.io/python-driver/index.html

**Comment by amnonh** [comment]
@tzach can you assign someone to set it up?
I'll do the content of course

**Comment by tzach** [comment]
@lauranovich lets wait for a recipe from @dgarcia360 on how to create a new doc project before starting with monitoring

**Comment by amnonh** [comment]
@tzach can we close this?
