### ISSUE TITLE
Some dashboards are not working for scylla in kubernetes

### ISSUE THREAD

**Issue by c0ffeec0der** [scylladb/scylla-monitoring#964]
- Installed scylla using scylla operator on kubernetes (docker desktop), namespace scylla
- Already had prometheus and grafana running, namespace monitoring
- Follow instruction on:
  - https://github.com/scylladb/scylla-monitoring#using-your-own-prometheus-server
  - https://github.com/scylladb/scylla-monitoring#using-your-own-grafana-installation
- Tested prometheus populating scylla metrics and replacement for node exporter metrics
- Grafana dashboards have issues, where following do not show data:
  > Alternator – Total, Unreach, Joining, Disk size by instance, Data plane actions, Data plane latencies, Control plane actions
  > Detailed – Hints written per instance, Hints sent per instance, Hints for view, 95% latency
  > OS Metrics – all
  > Overview - Total, Unreach, Joining, Disk size by instance
  > Scylla Manager Metrics - all
- Below grafana dashboards are ok
  > I/O
  > CPU metrics
  > Scylla CQL
  > Scylla Error monitoring

Question: Is there a guide specific for installing monitoring stack for scylla in kubernetes?

---
Scylla-Monitoring Version: 2.3
Scylla-Version: 4.0

**Comment by amnonh** [comment]
@dahankzter can you comment?

**Comment by amnonh** [comment]
@dahankzter ping

**Comment by dahankzter** [comment]
I am using "Overview" all the time in k8s. What happens with it? I can see nodes joining and leaving but I haven't explicitly checked disk size. I will try to check it.

**Comment by dahankzter** [comment]
Actually there seems to be some issues. For example when nodes come and go their IPs seem to remain and not get dropped. This is the case in the "Overview" at least.

**Comment by dahankzter** [comment]
The "Nodes" listing to the right keeps only the correct number of nodes so it would seem the state is consistently presented there.

**Comment by dahankzter** [comment]
After quite some time it seems to correct itself insofar as the IPs return to the correct count and seemingly correct values.

**Comment by dahankzter** [comment]
Actually they have 1 "extra" IP and "Requests served" graph displays the the incorrect IP as the one getting requests compared to the "Load" and the "Nodes" graphs.

**Comment by c0ffeec0der** [comment]
Hi, 

I did some digging into the promql in the grafana dashboard for the value "Total Node", it specify:

`count(up{job=\"scylla\",cluster=~\"$cluster|$^\"})`

However, if using deployment with scylla-operator the metric for up is:

`up{endpoint="prometheus",instance="10.1.1.14:9180",job="simple-cluster-client",namespace="scylla",pod="simple-cluster-us-east-1-us-east-1a-0",service="simple-cluster-client"}`

I could try to redeploy the scylla cluster with the job name with "scylla" in it .
However the grafana query for "cluster" seems not suitable for k8s deployment? since the metric itself does not expose cluster label

The probable solution would be to either:
1. Expose cluster label in the up metric
2. Modify the grafana query for cluster label to service label?

Your choice of fix would also need to consider that the same monitoring stack would work for both dedicated node and k8s deployment. My suggestion would be option 1

**Comment by amnonh** [comment]
@c0ffeec0der with Docker-based Scylla-Monitoring installation, we add the DC and cluster at the server.
We also manipulate the instance tag to remove the port

**Comment by c0ffeec0der** [comment]
So.. are you saying that if I have my own prometheus and grafana, the instructions on:

- https://github.com/scylladb/scylla-monitoring#using-your-own-prometheus-server
- https://github.com/scylladb/scylla-monitoring#using-your-own-grafana-installation

is out dated? and that the only option that scylla monitoring stack will work for k8s deployment is to install a new stack of prometheus and grafana? correct me if i am mistaken

**Comment by amnonh** [comment]
The use-your-own hasn't been updated in a while but there are no major changes and it is possible to run Scylla-Monitoring on your own installation.

Specifically, you have a configuration issue with the way Prometheus read its scylla and node_exporter targets.
You don't need to install a new stack, you do need to make sure that your scylla target contains the DC and cluster name (This is part of Prometheus target configuration)

Our documentation can be found here:
https://docs.scylladb.com/operating-scylla/monitoring/

**Comment by c0ffeec0der** [comment]
okay, thank you guys :) I'll take a look into the prometheus configuration for scylla and add it to my configuration
