### ISSUE TITLE
Collapsible panels

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla-monitoring#973]
Another app that uses seastar recently gave a demo and they use a collapsible panel. It's nice since one can show many panels in the same dashboard instead of sending the users to many dashboards:

https://community.grafana.com/t/grafana-5-how-to-hide-colapse-panel/4707

**Comment by tzach** [comment]
This would be useful on the more busy dashboards, like the per server one, and later maybe unify a few dashboards.
