### ISSUE TITLE
Dashboard Name: Overview; Panel Name: Disk size by Instance

### ISSUE THREAD

**Issue by c0ffeec0der** [scylladb/scylla-monitoring#975]
Problem:

The panel 'disk size by instance' will not show any data since the variable for instance is using scylla_reactor_utilization which return the ip address for scylla pod (not the node).

This is different in dashboard 'OS metric' since the variable node is using node_filesystem_avail_bytes which return the ip address for the node; Thus, panel 'disk size by instance' show data

Overall dashboard there is a confusing term of node and instance; i.e:
- In dashboard 'os metric', a node is a node
- However in dashboard 'overview', a node is an instance

Proposed solution

- Quick fix: temporarily remove panel 'disk size by instance' in dashboard 'overview'; or perhaps remove permanently it does not concern the instance but the node

- Standarize the term node and instance on all dashboard so they have the same meaning. (might need to create a seperate issue for tracking)

*Installation details*
Panel Name: Disk size by Instance
Dashboard Name: Overview
Scylla-Monitoring Version: 3.3
Scylla-Version: 4.0

**Comment by c0ffeec0der** [comment]
Hi guys, any thoughts?

**Comment by amnonh** [comment]
@c0ffeec0der Should we mix os related metrics and scylla metrics is an ongoing debate, previous monitoring versions separated the two but we realized the information was missing.
There is no perfect solution, I hope things we'll be clearer post our next dashboards reorganization
