### ISSUE TITLE
Upgrade to latest node_exporter 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#977]
node_exporter 0.17 is old now, there is no 1.0.1 release
https://github.com/prometheus/node_exporter/releases

**Comment by amnonh** [comment]
@tzach there should be an issue in scylladb/scylla for that installation

**Comment by amnonh** [comment]
@tzach I have tested the Monitoring stack with node_exporter 1.0.1 and everything worked fine.
what needs to be changed is the node_exporter_install in Scylla.
