### ISSUE TITLE
Reported rates may spuriously go down to zero when used with collectd_exporter

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-monitoring#98]
collectd_exporter will be polled by prometheus with period P. collectd_exporter will be updated through collectd by Scylla with period C. Assume that P is set to be the same as C.

It can happen that effective C will be slightly larger than P due to hiccups in the push path. If phases are right, the whole P period may be contained in the C period. Since collectd_exporter exports samples with the timestamp at poll time, it will return the same value of a counter but with different timestamps. In such case we will see the rate of 0 for that period, even though the actual rate is not zero.

Another effect at play here is that Scylla's collectd client will start its periodic timer after metrics are sent, which adds some delay, so the phase for C is moving. Periodically it will get close to the phase of P, increasing chances of seeing this effect.

If P is grated than C, rates would not go to zero, but can still get distorted.

This wouldn't be a problem if collectd_exporter was exporting actual timestamps of samples. Currently values are exported with the timestamp at poll time.

This doesn't happen in a setup which polls through Scylla's built-in prometheus server.

**Comment by tzach** [comment]
@tgrabiec I assume this is not relevant anymore since this project does not use collectd_exporter.
Can we close this issue?

**Comment by tgrabiec** [comment]
It used to be the case that you could setup the monitoring with collectd_exporter. Is it not possible now?

**Comment by tzach** [comment]
Maybe possible, but for sure its not the short path.

**Comment by amnonh** [comment]
@tzach can we close this

**Comment by tzach** [comment]
Closing, we are not using collectd_exporter by default or at all for this project.
