### ISSUE TITLE
"report an issue with scylla monitoring" button does not look like a button

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#985]
scylla-version=2019.1
monitoring-version=master (not sure this is correct)

![image](https://user-images.githubusercontent.com/1017210/86582024-ac474c80-bf89-11ea-8b61-c5f0c095d177.png)

expected: less noise

**Comment by amnonh** [comment]
Relates to #867

**Comment by amnonh** [comment]
@avikivity just to be clear, do you see the link you've put there or:
![image](https://user-images.githubusercontent.com/2118079/86597465-6fd51a00-bfa4-11ea-961c-350481f93278.png)
As it should, if it's the first (link) I'll need more information about the installation, is that a standalone server?

**Comment by avikivity** [comment]
I pasted a screenshot. I don't see the button you put.

It's a customer deployment so I don't have more information.

**Comment by amnonh** [comment]
ok, this is most likely a configuration issue.
Newer grafana enable the HTML sanitizer by default, it should be disabled:
https://grafana.com/docs/grafana/latest/administration/configuration/#disable-sanitize-html
