### ISSUE TITLE
hints sent is cumulative from node start time, but displayed as rate

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#986]
scylla-version=2019.1
monitoring-version=master (not sure this is correct)

![image](https://user-images.githubusercontent.com/1017210/86582194-ef092480-bf89-11ea-9d64-0c3f89801671.png)

This looks like slowly growing counters with node restarts, not real rates.

**Comment by amnonh** [comment]
Duplicate of #865
