### ISSUE TITLE
I/O tab hides query classes from workload prioritization

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#989]
scylla-version=2019.1
monitoring-version=master (not sure about that)

The Query section of the I/O dashboard does not show rates for the configured service levels.

**Comment by amnonh** [comment]
the description is a bit cryptic.
Are you talking about the IOPS panel?

**Comment by avikivity** [comment]
Scylla I/O -> I/O queue -> Query I/O Queue

**Comment by amnonh** [comment]
Maybe you are using an older version of the dashboard.
This is how it looks like now:
![image](https://user-images.githubusercontent.com/2118079/86592800-cb030e80-bf9c-11ea-8432-413c86c6ccfe.png)

**Comment by avikivity** [comment]
I don't see the service levels.

**Comment by avikivity** [comment]
2019.1 split the query class into multiple service levels, but I only see the original query class. /cc @eliransin

**Comment by eliransin** [comment]
I will look at the query to see what metric it is, if the metrics are labeled with scheduling_group/io_class so it should be there, if not, I might need to add it in a way similar I did with storage_proxy by changing to per scheduling group stats.

**Comment by amnonh** [comment]
It's part of 3.8.1 https://github.com/scylladb/scylla-monitoring/pull/1479
