### ISSUE TITLE
Meta issue: branch scylla-grafana-monitoring to match Scylla releases

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#99]
Each version of scylla-grafana-monitoring match particular version of Scylla.
With each Scylla release, we need to branch scylla-grafana-monitoring with the same tags, branches.

**Comment by tzach** [comment]
@slivne ?

**Comment by slivne** [comment]
you mean @penberg 

pekka - lets add scylla-grafana-monitoring to scylla-pkg and also to the branching procedure.

@tzach what do you suggest we do no to make sure a simple transition.

branch head for 1.4/1.5 and tag it accordignly

use 0.1 for 1.3 ?

**Comment by tzach** [comment]
0.1 can become 1.3
we need to find where 1.4, 1.5 are

**Comment by tzach** [comment]
Closing since we now have a dashboard pre Scylla release (and master)
