### ISSUE TITLE
Nodes went down and the changes were not reflected 

### ISSUE THREAD

**Issue by Phara0h** [scylladb/scylla-monitoring#990]
scylla-version=4.0
monitoring-version=3.3

[https://imgur.com/a/3CIAAw3](https://imgur.com/a/3CIAAw3)

**Comment by dorlaor** [comment]
@amnonh how does the monitor get an update from nodetool status?
@Phara0h you should check why the latency of the writes went
to the sky, even when a node goes down, the service should continue
to function, pretty much like before

**Comment by Phara0h** [comment]
> @amnonh how does the monitor get an update from nodetool status?
> @Phara0h you should check why the latency of the writes went
> to the sky, even when a node goes down, the service should continue
> to function, pretty much like before

💯 submitted a ticket regarding it, curious as well. So far other support in slack was saying "heavy compaction" and needs to be investigated. I'm currently running my scripts to migrate my data from mongo to Scylla. 

P. S love these charts!

**Comment by amnonh** [comment]
@dorlaor:  the monitoring reads it's information from Prometheus (Supported natively by Scylla, it does not get information from nodetool).

@Phara0h About the Graphs, it seems that the nodes are currently up, so maybe they were down and then back up again (unless I'm missing something), so from the monitoring perspective, it's a restart, 
Restarts should be seen as annotations on the graph, for example:
![Screenshot from 2020-07-10 11-30-58](https://user-images.githubusercontent.com/2118079/87134282-27b64000-c2a1-11ea-8148-2cd171fa0495.png)

I'm not sure why it is not shown in the graph, I've opened #991 for this particular issue.

There is an alert table panel for active alerts so while a node is unreachable after about 1m of grace period an active alert will be shown, that alert will be removed once the node is up again.

**Comment by Phara0h** [comment]
@amnonh 

My node has been down for hours and never got an alert and still says everything is good. [https://imgur.com/TZvoQ8F](https://imgur.com/TZvoQ8F)

**Comment by amnonh** [comment]
@Phara0h 
If, like in this case,  after a few minutes there is no alert it's between the Prometheus and the node.
Prometheus continues to report the node with zero values, which is wrong.

Just to be clear you are using Grafana and Prometheus with Docker, not a standalone installation.

I've never seen this kind of behavior from Prometheus, so there are a few things I would like to see.
can you connect to the Prometheus server dashboard (same IP as Grafana but port `9090`)

From the `status` menu get the `status` and the `configuration`

From the `graph` please query both as console and as graph the following:
* up
* ALERTS
* scrape_duration_seconds

Also, can you check for errors in the Prometheus log?
by `docker logs aprom`

**Comment by Phara0h** [comment]
This is with Scylla cloud

**Comment by amnonh** [comment]
ok, are you using the Grafana proxy?

**Comment by amnonh** [comment]
@Phara0h I've talked to the Cloud team, if you are a cloud customer, please open a ticket using the cloud support, this could be Cloud specific issue.
I'll continue to follow

**Comment by Phara0h** [comment]
@amnonh maybe? I'm just clicking on "Advance Monitoring" tab in the console. https://graphs.cloud.scylladb.com/cluster/690/monitor/d/overview-4-0/scylla-overview-metrics

**Comment by noamha** [comment]
@Phara0h Hi, as @amnonh suggested as a cloud customer please open a cloud ticket and we will take care of it there. Thanks.

**Comment by amnonh** [comment]
Closing, cloud can open an issue if it's needed
